// AUTO-GENERATED by tools/lv2_catalog_import — do not edit by hand.
// Re-run the tool to regenerate. Manual customisation goes in overrides.yaml.

#![allow(dead_code, unused_imports, unused_variables, clippy::all)]

use crate::registry::FilterModelDefinition;
use crate::FilterBackendKind;
use anyhow::Result;
use block_core::param::{
    bool_parameter, float_parameter, required_bool, required_f32,
    ModelParameterSchema, ParameterSet, ParameterUnit,
};
use block_core::{AudioChannelLayout, BlockProcessor, ModelAudioMode};

pub const MODEL_ID: &str = "lv2_rkr_bad_mu_tro_mojo";
pub const DISPLAY_NAME: &str = "rkr MuTroMojo";
const BRAND: &str = "rakarrack";

const PLUGIN_URI: &str = "http://rakarrack.sourceforge.net/effects.html#MuTroMojo";
const PLUGIN_DIR: &str = "rkr-bad";

#[cfg(target_os = "macos")]
const PLUGIN_BINARY: &str = "rkrlv2.dylib";
#[cfg(target_os = "linux")]
const PLUGIN_BINARY: &str = "rkrlv2.so";
#[cfg(target_os = "windows")]
const PLUGIN_BINARY: &str = "rkrlv2.dll";

// Port indices (from TTL)
const PORT_AUDIO_IN_INPUT_L: usize = 0;
const PORT_AUDIO_IN_INPUT_R: usize = 1;
const PORT_AUDIO_OUT_OUTPUT_L: usize = 2;
const PORT_AUDIO_OUT_OUTPUT_R: usize = 3;
const PORT_CTRL_BYPASS: usize = 4;
const PORT_CTRL_WETDRY: usize = 5;
const PORT_CTRL_Q: usize = 6;
const PORT_CTRL_TEMPO: usize = 7;
const PORT_CTRL_RND: usize = 8;
const PORT_CTRL_TYPE: usize = 9;
const PORT_CTRL_STDL: usize = 10;
const PORT_CTRL_DEPTH: usize = 11;
const PORT_CTRL_SENSE: usize = 12;
const PORT_CTRL_WAH: usize = 13;
const PORT_CTRL_SMOOTH: usize = 14;
const PORT_CTRL_LP: usize = 15;
const PORT_CTRL_BP: usize = 16;
const PORT_CTRL_HP: usize = 17;
const PORT_CTRL_STAGES: usize = 18;
const PORT_CTRL_RANGE: usize = 19;
const PORT_CTRL_MINFREQ: usize = 20;
const PORT_CTRL_VARIQ: usize = 21;
const PORT_CTRL_QMODE: usize = 22;
const PORT_CTRL_AMODE: usize = 23;

pub fn model_schema() -> ModelParameterSchema {
    ModelParameterSchema {
        effect_type: block_core::EFFECT_TYPE_FILTER.into(),
        model: MODEL_ID.into(),
        display_name: DISPLAY_NAME.into(),
        audio_mode: ModelAudioMode::TrueStereo,
        parameters: vec![
            bool_parameter("bypass", "Bypass", None, Some(false)),
            float_parameter("wetdry", "Wet/Dry", None, Some(0.0), 0.0, 127.0, 1.0, ParameterUnit::None),
            float_parameter("q", "Resonance", None, Some(10.0), 0.0, 127.0, 1.0, ParameterUnit::None),
            float_parameter("tempo", "Tempo", None, Some(128.0), 1.0, 600.0, 1.0, ParameterUnit::None),
            float_parameter("rnd", "LFO Randomness", None, Some(0.0), 0.0, 127.0, 1.0, ParameterUnit::None),
            float_parameter("p_type", "LFO Type", None, Some(0.0), 0.0, 11.0, 0.1, ParameterUnit::None),
            float_parameter("stdl", "LFO L/R Delay", None, Some(-2.0), -64.0, 63.0, 1.0, ParameterUnit::None),
            float_parameter("depth", "Depth", None, Some(50.0), 0.0, 127.0, 1.0, ParameterUnit::None),
            float_parameter("sense", "Envelope Sensitivity", None, Some(-30.0), -64.0, 64.0, 1.0, ParameterUnit::Hertz),
            float_parameter("wah", "Wah", None, Some(2.0), 0.0, 127.0, 1.0, ParameterUnit::None),
            float_parameter("smooth", "Envelope Smoothing", None, Some(0.0), 0.0, 127.0, 1.0, ParameterUnit::None),
            float_parameter("lp", "Lowpass Level", None, Some(0.0), -64.0, 64.0, 1.0, ParameterUnit::None),
            float_parameter("bp", "Bandpass Level", None, Some(10.0), -64.0, 64.0, 1.0, ParameterUnit::None),
            float_parameter("hp", "Highpass Level", None, Some(-30.0), -64.0, 64.0, 1.0, ParameterUnit::None),
            float_parameter("stages", "Filter Stages", None, Some(1.0), 1.0, 6.0, 0.01, ParameterUnit::None),
            float_parameter("range", "Sweep Range", None, Some(2000.0), 10.0, 5000.0, 10.0, ParameterUnit::Hertz),
            float_parameter("minfreq", "Starting Frequency", None, Some(300.0), 30.0, 800.0, 1.0, ParameterUnit::Hertz),
            bool_parameter("variq", "Modulate Resonance", None, Some(true)),
            bool_parameter("qmode", "Analog Gain Mode", None, Some(false)),
            bool_parameter("amode", "Exponential Wah", None, Some(false)),
        ],
    }
}

fn build(params: &ParameterSet, sample_rate: f32, layout: AudioChannelLayout) -> Result<BlockProcessor> {
    let bypass = required_bool(params, "bypass").map_err(anyhow::Error::msg)?;
    let wetdry = required_f32(params, "wetdry").map_err(anyhow::Error::msg)?;
    let q = required_f32(params, "q").map_err(anyhow::Error::msg)?;
    let tempo = required_f32(params, "tempo").map_err(anyhow::Error::msg)?;
    let rnd = required_f32(params, "rnd").map_err(anyhow::Error::msg)?;
    let p_type = required_f32(params, "p_type").map_err(anyhow::Error::msg)?;
    let stdl = required_f32(params, "stdl").map_err(anyhow::Error::msg)?;
    let depth = required_f32(params, "depth").map_err(anyhow::Error::msg)?;
    let sense = required_f32(params, "sense").map_err(anyhow::Error::msg)?;
    let wah = required_f32(params, "wah").map_err(anyhow::Error::msg)?;
    let smooth = required_f32(params, "smooth").map_err(anyhow::Error::msg)?;
    let lp = required_f32(params, "lp").map_err(anyhow::Error::msg)?;
    let bp = required_f32(params, "bp").map_err(anyhow::Error::msg)?;
    let hp = required_f32(params, "hp").map_err(anyhow::Error::msg)?;
    let stages = required_f32(params, "stages").map_err(anyhow::Error::msg)?;
    let range = required_f32(params, "range").map_err(anyhow::Error::msg)?;
    let minfreq = required_f32(params, "minfreq").map_err(anyhow::Error::msg)?;
    let variq = required_bool(params, "variq").map_err(anyhow::Error::msg)?;
    let qmode = required_bool(params, "qmode").map_err(anyhow::Error::msg)?;
    let amode = required_bool(params, "amode").map_err(anyhow::Error::msg)?;
    let lib_path = lv2::resolve_lv2_lib(PLUGIN_BINARY)?;
    let bundle_path = lv2::resolve_lv2_bundle(PLUGIN_DIR)?;

    let control_ports: &[(usize, f32)] = &[
        (PORT_CTRL_BYPASS, if bypass { 1.0 } else { 0.0 }),
        (PORT_CTRL_WETDRY, wetdry),
        (PORT_CTRL_Q, q),
        (PORT_CTRL_TEMPO, tempo),
        (PORT_CTRL_RND, rnd),
        (PORT_CTRL_TYPE, p_type),
        (PORT_CTRL_STDL, stdl),
        (PORT_CTRL_DEPTH, depth),
        (PORT_CTRL_SENSE, sense),
        (PORT_CTRL_WAH, wah),
        (PORT_CTRL_SMOOTH, smooth),
        (PORT_CTRL_LP, lp),
        (PORT_CTRL_BP, bp),
        (PORT_CTRL_HP, hp),
        (PORT_CTRL_STAGES, stages),
        (PORT_CTRL_RANGE, range),
        (PORT_CTRL_MINFREQ, minfreq),
        (PORT_CTRL_VARIQ, if variq { 1.0 } else { 0.0 }),
        (PORT_CTRL_QMODE, if qmode { 1.0 } else { 0.0 }),
        (PORT_CTRL_AMODE, if amode { 1.0 } else { 0.0 }),
    ];

    let processor = lv2::build_stereo_lv2_processor(&lib_path, PLUGIN_URI, sample_rate as f64, &bundle_path, &[PORT_AUDIO_IN_INPUT_L, PORT_AUDIO_IN_INPUT_R], &[PORT_AUDIO_OUT_OUTPUT_L, PORT_AUDIO_OUT_OUTPUT_R], control_ports)?;
    let _ = layout;
    Ok(BlockProcessor::Stereo(Box::new(processor)))
}

fn schema() -> Result<ModelParameterSchema> { Ok(model_schema()) }

pub const MODEL_DEFINITION: FilterModelDefinition = FilterModelDefinition {
    id: MODEL_ID, display_name: DISPLAY_NAME, brand: BRAND,
    backend_kind: FilterBackendKind::Lv2, schema, build,
    supported_instruments: block_core::ALL_INSTRUMENTS, knob_layout: &[],
};
