// AUTO-GENERATED by tools/lv2_catalog_import — do not edit by hand.
// Re-run the tool to regenerate. Manual customisation goes in overrides.yaml.

#![allow(dead_code, unused_imports, unused_variables, clippy::approx_constant, clippy::excessive_precision)]

use crate::registry::FilterModelDefinition;
use crate::FilterBackendKind;
use anyhow::Result;
use block_core::param::{
    float_parameter, required_f32, ModelParameterSchema, ParameterSet, ParameterUnit,
};
use block_core::{AudioChannelLayout, BlockProcessor, ModelAudioMode};

pub const MODEL_ID: &str = "lv2_mod_crossover2_cross_over2";
pub const DISPLAY_NAME: &str = "CrossOver 2";
const BRAND: &str = "mod";

const PLUGIN_URI: &str = "http://moddevices.com/plugins/mod-devel/CrossOver2";
const PLUGIN_DIR: &str = "mod-crossover2";

#[cfg(target_os = "macos")]
const PLUGIN_BINARY: &str = "mod-crossover2.dylib.dylib";
#[cfg(target_os = "linux")]
const PLUGIN_BINARY: &str = "mod-crossover2.dylib.so";
#[cfg(target_os = "windows")]
const PLUGIN_BINARY: &str = "mod-crossover2.dylib.dll";

// Port indices (from TTL)
const PORT_AUDIO_IN_IN: usize = 0;
const PORT_AUDIO_OUT_OUT1: usize = 1;
const PORT_AUDIO_OUT_OUT2: usize = 2;
const PORT_CTRL_FREQ: usize = 3;
const PORT_CTRL_GAIN_1: usize = 4;
const PORT_CTRL_GAIN_2: usize = 5;
const PORT_CTRL_ORDER: usize = 6;

pub fn model_schema() -> ModelParameterSchema {
    ModelParameterSchema {
        effect_type: block_core::EFFECT_TYPE_FILTER.into(),
        model: MODEL_ID.into(),
        display_name: DISPLAY_NAME.into(),
        audio_mode: ModelAudioMode::MonoToStereo,
        parameters: vec![
            float_parameter("freq", "Freq", None, Some(600.0), 20.0, 20000.0, 10.0, ParameterUnit::Hertz),
            float_parameter("gain_1", "Gain 1", None, Some(3.0), -40.0, 40.0, 0.1, ParameterUnit::Decibels),
            float_parameter("gain_2", "Gain 2", None, Some(3.0), -40.0, 40.0, 0.1, ParameterUnit::Decibels),
            float_parameter("order", "Order", None, Some(0.0), 0.0, 2.0, 0.01, ParameterUnit::None),
        ],
    }
}

fn build(params: &ParameterSet, sample_rate: f32, layout: AudioChannelLayout) -> Result<BlockProcessor> {
    let freq = required_f32(params, "freq").map_err(anyhow::Error::msg)?;
    let gain_1 = required_f32(params, "gain_1").map_err(anyhow::Error::msg)?;
    let gain_2 = required_f32(params, "gain_2").map_err(anyhow::Error::msg)?;
    let order = required_f32(params, "order").map_err(anyhow::Error::msg)?;
    let lib_path = lv2::resolve_lv2_lib(PLUGIN_BINARY)?;
    let bundle_path = lv2::resolve_lv2_bundle(PLUGIN_DIR)?;

    let control_ports: &[(usize, f32)] = &[
        (PORT_CTRL_FREQ, freq),
        (PORT_CTRL_GAIN_1, gain_1),
        (PORT_CTRL_GAIN_2, gain_2),
        (PORT_CTRL_ORDER, order),
    ];

    let extra_outs: &[usize] = &[PORT_AUDIO_OUT_OUT2];
    let _ = layout;
    let processor = lv2::build_lv2_processor_with_extras(&lib_path, PLUGIN_URI, sample_rate as f64, &bundle_path, &[PORT_AUDIO_IN_IN], &[PORT_AUDIO_OUT_OUT1], control_ports, extra_outs)?;
    Ok(BlockProcessor::Mono(Box::new(processor)))
}

fn schema() -> Result<ModelParameterSchema> { Ok(model_schema()) }

pub const MODEL_DEFINITION: FilterModelDefinition = FilterModelDefinition {
    id: MODEL_ID, display_name: DISPLAY_NAME, brand: BRAND,
    backend_kind: FilterBackendKind::Lv2, schema, build,
    supported_instruments: block_core::ALL_INSTRUMENTS, knob_layout: &[],
};
