// AUTO-GENERATED by tools/lv2_catalog_import — do not edit by hand.
// Re-run the tool to regenerate. Manual customisation goes in overrides.yaml.

#![allow(dead_code, unused_imports, unused_variables, clippy::all)]

use crate::registry::FilterModelDefinition;
use crate::FilterBackendKind;
use anyhow::Result;
use block_core::param::{
    bool_parameter, float_parameter, required_bool, required_f32,
    ModelParameterSchema, ParameterSet, ParameterUnit,
};
use block_core::{AudioChannelLayout, BlockProcessor, ModelAudioMode};

pub const MODEL_ID: &str = "lv2_rkr_synthfilter";
pub const DISPLAY_NAME: &str = "rkr Synthfilter";
const BRAND: &str = "rakarrack";

const PLUGIN_URI: &str = "http://rakarrack.sourceforge.net/effects.html#Synthfilter";
const PLUGIN_DIR: &str = "rkr";

#[cfg(target_os = "macos")]
const PLUGIN_BINARY: &str = "plugin.dylib";
#[cfg(target_os = "linux")]
const PLUGIN_BINARY: &str = "plugin.so";
#[cfg(target_os = "windows")]
const PLUGIN_BINARY: &str = "plugin.dll";

// Port indices (from TTL)
const PORT_AUDIO_IN_INPUT_L: usize = 0;
const PORT_AUDIO_IN_INPUT_R: usize = 1;
const PORT_AUDIO_OUT_OUTPUT_L: usize = 2;
const PORT_AUDIO_OUT_OUTPUT_R: usize = 3;
const PORT_CTRL_BYPASS: usize = 4;
const PORT_CTRL_WETDRY: usize = 5;
const PORT_CTRL_DIST: usize = 6;
const PORT_CTRL_TEMPO: usize = 7;
const PORT_CTRL_RND: usize = 8;
const PORT_CTRL_TYPE: usize = 9;
const PORT_CTRL_STDL: usize = 10;
const PORT_CTRL_WIDTH: usize = 11;
const PORT_CTRL_FB: usize = 12;
const PORT_CTRL_LSTAGES: usize = 13;
const PORT_CTRL_HSTAGES: usize = 14;
const PORT_CTRL_SUB: usize = 15;
const PORT_CTRL_DEPTH: usize = 16;
const PORT_CTRL_SENSE: usize = 17;
const PORT_CTRL_ATIME: usize = 18;
const PORT_CTRL_RTIME: usize = 19;
const PORT_CTRL_OFFSET: usize = 20;

pub fn model_schema() -> ModelParameterSchema {
    ModelParameterSchema {
        effect_type: block_core::EFFECT_TYPE_FILTER.into(),
        model: MODEL_ID.into(),
        display_name: DISPLAY_NAME.into(),
        audio_mode: ModelAudioMode::TrueStereo,
        parameters: vec![
            bool_parameter("bypass", "Bypass", None, Some(false)),
            float_parameter("wetdry", "Wet/Dry", None, Some(0.0), 0.0, 127.0, 1.0, ParameterUnit::None),
            float_parameter("dist", "Distort", None, Some(0.0), 0.0, 127.0, 1.0, ParameterUnit::None),
            float_parameter("tempo", "Tempo", None, Some(80.0), 1.0, 600.0, 1.0, ParameterUnit::None),
            float_parameter("rnd", "Randomness", None, Some(0.0), 0.0, 127.0, 1.0, ParameterUnit::None),
            float_parameter("p_type", "LFO Type", None, Some(0.0), 0.0, 11.0, 0.1, ParameterUnit::None),
            float_parameter("stdl", "LFO L/R Delay", None, Some(-2.0), -64.0, 63.0, 1.0, ParameterUnit::None),
            float_parameter("width", "Width", None, Some(50.0), 0.0, 127.0, 1.0, ParameterUnit::None),
            float_parameter("fb", "Feedback", None, Some(-30.0), -64.0, 64.0, 1.0, ParameterUnit::Hertz),
            float_parameter("lstages", "Lowpass Stages", None, Some(2.0), 0.0, 12.0, 0.1, ParameterUnit::None),
            float_parameter("hstages", "Highpass Stages", None, Some(1.0), 0.0, 12.0, 0.1, ParameterUnit::None),
            bool_parameter("sub", "Subtract Output", None, Some(false)),
            float_parameter("depth", "Depth", None, Some(100.0), 0.0, 127.0, 1.0, ParameterUnit::None),
            float_parameter("sense", "Envelope Sensitivity", None, Some(-30.0), -64.0, 64.0, 1.0, ParameterUnit::None),
            float_parameter("atime", "Attack Time", None, Some(80.0), 5.0, 1000.0, 1.0, ParameterUnit::Milliseconds),
            float_parameter("rtime", "Release Time", None, Some(100.0), 5.0, 500.0, 1.0, ParameterUnit::Milliseconds),
            float_parameter("offset", "HPF/LPF Offset", None, Some(0.0), 0.0, 127.0, 1.0, ParameterUnit::None),
        ],
    }
}

fn build(params: &ParameterSet, sample_rate: f32, layout: AudioChannelLayout) -> Result<BlockProcessor> {
    let bypass = required_bool(params, "bypass").map_err(anyhow::Error::msg)?;
    let wetdry = required_f32(params, "wetdry").map_err(anyhow::Error::msg)?;
    let dist = required_f32(params, "dist").map_err(anyhow::Error::msg)?;
    let tempo = required_f32(params, "tempo").map_err(anyhow::Error::msg)?;
    let rnd = required_f32(params, "rnd").map_err(anyhow::Error::msg)?;
    let p_type = required_f32(params, "p_type").map_err(anyhow::Error::msg)?;
    let stdl = required_f32(params, "stdl").map_err(anyhow::Error::msg)?;
    let width = required_f32(params, "width").map_err(anyhow::Error::msg)?;
    let fb = required_f32(params, "fb").map_err(anyhow::Error::msg)?;
    let lstages = required_f32(params, "lstages").map_err(anyhow::Error::msg)?;
    let hstages = required_f32(params, "hstages").map_err(anyhow::Error::msg)?;
    let sub = required_bool(params, "sub").map_err(anyhow::Error::msg)?;
    let depth = required_f32(params, "depth").map_err(anyhow::Error::msg)?;
    let sense = required_f32(params, "sense").map_err(anyhow::Error::msg)?;
    let atime = required_f32(params, "atime").map_err(anyhow::Error::msg)?;
    let rtime = required_f32(params, "rtime").map_err(anyhow::Error::msg)?;
    let offset = required_f32(params, "offset").map_err(anyhow::Error::msg)?;
    let lib_path = lv2::resolve_lv2_lib(PLUGIN_BINARY)?;
    let bundle_path = lv2::resolve_lv2_bundle(PLUGIN_DIR)?;

    let control_ports: &[(usize, f32)] = &[
        (PORT_CTRL_BYPASS, if bypass { 1.0 } else { 0.0 }),
        (PORT_CTRL_WETDRY, wetdry),
        (PORT_CTRL_DIST, dist),
        (PORT_CTRL_TEMPO, tempo),
        (PORT_CTRL_RND, rnd),
        (PORT_CTRL_TYPE, p_type),
        (PORT_CTRL_STDL, stdl),
        (PORT_CTRL_WIDTH, width),
        (PORT_CTRL_FB, fb),
        (PORT_CTRL_LSTAGES, lstages),
        (PORT_CTRL_HSTAGES, hstages),
        (PORT_CTRL_SUB, if sub { 1.0 } else { 0.0 }),
        (PORT_CTRL_DEPTH, depth),
        (PORT_CTRL_SENSE, sense),
        (PORT_CTRL_ATIME, atime),
        (PORT_CTRL_RTIME, rtime),
        (PORT_CTRL_OFFSET, offset),
    ];

    let processor = lv2::build_stereo_lv2_processor(&lib_path, PLUGIN_URI, sample_rate as f64, &bundle_path, &[PORT_AUDIO_IN_INPUT_L, PORT_AUDIO_IN_INPUT_R], &[PORT_AUDIO_OUT_OUTPUT_L, PORT_AUDIO_OUT_OUTPUT_R], control_ports)?;
    let _ = layout;
    Ok(BlockProcessor::Stereo(Box::new(processor)))
}

fn schema() -> Result<ModelParameterSchema> { Ok(model_schema()) }

pub const MODEL_DEFINITION: FilterModelDefinition = FilterModelDefinition {
    id: MODEL_ID, display_name: DISPLAY_NAME, brand: BRAND,
    backend_kind: FilterBackendKind::Lv2, schema, build,
    supported_instruments: block_core::ALL_INSTRUMENTS, knob_layout: &[],
};
