// AUTO-GENERATED by tools/lv2_catalog_import — do not edit by hand.
// Re-run the tool to regenerate. Manual customisation goes in overrides.yaml.

#![allow(dead_code, unused_imports, unused_variables, clippy::all)]

use crate::registry::FilterModelDefinition;
use crate::FilterBackendKind;
use anyhow::Result;
use block_core::param::{
    bool_parameter, float_parameter, required_bool, required_f32,
    ModelParameterSchema, ParameterSet, ParameterUnit,
};
use block_core::{AudioChannelLayout, BlockProcessor, ModelAudioMode};

pub const MODEL_ID: &str = "lv2_rkr_shelf_boost";
pub const DISPLAY_NAME: &str = "rkr Shelf Boost";
const BRAND: &str = "rakarrack";

const PLUGIN_URI: &str = "http://rakarrack.sourceforge.net/effects.html#ShelfBoost";
const PLUGIN_DIR: &str = "rkr";
pub const THUMBNAIL_PATH: Option<&str> = Some(".plugins/lv2/rkr.lv2/modgui/thumbnail-rkr-shelf-boost.png");

#[cfg(target_os = "macos")]
const PLUGIN_BINARY: &str = "plugin.dylib";
#[cfg(target_os = "linux")]
const PLUGIN_BINARY: &str = "plugin.so";
#[cfg(target_os = "windows")]
const PLUGIN_BINARY: &str = "plugin.dll";

// Port indices (from TTL)
const PORT_AUDIO_IN_INPUT_L: usize = 0;
const PORT_AUDIO_IN_INPUT_R: usize = 1;
const PORT_AUDIO_OUT_OUTPUT_L: usize = 2;
const PORT_AUDIO_OUT_OUTPUT_R: usize = 3;
const PORT_CTRL_BYPASS: usize = 4;
const PORT_CTRL_GAIN: usize = 5;
const PORT_CTRL_PRES: usize = 6;
const PORT_CTRL_TONE: usize = 7;
const PORT_CTRL_STEREO: usize = 8;
const PORT_CTRL_LEVEL: usize = 9;

pub fn model_schema() -> ModelParameterSchema {
    ModelParameterSchema {
        effect_type: block_core::EFFECT_TYPE_FILTER.into(),
        model: MODEL_ID.into(),
        display_name: DISPLAY_NAME.into(),
        audio_mode: ModelAudioMode::TrueStereo,
        parameters: vec![
            bool_parameter("bypass", "Bypass", None, Some(false)),
            float_parameter("gain", "Gain", None, Some(0.0), 0.0, 127.0, 1.0, ParameterUnit::None),
            float_parameter("pres", "Presence", None, Some(0.0), -64.0, 64.0, 1.0, ParameterUnit::None),
            float_parameter("tone", "Tone", None, Some(2020.0), 220.0, 16000.0, 10.0, ParameterUnit::Hertz),
            bool_parameter("stereo", "Stereo", None, Some(true)),
            float_parameter("level", "Level", None, Some(10.0), 1.0, 127.0, 1.0, ParameterUnit::None),
        ],
    }
}

fn build(params: &ParameterSet, sample_rate: f32, layout: AudioChannelLayout) -> Result<BlockProcessor> {
    let bypass = required_bool(params, "bypass").map_err(anyhow::Error::msg)?;
    let gain = required_f32(params, "gain").map_err(anyhow::Error::msg)?;
    let pres = required_f32(params, "pres").map_err(anyhow::Error::msg)?;
    let tone = required_f32(params, "tone").map_err(anyhow::Error::msg)?;
    let stereo = required_bool(params, "stereo").map_err(anyhow::Error::msg)?;
    let level = required_f32(params, "level").map_err(anyhow::Error::msg)?;
    let lib_path = lv2::resolve_lv2_lib(PLUGIN_BINARY)?;
    let bundle_path = lv2::resolve_lv2_bundle(PLUGIN_DIR)?;

    let control_ports: &[(usize, f32)] = &[
        (PORT_CTRL_BYPASS, if bypass { 1.0 } else { 0.0 }),
        (PORT_CTRL_GAIN, gain),
        (PORT_CTRL_PRES, pres),
        (PORT_CTRL_TONE, tone),
        (PORT_CTRL_STEREO, if stereo { 1.0 } else { 0.0 }),
        (PORT_CTRL_LEVEL, level),
    ];

    let processor = lv2::build_stereo_lv2_processor(&lib_path, PLUGIN_URI, sample_rate as f64, &bundle_path, &[PORT_AUDIO_IN_INPUT_L, PORT_AUDIO_IN_INPUT_R], &[PORT_AUDIO_OUT_OUTPUT_L, PORT_AUDIO_OUT_OUTPUT_R], control_ports)?;
    let _ = layout;
    Ok(BlockProcessor::Stereo(Box::new(processor)))
}

fn schema() -> Result<ModelParameterSchema> { Ok(model_schema()) }

pub const MODEL_DEFINITION: FilterModelDefinition = FilterModelDefinition {
    id: MODEL_ID, display_name: DISPLAY_NAME, brand: BRAND,
    backend_kind: FilterBackendKind::Lv2, schema, build,
    supported_instruments: block_core::ALL_INSTRUMENTS, knob_layout: &[],
};
