// AUTO-GENERATED by tools/lv2_catalog_import — do not edit by hand.
// Re-run the tool to regenerate. Manual customisation goes in overrides.yaml.

#![allow(dead_code, unused_imports, unused_variables, clippy::approx_constant, clippy::excessive_precision)]

use crate::registry::FilterModelDefinition;
use crate::FilterBackendKind;
use anyhow::Result;
use block_core::param::{
    bool_parameter, float_parameter, required_bool, required_f32,
    ModelParameterSchema, ParameterSet, ParameterUnit,
};
use block_core::{AudioChannelLayout, BlockProcessor, ModelAudioMode, MonoProcessor, StereoProcessor};

pub const MODEL_ID: &str = "lv2_artyfx_kuiza";
pub const DISPLAY_NAME: &str = "Kuiza";
const BRAND: &str = "openav";

const PLUGIN_URI: &str = "http://www.openavproductions.com/artyfx#kuiza";
const PLUGIN_DIR: &str = "artyfx";

#[cfg(target_os = "macos")]
const PLUGIN_BINARY: &str = "artyfx.dylib";
#[cfg(target_os = "linux")]
const PLUGIN_BINARY: &str = "artyfx.so";
#[cfg(target_os = "windows")]
const PLUGIN_BINARY: &str = "artyfx.dll";

// Port indices (from TTL)
const PORT_AUDIO_IN_INPUT: usize = 0;
const PORT_AUDIO_OUT_OUTPUT: usize = 1;
const PORT_CTRL_LEVEL: usize = 2;
const PORT_CTRL_LOW: usize = 3;
const PORT_CTRL_LO_MID: usize = 4;
const PORT_CTRL_HI_MID: usize = 5;
const PORT_CTRL_HIGH: usize = 6;
const PORT_CTRL_ACTIVE: usize = 7;

pub fn model_schema() -> ModelParameterSchema {
    ModelParameterSchema {
        effect_type: block_core::EFFECT_TYPE_FILTER.into(),
        model: MODEL_ID.into(),
        display_name: DISPLAY_NAME.into(),
        audio_mode: ModelAudioMode::DualMono,
        parameters: vec![
            float_parameter("level", "Gain", None, Some(0.5), 0.0, 1.0, 0.01, ParameterUnit::None),
            float_parameter("low", "Low Gain", None, Some(0.5), 0.0, 1.0, 0.01, ParameterUnit::None),
            float_parameter("lo_mid", "LoMid Gain", None, Some(0.5), 0.0, 1.0, 0.01, ParameterUnit::None),
            float_parameter("hi_mid", "HiMid Gain", None, Some(0.5), 0.0, 1.0, 0.01, ParameterUnit::None),
            float_parameter("high", "High Gain", None, Some(0.5), 0.0, 1.0, 0.01, ParameterUnit::None),
            bool_parameter("active", "Active", None, Some(true)),
        ],
    }
}

fn build(params: &ParameterSet, sample_rate: f32, layout: AudioChannelLayout) -> Result<BlockProcessor> {
    let level = required_f32(params, "level").map_err(anyhow::Error::msg)?;
    let low = required_f32(params, "low").map_err(anyhow::Error::msg)?;
    let lo_mid = required_f32(params, "lo_mid").map_err(anyhow::Error::msg)?;
    let hi_mid = required_f32(params, "hi_mid").map_err(anyhow::Error::msg)?;
    let high = required_f32(params, "high").map_err(anyhow::Error::msg)?;
    let active = required_bool(params, "active").map_err(anyhow::Error::msg)?;
    let lib_path = lv2::resolve_lv2_lib(PLUGIN_BINARY)?;
    let bundle_path = lv2::resolve_lv2_bundle(PLUGIN_DIR)?;

    let control_ports: &[(usize, f32)] = &[
        (PORT_CTRL_LEVEL, level),
        (PORT_CTRL_LOW, low),
        (PORT_CTRL_LO_MID, lo_mid),
        (PORT_CTRL_HI_MID, hi_mid),
        (PORT_CTRL_HIGH, high),
        (PORT_CTRL_ACTIVE, if active { 1.0 } else { 0.0 }),
    ];

    match layout {
        AudioChannelLayout::Mono => {
            let processor = lv2::build_lv2_processor(&lib_path, PLUGIN_URI, sample_rate as f64, &bundle_path, &[PORT_AUDIO_IN_INPUT], &[PORT_AUDIO_OUT_OUTPUT], control_ports)?;
            Ok(BlockProcessor::Mono(Box::new(processor)))
        }
        AudioChannelLayout::Stereo => {
            let left = lv2::build_lv2_processor(&lib_path, PLUGIN_URI, sample_rate as f64, &bundle_path, &[PORT_AUDIO_IN_INPUT], &[PORT_AUDIO_OUT_OUTPUT], control_ports)?;
            let right = lv2::build_lv2_processor(&lib_path, PLUGIN_URI, sample_rate as f64, &bundle_path, &[PORT_AUDIO_IN_INPUT], &[PORT_AUDIO_OUT_OUTPUT], control_ports)?;
            Ok(BlockProcessor::Stereo(Box::new(DualMonoProcessor { left, right })))
        }
    }
}

struct DualMonoProcessor { left: lv2::Lv2Processor, right: lv2::Lv2Processor }
impl StereoProcessor for DualMonoProcessor {
    fn process_frame(&mut self, input: [f32; 2]) -> [f32; 2] {
        [self.left.process_sample(input[0]), self.right.process_sample(input[1])]
    }
}

fn schema() -> Result<ModelParameterSchema> { Ok(model_schema()) }

pub const MODEL_DEFINITION: FilterModelDefinition = FilterModelDefinition {
    id: MODEL_ID, display_name: DISPLAY_NAME, brand: BRAND,
    backend_kind: FilterBackendKind::Lv2, schema, build,
    supported_instruments: block_core::ALL_INSTRUMENTS, knob_layout: &[],
};
