// AUTO-GENERATED by tools/lv2_catalog_import — do not edit by hand.
// Re-run the tool to regenerate. Manual customisation goes in overrides.yaml.

#![allow(dead_code, unused_imports, unused_variables, clippy::all)]

use crate::registry::FilterModelDefinition;
use crate::FilterBackendKind;
use anyhow::Result;
use block_core::param::{
    bool_parameter, float_parameter, required_bool, required_f32,
    ModelParameterSchema, ParameterSet, ParameterUnit,
};
use block_core::{AudioChannelLayout, BlockProcessor, ModelAudioMode, MonoProcessor, StereoProcessor};

pub const MODEL_ID: &str = "lv2_fomp_bad_parametric1";
pub const DISPLAY_NAME: &str = "4-Band Parametric Filter";
const BRAND: &str = "fomp";

const PLUGIN_URI: &str = "http://drobilla.net/plugins/fomp/parametric1";
const PLUGIN_DIR: &str = "fomp-bad";
pub const THUMBNAIL_PATH: Option<&str> = Some(".plugins/lv2/fomp-bad.lv2/modgui/thumbnail-4-band-parametric-filter.png");

#[cfg(target_os = "macos")]
const PLUGIN_BINARY: &str = "filters.dylib";
#[cfg(target_os = "linux")]
const PLUGIN_BINARY: &str = "filters.so";
#[cfg(target_os = "windows")]
const PLUGIN_BINARY: &str = "filters.dll";

// Port indices (from TTL)
const PORT_AUDIO_IN_IN: usize = 0;
const PORT_AUDIO_OUT_OUT: usize = 1;
const PORT_CTRL_FILTER: usize = 2;
const PORT_CTRL_GAIN: usize = 3;
const PORT_CTRL_SEC_1: usize = 4;
const PORT_CTRL_FREQ_1: usize = 5;
const PORT_CTRL_BW_1: usize = 6;
const PORT_CTRL_GAIN_1: usize = 7;
const PORT_CTRL_SEC_2: usize = 8;
const PORT_CTRL_FREQ_2: usize = 9;
const PORT_CTRL_BW_2: usize = 10;
const PORT_CTRL_GAIN_2: usize = 11;
const PORT_CTRL_SEC_3: usize = 12;
const PORT_CTRL_FREQ_3: usize = 13;
const PORT_CTRL_BW_3: usize = 14;
const PORT_CTRL_GAIN_3: usize = 15;
const PORT_CTRL_SEC_4: usize = 16;
const PORT_CTRL_FREQ_4: usize = 17;
const PORT_CTRL_BW_4: usize = 18;
const PORT_CTRL_GAIN_4: usize = 19;

pub fn model_schema() -> ModelParameterSchema {
    ModelParameterSchema {
        effect_type: block_core::EFFECT_TYPE_FILTER.into(),
        model: MODEL_ID.into(),
        display_name: DISPLAY_NAME.into(),
        audio_mode: ModelAudioMode::DualMono,
        parameters: vec![
            bool_parameter("filter", "Filter", None, Some(false)),
            float_parameter("gain", "Gain", None, Some(0.0), -20.0, 20.0, 0.1, ParameterUnit::None),
            bool_parameter("sec_1", "Section 1", None, Some(false)),
            float_parameter("freq_1", "Frequency 1", None, Some(200.0), 20.0, 2000.0, 10.0, ParameterUnit::Hertz),
            float_parameter("bw_1", "Bandwidth 1", None, Some(1.0), 0.125, 8.0, 0.01, ParameterUnit::None),
            float_parameter("gain_1", "Gain 1", None, Some(0.0), -20.0, 20.0, 0.1, ParameterUnit::None),
            bool_parameter("sec_2", "Section 2", None, Some(false)),
            float_parameter("freq_2", "Frequency 2", None, Some(400.0), 40.0, 4000.0, 10.0, ParameterUnit::Hertz),
            float_parameter("bw_2", "Bandwidth 2", None, Some(1.0), 0.125, 8.0, 0.01, ParameterUnit::None),
            float_parameter("gain_2", "Gain 2", None, Some(0.0), -20.0, 20.0, 0.1, ParameterUnit::None),
            bool_parameter("sec_3", "Section 3", None, Some(false)),
            float_parameter("freq_3", "Frequency 3", None, Some(1000.0), 100.0, 10000.0, 10.0, ParameterUnit::Hertz),
            float_parameter("bw_3", "Bandwidth 3", None, Some(1.0), 0.125, 8.0, 0.01, ParameterUnit::None),
            float_parameter("gain_3", "Gain 3", None, Some(0.0), -20.0, 20.0, 0.1, ParameterUnit::None),
            bool_parameter("sec_4", "Section 4", None, Some(false)),
            float_parameter("freq_4", "Frequency 4", None, Some(2000.0), 200.0, 20000.0, 10.0, ParameterUnit::Hertz),
            float_parameter("bw_4", "Bandwidth 4", None, Some(1.0), 0.125, 8.0, 0.01, ParameterUnit::None),
            float_parameter("gain_4", "Gain 4", None, Some(0.0), -20.0, 20.0, 0.1, ParameterUnit::None),
        ],
    }
}

fn build(params: &ParameterSet, sample_rate: f32, layout: AudioChannelLayout) -> Result<BlockProcessor> {
    let filter = required_bool(params, "filter").map_err(anyhow::Error::msg)?;
    let gain = required_f32(params, "gain").map_err(anyhow::Error::msg)?;
    let sec_1 = required_bool(params, "sec_1").map_err(anyhow::Error::msg)?;
    let freq_1 = required_f32(params, "freq_1").map_err(anyhow::Error::msg)?;
    let bw_1 = required_f32(params, "bw_1").map_err(anyhow::Error::msg)?;
    let gain_1 = required_f32(params, "gain_1").map_err(anyhow::Error::msg)?;
    let sec_2 = required_bool(params, "sec_2").map_err(anyhow::Error::msg)?;
    let freq_2 = required_f32(params, "freq_2").map_err(anyhow::Error::msg)?;
    let bw_2 = required_f32(params, "bw_2").map_err(anyhow::Error::msg)?;
    let gain_2 = required_f32(params, "gain_2").map_err(anyhow::Error::msg)?;
    let sec_3 = required_bool(params, "sec_3").map_err(anyhow::Error::msg)?;
    let freq_3 = required_f32(params, "freq_3").map_err(anyhow::Error::msg)?;
    let bw_3 = required_f32(params, "bw_3").map_err(anyhow::Error::msg)?;
    let gain_3 = required_f32(params, "gain_3").map_err(anyhow::Error::msg)?;
    let sec_4 = required_bool(params, "sec_4").map_err(anyhow::Error::msg)?;
    let freq_4 = required_f32(params, "freq_4").map_err(anyhow::Error::msg)?;
    let bw_4 = required_f32(params, "bw_4").map_err(anyhow::Error::msg)?;
    let gain_4 = required_f32(params, "gain_4").map_err(anyhow::Error::msg)?;
    let lib_path = lv2::resolve_lv2_lib(PLUGIN_BINARY)?;
    let bundle_path = lv2::resolve_lv2_bundle(PLUGIN_DIR)?;

    let control_ports: &[(usize, f32)] = &[
        (PORT_CTRL_FILTER, if filter { 1.0 } else { 0.0 }),
        (PORT_CTRL_GAIN, gain),
        (PORT_CTRL_SEC_1, if sec_1 { 1.0 } else { 0.0 }),
        (PORT_CTRL_FREQ_1, freq_1),
        (PORT_CTRL_BW_1, bw_1),
        (PORT_CTRL_GAIN_1, gain_1),
        (PORT_CTRL_SEC_2, if sec_2 { 1.0 } else { 0.0 }),
        (PORT_CTRL_FREQ_2, freq_2),
        (PORT_CTRL_BW_2, bw_2),
        (PORT_CTRL_GAIN_2, gain_2),
        (PORT_CTRL_SEC_3, if sec_3 { 1.0 } else { 0.0 }),
        (PORT_CTRL_FREQ_3, freq_3),
        (PORT_CTRL_BW_3, bw_3),
        (PORT_CTRL_GAIN_3, gain_3),
        (PORT_CTRL_SEC_4, if sec_4 { 1.0 } else { 0.0 }),
        (PORT_CTRL_FREQ_4, freq_4),
        (PORT_CTRL_BW_4, bw_4),
        (PORT_CTRL_GAIN_4, gain_4),
    ];

    match layout {
        AudioChannelLayout::Mono => {
            let processor = lv2::build_lv2_processor(&lib_path, PLUGIN_URI, sample_rate as f64, &bundle_path, &[PORT_AUDIO_IN_IN], &[PORT_AUDIO_OUT_OUT], control_ports)?;
            Ok(BlockProcessor::Mono(Box::new(processor)))
        }
        AudioChannelLayout::Stereo => {
            let left = lv2::build_lv2_processor(&lib_path, PLUGIN_URI, sample_rate as f64, &bundle_path, &[PORT_AUDIO_IN_IN], &[PORT_AUDIO_OUT_OUT], control_ports)?;
            let right = lv2::build_lv2_processor(&lib_path, PLUGIN_URI, sample_rate as f64, &bundle_path, &[PORT_AUDIO_IN_IN], &[PORT_AUDIO_OUT_OUT], control_ports)?;
            Ok(BlockProcessor::Stereo(Box::new(DualMonoProcessor { left, right })))
        }
    }
}

struct DualMonoProcessor { left: lv2::Lv2Processor, right: lv2::Lv2Processor }
impl StereoProcessor for DualMonoProcessor {
    fn process_frame(&mut self, input: [f32; 2]) -> [f32; 2] {
        [self.left.process_sample(input[0]), self.right.process_sample(input[1])]
    }
}

fn schema() -> Result<ModelParameterSchema> { Ok(model_schema()) }

pub const MODEL_DEFINITION: FilterModelDefinition = FilterModelDefinition {
    id: MODEL_ID, display_name: DISPLAY_NAME, brand: BRAND,
    backend_kind: FilterBackendKind::Lv2, schema, build,
    supported_instruments: block_core::ALL_INSTRUMENTS, knob_layout: &[],
};
