// AUTO-GENERATED by tools/lv2_catalog_import — do not edit by hand.
// Re-run the tool to regenerate. Manual customisation goes in overrides.yaml.

#![allow(dead_code, unused_imports, unused_variables, clippy::all)]

use crate::registry::FilterModelDefinition;
use crate::FilterBackendKind;
use anyhow::Result;
use block_core::param::{
    bool_parameter, float_parameter, required_bool, required_f32,
    ModelParameterSchema, ParameterSet, ParameterUnit,
};
use block_core::{AudioChannelLayout, BlockProcessor, ModelAudioMode};

pub const MODEL_ID: &str = "lv2_calf_bad_equalizer12_band";
pub const DISPLAY_NAME: &str = "Calf Equalizer 12 Band";
const BRAND: &str = "calf";

const PLUGIN_URI: &str = "http://calf.sourceforge.net/plugins/Equalizer12Band";
const PLUGIN_DIR: &str = "calf-bad";

#[cfg(target_os = "macos")]
const PLUGIN_BINARY: &str = "calf.dylib";
#[cfg(target_os = "linux")]
const PLUGIN_BINARY: &str = "calf.so";
#[cfg(target_os = "windows")]
const PLUGIN_BINARY: &str = "calf.dll";

// Port indices (from TTL)
const PORT_AUDIO_IN_IN_L: usize = 0;
const PORT_AUDIO_IN_IN_R: usize = 1;
const PORT_AUDIO_OUT_OUT_L: usize = 2;
const PORT_AUDIO_OUT_OUT_R: usize = 3;
const PORT_CTRL_BYPASS: usize = 4;
const PORT_CTRL_LEVEL_IN: usize = 5;
const PORT_CTRL_LEVEL_OUT: usize = 6;
const PORT_CTRL_METER_IN_L: usize = 7;
const PORT_CTRL_METER_IN_R: usize = 8;
const PORT_CTRL_METER_OUT_L: usize = 9;
const PORT_CTRL_METER_OUT_R: usize = 10;
const PORT_CTRL_CLIP_IN_L: usize = 11;
const PORT_CTRL_CLIP_IN_R: usize = 12;
const PORT_CTRL_CLIP_OUT_L: usize = 13;
const PORT_CTRL_CLIP_OUT_R: usize = 14;
const PORT_CTRL_HP_ACTIVE: usize = 15;
const PORT_CTRL_HP_FREQ: usize = 16;
const PORT_CTRL_HP_MODE: usize = 17;
const PORT_CTRL_LP_ACTIVE: usize = 18;
const PORT_CTRL_LP_FREQ: usize = 19;
const PORT_CTRL_LP_MODE: usize = 20;
const PORT_CTRL_LS_ACTIVE: usize = 21;
const PORT_CTRL_LS_LEVEL: usize = 22;
const PORT_CTRL_LS_FREQ: usize = 23;
const PORT_CTRL_HS_ACTIVE: usize = 24;
const PORT_CTRL_HS_LEVEL: usize = 25;
const PORT_CTRL_HS_FREQ: usize = 26;
const PORT_CTRL_P1_ACTIVE: usize = 27;
const PORT_CTRL_P1_LEVEL: usize = 28;
const PORT_CTRL_P1_FREQ: usize = 29;
const PORT_CTRL_P1_Q: usize = 30;
const PORT_CTRL_P2_ACTIVE: usize = 31;
const PORT_CTRL_P2_LEVEL: usize = 32;
const PORT_CTRL_P2_FREQ: usize = 33;
const PORT_CTRL_P2_Q: usize = 34;
const PORT_CTRL_P3_ACTIVE: usize = 35;
const PORT_CTRL_P3_LEVEL: usize = 36;
const PORT_CTRL_P3_FREQ: usize = 37;
const PORT_CTRL_P3_Q: usize = 38;
const PORT_CTRL_P4_ACTIVE: usize = 39;
const PORT_CTRL_P4_LEVEL: usize = 40;
const PORT_CTRL_P4_FREQ: usize = 41;
const PORT_CTRL_P4_Q: usize = 42;
const PORT_CTRL_P5_ACTIVE: usize = 43;
const PORT_CTRL_P5_LEVEL: usize = 44;
const PORT_CTRL_P5_FREQ: usize = 45;
const PORT_CTRL_P5_Q: usize = 46;
const PORT_CTRL_P6_ACTIVE: usize = 47;
const PORT_CTRL_P6_LEVEL: usize = 48;
const PORT_CTRL_P6_FREQ: usize = 49;
const PORT_CTRL_P6_Q: usize = 50;
const PORT_CTRL_P7_ACTIVE: usize = 51;
const PORT_CTRL_P7_LEVEL: usize = 52;
const PORT_CTRL_P7_FREQ: usize = 53;
const PORT_CTRL_P7_Q: usize = 54;
const PORT_CTRL_P8_ACTIVE: usize = 55;
const PORT_CTRL_P8_LEVEL: usize = 56;
const PORT_CTRL_P8_FREQ: usize = 57;
const PORT_CTRL_P8_Q: usize = 58;
const PORT_CTRL_INDIVIDUALS: usize = 59;
const PORT_CTRL_ZOOM: usize = 60;
const PORT_CTRL_ANALYZER: usize = 61;
const PORT_CTRL_ANALYZER_MODE: usize = 62;

pub fn model_schema() -> ModelParameterSchema {
    ModelParameterSchema {
        effect_type: block_core::EFFECT_TYPE_FILTER.into(),
        model: MODEL_ID.into(),
        display_name: DISPLAY_NAME.into(),
        audio_mode: ModelAudioMode::TrueStereo,
        parameters: vec![
            bool_parameter("bypass", "Bypass", None, Some(false)),
            float_parameter("level_in", "Input Gain", None, Some(1.0), 0.015625, 64.0, 0.1, ParameterUnit::None),
            float_parameter("level_out", "Output Gain", None, Some(1.0), 0.015625, 64.0, 0.1, ParameterUnit::None),
            float_parameter("hp_active", "HP Active", None, Some(0.0), 0.0, 5.0, 0.01, ParameterUnit::None),
            float_parameter("hp_freq", "HP Freq", None, Some(30.0), 10.0, 20000.0, 10.0, ParameterUnit::Hertz),
            float_parameter("hp_mode", "HP Mode", None, Some(1.0), 0.0, 2.0, 0.01, ParameterUnit::None),
            float_parameter("lp_active", "LP Active", None, Some(0.0), 0.0, 5.0, 0.01, ParameterUnit::None),
            float_parameter("lp_freq", "LP Freq", None, Some(18000.0), 10.0, 20000.0, 10.0, ParameterUnit::Hertz),
            float_parameter("lp_mode", "LP Mode", None, Some(1.0), 0.0, 2.0, 0.01, ParameterUnit::None),
            float_parameter("ls_active", "LS Active", None, Some(0.0), 0.0, 5.0, 0.01, ParameterUnit::None),
            float_parameter("ls_level", "Level L", None, Some(1.0), 0.015625, 64.0, 0.1, ParameterUnit::None),
            float_parameter("ls_freq", "Freq L", None, Some(100.0), 10.0, 20000.0, 10.0, ParameterUnit::Hertz),
            float_parameter("hs_active", "HS Active", None, Some(0.0), 0.0, 5.0, 0.01, ParameterUnit::None),
            float_parameter("hs_level", "Level H", None, Some(1.0), 0.015625, 64.0, 0.1, ParameterUnit::None),
            float_parameter("hs_freq", "Freq H", None, Some(5000.0), 10.0, 20000.0, 10.0, ParameterUnit::Hertz),
            float_parameter("p1_active", "F1 Active", None, Some(0.0), 0.0, 5.0, 0.01, ParameterUnit::None),
            float_parameter("p1_level", "Level 1", None, Some(1.0), 0.015625, 64.0, 0.1, ParameterUnit::None),
            float_parameter("p1_freq", "Freq 1", None, Some(60.0), 10.0, 20000.0, 10.0, ParameterUnit::Hertz),
            float_parameter("p1_q", "Q 1", None, Some(1.0), 0.1, 100.0, 0.1, ParameterUnit::None),
            float_parameter("p2_active", "F2 Active", None, Some(0.0), 0.0, 5.0, 0.01, ParameterUnit::None),
            float_parameter("p2_level", "Level 2", None, Some(1.0), 0.015625, 64.0, 0.1, ParameterUnit::None),
            float_parameter("p2_freq", "Freq 2", None, Some(120.0), 10.0, 20000.0, 10.0, ParameterUnit::Hertz),
            float_parameter("p2_q", "Q 2", None, Some(1.0), 0.1, 100.0, 0.1, ParameterUnit::None),
            float_parameter("p3_active", "F3 Active", None, Some(0.0), 0.0, 5.0, 0.01, ParameterUnit::None),
            float_parameter("p3_level", "Level 3", None, Some(1.0), 0.015625, 64.0, 0.1, ParameterUnit::None),
            float_parameter("p3_freq", "Freq 3", None, Some(250.0), 10.0, 20000.0, 10.0, ParameterUnit::Hertz),
            float_parameter("p3_q", "Q 3", None, Some(1.0), 0.1, 100.0, 0.1, ParameterUnit::None),
            float_parameter("p4_active", "F4 Active", None, Some(0.0), 0.0, 5.0, 0.01, ParameterUnit::None),
            float_parameter("p4_level", "Level 4", None, Some(1.0), 0.015625, 64.0, 0.1, ParameterUnit::None),
            float_parameter("p4_freq", "Freq 4", None, Some(500.0), 10.0, 20000.0, 10.0, ParameterUnit::Hertz),
            float_parameter("p4_q", "Q 4", None, Some(1.0), 0.1, 100.0, 0.1, ParameterUnit::None),
            float_parameter("p5_active", "F5 Active", None, Some(0.0), 0.0, 5.0, 0.01, ParameterUnit::None),
            float_parameter("p5_level", "Level 5", None, Some(1.0), 0.015625, 64.0, 0.1, ParameterUnit::None),
            float_parameter("p5_freq", "Freq 5", None, Some(1000.0), 10.0, 20000.0, 10.0, ParameterUnit::Hertz),
            float_parameter("p5_q", "Q 5", None, Some(1.0), 0.1, 100.0, 0.1, ParameterUnit::None),
            float_parameter("p6_active", "F6 Active", None, Some(0.0), 0.0, 5.0, 0.01, ParameterUnit::None),
            float_parameter("p6_level", "Level 6", None, Some(1.0), 0.015625, 64.0, 0.1, ParameterUnit::None),
            float_parameter("p6_freq", "Freq 6", None, Some(2000.0), 10.0, 20000.0, 10.0, ParameterUnit::Hertz),
            float_parameter("p6_q", "Q 6", None, Some(1.0), 0.1, 100.0, 0.1, ParameterUnit::None),
            float_parameter("p7_active", "F7 Active", None, Some(0.0), 0.0, 5.0, 0.01, ParameterUnit::None),
            float_parameter("p7_level", "Level 7", None, Some(1.0), 0.015625, 64.0, 0.1, ParameterUnit::None),
            float_parameter("p7_freq", "Freq 7", None, Some(4000.0), 10.0, 20000.0, 10.0, ParameterUnit::Hertz),
            float_parameter("p7_q", "Q 7", None, Some(1.0), 0.1, 100.0, 0.1, ParameterUnit::None),
            float_parameter("p8_active", "F8 Active", None, Some(0.0), 0.0, 5.0, 0.01, ParameterUnit::None),
            float_parameter("p8_level", "Level 8", None, Some(1.0), 0.015625, 64.0, 0.1, ParameterUnit::None),
            float_parameter("p8_freq", "Freq 8", None, Some(8000.0), 10.0, 20000.0, 10.0, ParameterUnit::Hertz),
            float_parameter("p8_q", "Q 8", None, Some(1.0), 0.1, 100.0, 0.1, ParameterUnit::None),
            bool_parameter("individuals", "Individual Filters", None, Some(true)),
            float_parameter("zoom", "Zoom", None, Some(0.25), 0.0625, 1.0, 0.001, ParameterUnit::None),
            bool_parameter("analyzer", "Analyzer Active", None, Some(false)),
            float_parameter("analyzer_mode", "Analyzer Mode", None, Some(1.0), 0.0, 2.0, 0.01, ParameterUnit::None),
        ],
    }
}

fn build(params: &ParameterSet, sample_rate: f32, layout: AudioChannelLayout) -> Result<BlockProcessor> {
    let bypass = required_bool(params, "bypass").map_err(anyhow::Error::msg)?;
    let level_in = required_f32(params, "level_in").map_err(anyhow::Error::msg)?;
    let level_out = required_f32(params, "level_out").map_err(anyhow::Error::msg)?;
    let hp_active = required_f32(params, "hp_active").map_err(anyhow::Error::msg)?;
    let hp_freq = required_f32(params, "hp_freq").map_err(anyhow::Error::msg)?;
    let hp_mode = required_f32(params, "hp_mode").map_err(anyhow::Error::msg)?;
    let lp_active = required_f32(params, "lp_active").map_err(anyhow::Error::msg)?;
    let lp_freq = required_f32(params, "lp_freq").map_err(anyhow::Error::msg)?;
    let lp_mode = required_f32(params, "lp_mode").map_err(anyhow::Error::msg)?;
    let ls_active = required_f32(params, "ls_active").map_err(anyhow::Error::msg)?;
    let ls_level = required_f32(params, "ls_level").map_err(anyhow::Error::msg)?;
    let ls_freq = required_f32(params, "ls_freq").map_err(anyhow::Error::msg)?;
    let hs_active = required_f32(params, "hs_active").map_err(anyhow::Error::msg)?;
    let hs_level = required_f32(params, "hs_level").map_err(anyhow::Error::msg)?;
    let hs_freq = required_f32(params, "hs_freq").map_err(anyhow::Error::msg)?;
    let p1_active = required_f32(params, "p1_active").map_err(anyhow::Error::msg)?;
    let p1_level = required_f32(params, "p1_level").map_err(anyhow::Error::msg)?;
    let p1_freq = required_f32(params, "p1_freq").map_err(anyhow::Error::msg)?;
    let p1_q = required_f32(params, "p1_q").map_err(anyhow::Error::msg)?;
    let p2_active = required_f32(params, "p2_active").map_err(anyhow::Error::msg)?;
    let p2_level = required_f32(params, "p2_level").map_err(anyhow::Error::msg)?;
    let p2_freq = required_f32(params, "p2_freq").map_err(anyhow::Error::msg)?;
    let p2_q = required_f32(params, "p2_q").map_err(anyhow::Error::msg)?;
    let p3_active = required_f32(params, "p3_active").map_err(anyhow::Error::msg)?;
    let p3_level = required_f32(params, "p3_level").map_err(anyhow::Error::msg)?;
    let p3_freq = required_f32(params, "p3_freq").map_err(anyhow::Error::msg)?;
    let p3_q = required_f32(params, "p3_q").map_err(anyhow::Error::msg)?;
    let p4_active = required_f32(params, "p4_active").map_err(anyhow::Error::msg)?;
    let p4_level = required_f32(params, "p4_level").map_err(anyhow::Error::msg)?;
    let p4_freq = required_f32(params, "p4_freq").map_err(anyhow::Error::msg)?;
    let p4_q = required_f32(params, "p4_q").map_err(anyhow::Error::msg)?;
    let p5_active = required_f32(params, "p5_active").map_err(anyhow::Error::msg)?;
    let p5_level = required_f32(params, "p5_level").map_err(anyhow::Error::msg)?;
    let p5_freq = required_f32(params, "p5_freq").map_err(anyhow::Error::msg)?;
    let p5_q = required_f32(params, "p5_q").map_err(anyhow::Error::msg)?;
    let p6_active = required_f32(params, "p6_active").map_err(anyhow::Error::msg)?;
    let p6_level = required_f32(params, "p6_level").map_err(anyhow::Error::msg)?;
    let p6_freq = required_f32(params, "p6_freq").map_err(anyhow::Error::msg)?;
    let p6_q = required_f32(params, "p6_q").map_err(anyhow::Error::msg)?;
    let p7_active = required_f32(params, "p7_active").map_err(anyhow::Error::msg)?;
    let p7_level = required_f32(params, "p7_level").map_err(anyhow::Error::msg)?;
    let p7_freq = required_f32(params, "p7_freq").map_err(anyhow::Error::msg)?;
    let p7_q = required_f32(params, "p7_q").map_err(anyhow::Error::msg)?;
    let p8_active = required_f32(params, "p8_active").map_err(anyhow::Error::msg)?;
    let p8_level = required_f32(params, "p8_level").map_err(anyhow::Error::msg)?;
    let p8_freq = required_f32(params, "p8_freq").map_err(anyhow::Error::msg)?;
    let p8_q = required_f32(params, "p8_q").map_err(anyhow::Error::msg)?;
    let individuals = required_bool(params, "individuals").map_err(anyhow::Error::msg)?;
    let zoom = required_f32(params, "zoom").map_err(anyhow::Error::msg)?;
    let analyzer = required_bool(params, "analyzer").map_err(anyhow::Error::msg)?;
    let analyzer_mode = required_f32(params, "analyzer_mode").map_err(anyhow::Error::msg)?;
    let lib_path = lv2::resolve_lv2_lib(PLUGIN_BINARY)?;
    let bundle_path = lv2::resolve_lv2_bundle(PLUGIN_DIR)?;

    let control_ports: &[(usize, f32)] = &[
        (PORT_CTRL_BYPASS, if bypass { 1.0 } else { 0.0 }),
        (PORT_CTRL_LEVEL_IN, level_in),
        (PORT_CTRL_LEVEL_OUT, level_out),
        (PORT_CTRL_HP_ACTIVE, hp_active),
        (PORT_CTRL_HP_FREQ, hp_freq),
        (PORT_CTRL_HP_MODE, hp_mode),
        (PORT_CTRL_LP_ACTIVE, lp_active),
        (PORT_CTRL_LP_FREQ, lp_freq),
        (PORT_CTRL_LP_MODE, lp_mode),
        (PORT_CTRL_LS_ACTIVE, ls_active),
        (PORT_CTRL_LS_LEVEL, ls_level),
        (PORT_CTRL_LS_FREQ, ls_freq),
        (PORT_CTRL_HS_ACTIVE, hs_active),
        (PORT_CTRL_HS_LEVEL, hs_level),
        (PORT_CTRL_HS_FREQ, hs_freq),
        (PORT_CTRL_P1_ACTIVE, p1_active),
        (PORT_CTRL_P1_LEVEL, p1_level),
        (PORT_CTRL_P1_FREQ, p1_freq),
        (PORT_CTRL_P1_Q, p1_q),
        (PORT_CTRL_P2_ACTIVE, p2_active),
        (PORT_CTRL_P2_LEVEL, p2_level),
        (PORT_CTRL_P2_FREQ, p2_freq),
        (PORT_CTRL_P2_Q, p2_q),
        (PORT_CTRL_P3_ACTIVE, p3_active),
        (PORT_CTRL_P3_LEVEL, p3_level),
        (PORT_CTRL_P3_FREQ, p3_freq),
        (PORT_CTRL_P3_Q, p3_q),
        (PORT_CTRL_P4_ACTIVE, p4_active),
        (PORT_CTRL_P4_LEVEL, p4_level),
        (PORT_CTRL_P4_FREQ, p4_freq),
        (PORT_CTRL_P4_Q, p4_q),
        (PORT_CTRL_P5_ACTIVE, p5_active),
        (PORT_CTRL_P5_LEVEL, p5_level),
        (PORT_CTRL_P5_FREQ, p5_freq),
        (PORT_CTRL_P5_Q, p5_q),
        (PORT_CTRL_P6_ACTIVE, p6_active),
        (PORT_CTRL_P6_LEVEL, p6_level),
        (PORT_CTRL_P6_FREQ, p6_freq),
        (PORT_CTRL_P6_Q, p6_q),
        (PORT_CTRL_P7_ACTIVE, p7_active),
        (PORT_CTRL_P7_LEVEL, p7_level),
        (PORT_CTRL_P7_FREQ, p7_freq),
        (PORT_CTRL_P7_Q, p7_q),
        (PORT_CTRL_P8_ACTIVE, p8_active),
        (PORT_CTRL_P8_LEVEL, p8_level),
        (PORT_CTRL_P8_FREQ, p8_freq),
        (PORT_CTRL_P8_Q, p8_q),
        (PORT_CTRL_INDIVIDUALS, if individuals { 1.0 } else { 0.0 }),
        (PORT_CTRL_ZOOM, zoom),
        (PORT_CTRL_ANALYZER, if analyzer { 1.0 } else { 0.0 }),
        (PORT_CTRL_ANALYZER_MODE, analyzer_mode),
    ];

    let processor = lv2::build_stereo_lv2_processor(&lib_path, PLUGIN_URI, sample_rate as f64, &bundle_path, &[PORT_AUDIO_IN_IN_L, PORT_AUDIO_IN_IN_R], &[PORT_AUDIO_OUT_OUT_L, PORT_AUDIO_OUT_OUT_R], control_ports)?;
    let _ = layout;
    Ok(BlockProcessor::Stereo(Box::new(processor)))
}

fn schema() -> Result<ModelParameterSchema> { Ok(model_schema()) }

pub const MODEL_DEFINITION: FilterModelDefinition = FilterModelDefinition {
    id: MODEL_ID, display_name: DISPLAY_NAME, brand: BRAND,
    backend_kind: FilterBackendKind::Lv2, schema, build,
    supported_instruments: block_core::ALL_INSTRUMENTS, knob_layout: &[],
};
