// AUTO-GENERATED by tools/lv2_catalog_import — do not edit by hand.
// Re-run the tool to regenerate. Manual customisation goes in overrides.yaml.

#![allow(dead_code, unused_imports, unused_variables, clippy::approx_constant, clippy::excessive_precision)]

use crate::registry::FilterModelDefinition;
use crate::FilterBackendKind;
use anyhow::Result;
use block_core::param::{
    float_parameter, required_f32, ModelParameterSchema, ParameterSet, ParameterUnit,
};
use block_core::{AudioChannelLayout, BlockProcessor, ModelAudioMode, MonoProcessor, StereoProcessor};

pub const MODEL_ID: &str = "lv2_gx_gcb_95";
pub const DISPLAY_NAME: &str = "GxCrybabyGCB95";
const BRAND: &str = "guitarix";

const PLUGIN_URI: &str = "http://guitarix.sourceforge.net/plugins/gx_gcb_95_#_gcb_95_";
const PLUGIN_DIR: &str = "gx_gcb_95";

#[cfg(target_os = "macos")]
const PLUGIN_BINARY: &str = "gx_gcb_95.dylib";
#[cfg(target_os = "linux")]
const PLUGIN_BINARY: &str = "gx_gcb_95.so";
#[cfg(target_os = "windows")]
const PLUGIN_BINARY: &str = "gx_gcb_95.dll";

// Port indices (from TTL)
const PORT_AUDIO_OUT_OUT: usize = 0;
const PORT_AUDIO_IN_IN: usize = 1;
const PORT_CTRL_VOLUME: usize = 2;
const PORT_CTRL_HOTPOTZ: usize = 3;

pub fn model_schema() -> ModelParameterSchema {
    ModelParameterSchema {
        effect_type: block_core::EFFECT_TYPE_FILTER.into(),
        model: MODEL_ID.into(),
        display_name: DISPLAY_NAME.into(),
        audio_mode: ModelAudioMode::DualMono,
        parameters: vec![
            float_parameter("volume", "VOLUME", None, Some(0.0), -20.0, 4.0, 0.1, ParameterUnit::None),
            float_parameter("hotpotz", "WAH", None, Some(0.5), 0.0, 1.0, 0.01, ParameterUnit::None),
        ],
    }
}

fn build(params: &ParameterSet, sample_rate: f32, layout: AudioChannelLayout) -> Result<BlockProcessor> {
    let volume = required_f32(params, "volume").map_err(anyhow::Error::msg)?;
    let hotpotz = required_f32(params, "hotpotz").map_err(anyhow::Error::msg)?;
    let lib_path = lv2::resolve_lv2_lib(PLUGIN_BINARY)?;
    let bundle_path = lv2::resolve_lv2_bundle(PLUGIN_DIR)?;

    let control_ports: &[(usize, f32)] = &[
        (PORT_CTRL_VOLUME, volume),
        (PORT_CTRL_HOTPOTZ, hotpotz),
    ];

    match layout {
        AudioChannelLayout::Mono => {
            let processor = lv2::build_lv2_processor(&lib_path, PLUGIN_URI, sample_rate as f64, &bundle_path, &[PORT_AUDIO_IN_IN], &[PORT_AUDIO_OUT_OUT], control_ports)?;
            Ok(BlockProcessor::Mono(Box::new(processor)))
        }
        AudioChannelLayout::Stereo => {
            let left = lv2::build_lv2_processor(&lib_path, PLUGIN_URI, sample_rate as f64, &bundle_path, &[PORT_AUDIO_IN_IN], &[PORT_AUDIO_OUT_OUT], control_ports)?;
            let right = lv2::build_lv2_processor(&lib_path, PLUGIN_URI, sample_rate as f64, &bundle_path, &[PORT_AUDIO_IN_IN], &[PORT_AUDIO_OUT_OUT], control_ports)?;
            Ok(BlockProcessor::Stereo(Box::new(DualMonoProcessor { left, right })))
        }
    }
}

struct DualMonoProcessor { left: lv2::Lv2Processor, right: lv2::Lv2Processor }
impl StereoProcessor for DualMonoProcessor {
    fn process_frame(&mut self, input: [f32; 2]) -> [f32; 2] {
        [self.left.process_sample(input[0]), self.right.process_sample(input[1])]
    }
}

fn schema() -> Result<ModelParameterSchema> { Ok(model_schema()) }

pub const MODEL_DEFINITION: FilterModelDefinition = FilterModelDefinition {
    id: MODEL_ID, display_name: DISPLAY_NAME, brand: BRAND,
    backend_kind: FilterBackendKind::Lv2, schema, build,
    supported_instruments: block_core::ALL_INSTRUMENTS, knob_layout: &[],
};
