// AUTO-GENERATED by tools/lv2_catalog_import — do not edit by hand.
// Re-run the tool to regenerate. Manual customisation goes in overrides.yaml.

#![allow(dead_code, unused_imports, unused_variables, clippy::approx_constant, clippy::excessive_precision)]

use crate::registry::FilterModelDefinition;
use crate::FilterBackendKind;
use anyhow::Result;
use block_core::param::{
    float_parameter, required_f32, ModelParameterSchema, ParameterSet, ParameterUnit,
};
use block_core::{AudioChannelLayout, BlockProcessor, ModelAudioMode, MonoProcessor, StereoProcessor};

pub const MODEL_ID: &str = "lv2_mod_caps_auto_filter";
pub const DISPLAY_NAME: &str = "C* AutoFilter";
const BRAND: &str = "caps";

const PLUGIN_URI: &str = "http://moddevices.com/plugins/caps/AutoFilter";
const PLUGIN_DIR: &str = "mod-caps-AutoFilter";

#[cfg(target_os = "macos")]
const PLUGIN_BINARY: &str = "AutoFilter.dylib.dylib";
#[cfg(target_os = "linux")]
const PLUGIN_BINARY: &str = "AutoFilter.dylib.so";
#[cfg(target_os = "windows")]
const PLUGIN_BINARY: &str = "AutoFilter.dylib.dll";

// Port indices (from TTL)
const PORT_CTRL_MODE: usize = 0;
const PORT_CTRL_FILTER: usize = 1;
const PORT_CTRL_FREQUENCY: usize = 2;
const PORT_CTRL_Q: usize = 3;
const PORT_CTRL_DEPTH: usize = 4;
const PORT_CTRL_LFOENV: usize = 5;
const PORT_CTRL_RATE: usize = 6;
const PORT_CTRL_X_Z: usize = 7;
const PORT_AUDIO_IN_IN: usize = 8;
const PORT_AUDIO_OUT_OUT: usize = 9;

pub fn model_schema() -> ModelParameterSchema {
    ModelParameterSchema {
        effect_type: block_core::EFFECT_TYPE_FILTER.into(),
        model: MODEL_ID.into(),
        display_name: DISPLAY_NAME.into(),
        audio_mode: ModelAudioMode::DualMono,
        parameters: vec![
            float_parameter("mode", "Mode", None, Some(0.0), 0.0, 1.0, 0.01, ParameterUnit::None),
            float_parameter("filter", "Filter", None, Some(1.0), 0.0, 1.0, 0.01, ParameterUnit::None),
            float_parameter("frequency", "Frequency", None, Some(2500.0), 20.0, 3400.0, 10.0, ParameterUnit::Hertz),
            float_parameter("q", "Q", None, Some(0.27), 0.0, 1.0, 0.01, ParameterUnit::None),
            float_parameter("depth", "Depth", None, Some(0.81), 0.0, 1.0, 0.01, ParameterUnit::None),
            float_parameter("lfoenv", "LFO/Envelope", None, Some(0.16), 0.0, 1.0, 0.01, ParameterUnit::None),
            float_parameter("rate", "Rate", None, Some(0.26), 0.0, 1.0, 0.01, ParameterUnit::None),
            float_parameter("x_z", "X/Z", None, Some(0.35), 0.0, 1.0, 0.01, ParameterUnit::None),
        ],
    }
}

fn build(params: &ParameterSet, sample_rate: f32, layout: AudioChannelLayout) -> Result<BlockProcessor> {
    let mode = required_f32(params, "mode").map_err(anyhow::Error::msg)?;
    let filter = required_f32(params, "filter").map_err(anyhow::Error::msg)?;
    let frequency = required_f32(params, "frequency").map_err(anyhow::Error::msg)?;
    let q = required_f32(params, "q").map_err(anyhow::Error::msg)?;
    let depth = required_f32(params, "depth").map_err(anyhow::Error::msg)?;
    let lfoenv = required_f32(params, "lfoenv").map_err(anyhow::Error::msg)?;
    let rate = required_f32(params, "rate").map_err(anyhow::Error::msg)?;
    let x_z = required_f32(params, "x_z").map_err(anyhow::Error::msg)?;
    let lib_path = lv2::resolve_lv2_lib(PLUGIN_BINARY)?;
    let bundle_path = lv2::resolve_lv2_bundle(PLUGIN_DIR)?;

    let control_ports: &[(usize, f32)] = &[
        (PORT_CTRL_MODE, mode),
        (PORT_CTRL_FILTER, filter),
        (PORT_CTRL_FREQUENCY, frequency),
        (PORT_CTRL_Q, q),
        (PORT_CTRL_DEPTH, depth),
        (PORT_CTRL_LFOENV, lfoenv),
        (PORT_CTRL_RATE, rate),
        (PORT_CTRL_X_Z, x_z),
    ];

    match layout {
        AudioChannelLayout::Mono => {
            let processor = lv2::build_lv2_processor(&lib_path, PLUGIN_URI, sample_rate as f64, &bundle_path, &[PORT_AUDIO_IN_IN], &[PORT_AUDIO_OUT_OUT], control_ports)?;
            Ok(BlockProcessor::Mono(Box::new(processor)))
        }
        AudioChannelLayout::Stereo => {
            let left = lv2::build_lv2_processor(&lib_path, PLUGIN_URI, sample_rate as f64, &bundle_path, &[PORT_AUDIO_IN_IN], &[PORT_AUDIO_OUT_OUT], control_ports)?;
            let right = lv2::build_lv2_processor(&lib_path, PLUGIN_URI, sample_rate as f64, &bundle_path, &[PORT_AUDIO_IN_IN], &[PORT_AUDIO_OUT_OUT], control_ports)?;
            Ok(BlockProcessor::Stereo(Box::new(DualMonoProcessor { left, right })))
        }
    }
}

struct DualMonoProcessor { left: lv2::Lv2Processor, right: lv2::Lv2Processor }
impl StereoProcessor for DualMonoProcessor {
    fn process_frame(&mut self, input: [f32; 2]) -> [f32; 2] {
        [self.left.process_sample(input[0]), self.right.process_sample(input[1])]
    }
}

fn schema() -> Result<ModelParameterSchema> { Ok(model_schema()) }

pub const MODEL_DEFINITION: FilterModelDefinition = FilterModelDefinition {
    id: MODEL_ID, display_name: DISPLAY_NAME, brand: BRAND,
    backend_kind: FilterBackendKind::Lv2, schema, build,
    supported_instruments: block_core::ALL_INSTRUMENTS, knob_layout: &[],
};
