// AUTO-GENERATED by tools/lv2_catalog_import — do not edit by hand.
// Re-run the tool to regenerate. Manual customisation goes in overrides.yaml.

#![allow(dead_code, unused_imports, unused_variables, clippy::all)]

use crate::registry::FilterModelDefinition;
use crate::FilterBackendKind;
use anyhow::Result;
use block_core::param::{
    bool_parameter, float_parameter, required_bool, required_f32,
    ModelParameterSchema, ParameterSet, ParameterUnit,
};
use block_core::{AudioChannelLayout, BlockProcessor, ModelAudioMode};

pub const MODEL_ID: &str = "lv2_fil4_fil4_stereo";
pub const DISPLAY_NAME: &str = "x42-eq - Parametric Equalizer Stereo";
const BRAND: &str = "x42";

const PLUGIN_URI: &str = "http://gareus.org/oss/lv2/fil4#stereo";
const PLUGIN_DIR: &str = "fil4";

#[cfg(target_os = "macos")]
const PLUGIN_BINARY: &str = "fil4.dylib";
#[cfg(target_os = "linux")]
const PLUGIN_BINARY: &str = "fil4.so";
#[cfg(target_os = "windows")]
const PLUGIN_BINARY: &str = "fil4.dll";

// Port indices (from TTL)
const PORT_ATOM_IN_CONTROL: usize = 0;
const PORT_ATOM_OUT_NOTIFY: usize = 1;
const PORT_CTRL_ENABLE: usize = 2;
const PORT_CTRL_GAIN: usize = 3;
const PORT_CTRL_PEAK: usize = 4;
const PORT_CTRL_PEAKRESET: usize = 5;
const PORT_CTRL_HIGH_PASS: usize = 6;
const PORT_CTRL_H_PFREQ: usize = 7;
const PORT_CTRL_HPQ: usize = 8;
const PORT_CTRL_LOW_PASS: usize = 9;
const PORT_CTRL_L_PFREQ: usize = 10;
const PORT_CTRL_LPQ: usize = 11;
const PORT_CTRL_L_SSEC: usize = 12;
const PORT_CTRL_L_SFREQ: usize = 13;
const PORT_CTRL_L_SQ: usize = 14;
const PORT_CTRL_L_SGAIN: usize = 15;
const PORT_CTRL_SEC1: usize = 16;
const PORT_CTRL_FREQ1: usize = 17;
const PORT_CTRL_Q1: usize = 18;
const PORT_CTRL_GAIN1: usize = 19;
const PORT_CTRL_SEC2: usize = 20;
const PORT_CTRL_FREQ2: usize = 21;
const PORT_CTRL_Q2: usize = 22;
const PORT_CTRL_GAIN2: usize = 23;
const PORT_CTRL_SEC3: usize = 24;
const PORT_CTRL_FREQ3: usize = 25;
const PORT_CTRL_Q3: usize = 26;
const PORT_CTRL_GAIN3: usize = 27;
const PORT_CTRL_SEC4: usize = 28;
const PORT_CTRL_FREQ4: usize = 29;
const PORT_CTRL_Q4: usize = 30;
const PORT_CTRL_GAIN4: usize = 31;
const PORT_CTRL_H_SSEC: usize = 32;
const PORT_CTRL_H_SFREQ: usize = 33;
const PORT_CTRL_H_SQ: usize = 34;
const PORT_CTRL_H_SGAIN: usize = 35;
const PORT_AUDIO_IN_IN_L: usize = 36;
const PORT_AUDIO_OUT_OUT_L: usize = 37;
const PORT_AUDIO_IN_IN_R: usize = 38;
const PORT_AUDIO_OUT_OUT_R: usize = 39;

pub fn model_schema() -> ModelParameterSchema {
    ModelParameterSchema {
        effect_type: block_core::EFFECT_TYPE_FILTER.into(),
        model: MODEL_ID.into(),
        display_name: DISPLAY_NAME.into(),
        audio_mode: ModelAudioMode::TrueStereo,
        parameters: vec![
            bool_parameter("enable", "Enable", None, Some(true)),
            float_parameter("gain", "Gain", None, Some(0.0), -18.0, 18.0, 0.1, ParameterUnit::Decibels),
            bool_parameter("peakreset", "Reset Peak Hold", None, Some(true)),
            bool_parameter("highpass", "Highpass", None, Some(false)),
            float_parameter("hpfreq", "Highpass Frequency", None, Some(20.0), 5.0, 1250.0, 10.0, ParameterUnit::Hertz),
            float_parameter("hpq", "HighPass Resonance", None, Some(0.7), 0.0, 1.4, 0.01, ParameterUnit::None),
            bool_parameter("lowpass", "Lowpass", None, Some(false)),
            float_parameter("lpfreq", "Lowpass Frequency", None, Some(20000.0), 500.0, 20000.0, 10.0, ParameterUnit::Hertz),
            float_parameter("lpq", "LowPass Resonance", None, Some(1.0), 0.0, 1.4, 0.01, ParameterUnit::None),
            bool_parameter("lssec", "Lowshelf", None, Some(true)),
            float_parameter("lsfreq", "Lowshelf Frequency", None, Some(80.0), 25.0, 400.0, 1.0, ParameterUnit::Hertz),
            float_parameter("lsq", "Lowshelf Bandwidth", None, Some(1.0), 0.0625, 4.0, 0.01, ParameterUnit::None),
            float_parameter("lsgain", "Lowshelf Gain", None, Some(0.0), -18.0, 18.0, 0.1, ParameterUnit::Decibels),
            bool_parameter("sec1", "Section 1", None, Some(true)),
            float_parameter("freq1", "Frequency 1", None, Some(160.0), 20.0, 2000.0, 10.0, ParameterUnit::Hertz),
            float_parameter("q1", "Bandwidth 1", None, Some(0.6), 0.0625, 4.0, 0.01, ParameterUnit::None),
            float_parameter("gain1", "Gain 1", None, Some(0.0), -18.0, 18.0, 0.1, ParameterUnit::Decibels),
            bool_parameter("sec2", "Section 2", None, Some(true)),
            float_parameter("freq2", "Frequency 2", None, Some(397.0), 40.0, 4000.0, 10.0, ParameterUnit::Hertz),
            float_parameter("q2", "Bandwidth 2", None, Some(0.6), 0.0625, 4.0, 0.01, ParameterUnit::None),
            float_parameter("gain2", "Gain 2", None, Some(0.0), -18.0, 18.0, 0.1, ParameterUnit::Decibels),
            bool_parameter("sec3", "Section 3", None, Some(true)),
            float_parameter("freq3", "Frequency 3", None, Some(1250.0), 100.0, 10000.0, 10.0, ParameterUnit::Hertz),
            float_parameter("q3", "Bandwidth 3", None, Some(0.6), 0.0625, 4.0, 0.01, ParameterUnit::None),
            float_parameter("gain3", "Gain 3", None, Some(0.0), -18.0, 18.0, 0.1, ParameterUnit::Decibels),
            bool_parameter("sec4", "Section 4", None, Some(true)),
            float_parameter("freq4", "Frequency 4", None, Some(2500.0), 200.0, 20000.0, 10.0, ParameterUnit::Hertz),
            float_parameter("q4", "Bandwidth 4", None, Some(0.6), 0.0625, 4.0, 0.01, ParameterUnit::None),
            float_parameter("gain4", "Gain 4", None, Some(0.0), -18.0, 18.0, 0.1, ParameterUnit::Decibels),
            bool_parameter("hssec", "Highshelf", None, Some(true)),
            float_parameter("hsfreq", "Highshelf Frequency", None, Some(8000.0), 1000.0, 16000.0, 10.0, ParameterUnit::Hertz),
            float_parameter("hsq", "Highshelf Bandwidth", None, Some(1.0), 0.0625, 4.0, 0.01, ParameterUnit::None),
            float_parameter("hsgain", "Highshelf Gain", None, Some(0.0), -18.0, 18.0, 0.1, ParameterUnit::Decibels),
        ],
    }
}

fn build(params: &ParameterSet, sample_rate: f32, layout: AudioChannelLayout) -> Result<BlockProcessor> {
    let enable = required_bool(params, "enable").map_err(anyhow::Error::msg)?;
    let gain = required_f32(params, "gain").map_err(anyhow::Error::msg)?;
    let peakreset = required_bool(params, "peakreset").map_err(anyhow::Error::msg)?;
    let highpass = required_bool(params, "highpass").map_err(anyhow::Error::msg)?;
    let hpfreq = required_f32(params, "hpfreq").map_err(anyhow::Error::msg)?;
    let hpq = required_f32(params, "hpq").map_err(anyhow::Error::msg)?;
    let lowpass = required_bool(params, "lowpass").map_err(anyhow::Error::msg)?;
    let lpfreq = required_f32(params, "lpfreq").map_err(anyhow::Error::msg)?;
    let lpq = required_f32(params, "lpq").map_err(anyhow::Error::msg)?;
    let lssec = required_bool(params, "lssec").map_err(anyhow::Error::msg)?;
    let lsfreq = required_f32(params, "lsfreq").map_err(anyhow::Error::msg)?;
    let lsq = required_f32(params, "lsq").map_err(anyhow::Error::msg)?;
    let lsgain = required_f32(params, "lsgain").map_err(anyhow::Error::msg)?;
    let sec1 = required_bool(params, "sec1").map_err(anyhow::Error::msg)?;
    let freq1 = required_f32(params, "freq1").map_err(anyhow::Error::msg)?;
    let q1 = required_f32(params, "q1").map_err(anyhow::Error::msg)?;
    let gain1 = required_f32(params, "gain1").map_err(anyhow::Error::msg)?;
    let sec2 = required_bool(params, "sec2").map_err(anyhow::Error::msg)?;
    let freq2 = required_f32(params, "freq2").map_err(anyhow::Error::msg)?;
    let q2 = required_f32(params, "q2").map_err(anyhow::Error::msg)?;
    let gain2 = required_f32(params, "gain2").map_err(anyhow::Error::msg)?;
    let sec3 = required_bool(params, "sec3").map_err(anyhow::Error::msg)?;
    let freq3 = required_f32(params, "freq3").map_err(anyhow::Error::msg)?;
    let q3 = required_f32(params, "q3").map_err(anyhow::Error::msg)?;
    let gain3 = required_f32(params, "gain3").map_err(anyhow::Error::msg)?;
    let sec4 = required_bool(params, "sec4").map_err(anyhow::Error::msg)?;
    let freq4 = required_f32(params, "freq4").map_err(anyhow::Error::msg)?;
    let q4 = required_f32(params, "q4").map_err(anyhow::Error::msg)?;
    let gain4 = required_f32(params, "gain4").map_err(anyhow::Error::msg)?;
    let hssec = required_bool(params, "hssec").map_err(anyhow::Error::msg)?;
    let hsfreq = required_f32(params, "hsfreq").map_err(anyhow::Error::msg)?;
    let hsq = required_f32(params, "hsq").map_err(anyhow::Error::msg)?;
    let hsgain = required_f32(params, "hsgain").map_err(anyhow::Error::msg)?;
    let lib_path = lv2::resolve_lv2_lib(PLUGIN_BINARY)?;
    let bundle_path = lv2::resolve_lv2_bundle(PLUGIN_DIR)?;

    let control_ports: &[(usize, f32)] = &[
        (PORT_CTRL_ENABLE, if enable { 1.0 } else { 0.0 }),
        (PORT_CTRL_GAIN, gain),
        (PORT_CTRL_PEAKRESET, if peakreset { 1.0 } else { 0.0 }),
        (PORT_CTRL_HIGH_PASS, if highpass { 1.0 } else { 0.0 }),
        (PORT_CTRL_H_PFREQ, hpfreq),
        (PORT_CTRL_HPQ, hpq),
        (PORT_CTRL_LOW_PASS, if lowpass { 1.0 } else { 0.0 }),
        (PORT_CTRL_L_PFREQ, lpfreq),
        (PORT_CTRL_LPQ, lpq),
        (PORT_CTRL_L_SSEC, if lssec { 1.0 } else { 0.0 }),
        (PORT_CTRL_L_SFREQ, lsfreq),
        (PORT_CTRL_L_SQ, lsq),
        (PORT_CTRL_L_SGAIN, lsgain),
        (PORT_CTRL_SEC1, if sec1 { 1.0 } else { 0.0 }),
        (PORT_CTRL_FREQ1, freq1),
        (PORT_CTRL_Q1, q1),
        (PORT_CTRL_GAIN1, gain1),
        (PORT_CTRL_SEC2, if sec2 { 1.0 } else { 0.0 }),
        (PORT_CTRL_FREQ2, freq2),
        (PORT_CTRL_Q2, q2),
        (PORT_CTRL_GAIN2, gain2),
        (PORT_CTRL_SEC3, if sec3 { 1.0 } else { 0.0 }),
        (PORT_CTRL_FREQ3, freq3),
        (PORT_CTRL_Q3, q3),
        (PORT_CTRL_GAIN3, gain3),
        (PORT_CTRL_SEC4, if sec4 { 1.0 } else { 0.0 }),
        (PORT_CTRL_FREQ4, freq4),
        (PORT_CTRL_Q4, q4),
        (PORT_CTRL_GAIN4, gain4),
        (PORT_CTRL_H_SSEC, if hssec { 1.0 } else { 0.0 }),
        (PORT_CTRL_H_SFREQ, hsfreq),
        (PORT_CTRL_H_SQ, hsq),
        (PORT_CTRL_H_SGAIN, hsgain),
    ];

    let processor = lv2::build_stereo_lv2_processor(&lib_path, PLUGIN_URI, sample_rate as f64, &bundle_path, &[PORT_AUDIO_IN_IN_L, PORT_AUDIO_IN_IN_R], &[PORT_AUDIO_OUT_OUT_L, PORT_AUDIO_OUT_OUT_R], control_ports)?;
    let _ = layout;
    Ok(BlockProcessor::Stereo(Box::new(processor)))
}

fn schema() -> Result<ModelParameterSchema> { Ok(model_schema()) }

pub const MODEL_DEFINITION: FilterModelDefinition = FilterModelDefinition {
    id: MODEL_ID, display_name: DISPLAY_NAME, brand: BRAND,
    backend_kind: FilterBackendKind::Lv2, schema, build,
    supported_instruments: block_core::ALL_INSTRUMENTS, knob_layout: &[],
};
