// AUTO-GENERATED by tools/lv2_catalog_import — do not edit by hand.
// Re-run the tool to regenerate. Manual customisation goes in overrides.yaml.

#![allow(dead_code, unused_imports, unused_variables, clippy::all)]

use crate::registry::FilterModelDefinition;
use crate::FilterBackendKind;
use anyhow::Result;
use block_core::param::{
    float_parameter, required_f32, ModelParameterSchema, ParameterSet, ParameterUnit,
};
use block_core::{AudioChannelLayout, BlockProcessor, ModelAudioMode};

pub const MODEL_ID: &str = "lv2_calf_bad_filterclavier";
pub const DISPLAY_NAME: &str = "Calf Filterclavier";
const BRAND: &str = "calf";

const PLUGIN_URI: &str = "http://calf.sourceforge.net/plugins/Filterclavier";
const PLUGIN_DIR: &str = "calf-bad";

#[cfg(target_os = "macos")]
const PLUGIN_BINARY: &str = "calf.dylib";
#[cfg(target_os = "linux")]
const PLUGIN_BINARY: &str = "calf.so";
#[cfg(target_os = "windows")]
const PLUGIN_BINARY: &str = "calf.dll";

// Port indices (from TTL)
const PORT_AUDIO_IN_IN_L: usize = 0;
const PORT_AUDIO_IN_IN_R: usize = 1;
const PORT_AUDIO_OUT_OUT_L: usize = 2;
const PORT_AUDIO_OUT_OUT_R: usize = 3;
const PORT_CTRL_TRANSPOSE: usize = 4;
const PORT_CTRL_DETUNE: usize = 5;
const PORT_CTRL_MAXRES: usize = 6;
const PORT_CTRL_MODE: usize = 7;
const PORT_CTRL_INERTIA: usize = 8;
const PORT_ATOM_IN_MIDI_IN: usize = 9;

pub fn model_schema() -> ModelParameterSchema {
    ModelParameterSchema {
        effect_type: block_core::EFFECT_TYPE_FILTER.into(),
        model: MODEL_ID.into(),
        display_name: DISPLAY_NAME.into(),
        audio_mode: ModelAudioMode::TrueStereo,
        parameters: vec![
            float_parameter("transpose", "Transpose", None, Some(0.0), -48.0, 48.0, 0.1, ParameterUnit::None),
            float_parameter("detune", "Detune", None, Some(0.0), -100.0, 100.0, 1.0, ParameterUnit::None),
            float_parameter("maxres", "Max. Resonance", None, Some(32.0), 0.707, 32.0, 0.1, ParameterUnit::None),
            float_parameter("mode", "Mode", None, Some(6.0), 0.0, 11.0, 0.1, ParameterUnit::None),
            float_parameter("inertia", "Portamento time", None, Some(20.0), 1.0, 2000.0, 10.0, ParameterUnit::Milliseconds),
        ],
    }
}

fn build(params: &ParameterSet, sample_rate: f32, layout: AudioChannelLayout) -> Result<BlockProcessor> {
    let transpose = required_f32(params, "transpose").map_err(anyhow::Error::msg)?;
    let detune = required_f32(params, "detune").map_err(anyhow::Error::msg)?;
    let maxres = required_f32(params, "maxres").map_err(anyhow::Error::msg)?;
    let mode = required_f32(params, "mode").map_err(anyhow::Error::msg)?;
    let inertia = required_f32(params, "inertia").map_err(anyhow::Error::msg)?;
    let lib_path = lv2::resolve_lv2_lib(PLUGIN_BINARY)?;
    let bundle_path = lv2::resolve_lv2_bundle(PLUGIN_DIR)?;

    let control_ports: &[(usize, f32)] = &[
        (PORT_CTRL_TRANSPOSE, transpose),
        (PORT_CTRL_DETUNE, detune),
        (PORT_CTRL_MAXRES, maxres),
        (PORT_CTRL_MODE, mode),
        (PORT_CTRL_INERTIA, inertia),
    ];

    let processor = lv2::build_stereo_lv2_processor(&lib_path, PLUGIN_URI, sample_rate as f64, &bundle_path, &[PORT_AUDIO_IN_IN_L, PORT_AUDIO_IN_IN_R], &[PORT_AUDIO_OUT_OUT_L, PORT_AUDIO_OUT_OUT_R], control_ports)?;
    let _ = layout;
    Ok(BlockProcessor::Stereo(Box::new(processor)))
}

fn schema() -> Result<ModelParameterSchema> { Ok(model_schema()) }

pub const MODEL_DEFINITION: FilterModelDefinition = FilterModelDefinition {
    id: MODEL_ID, display_name: DISPLAY_NAME, brand: BRAND,
    backend_kind: FilterBackendKind::Lv2, schema, build,
    supported_instruments: block_core::ALL_INSTRUMENTS, knob_layout: &[],
};
