// AUTO-GENERATED by tools/lv2_catalog_import — do not edit by hand.
// Re-run the tool to regenerate. Manual customisation goes in overrides.yaml.

#![allow(dead_code, unused_imports, unused_variables, clippy::all)]

use crate::registry::FilterModelDefinition;
use crate::FilterBackendKind;
use anyhow::Result;
use block_core::param::{
    bool_parameter, float_parameter, required_bool, required_f32,
    ModelParameterSchema, ParameterSet, ParameterUnit,
};
use block_core::{AudioChannelLayout, BlockProcessor, ModelAudioMode};

pub const MODEL_ID: &str = "lv2_rkr_eqp";
pub const DISPLAY_NAME: &str = "rkr Parametric EQ";
const BRAND: &str = "rakarrack";

const PLUGIN_URI: &str = "http://rakarrack.sourceforge.net/effects.html#eqp";
const PLUGIN_DIR: &str = "rkr";

#[cfg(target_os = "macos")]
const PLUGIN_BINARY: &str = "rkrlv2.dylib";
#[cfg(target_os = "linux")]
const PLUGIN_BINARY: &str = "rkrlv2.so";
#[cfg(target_os = "windows")]
const PLUGIN_BINARY: &str = "rkrlv2.dll";

// Port indices (from TTL)
const PORT_AUDIO_IN_INPUT_L: usize = 0;
const PORT_AUDIO_IN_INPUT_R: usize = 1;
const PORT_AUDIO_OUT_OUTPUT_L: usize = 2;
const PORT_AUDIO_OUT_OUTPUT_R: usize = 3;
const PORT_CTRL_BYPASS: usize = 4;
const PORT_CTRL_GAIN: usize = 5;
const PORT_CTRL_LFREQ: usize = 6;
const PORT_CTRL_LGAIN: usize = 7;
const PORT_CTRL_LQ: usize = 8;
const PORT_CTRL_MFREQ: usize = 9;
const PORT_CTRL_MGAIN: usize = 10;
const PORT_CTRL_MQ: usize = 11;
const PORT_CTRL_HFREQ: usize = 12;
const PORT_CTRL_HGAIN: usize = 13;
const PORT_CTRL_HQ: usize = 14;

pub fn model_schema() -> ModelParameterSchema {
    ModelParameterSchema {
        effect_type: block_core::EFFECT_TYPE_FILTER.into(),
        model: MODEL_ID.into(),
        display_name: DISPLAY_NAME.into(),
        audio_mode: ModelAudioMode::TrueStereo,
        parameters: vec![
            bool_parameter("bypass", "Bypass", None, Some(false)),
            float_parameter("gain", "Gain", None, Some(0.0), -64.0, 63.0, 1.0, ParameterUnit::None),
            float_parameter("lfreq", "Low Frequency", None, Some(200.0), 20.0, 1000.0, 1.0, ParameterUnit::Hertz),
            float_parameter("lgain", "Low Gain", None, Some(0.0), -64.0, 63.0, 1.0, ParameterUnit::None),
            float_parameter("lq", "Low Q", None, Some(0.0), -64.0, 63.0, 1.0, ParameterUnit::None),
            float_parameter("mfreq", "Mid Frequency", None, Some(800.0), 80.0, 8000.0, 10.0, ParameterUnit::Hertz),
            float_parameter("mgain", "Mid Gain", None, Some(0.0), -64.0, 63.0, 1.0, ParameterUnit::None),
            float_parameter("mq", "Mid Q", None, Some(0.0), -64.0, 63.0, 1.0, ParameterUnit::None),
            float_parameter("hfreq", "High Frequency", None, Some(12000.0), 6000.0, 26000.0, 10.0, ParameterUnit::Hertz),
            float_parameter("hgain", "Gain", None, Some(0.0), -64.0, 63.0, 1.0, ParameterUnit::None),
            float_parameter("hq", "High Q", None, Some(0.0), -64.0, 63.0, 1.0, ParameterUnit::None),
        ],
    }
}

fn build(params: &ParameterSet, sample_rate: f32, layout: AudioChannelLayout) -> Result<BlockProcessor> {
    let bypass = required_bool(params, "bypass").map_err(anyhow::Error::msg)?;
    let gain = required_f32(params, "gain").map_err(anyhow::Error::msg)?;
    let lfreq = required_f32(params, "lfreq").map_err(anyhow::Error::msg)?;
    let lgain = required_f32(params, "lgain").map_err(anyhow::Error::msg)?;
    let lq = required_f32(params, "lq").map_err(anyhow::Error::msg)?;
    let mfreq = required_f32(params, "mfreq").map_err(anyhow::Error::msg)?;
    let mgain = required_f32(params, "mgain").map_err(anyhow::Error::msg)?;
    let mq = required_f32(params, "mq").map_err(anyhow::Error::msg)?;
    let hfreq = required_f32(params, "hfreq").map_err(anyhow::Error::msg)?;
    let hgain = required_f32(params, "hgain").map_err(anyhow::Error::msg)?;
    let hq = required_f32(params, "hq").map_err(anyhow::Error::msg)?;
    let lib_path = lv2::resolve_lv2_lib(PLUGIN_BINARY)?;
    let bundle_path = lv2::resolve_lv2_bundle(PLUGIN_DIR)?;

    let control_ports: &[(usize, f32)] = &[
        (PORT_CTRL_BYPASS, if bypass { 1.0 } else { 0.0 }),
        (PORT_CTRL_GAIN, gain),
        (PORT_CTRL_LFREQ, lfreq),
        (PORT_CTRL_LGAIN, lgain),
        (PORT_CTRL_LQ, lq),
        (PORT_CTRL_MFREQ, mfreq),
        (PORT_CTRL_MGAIN, mgain),
        (PORT_CTRL_MQ, mq),
        (PORT_CTRL_HFREQ, hfreq),
        (PORT_CTRL_HGAIN, hgain),
        (PORT_CTRL_HQ, hq),
    ];

    let processor = lv2::build_stereo_lv2_processor(&lib_path, PLUGIN_URI, sample_rate as f64, &bundle_path, &[PORT_AUDIO_IN_INPUT_L, PORT_AUDIO_IN_INPUT_R], &[PORT_AUDIO_OUT_OUTPUT_L, PORT_AUDIO_OUT_OUTPUT_R], control_ports)?;
    let _ = layout;
    Ok(BlockProcessor::Stereo(Box::new(processor)))
}

fn schema() -> Result<ModelParameterSchema> { Ok(model_schema()) }

pub const MODEL_DEFINITION: FilterModelDefinition = FilterModelDefinition {
    id: MODEL_ID, display_name: DISPLAY_NAME, brand: BRAND,
    backend_kind: FilterBackendKind::Lv2, schema, build,
    supported_instruments: block_core::ALL_INSTRUMENTS, knob_layout: &[],
};
