// AUTO-GENERATED by tools/lv2_catalog_import — do not edit by hand.
// Re-run the tool to regenerate. Manual customisation goes in overrides.yaml.

#![allow(dead_code, unused_imports, unused_variables, clippy::all)]

use crate::registry::ModModelDefinition;
use crate::ModBackendKind;
use anyhow::Result;
use block_core::param::{
    float_parameter, required_f32, ModelParameterSchema, ParameterSet, ParameterUnit,
};
use block_core::{AudioChannelLayout, BlockProcessor, ModelAudioMode};

pub const MODEL_ID: &str = "lv2_mod_mda_ring_mod";
pub const DISPLAY_NAME: &str = "MDA RingMod";
const BRAND: &str = "mda";

const PLUGIN_URI: &str = "http://moddevices.com/plugins/mda/RingMod";
const PLUGIN_DIR: &str = "mod-mda-RingMod";

#[cfg(target_os = "macos")]
const PLUGIN_BINARY: &str = "RingMod.dylib";
#[cfg(target_os = "linux")]
const PLUGIN_BINARY: &str = "RingMod.so";
#[cfg(target_os = "windows")]
const PLUGIN_BINARY: &str = "RingMod.dll";

// Port indices (from TTL)
const PORT_CTRL_FREQ: usize = 0;
const PORT_CTRL_FINE: usize = 1;
const PORT_CTRL_FEEDBACK: usize = 2;
const PORT_AUDIO_IN_LEFT_IN: usize = 3;
const PORT_AUDIO_IN_RIGHT_IN: usize = 4;
const PORT_AUDIO_OUT_LEFT_OUT: usize = 5;
const PORT_AUDIO_OUT_RIGHT_OUT: usize = 6;

pub fn model_schema() -> ModelParameterSchema {
    ModelParameterSchema {
        effect_type: block_core::EFFECT_TYPE_MODULATION.into(),
        model: MODEL_ID.into(),
        display_name: DISPLAY_NAME.into(),
        audio_mode: ModelAudioMode::TrueStereo,
        parameters: vec![
            float_parameter("freq", "Freq", None, Some(1000.0), 0.0, 16000.0, 10.0, ParameterUnit::Hertz),
            float_parameter("fine", "Fine", None, Some(0.0), 0.0, 100.0, 1.0, ParameterUnit::Hertz),
            float_parameter("feedback", "Feedback", None, Some(0.0), 0.0, 100.0, 1.0, ParameterUnit::Percent),
        ],
    }
}

fn build(params: &ParameterSet, sample_rate: f32, layout: AudioChannelLayout) -> Result<BlockProcessor> {
    let freq = required_f32(params, "freq").map_err(anyhow::Error::msg)?;
    let fine = required_f32(params, "fine").map_err(anyhow::Error::msg)?;
    let feedback = required_f32(params, "feedback").map_err(anyhow::Error::msg)?;
    let lib_path = lv2::resolve_lv2_lib(PLUGIN_BINARY)?;
    let bundle_path = lv2::resolve_lv2_bundle(PLUGIN_DIR)?;

    let control_ports: &[(usize, f32)] = &[
        (PORT_CTRL_FREQ, freq),
        (PORT_CTRL_FINE, fine),
        (PORT_CTRL_FEEDBACK, feedback),
    ];

    let processor = lv2::build_stereo_lv2_processor(&lib_path, PLUGIN_URI, sample_rate as f64, &bundle_path, &[PORT_AUDIO_IN_LEFT_IN, PORT_AUDIO_IN_RIGHT_IN], &[PORT_AUDIO_OUT_LEFT_OUT, PORT_AUDIO_OUT_RIGHT_OUT], control_ports)?;
    let _ = layout;
    Ok(BlockProcessor::Stereo(Box::new(processor)))
}

fn schema() -> Result<ModelParameterSchema> { Ok(model_schema()) }

pub const MODEL_DEFINITION: ModModelDefinition = ModModelDefinition {
    id: MODEL_ID, display_name: DISPLAY_NAME, brand: BRAND,
    backend_kind: ModBackendKind::Lv2, schema, build,
    supported_instruments: block_core::ALL_INSTRUMENTS, knob_layout: &[],
};
