// AUTO-GENERATED by tools/lv2_catalog_import — do not edit by hand.
// Re-run the tool to regenerate. Manual customisation goes in overrides.yaml.

#![allow(dead_code, unused_imports, unused_variables, clippy::approx_constant, clippy::excessive_precision)]

use crate::registry::ModModelDefinition;
use crate::ModBackendKind;
use anyhow::Result;
use block_core::param::{
    bool_parameter, float_parameter, required_bool, required_f32,
    ModelParameterSchema, ParameterSet, ParameterUnit,
};
use block_core::{AudioChannelLayout, BlockProcessor, ModelAudioMode};

pub const MODEL_ID: &str = "lv2_rkr_bad_ring";
pub const DISPLAY_NAME: &str = "rkr Ring";
const BRAND: &str = "rakarrack";

const PLUGIN_URI: &str = "http://rakarrack.sourceforge.net/effects.html#Ring";
const PLUGIN_DIR: &str = "rkr-bad";

#[cfg(target_os = "macos")]
const PLUGIN_BINARY: &str = "rkrlv2.dylib";
#[cfg(target_os = "linux")]
const PLUGIN_BINARY: &str = "rkrlv2.so";
#[cfg(target_os = "windows")]
const PLUGIN_BINARY: &str = "rkrlv2.dll";

// Port indices (from TTL)
const PORT_AUDIO_IN_INPUT_L: usize = 0;
const PORT_AUDIO_IN_INPUT_R: usize = 1;
const PORT_AUDIO_OUT_OUTPUT_L: usize = 2;
const PORT_AUDIO_OUT_OUTPUT_R: usize = 3;
const PORT_CTRL_BYPASS: usize = 4;
const PORT_CTRL_WETDRY: usize = 5;
const PORT_CTRL_PAN: usize = 6;
const PORT_CTRL_LR_CR: usize = 7;
const PORT_CTRL_LEVEL: usize = 8;
const PORT_CTRL_DEPTH: usize = 9;
const PORT_CTRL_FREQ: usize = 10;
const PORT_CTRL_STEREO: usize = 11;
const PORT_CTRL_SIN: usize = 12;
const PORT_CTRL_TRI: usize = 13;
const PORT_CTRL_SAW: usize = 14;
const PORT_CTRL_SQUARE: usize = 15;
const PORT_CTRL_INPUT: usize = 16;
const PORT_CTRL_AFREQ: usize = 17;

pub fn model_schema() -> ModelParameterSchema {
    ModelParameterSchema {
        effect_type: block_core::EFFECT_TYPE_MODULATION.into(),
        model: MODEL_ID.into(),
        display_name: DISPLAY_NAME.into(),
        audio_mode: ModelAudioMode::TrueStereo,
        parameters: vec![
            bool_parameter("bypass", "Bypass", None, Some(false)),
            float_parameter("wetdry", "Wet/Dry", None, Some(64.0), 0.0, 127.0, 1.0, ParameterUnit::None),
            float_parameter("pan", "Pan", None, Some(0.0), -64.0, 64.0, 1.0, ParameterUnit::None),
            float_parameter("lrcr", "Left/Right Crossover", None, Some(14.0), 0.0, 127.0, 1.0, ParameterUnit::None),
            float_parameter("level", "Level", None, Some(0.0), 0.0, 127.0, 1.0, ParameterUnit::None),
            float_parameter("depth", "Depth", None, Some(1.0), 0.0, 100.0, 1.0, ParameterUnit::None),
            float_parameter("freq", "Frequency", None, Some(64.0), 1.0, 20000.0, 10.0, ParameterUnit::None),
            bool_parameter("stereo", "Stereo", None, Some(false)),
            float_parameter("sin", "Sine", None, Some(40.0), 0.0, 100.0, 1.0, ParameterUnit::None),
            float_parameter("tri", "Triangle", None, Some(4.0), 0.0, 100.0, 1.0, ParameterUnit::None),
            float_parameter("saw", "Sawtooth", None, Some(10.0), 0.0, 100.0, 1.0, ParameterUnit::None),
            float_parameter("square", "Square", None, Some(0.0), 0.0, 100.0, 1.0, ParameterUnit::None),
            float_parameter("input", "Input Gain", None, Some(64.0), 0.0, 127.0, 1.0, ParameterUnit::None),
            bool_parameter("afreq", "Auto-Frequency", None, Some(false)),
        ],
    }
}

fn build(params: &ParameterSet, sample_rate: f32, layout: AudioChannelLayout) -> Result<BlockProcessor> {
    let bypass = required_bool(params, "bypass").map_err(anyhow::Error::msg)?;
    let wetdry = required_f32(params, "wetdry").map_err(anyhow::Error::msg)?;
    let pan = required_f32(params, "pan").map_err(anyhow::Error::msg)?;
    let lrcr = required_f32(params, "lrcr").map_err(anyhow::Error::msg)?;
    let level = required_f32(params, "level").map_err(anyhow::Error::msg)?;
    let depth = required_f32(params, "depth").map_err(anyhow::Error::msg)?;
    let freq = required_f32(params, "freq").map_err(anyhow::Error::msg)?;
    let stereo = required_bool(params, "stereo").map_err(anyhow::Error::msg)?;
    let sin = required_f32(params, "sin").map_err(anyhow::Error::msg)?;
    let tri = required_f32(params, "tri").map_err(anyhow::Error::msg)?;
    let saw = required_f32(params, "saw").map_err(anyhow::Error::msg)?;
    let square = required_f32(params, "square").map_err(anyhow::Error::msg)?;
    let input = required_f32(params, "input").map_err(anyhow::Error::msg)?;
    let afreq = required_bool(params, "afreq").map_err(anyhow::Error::msg)?;
    let lib_path = lv2::resolve_lv2_lib(PLUGIN_BINARY)?;
    let bundle_path = lv2::resolve_lv2_bundle(PLUGIN_DIR)?;

    let control_ports: &[(usize, f32)] = &[
        (PORT_CTRL_BYPASS, if bypass { 1.0 } else { 0.0 }),
        (PORT_CTRL_WETDRY, wetdry),
        (PORT_CTRL_PAN, pan),
        (PORT_CTRL_LR_CR, lrcr),
        (PORT_CTRL_LEVEL, level),
        (PORT_CTRL_DEPTH, depth),
        (PORT_CTRL_FREQ, freq),
        (PORT_CTRL_STEREO, if stereo { 1.0 } else { 0.0 }),
        (PORT_CTRL_SIN, sin),
        (PORT_CTRL_TRI, tri),
        (PORT_CTRL_SAW, saw),
        (PORT_CTRL_SQUARE, square),
        (PORT_CTRL_INPUT, input),
        (PORT_CTRL_AFREQ, if afreq { 1.0 } else { 0.0 }),
    ];

    let processor = lv2::build_stereo_lv2_processor(&lib_path, PLUGIN_URI, sample_rate as f64, &bundle_path, &[PORT_AUDIO_IN_INPUT_L, PORT_AUDIO_IN_INPUT_R], &[PORT_AUDIO_OUT_OUTPUT_L, PORT_AUDIO_OUT_OUTPUT_R], control_ports)?;
    let _ = layout;
    Ok(BlockProcessor::Stereo(Box::new(processor)))
}

fn schema() -> Result<ModelParameterSchema> { Ok(model_schema()) }

pub const MODEL_DEFINITION: ModModelDefinition = ModModelDefinition {
    id: MODEL_ID, display_name: DISPLAY_NAME, brand: BRAND,
    backend_kind: ModBackendKind::Lv2, schema, build,
    supported_instruments: block_core::ALL_INSTRUMENTS, knob_layout: &[],
};
