// AUTO-GENERATED by tools/lv2_catalog_import — do not edit by hand.
// Re-run the tool to regenerate. Manual customisation goes in overrides.yaml.

#![allow(dead_code, unused_imports, unused_variables, clippy::approx_constant, clippy::excessive_precision)]

use crate::registry::ModModelDefinition;
use crate::ModBackendKind;
use anyhow::Result;
use block_core::param::{
    bool_parameter, float_parameter, required_bool, required_f32,
    ModelParameterSchema, ParameterSet, ParameterUnit,
};
use block_core::{AudioChannelLayout, BlockProcessor, ModelAudioMode};

pub const MODEL_ID: &str = "lv2_calf_bad_ring_modulator";
pub const DISPLAY_NAME: &str = "Calf Ring Modulator";
const BRAND: &str = "calf";

const PLUGIN_URI: &str = "http://calf.sourceforge.net/plugins/RingModulator";
const PLUGIN_DIR: &str = "calf-bad";

#[cfg(target_os = "macos")]
const PLUGIN_BINARY: &str = "calf.dylib";
#[cfg(target_os = "linux")]
const PLUGIN_BINARY: &str = "calf.so";
#[cfg(target_os = "windows")]
const PLUGIN_BINARY: &str = "calf.dll";

// Port indices (from TTL)
const PORT_AUDIO_IN_IN_L: usize = 0;
const PORT_AUDIO_IN_IN_R: usize = 1;
const PORT_AUDIO_OUT_OUT_L: usize = 2;
const PORT_AUDIO_OUT_OUT_R: usize = 3;
const PORT_CTRL_BYPASS: usize = 4;
const PORT_CTRL_LEVEL_IN: usize = 5;
const PORT_CTRL_LEVEL_OUT: usize = 6;
const PORT_CTRL_METER_IN_L: usize = 7;
const PORT_CTRL_METER_IN_R: usize = 8;
const PORT_CTRL_METER_OUT_L: usize = 9;
const PORT_CTRL_METER_OUT_R: usize = 10;
const PORT_CTRL_CLIP_IN_L: usize = 11;
const PORT_CTRL_CLIP_IN_R: usize = 12;
const PORT_CTRL_CLIP_OUT_L: usize = 13;
const PORT_CTRL_CLIP_OUT_R: usize = 14;
const PORT_CTRL_MOD_MODE: usize = 15;
const PORT_CTRL_MOD_FREQ: usize = 16;
const PORT_CTRL_MOD_AMOUNT: usize = 17;
const PORT_CTRL_MOD_PHASE: usize = 18;
const PORT_CTRL_MOD_DETUNE: usize = 19;
const PORT_CTRL_MOD_LISTEN: usize = 20;
const PORT_CTRL_LFO1_MODE: usize = 21;
const PORT_CTRL_LFO1_FREQ: usize = 22;
const PORT_CTRL_LFO1_RESET: usize = 23;
const PORT_CTRL_LFO1_MOD_FREQ_LO: usize = 24;
const PORT_CTRL_LFO1_MOD_FREQ_HI: usize = 25;
const PORT_CTRL_LFO1_MOD_FREQ_ACTIVE: usize = 26;
const PORT_CTRL_LFO1_MOD_DETUNE_LO: usize = 27;
const PORT_CTRL_LFO1_MOD_DETUNE_HI: usize = 28;
const PORT_CTRL_LFO1_MOD_DETUNE_ACTIVE: usize = 29;
const PORT_CTRL_LFO1_ACTIVITY: usize = 30;
const PORT_CTRL_LFO2_MODE: usize = 31;
const PORT_CTRL_LFO2_FREQ: usize = 32;
const PORT_CTRL_LFO2_RESET: usize = 33;
const PORT_CTRL_LFO2_LFO1_FREQ_LO: usize = 34;
const PORT_CTRL_LFO2_LFO1_FREQ_HI: usize = 35;
const PORT_CTRL_LFO2_LFO1_FREQ_ACTIVE: usize = 36;
const PORT_CTRL_LFO2_MOD_AMOUNT_LO: usize = 37;
const PORT_CTRL_LFO2_MOD_AMOUNT_HI: usize = 38;
const PORT_CTRL_LFO2_MOD_AMOUNT_ACTIVE: usize = 39;
const PORT_CTRL_LFO2_ACTIVITY: usize = 40;

pub fn model_schema() -> ModelParameterSchema {
    ModelParameterSchema {
        effect_type: block_core::EFFECT_TYPE_MODULATION.into(),
        model: MODEL_ID.into(),
        display_name: DISPLAY_NAME.into(),
        audio_mode: ModelAudioMode::TrueStereo,
        parameters: vec![
            bool_parameter("bypass", "Bypass", None, Some(false)),
            float_parameter("level_in", "Input Gain", None, Some(1.0), 0.015625, 64.0, 0.1, ParameterUnit::None),
            float_parameter("level_out", "Output Gain", None, Some(1.0), 0.015625, 64.0, 0.1, ParameterUnit::None),
            float_parameter("mod_mode", "Modulator", None, Some(0.0), 0.0, 4.0, 0.01, ParameterUnit::None),
            float_parameter("mod_freq", "Mod Freq", None, Some(1000.0), 1.0, 20000.0, 10.0, ParameterUnit::Hertz),
            float_parameter("mod_amount", "Mod Amount", None, Some(0.5), 0.0, 1.0, 0.01, ParameterUnit::None),
            float_parameter("mod_phase", "Mod Phase", None, Some(0.5), 0.0, 1.0, 0.01, ParameterUnit::None),
            float_parameter("mod_detune", "Mod Detune", None, Some(0.0), -200.0, 200.0, 1.0, ParameterUnit::None),
            bool_parameter("mod_listen", "Listen", None, Some(false)),
            float_parameter("lfo1_mode", "LFO 1", None, Some(0.0), 0.0, 4.0, 0.01, ParameterUnit::None),
            float_parameter("lfo1_freq", "LFO 1 Freq", None, Some(0.1), 0.01, 10.0, 0.01, ParameterUnit::Hertz),
            bool_parameter("lfo1_reset", "Reset 1", None, Some(false)),
            float_parameter("lfo1_mod_freq_lo", "Mod Freq LO", None, Some(100.0), 1.0, 20000.0, 10.0, ParameterUnit::Hertz),
            float_parameter("lfo1_mod_freq_hi", "Mod Freq HI", None, Some(10000.0), 1.0, 20000.0, 10.0, ParameterUnit::Hertz),
            bool_parameter("lfo1_mod_freq_active", "Mod Freq Active", None, Some(false)),
            float_parameter("lfo1_mod_detune_lo", "Mod Detune LO", None, Some(-100.0), -200.0, 200.0, 1.0, ParameterUnit::None),
            float_parameter("lfo1_mod_detune_hi", "Mod Detune HI", None, Some(100.0), -200.0, 200.0, 1.0, ParameterUnit::None),
            bool_parameter("lfo1_mod_detune_active", "Mod Detune Active", None, Some(false)),
            float_parameter("lfo2_mode", "LFO 2", None, Some(0.0), 0.0, 4.0, 0.01, ParameterUnit::None),
            float_parameter("lfo2_freq", "LFO 2 Freq", None, Some(0.2), 0.01, 10.0, 0.01, ParameterUnit::Hertz),
            bool_parameter("lfo2_reset", "Reset 2", None, Some(false)),
            float_parameter("lfo2_lfo1_freq_lo", "LFO Freq LO", None, Some(0.05), 0.01, 10.0, 0.01, ParameterUnit::Hertz),
            float_parameter("lfo2_lfo1_freq_hi", "LFO Freq HI", None, Some(0.5), 0.01, 10.0, 0.01, ParameterUnit::Hertz),
            bool_parameter("lfo2_lfo1_freq_active", "LFO 1 Freq Active", None, Some(false)),
            float_parameter("lfo2_mod_amount_lo", "Mod Amount LO", None, Some(0.3), 0.0, 1.0, 0.01, ParameterUnit::None),
            float_parameter("lfo2_mod_amount_hi", "Mod Amount HI", None, Some(0.6), 0.0, 1.0, 0.01, ParameterUnit::None),
            bool_parameter("lfo2_mod_amount_active", "Mod Amount Active", None, Some(false)),
        ],
    }
}

fn build(params: &ParameterSet, sample_rate: f32, layout: AudioChannelLayout) -> Result<BlockProcessor> {
    let bypass = required_bool(params, "bypass").map_err(anyhow::Error::msg)?;
    let level_in = required_f32(params, "level_in").map_err(anyhow::Error::msg)?;
    let level_out = required_f32(params, "level_out").map_err(anyhow::Error::msg)?;
    let mod_mode = required_f32(params, "mod_mode").map_err(anyhow::Error::msg)?;
    let mod_freq = required_f32(params, "mod_freq").map_err(anyhow::Error::msg)?;
    let mod_amount = required_f32(params, "mod_amount").map_err(anyhow::Error::msg)?;
    let mod_phase = required_f32(params, "mod_phase").map_err(anyhow::Error::msg)?;
    let mod_detune = required_f32(params, "mod_detune").map_err(anyhow::Error::msg)?;
    let mod_listen = required_bool(params, "mod_listen").map_err(anyhow::Error::msg)?;
    let lfo1_mode = required_f32(params, "lfo1_mode").map_err(anyhow::Error::msg)?;
    let lfo1_freq = required_f32(params, "lfo1_freq").map_err(anyhow::Error::msg)?;
    let lfo1_reset = required_bool(params, "lfo1_reset").map_err(anyhow::Error::msg)?;
    let lfo1_mod_freq_lo = required_f32(params, "lfo1_mod_freq_lo").map_err(anyhow::Error::msg)?;
    let lfo1_mod_freq_hi = required_f32(params, "lfo1_mod_freq_hi").map_err(anyhow::Error::msg)?;
    let lfo1_mod_freq_active = required_bool(params, "lfo1_mod_freq_active").map_err(anyhow::Error::msg)?;
    let lfo1_mod_detune_lo = required_f32(params, "lfo1_mod_detune_lo").map_err(anyhow::Error::msg)?;
    let lfo1_mod_detune_hi = required_f32(params, "lfo1_mod_detune_hi").map_err(anyhow::Error::msg)?;
    let lfo1_mod_detune_active = required_bool(params, "lfo1_mod_detune_active").map_err(anyhow::Error::msg)?;
    let lfo2_mode = required_f32(params, "lfo2_mode").map_err(anyhow::Error::msg)?;
    let lfo2_freq = required_f32(params, "lfo2_freq").map_err(anyhow::Error::msg)?;
    let lfo2_reset = required_bool(params, "lfo2_reset").map_err(anyhow::Error::msg)?;
    let lfo2_lfo1_freq_lo = required_f32(params, "lfo2_lfo1_freq_lo").map_err(anyhow::Error::msg)?;
    let lfo2_lfo1_freq_hi = required_f32(params, "lfo2_lfo1_freq_hi").map_err(anyhow::Error::msg)?;
    let lfo2_lfo1_freq_active = required_bool(params, "lfo2_lfo1_freq_active").map_err(anyhow::Error::msg)?;
    let lfo2_mod_amount_lo = required_f32(params, "lfo2_mod_amount_lo").map_err(anyhow::Error::msg)?;
    let lfo2_mod_amount_hi = required_f32(params, "lfo2_mod_amount_hi").map_err(anyhow::Error::msg)?;
    let lfo2_mod_amount_active = required_bool(params, "lfo2_mod_amount_active").map_err(anyhow::Error::msg)?;
    let lib_path = lv2::resolve_lv2_lib(PLUGIN_BINARY)?;
    let bundle_path = lv2::resolve_lv2_bundle(PLUGIN_DIR)?;

    let control_ports: &[(usize, f32)] = &[
        (PORT_CTRL_BYPASS, if bypass { 1.0 } else { 0.0 }),
        (PORT_CTRL_LEVEL_IN, level_in),
        (PORT_CTRL_LEVEL_OUT, level_out),
        (PORT_CTRL_MOD_MODE, mod_mode),
        (PORT_CTRL_MOD_FREQ, mod_freq),
        (PORT_CTRL_MOD_AMOUNT, mod_amount),
        (PORT_CTRL_MOD_PHASE, mod_phase),
        (PORT_CTRL_MOD_DETUNE, mod_detune),
        (PORT_CTRL_MOD_LISTEN, if mod_listen { 1.0 } else { 0.0 }),
        (PORT_CTRL_LFO1_MODE, lfo1_mode),
        (PORT_CTRL_LFO1_FREQ, lfo1_freq),
        (PORT_CTRL_LFO1_RESET, if lfo1_reset { 1.0 } else { 0.0 }),
        (PORT_CTRL_LFO1_MOD_FREQ_LO, lfo1_mod_freq_lo),
        (PORT_CTRL_LFO1_MOD_FREQ_HI, lfo1_mod_freq_hi),
        (PORT_CTRL_LFO1_MOD_FREQ_ACTIVE, if lfo1_mod_freq_active { 1.0 } else { 0.0 }),
        (PORT_CTRL_LFO1_MOD_DETUNE_LO, lfo1_mod_detune_lo),
        (PORT_CTRL_LFO1_MOD_DETUNE_HI, lfo1_mod_detune_hi),
        (PORT_CTRL_LFO1_MOD_DETUNE_ACTIVE, if lfo1_mod_detune_active { 1.0 } else { 0.0 }),
        (PORT_CTRL_LFO2_MODE, lfo2_mode),
        (PORT_CTRL_LFO2_FREQ, lfo2_freq),
        (PORT_CTRL_LFO2_RESET, if lfo2_reset { 1.0 } else { 0.0 }),
        (PORT_CTRL_LFO2_LFO1_FREQ_LO, lfo2_lfo1_freq_lo),
        (PORT_CTRL_LFO2_LFO1_FREQ_HI, lfo2_lfo1_freq_hi),
        (PORT_CTRL_LFO2_LFO1_FREQ_ACTIVE, if lfo2_lfo1_freq_active { 1.0 } else { 0.0 }),
        (PORT_CTRL_LFO2_MOD_AMOUNT_LO, lfo2_mod_amount_lo),
        (PORT_CTRL_LFO2_MOD_AMOUNT_HI, lfo2_mod_amount_hi),
        (PORT_CTRL_LFO2_MOD_AMOUNT_ACTIVE, if lfo2_mod_amount_active { 1.0 } else { 0.0 }),
    ];

    let processor = lv2::build_stereo_lv2_processor(&lib_path, PLUGIN_URI, sample_rate as f64, &bundle_path, &[PORT_AUDIO_IN_IN_L, PORT_AUDIO_IN_IN_R], &[PORT_AUDIO_OUT_OUT_L, PORT_AUDIO_OUT_OUT_R], control_ports)?;
    let _ = layout;
    Ok(BlockProcessor::Stereo(Box::new(processor)))
}

fn schema() -> Result<ModelParameterSchema> { Ok(model_schema()) }

pub const MODEL_DEFINITION: ModModelDefinition = ModModelDefinition {
    id: MODEL_ID, display_name: DISPLAY_NAME, brand: BRAND,
    backend_kind: ModBackendKind::Lv2, schema, build,
    supported_instruments: block_core::ALL_INSTRUMENTS, knob_layout: &[],
};
