// AUTO-GENERATED by tools/lv2_catalog_import — do not edit by hand.
// Re-run the tool to regenerate. Manual customisation goes in overrides.yaml.

#![allow(dead_code, unused_imports, unused_variables, clippy::all)]

use crate::registry::ModModelDefinition;
use crate::ModBackendKind;
use anyhow::Result;
use block_core::param::{
    float_parameter, required_f32, ModelParameterSchema, ParameterSet, ParameterUnit,
};
use block_core::{AudioChannelLayout, BlockProcessor, ModelAudioMode};

pub const MODEL_ID: &str = "lv2_calf_bad_rotary_speaker";
pub const DISPLAY_NAME: &str = "Calf Rotary Speaker";
const BRAND: &str = "calf";

const PLUGIN_URI: &str = "http://calf.sourceforge.net/plugins/RotarySpeaker";
const PLUGIN_DIR: &str = "calf-bad";
pub const THUMBNAIL_PATH: Option<&str> = None;

#[cfg(target_os = "macos")]
const PLUGIN_BINARY: &str = "calf.dylib";
#[cfg(target_os = "linux")]
const PLUGIN_BINARY: &str = "calf.so";
#[cfg(target_os = "windows")]
const PLUGIN_BINARY: &str = "calf.dll";

// Port indices (from TTL)
const PORT_AUDIO_IN_IN_L: usize = 0;
const PORT_AUDIO_IN_IN_R: usize = 1;
const PORT_AUDIO_OUT_OUT_L: usize = 2;
const PORT_AUDIO_OUT_OUT_R: usize = 3;
const PORT_CTRL_VIB_SPEED: usize = 4;
const PORT_CTRL_SPACING: usize = 5;
const PORT_CTRL_SHIFT: usize = 6;
const PORT_CTRL_MOD_DEPTH: usize = 7;
const PORT_CTRL_TREBLE_SPEED: usize = 8;
const PORT_CTRL_BASS_SPEED: usize = 9;
const PORT_CTRL_MIC_DISTANCE: usize = 10;
const PORT_CTRL_REFLECTION: usize = 11;
const PORT_CTRL_AM_DEPTH: usize = 12;
const PORT_CTRL_TEST: usize = 13;
const PORT_CTRL_METER_L: usize = 14;
const PORT_CTRL_METER_H: usize = 15;
const PORT_ATOM_IN_MIDI_IN: usize = 16;

pub fn model_schema() -> ModelParameterSchema {
    ModelParameterSchema {
        effect_type: block_core::EFFECT_TYPE_MODULATION.into(),
        model: MODEL_ID.into(),
        display_name: DISPLAY_NAME.into(),
        audio_mode: ModelAudioMode::TrueStereo,
        parameters: vec![
            float_parameter("vib_speed", "Speed Mode", None, Some(5.0), 0.0, 5.0, 0.01, ParameterUnit::None),
            float_parameter("spacing", "Tap Spacing", None, Some(0.5), 0.0, 1.0, 0.01, ParameterUnit::None),
            float_parameter("shift", "Tap Offset", None, Some(0.5), 0.0, 1.0, 0.01, ParameterUnit::None),
            float_parameter("mod_depth", "FM Depth", None, Some(0.45), 0.0, 1.0, 0.01, ParameterUnit::None),
            float_parameter("treble_speed", "Treble Motor", None, Some(36.0), 10.0, 600.0, 1.0, ParameterUnit::None),
            float_parameter("bass_speed", "Bass Motor", None, Some(30.0), 10.0, 600.0, 1.0, ParameterUnit::None),
            float_parameter("mic_distance", "Mic Distance", None, Some(0.7), 0.0, 1.0, 0.01, ParameterUnit::None),
            float_parameter("reflection", "Reflection", None, Some(0.3), 0.0, 1.0, 0.01, ParameterUnit::None),
            float_parameter("am_depth", "AM Depth", None, Some(0.45), 0.0, 1.0, 0.01, ParameterUnit::None),
            float_parameter("test", "Test", None, Some(0.0), 0.0, 1.0, 0.01, ParameterUnit::None),
        ],
    }
}

fn build(params: &ParameterSet, sample_rate: f32, layout: AudioChannelLayout) -> Result<BlockProcessor> {
    let vib_speed = required_f32(params, "vib_speed").map_err(anyhow::Error::msg)?;
    let spacing = required_f32(params, "spacing").map_err(anyhow::Error::msg)?;
    let shift = required_f32(params, "shift").map_err(anyhow::Error::msg)?;
    let mod_depth = required_f32(params, "mod_depth").map_err(anyhow::Error::msg)?;
    let treble_speed = required_f32(params, "treble_speed").map_err(anyhow::Error::msg)?;
    let bass_speed = required_f32(params, "bass_speed").map_err(anyhow::Error::msg)?;
    let mic_distance = required_f32(params, "mic_distance").map_err(anyhow::Error::msg)?;
    let reflection = required_f32(params, "reflection").map_err(anyhow::Error::msg)?;
    let am_depth = required_f32(params, "am_depth").map_err(anyhow::Error::msg)?;
    let test = required_f32(params, "test").map_err(anyhow::Error::msg)?;
    let lib_path = lv2::resolve_lv2_lib(PLUGIN_BINARY)?;
    let bundle_path = lv2::resolve_lv2_bundle(PLUGIN_DIR)?;

    let control_ports: &[(usize, f32)] = &[
        (PORT_CTRL_VIB_SPEED, vib_speed),
        (PORT_CTRL_SPACING, spacing),
        (PORT_CTRL_SHIFT, shift),
        (PORT_CTRL_MOD_DEPTH, mod_depth),
        (PORT_CTRL_TREBLE_SPEED, treble_speed),
        (PORT_CTRL_BASS_SPEED, bass_speed),
        (PORT_CTRL_MIC_DISTANCE, mic_distance),
        (PORT_CTRL_REFLECTION, reflection),
        (PORT_CTRL_AM_DEPTH, am_depth),
        (PORT_CTRL_TEST, test),
    ];

    let processor = lv2::build_stereo_lv2_processor(&lib_path, PLUGIN_URI, sample_rate as f64, &bundle_path, &[PORT_AUDIO_IN_IN_L, PORT_AUDIO_IN_IN_R], &[PORT_AUDIO_OUT_OUT_L, PORT_AUDIO_OUT_OUT_R], control_ports)?;
    let _ = layout;
    Ok(BlockProcessor::Stereo(Box::new(processor)))
}

fn schema() -> Result<ModelParameterSchema> { Ok(model_schema()) }

pub const MODEL_DEFINITION: ModModelDefinition = ModModelDefinition {
    id: MODEL_ID, display_name: DISPLAY_NAME, brand: BRAND,
    backend_kind: ModBackendKind::Lv2, schema, build,
    supported_instruments: block_core::ALL_INSTRUMENTS, knob_layout: &[],
};
