// AUTO-GENERATED by tools/lv2_catalog_import — do not edit by hand.
// Re-run the tool to regenerate. Manual customisation goes in overrides.yaml.

#![allow(dead_code, unused_imports, unused_variables, clippy::all)]

use crate::registry::ModModelDefinition;
use crate::ModBackendKind;
use anyhow::Result;
use block_core::param::{
    float_parameter, required_f32, ModelParameterSchema, ParameterSet, ParameterUnit,
};
use block_core::{AudioChannelLayout, BlockProcessor, ModelAudioMode, MonoProcessor, StereoProcessor};

pub const MODEL_ID: &str = "lv2_tap_vibrato";
pub const DISPLAY_NAME: &str = "TAP Vibrato";
const BRAND: &str = "tap";

const PLUGIN_URI: &str = "http://moddevices.com/plugins/tap/vibrato";
const PLUGIN_DIR: &str = "tap-vibrato";

#[cfg(target_os = "macos")]
const PLUGIN_BINARY: &str = "tap_vibrato.dylib";
#[cfg(target_os = "linux")]
const PLUGIN_BINARY: &str = "tap_vibrato.so";
#[cfg(target_os = "windows")]
const PLUGIN_BINARY: &str = "tap_vibrato.dll";

// Port indices (from TTL)
const PORT_CTRL_FREQUENCY: usize = 0;
const PORT_CTRL_DEPTH: usize = 1;
const PORT_CTRL_DRYLEVEL: usize = 2;
const PORT_CTRL_WETLEVEL: usize = 3;
const PORT_CTRL_LATENCY: usize = 4;
const PORT_AUDIO_IN_INPUT: usize = 5;
const PORT_AUDIO_OUT_OUTPUT: usize = 6;

pub fn model_schema() -> ModelParameterSchema {
    ModelParameterSchema {
        effect_type: block_core::EFFECT_TYPE_MODULATION.into(),
        model: MODEL_ID.into(),
        display_name: DISPLAY_NAME.into(),
        audio_mode: ModelAudioMode::DualMono,
        parameters: vec![
            float_parameter("frequency", "Frequency", None, Some(0.0), 0.0, 30.0, 0.1, ParameterUnit::Hertz),
            float_parameter("depth", "Depth", None, Some(0.0), 0.0, 20.0, 0.1, ParameterUnit::Milliseconds),
            float_parameter("drylevel", "Drylevel", None, Some(0.0), -90.0, 20.0, 1.0, ParameterUnit::Decibels),
            float_parameter("wetlevel", "Wetlevel", None, Some(0.0), -90.0, 20.0, 1.0, ParameterUnit::Decibels),
        ],
    }
}

fn build(params: &ParameterSet, sample_rate: f32, layout: AudioChannelLayout) -> Result<BlockProcessor> {
    let frequency = required_f32(params, "frequency").map_err(anyhow::Error::msg)?;
    let depth = required_f32(params, "depth").map_err(anyhow::Error::msg)?;
    let drylevel = required_f32(params, "drylevel").map_err(anyhow::Error::msg)?;
    let wetlevel = required_f32(params, "wetlevel").map_err(anyhow::Error::msg)?;
    let lib_path = lv2::resolve_lv2_lib(PLUGIN_BINARY)?;
    let bundle_path = lv2::resolve_lv2_bundle(PLUGIN_DIR)?;

    let control_ports: &[(usize, f32)] = &[
        (PORT_CTRL_FREQUENCY, frequency),
        (PORT_CTRL_DEPTH, depth),
        (PORT_CTRL_DRYLEVEL, drylevel),
        (PORT_CTRL_WETLEVEL, wetlevel),
    ];

    match layout {
        AudioChannelLayout::Mono => {
            let processor = lv2::build_lv2_processor(&lib_path, PLUGIN_URI, sample_rate as f64, &bundle_path, &[PORT_AUDIO_IN_INPUT], &[PORT_AUDIO_OUT_OUTPUT], control_ports)?;
            Ok(BlockProcessor::Mono(Box::new(processor)))
        }
        AudioChannelLayout::Stereo => {
            let left = lv2::build_lv2_processor(&lib_path, PLUGIN_URI, sample_rate as f64, &bundle_path, &[PORT_AUDIO_IN_INPUT], &[PORT_AUDIO_OUT_OUTPUT], control_ports)?;
            let right = lv2::build_lv2_processor(&lib_path, PLUGIN_URI, sample_rate as f64, &bundle_path, &[PORT_AUDIO_IN_INPUT], &[PORT_AUDIO_OUT_OUTPUT], control_ports)?;
            Ok(BlockProcessor::Stereo(Box::new(DualMonoProcessor { left, right })))
        }
    }
}

struct DualMonoProcessor { left: lv2::Lv2Processor, right: lv2::Lv2Processor }
impl StereoProcessor for DualMonoProcessor {
    fn process_frame(&mut self, input: [f32; 2]) -> [f32; 2] {
        [self.left.process_sample(input[0]), self.right.process_sample(input[1])]
    }
}

fn schema() -> Result<ModelParameterSchema> { Ok(model_schema()) }

pub const MODEL_DEFINITION: ModModelDefinition = ModModelDefinition {
    id: MODEL_ID, display_name: DISPLAY_NAME, brand: BRAND,
    backend_kind: ModBackendKind::Lv2, schema, build,
    supported_instruments: block_core::ALL_INSTRUMENTS, knob_layout: &[],
};
