// AUTO-GENERATED by tools/lv2_catalog_import — do not edit by hand.
// Re-run the tool to regenerate. Manual customisation goes in overrides.yaml.

#![allow(dead_code, unused_imports, unused_variables, clippy::all)]

use crate::registry::ModModelDefinition;
use crate::ModBackendKind;
use anyhow::Result;
use block_core::param::{
    bool_parameter, float_parameter, required_bool, required_f32,
    ModelParameterSchema, ParameterSet, ParameterUnit,
};
use block_core::{AudioChannelLayout, BlockProcessor, ModelAudioMode};

pub const MODEL_ID: &str = "lv2_calf_flanger";
pub const DISPLAY_NAME: &str = "Calf Flanger";
const BRAND: &str = "calf";

const PLUGIN_URI: &str = "http://calf.sourceforge.net/plugins/Flanger";
const PLUGIN_DIR: &str = "calf";

#[cfg(target_os = "macos")]
const PLUGIN_BINARY: &str = "calf.dylib";
#[cfg(target_os = "linux")]
const PLUGIN_BINARY: &str = "calf.so";
#[cfg(target_os = "windows")]
const PLUGIN_BINARY: &str = "calf.dll";

// Port indices (from TTL)
const PORT_AUDIO_IN_IN_L: usize = 0;
const PORT_AUDIO_IN_IN_R: usize = 1;
const PORT_AUDIO_OUT_OUT_L: usize = 2;
const PORT_AUDIO_OUT_OUT_R: usize = 3;
const PORT_CTRL_MIN_DELAY: usize = 4;
const PORT_CTRL_MOD_DEPTH: usize = 5;
const PORT_CTRL_MOD_RATE: usize = 6;
const PORT_CTRL_FEEDBACK: usize = 7;
const PORT_CTRL_STEREO: usize = 8;
const PORT_CTRL_RESET: usize = 9;
const PORT_CTRL_AMOUNT: usize = 10;
const PORT_CTRL_DRY: usize = 11;

pub fn model_schema() -> ModelParameterSchema {
    ModelParameterSchema {
        effect_type: block_core::EFFECT_TYPE_MODULATION.into(),
        model: MODEL_ID.into(),
        display_name: DISPLAY_NAME.into(),
        audio_mode: ModelAudioMode::TrueStereo,
        parameters: vec![
            float_parameter("min_delay", "Min delay", None, Some(0.1), 0.1, 10.0, 0.01, ParameterUnit::Milliseconds),
            float_parameter("mod_depth", "Mod depth", None, Some(1.0), 0.1, 10.0, 0.01, ParameterUnit::Milliseconds),
            float_parameter("mod_rate", "Mod rate", None, Some(0.2), 0.01, 20.0, 0.1, ParameterUnit::Hertz),
            float_parameter("feedback", "Feedback", None, Some(0.9), -0.99, 0.99, 0.01, ParameterUnit::None),
            float_parameter("stereo", "Stereo phase", None, Some(90.0), 0.0, 360.0, 1.0, ParameterUnit::None),
            bool_parameter("reset", "Reset", None, Some(false)),
            float_parameter("amount", "Amount", None, Some(1.0), 0.0, 4.0, 0.01, ParameterUnit::None),
            float_parameter("dry", "Dry Amount", None, Some(1.0), 0.0, 4.0, 0.01, ParameterUnit::None),
        ],
    }
}

fn build(params: &ParameterSet, sample_rate: f32, layout: AudioChannelLayout) -> Result<BlockProcessor> {
    let min_delay = required_f32(params, "min_delay").map_err(anyhow::Error::msg)?;
    let mod_depth = required_f32(params, "mod_depth").map_err(anyhow::Error::msg)?;
    let mod_rate = required_f32(params, "mod_rate").map_err(anyhow::Error::msg)?;
    let feedback = required_f32(params, "feedback").map_err(anyhow::Error::msg)?;
    let stereo = required_f32(params, "stereo").map_err(anyhow::Error::msg)?;
    let reset = required_bool(params, "reset").map_err(anyhow::Error::msg)?;
    let amount = required_f32(params, "amount").map_err(anyhow::Error::msg)?;
    let dry = required_f32(params, "dry").map_err(anyhow::Error::msg)?;
    let lib_path = lv2::resolve_lv2_lib(PLUGIN_BINARY)?;
    let bundle_path = lv2::resolve_lv2_bundle(PLUGIN_DIR)?;

    let control_ports: &[(usize, f32)] = &[
        (PORT_CTRL_MIN_DELAY, min_delay),
        (PORT_CTRL_MOD_DEPTH, mod_depth),
        (PORT_CTRL_MOD_RATE, mod_rate),
        (PORT_CTRL_FEEDBACK, feedback),
        (PORT_CTRL_STEREO, stereo),
        (PORT_CTRL_RESET, if reset { 1.0 } else { 0.0 }),
        (PORT_CTRL_AMOUNT, amount),
        (PORT_CTRL_DRY, dry),
    ];

    let processor = lv2::build_stereo_lv2_processor(&lib_path, PLUGIN_URI, sample_rate as f64, &bundle_path, &[PORT_AUDIO_IN_IN_L, PORT_AUDIO_IN_IN_R], &[PORT_AUDIO_OUT_OUT_L, PORT_AUDIO_OUT_OUT_R], control_ports)?;
    let _ = layout;
    Ok(BlockProcessor::Stereo(Box::new(processor)))
}

fn schema() -> Result<ModelParameterSchema> { Ok(model_schema()) }

pub const MODEL_DEFINITION: ModModelDefinition = ModModelDefinition {
    id: MODEL_ID, display_name: DISPLAY_NAME, brand: BRAND,
    backend_kind: ModBackendKind::Lv2, schema, build,
    supported_instruments: block_core::ALL_INSTRUMENTS, knob_layout: &[],
};
