// AUTO-GENERATED by tools/lv2_catalog_import — do not edit by hand.
// Re-run the tool to regenerate. Manual customisation goes in overrides.yaml.

#![allow(dead_code, unused_imports, unused_variables, clippy::all)]

use crate::registry::ModModelDefinition;
use crate::ModBackendKind;
use anyhow::Result;
use block_core::param::{
    float_parameter, required_f32, ModelParameterSchema, ParameterSet, ParameterUnit,
};
use block_core::{AudioChannelLayout, BlockProcessor, ModelAudioMode};

pub const MODEL_ID: &str = "lv2_mod_mda_thru_zero";
pub const DISPLAY_NAME: &str = "MDA ThruZero";
const BRAND: &str = "mda";

const PLUGIN_URI: &str = "http://moddevices.com/plugins/mda/ThruZero";
const PLUGIN_DIR: &str = "mod-mda-ThruZero";
pub const THUMBNAIL_PATH: Option<&str> = Some(".plugins/lv2/mod-mda-ThruZero.lv2/modgui/thumbnail-mda-thruzero.png");

#[cfg(target_os = "macos")]
const PLUGIN_BINARY: &str = "ThruZero.dylib";
#[cfg(target_os = "linux")]
const PLUGIN_BINARY: &str = "ThruZero.so";
#[cfg(target_os = "windows")]
const PLUGIN_BINARY: &str = "ThruZero.dll";

// Port indices (from TTL)
const PORT_CTRL_RATE: usize = 0;
const PORT_CTRL_DEPTH: usize = 1;
const PORT_CTRL_MIX: usize = 2;
const PORT_CTRL_FEEDBACK: usize = 3;
const PORT_CTRL_DEPTH_MOD: usize = 4;
const PORT_AUDIO_IN_LEFT_IN: usize = 5;
const PORT_AUDIO_IN_RIGHT_IN: usize = 6;
const PORT_AUDIO_OUT_LEFT_OUT: usize = 7;
const PORT_AUDIO_OUT_RIGHT_OUT: usize = 8;

pub fn model_schema() -> ModelParameterSchema {
    ModelParameterSchema {
        effect_type: block_core::EFFECT_TYPE_MODULATION.into(),
        model: MODEL_ID.into(),
        display_name: DISPLAY_NAME.into(),
        audio_mode: ModelAudioMode::TrueStereo,
        parameters: vec![
            float_parameter("rate", "Rate", None, Some(0.08), 0.01, 10.0, 0.01, ParameterUnit::Hertz),
            float_parameter("depth", "Depth", None, Some(20.0), 0.0, 42.0, 0.1, ParameterUnit::Milliseconds),
            float_parameter("mix", "Mix", None, Some(47.0), 0.0, 100.0, 1.0, ParameterUnit::Percent),
            float_parameter("feedback", "Feedback", None, Some(-40.0), -100.0, 100.0, 1.0, ParameterUnit::Percent),
            float_parameter("depth_mod", "Depth Mod", None, Some(100.0), 0.0, 100.0, 1.0, ParameterUnit::Percent),
        ],
    }
}

fn build(params: &ParameterSet, sample_rate: f32, layout: AudioChannelLayout) -> Result<BlockProcessor> {
    let rate = required_f32(params, "rate").map_err(anyhow::Error::msg)?;
    let depth = required_f32(params, "depth").map_err(anyhow::Error::msg)?;
    let mix = required_f32(params, "mix").map_err(anyhow::Error::msg)?;
    let feedback = required_f32(params, "feedback").map_err(anyhow::Error::msg)?;
    let depth_mod = required_f32(params, "depth_mod").map_err(anyhow::Error::msg)?;
    let lib_path = lv2::resolve_lv2_lib(PLUGIN_BINARY)?;
    let bundle_path = lv2::resolve_lv2_bundle(PLUGIN_DIR)?;

    let control_ports: &[(usize, f32)] = &[
        (PORT_CTRL_RATE, rate),
        (PORT_CTRL_DEPTH, depth),
        (PORT_CTRL_MIX, mix),
        (PORT_CTRL_FEEDBACK, feedback),
        (PORT_CTRL_DEPTH_MOD, depth_mod),
    ];

    let processor = lv2::build_stereo_lv2_processor(&lib_path, PLUGIN_URI, sample_rate as f64, &bundle_path, &[PORT_AUDIO_IN_LEFT_IN, PORT_AUDIO_IN_RIGHT_IN], &[PORT_AUDIO_OUT_LEFT_OUT, PORT_AUDIO_OUT_RIGHT_OUT], control_ports)?;
    let _ = layout;
    Ok(BlockProcessor::Stereo(Box::new(processor)))
}

fn schema() -> Result<ModelParameterSchema> { Ok(model_schema()) }

pub const MODEL_DEFINITION: ModModelDefinition = ModModelDefinition {
    id: MODEL_ID, display_name: DISPLAY_NAME, brand: BRAND,
    backend_kind: ModBackendKind::Lv2, schema, build,
    supported_instruments: block_core::ALL_INSTRUMENTS, knob_layout: &[],
};
