// AUTO-GENERATED by tools/lv2_catalog_import — do not edit by hand.
// Re-run the tool to regenerate. Manual customisation goes in overrides.yaml.

#![allow(dead_code, unused_imports, unused_variables, clippy::all)]

use crate::registry::ModModelDefinition;
use crate::ModBackendKind;
use anyhow::Result;
use block_core::param::{
    float_parameter, required_f32, ModelParameterSchema, ParameterSet, ParameterUnit,
};
use block_core::{AudioChannelLayout, BlockProcessor, ModelAudioMode, MonoProcessor, StereoProcessor};

pub const MODEL_ID: &str = "lv2_fomp_cs_phaser1_lfo";
pub const DISPLAY_NAME: &str = "CS Phaser 1 with LFO";
const BRAND: &str = "fomp";

const PLUGIN_URI: &str = "http://drobilla.net/plugins/fomp/cs_phaser1_lfo";
const PLUGIN_DIR: &str = "fomp";

#[cfg(target_os = "macos")]
const PLUGIN_BINARY: &str = "cs_phaser.dylib";
#[cfg(target_os = "linux")]
const PLUGIN_BINARY: &str = "cs_phaser.so";
#[cfg(target_os = "windows")]
const PLUGIN_BINARY: &str = "cs_phaser.dll";

// Port indices (from TTL)
const PORT_AUDIO_IN_IN: usize = 0;
const PORT_AUDIO_OUT_OUT: usize = 1;
const PORT_CTRL_IN_GAIN: usize = 2;
const PORT_CTRL_SECTIONS: usize = 3;
const PORT_CTRL_FREQ: usize = 4;
const PORT_CTRL_LFO_FREQ: usize = 5;
const PORT_CTRL_LFO_WAVEFORM: usize = 6;
const PORT_CTRL_MOD_GAIN: usize = 7;
const PORT_CTRL_FB_GAIN: usize = 8;
const PORT_CTRL_OUT_MIX: usize = 9;

pub fn model_schema() -> ModelParameterSchema {
    ModelParameterSchema {
        effect_type: block_core::EFFECT_TYPE_MODULATION.into(),
        model: MODEL_ID.into(),
        display_name: DISPLAY_NAME.into(),
        audio_mode: ModelAudioMode::DualMono,
        parameters: vec![
            float_parameter("in_gain", "Input gain", None, Some(0.0), -40.0, 10.0, 0.1, ParameterUnit::Decibels),
            float_parameter("sections", "Sections", None, Some(1.0), 1.0, 30.0, 0.1, ParameterUnit::None),
            float_parameter("freq", "Frequency", None, Some(0.0), -6.0, 6.0, 0.1, ParameterUnit::None),
            float_parameter("lfo_freq", "LFO frequency", None, Some(0.01), 0.01, 30.0, 0.1, ParameterUnit::Hertz),
            float_parameter("lfo_waveform", "LFO waveform", None, Some(0.0), -1.0, 1.0, 0.01, ParameterUnit::None),
            float_parameter("mod_gain", "Modulation gain", None, Some(0.0), 0.0, 10.0, 0.1, ParameterUnit::None),
            float_parameter("fb_gain", "Feedback gain", None, Some(0.0), -1.0, 1.0, 0.01, ParameterUnit::None),
            float_parameter("out_mix", "Output mix", None, Some(0.0), -1.0, 1.0, 0.01, ParameterUnit::None),
        ],
    }
}

fn build(params: &ParameterSet, sample_rate: f32, layout: AudioChannelLayout) -> Result<BlockProcessor> {
    let in_gain = required_f32(params, "in_gain").map_err(anyhow::Error::msg)?;
    let sections = required_f32(params, "sections").map_err(anyhow::Error::msg)?;
    let freq = required_f32(params, "freq").map_err(anyhow::Error::msg)?;
    let lfo_freq = required_f32(params, "lfo_freq").map_err(anyhow::Error::msg)?;
    let lfo_waveform = required_f32(params, "lfo_waveform").map_err(anyhow::Error::msg)?;
    let mod_gain = required_f32(params, "mod_gain").map_err(anyhow::Error::msg)?;
    let fb_gain = required_f32(params, "fb_gain").map_err(anyhow::Error::msg)?;
    let out_mix = required_f32(params, "out_mix").map_err(anyhow::Error::msg)?;
    let lib_path = lv2::resolve_lv2_lib(PLUGIN_BINARY)?;
    let bundle_path = lv2::resolve_lv2_bundle(PLUGIN_DIR)?;

    let control_ports: &[(usize, f32)] = &[
        (PORT_CTRL_IN_GAIN, in_gain),
        (PORT_CTRL_SECTIONS, sections),
        (PORT_CTRL_FREQ, freq),
        (PORT_CTRL_LFO_FREQ, lfo_freq),
        (PORT_CTRL_LFO_WAVEFORM, lfo_waveform),
        (PORT_CTRL_MOD_GAIN, mod_gain),
        (PORT_CTRL_FB_GAIN, fb_gain),
        (PORT_CTRL_OUT_MIX, out_mix),
    ];

    match layout {
        AudioChannelLayout::Mono => {
            let processor = lv2::build_lv2_processor(&lib_path, PLUGIN_URI, sample_rate as f64, &bundle_path, &[PORT_AUDIO_IN_IN], &[PORT_AUDIO_OUT_OUT], control_ports)?;
            Ok(BlockProcessor::Mono(Box::new(processor)))
        }
        AudioChannelLayout::Stereo => {
            let left = lv2::build_lv2_processor(&lib_path, PLUGIN_URI, sample_rate as f64, &bundle_path, &[PORT_AUDIO_IN_IN], &[PORT_AUDIO_OUT_OUT], control_ports)?;
            let right = lv2::build_lv2_processor(&lib_path, PLUGIN_URI, sample_rate as f64, &bundle_path, &[PORT_AUDIO_IN_IN], &[PORT_AUDIO_OUT_OUT], control_ports)?;
            Ok(BlockProcessor::Stereo(Box::new(DualMonoProcessor { left, right })))
        }
    }
}

struct DualMonoProcessor { left: lv2::Lv2Processor, right: lv2::Lv2Processor }
impl StereoProcessor for DualMonoProcessor {
    fn process_frame(&mut self, input: [f32; 2]) -> [f32; 2] {
        [self.left.process_sample(input[0]), self.right.process_sample(input[1])]
    }
}

fn schema() -> Result<ModelParameterSchema> { Ok(model_schema()) }

pub const MODEL_DEFINITION: ModModelDefinition = ModModelDefinition {
    id: MODEL_ID, display_name: DISPLAY_NAME, brand: BRAND,
    backend_kind: ModBackendKind::Lv2, schema, build,
    supported_instruments: block_core::ALL_INSTRUMENTS, knob_layout: &[],
};
