// AUTO-GENERATED by tools/lv2_catalog_import — do not edit by hand.
// Re-run the tool to regenerate. Manual customisation goes in overrides.yaml.

#![allow(dead_code, unused_imports, unused_variables, clippy::all)]

use crate::registry::GainModelDefinition;
use crate::GainBackendKind;
use anyhow::Result;
use block_core::param::{
    bool_parameter, float_parameter, required_bool, required_f32,
    ModelParameterSchema, ParameterSet, ParameterUnit,
};
use block_core::{AudioChannelLayout, BlockProcessor, ModelAudioMode};

pub const MODEL_ID: &str = "lv2_rkr_exciter";
pub const DISPLAY_NAME: &str = "rkr Exciter";
const BRAND: &str = "rakarrack";

const PLUGIN_URI: &str = "http://rakarrack.sourceforge.net/effects.html#Exciter";
const PLUGIN_DIR: &str = "rkr";

#[cfg(target_os = "macos")]
const PLUGIN_BINARY: &str = "plugin.dylib";
#[cfg(target_os = "linux")]
const PLUGIN_BINARY: &str = "plugin.so";
#[cfg(target_os = "windows")]
const PLUGIN_BINARY: &str = "plugin.dll";

// Port indices (from TTL)
const PORT_AUDIO_IN_INPUT_L: usize = 0;
const PORT_AUDIO_IN_INPUT_R: usize = 1;
const PORT_AUDIO_OUT_OUTPUT_L: usize = 2;
const PORT_AUDIO_OUT_OUTPUT_R: usize = 3;
const PORT_CTRL_BYPASS: usize = 4;
const PORT_CTRL_GAIN: usize = 5;
const PORT_CTRL_HAR1: usize = 6;
const PORT_CTRL_HAR2: usize = 7;
const PORT_CTRL_HAR3: usize = 8;
const PORT_CTRL_HAR4: usize = 9;
const PORT_CTRL_HAR5: usize = 10;
const PORT_CTRL_HAR6: usize = 11;
const PORT_CTRL_HAR7: usize = 12;
const PORT_CTRL_HAR8: usize = 13;
const PORT_CTRL_HAR9: usize = 14;
const PORT_CTRL_HAR10: usize = 15;
const PORT_CTRL_LPF: usize = 16;
const PORT_CTRL_HPF: usize = 17;

pub fn model_schema() -> ModelParameterSchema {
    ModelParameterSchema {
        effect_type: block_core::EFFECT_TYPE_GAIN.into(),
        model: MODEL_ID.into(),
        display_name: DISPLAY_NAME.into(),
        audio_mode: ModelAudioMode::TrueStereo,
        parameters: vec![
            bool_parameter("bypass", "Bypass", None, Some(false)),
            float_parameter("gain", "Gain", None, Some(0.0), 0.0, 127.0, 1.0, ParameterUnit::None),
            float_parameter("har1", "1st Harmonic", None, Some(0.0), -64.0, 64.0, 1.0, ParameterUnit::None),
            float_parameter("har2", "2nd Harmonic", None, Some(0.0), -64.0, 64.0, 1.0, ParameterUnit::None),
            float_parameter("har3", "3rd Harmonic", None, Some(0.0), -64.0, 64.0, 1.0, ParameterUnit::None),
            float_parameter("har4", "4th Harmonic", None, Some(0.0), -64.0, 64.0, 1.0, ParameterUnit::None),
            float_parameter("har5", "5th Harmonic", None, Some(0.0), -64.0, 64.0, 1.0, ParameterUnit::None),
            float_parameter("har6", "6th Harmonic", None, Some(0.0), -64.0, 64.0, 1.0, ParameterUnit::None),
            float_parameter("har7", "7th Harmonic", None, Some(0.0), -64.0, 64.0, 1.0, ParameterUnit::None),
            float_parameter("har8", "8th Harmonic", None, Some(0.0), -64.0, 64.0, 1.0, ParameterUnit::None),
            float_parameter("har9", "9th Harmonic", None, Some(0.0), -64.0, 64.0, 1.0, ParameterUnit::None),
            float_parameter("har10", "10th Harmonic", None, Some(0.0), -64.0, 64.0, 1.0, ParameterUnit::None),
            float_parameter("lpf", "Low-Pass Filter Cutoff", None, Some(20000.0), 20.0, 26000.0, 10.0, ParameterUnit::Hertz),
            float_parameter("hpf", "High-Pass Filter Cutoff", None, Some(20.0), 20.0, 20000.0, 10.0, ParameterUnit::Hertz),
        ],
    }
}

fn build(params: &ParameterSet, sample_rate: f32, layout: AudioChannelLayout) -> Result<BlockProcessor> {
    let bypass = required_bool(params, "bypass").map_err(anyhow::Error::msg)?;
    let gain = required_f32(params, "gain").map_err(anyhow::Error::msg)?;
    let har1 = required_f32(params, "har1").map_err(anyhow::Error::msg)?;
    let har2 = required_f32(params, "har2").map_err(anyhow::Error::msg)?;
    let har3 = required_f32(params, "har3").map_err(anyhow::Error::msg)?;
    let har4 = required_f32(params, "har4").map_err(anyhow::Error::msg)?;
    let har5 = required_f32(params, "har5").map_err(anyhow::Error::msg)?;
    let har6 = required_f32(params, "har6").map_err(anyhow::Error::msg)?;
    let har7 = required_f32(params, "har7").map_err(anyhow::Error::msg)?;
    let har8 = required_f32(params, "har8").map_err(anyhow::Error::msg)?;
    let har9 = required_f32(params, "har9").map_err(anyhow::Error::msg)?;
    let har10 = required_f32(params, "har10").map_err(anyhow::Error::msg)?;
    let lpf = required_f32(params, "lpf").map_err(anyhow::Error::msg)?;
    let hpf = required_f32(params, "hpf").map_err(anyhow::Error::msg)?;
    let lib_path = lv2::resolve_lv2_lib(PLUGIN_BINARY)?;
    let bundle_path = lv2::resolve_lv2_bundle(PLUGIN_DIR)?;

    let control_ports: &[(usize, f32)] = &[
        (PORT_CTRL_BYPASS, if bypass { 1.0 } else { 0.0 }),
        (PORT_CTRL_GAIN, gain),
        (PORT_CTRL_HAR1, har1),
        (PORT_CTRL_HAR2, har2),
        (PORT_CTRL_HAR3, har3),
        (PORT_CTRL_HAR4, har4),
        (PORT_CTRL_HAR5, har5),
        (PORT_CTRL_HAR6, har6),
        (PORT_CTRL_HAR7, har7),
        (PORT_CTRL_HAR8, har8),
        (PORT_CTRL_HAR9, har9),
        (PORT_CTRL_HAR10, har10),
        (PORT_CTRL_LPF, lpf),
        (PORT_CTRL_HPF, hpf),
    ];

    let processor = lv2::build_stereo_lv2_processor(&lib_path, PLUGIN_URI, sample_rate as f64, &bundle_path, &[PORT_AUDIO_IN_INPUT_L, PORT_AUDIO_IN_INPUT_R], &[PORT_AUDIO_OUT_OUTPUT_L, PORT_AUDIO_OUT_OUTPUT_R], control_ports)?;
    let _ = layout;
    Ok(BlockProcessor::Stereo(Box::new(processor)))
}

fn schema() -> Result<ModelParameterSchema> { Ok(model_schema()) }

pub const MODEL_DEFINITION: GainModelDefinition = GainModelDefinition {
    id: MODEL_ID, display_name: DISPLAY_NAME, brand: BRAND,
    backend_kind: GainBackendKind::Lv2, schema, build,
    validate, asset_summary,
    supported_instruments: block_core::ALL_INSTRUMENTS, knob_layout: &[],
};

fn validate(_params: &ParameterSet) -> Result<()> { Ok(()) }
fn asset_summary(_params: &ParameterSet) -> Result<String> { Ok(String::new()) }
