// AUTO-GENERATED by tools/lv2_catalog_import — do not edit by hand.
// Re-run the tool to regenerate. Manual customisation goes in overrides.yaml.

#![allow(dead_code, unused_imports, unused_variables, clippy::all)]

use crate::registry::GainModelDefinition;
use crate::GainBackendKind;
use anyhow::Result;
use block_core::param::{
    bool_parameter, float_parameter, required_bool, required_f32,
    ModelParameterSchema, ParameterSet, ParameterUnit,
};
use block_core::{AudioChannelLayout, BlockProcessor, ModelAudioMode};

pub const MODEL_ID: &str = "lv2_rkr_bad_valve";
pub const DISPLAY_NAME: &str = "rkr Valve";
const BRAND: &str = "rakarrack";

const PLUGIN_URI: &str = "http://rakarrack.sourceforge.net/effects.html#Valve";
const PLUGIN_DIR: &str = "rkr-bad";
pub const THUMBNAIL_PATH: Option<&str> = Some(".plugins/lv2/rkr-bad.lv2/modgui/thumbnail-rkr-valve.png");

#[cfg(target_os = "macos")]
const PLUGIN_BINARY: &str = "rkrlv2.dylib";
#[cfg(target_os = "linux")]
const PLUGIN_BINARY: &str = "rkrlv2.so";
#[cfg(target_os = "windows")]
const PLUGIN_BINARY: &str = "rkrlv2.dll";

// Port indices (from TTL)
const PORT_AUDIO_IN_INPUT_L: usize = 0;
const PORT_AUDIO_IN_INPUT_R: usize = 1;
const PORT_AUDIO_OUT_OUTPUT_L: usize = 2;
const PORT_AUDIO_OUT_OUTPUT_R: usize = 3;
const PORT_CTRL_BYPASS: usize = 4;
const PORT_CTRL_WETDRY: usize = 5;
const PORT_CTRL_PAN: usize = 6;
const PORT_CTRL_LR_CR: usize = 7;
const PORT_CTRL_DRIVE: usize = 8;
const PORT_CTRL_LEVEL: usize = 9;
const PORT_CTRL_NEG: usize = 10;
const PORT_CTRL_LPF: usize = 11;
const PORT_CTRL_HPF: usize = 12;
const PORT_CTRL_STEREO: usize = 13;
const PORT_CTRL_PREFILTER: usize = 14;
const PORT_CTRL_DIST: usize = 15;
const PORT_CTRL_ED: usize = 16;
const PORT_CTRL_PRES: usize = 17;

pub fn model_schema() -> ModelParameterSchema {
    ModelParameterSchema {
        effect_type: block_core::EFFECT_TYPE_GAIN.into(),
        model: MODEL_ID.into(),
        display_name: DISPLAY_NAME.into(),
        audio_mode: ModelAudioMode::TrueStereo,
        parameters: vec![
            bool_parameter("bypass", "Bypass", None, Some(false)),
            float_parameter("wetdry", "Wet/Dry", None, Some(84.0), 0.0, 127.0, 1.0, ParameterUnit::None),
            float_parameter("pan", "Panning", None, Some(0.0), -64.0, 63.0, 1.0, ParameterUnit::None),
            float_parameter("lrcr", "Left/Right Crossover", None, Some(87.0), 0.0, 127.0, 1.0, ParameterUnit::None),
            float_parameter("drive", "Drive", None, Some(56.0), 0.0, 127.0, 1.0, ParameterUnit::None),
            float_parameter("level", "Level", None, Some(40.0), 0.0, 127.0, 1.0, ParameterUnit::None),
            bool_parameter("neg", "Negate (Polarity Switch)", None, Some(false)),
            float_parameter("lpf", "Lowpass Filter", None, Some(6703.0), 20.0, 26000.0, 10.0, ParameterUnit::Hertz),
            float_parameter("hpf", "Highpass Filter", None, Some(21.0), 20.0, 20000.0, 10.0, ParameterUnit::Hertz),
            bool_parameter("stereo", "Stereo", None, Some(false)),
            bool_parameter("prefilter", "Prefilter", None, Some(false)),
            float_parameter("dist", "Distortion", None, Some(52.0), 0.0, 127.0, 1.0, ParameterUnit::None),
            bool_parameter("ed", "Extra Distortion", None, Some(true)),
            float_parameter("pres", "Presence", None, Some(18.0), 0.0, 100.0, 1.0, ParameterUnit::None),
        ],
    }
}

fn build(params: &ParameterSet, sample_rate: f32, layout: AudioChannelLayout) -> Result<BlockProcessor> {
    let bypass = required_bool(params, "bypass").map_err(anyhow::Error::msg)?;
    let wetdry = required_f32(params, "wetdry").map_err(anyhow::Error::msg)?;
    let pan = required_f32(params, "pan").map_err(anyhow::Error::msg)?;
    let lrcr = required_f32(params, "lrcr").map_err(anyhow::Error::msg)?;
    let drive = required_f32(params, "drive").map_err(anyhow::Error::msg)?;
    let level = required_f32(params, "level").map_err(anyhow::Error::msg)?;
    let neg = required_bool(params, "neg").map_err(anyhow::Error::msg)?;
    let lpf = required_f32(params, "lpf").map_err(anyhow::Error::msg)?;
    let hpf = required_f32(params, "hpf").map_err(anyhow::Error::msg)?;
    let stereo = required_bool(params, "stereo").map_err(anyhow::Error::msg)?;
    let prefilter = required_bool(params, "prefilter").map_err(anyhow::Error::msg)?;
    let dist = required_f32(params, "dist").map_err(anyhow::Error::msg)?;
    let ed = required_bool(params, "ed").map_err(anyhow::Error::msg)?;
    let pres = required_f32(params, "pres").map_err(anyhow::Error::msg)?;
    let lib_path = lv2::resolve_lv2_lib(PLUGIN_BINARY)?;
    let bundle_path = lv2::resolve_lv2_bundle(PLUGIN_DIR)?;

    let control_ports: &[(usize, f32)] = &[
        (PORT_CTRL_BYPASS, if bypass { 1.0 } else { 0.0 }),
        (PORT_CTRL_WETDRY, wetdry),
        (PORT_CTRL_PAN, pan),
        (PORT_CTRL_LR_CR, lrcr),
        (PORT_CTRL_DRIVE, drive),
        (PORT_CTRL_LEVEL, level),
        (PORT_CTRL_NEG, if neg { 1.0 } else { 0.0 }),
        (PORT_CTRL_LPF, lpf),
        (PORT_CTRL_HPF, hpf),
        (PORT_CTRL_STEREO, if stereo { 1.0 } else { 0.0 }),
        (PORT_CTRL_PREFILTER, if prefilter { 1.0 } else { 0.0 }),
        (PORT_CTRL_DIST, dist),
        (PORT_CTRL_ED, if ed { 1.0 } else { 0.0 }),
        (PORT_CTRL_PRES, pres),
    ];

    let processor = lv2::build_stereo_lv2_processor(&lib_path, PLUGIN_URI, sample_rate as f64, &bundle_path, &[PORT_AUDIO_IN_INPUT_L, PORT_AUDIO_IN_INPUT_R], &[PORT_AUDIO_OUT_OUTPUT_L, PORT_AUDIO_OUT_OUTPUT_R], control_ports)?;
    let _ = layout;
    Ok(BlockProcessor::Stereo(Box::new(processor)))
}

fn schema() -> Result<ModelParameterSchema> { Ok(model_schema()) }

pub const MODEL_DEFINITION: GainModelDefinition = GainModelDefinition {
    id: MODEL_ID, display_name: DISPLAY_NAME, brand: BRAND,
    backend_kind: GainBackendKind::Lv2, schema, build,
    validate, asset_summary,
    supported_instruments: block_core::ALL_INSTRUMENTS, knob_layout: &[],
};

fn validate(_params: &ParameterSet) -> Result<()> { Ok(()) }
fn asset_summary(_params: &ParameterSet) -> Result<String> { Ok(String::new()) }
