// AUTO-GENERATED by tools/lv2_catalog_import — do not edit by hand.
// Re-run the tool to regenerate. Manual customisation goes in overrides.yaml.

#![allow(dead_code, unused_imports, unused_variables, clippy::all)]

use crate::registry::GainModelDefinition;
use crate::GainBackendKind;
use anyhow::Result;
use block_core::param::{
    float_parameter, required_f32, ModelParameterSchema, ParameterSet, ParameterUnit,
};
use block_core::{AudioChannelLayout, BlockProcessor, ModelAudioMode, MonoProcessor, StereoProcessor};

pub const MODEL_ID: &str = "lv2_mod_caps_saturate";
pub const DISPLAY_NAME: &str = "C* Saturate";
const BRAND: &str = "caps";

const PLUGIN_URI: &str = "http://moddevices.com/plugins/caps/Saturate";
const PLUGIN_DIR: &str = "mod-caps-Saturate";

#[cfg(target_os = "macos")]
const PLUGIN_BINARY: &str = "Saturate.dylib";
#[cfg(target_os = "linux")]
const PLUGIN_BINARY: &str = "Saturate.so";
#[cfg(target_os = "windows")]
const PLUGIN_BINARY: &str = "Saturate.dll";

// Port indices (from TTL)
const PORT_CTRL_MODE: usize = 0;
const PORT_CTRL_GAIN: usize = 1;
const PORT_CTRL_BIAS: usize = 2;
const PORT_AUDIO_IN_IN: usize = 3;
const PORT_AUDIO_OUT_OUT: usize = 4;

pub fn model_schema() -> ModelParameterSchema {
    ModelParameterSchema {
        effect_type: block_core::EFFECT_TYPE_GAIN.into(),
        model: MODEL_ID.into(),
        display_name: DISPLAY_NAME.into(),
        audio_mode: ModelAudioMode::DualMono,
        parameters: vec![
            float_parameter("mode", "Mode", None, Some(1.0), 0.0, 11.0, 0.1, ParameterUnit::None),
            float_parameter("gain", "Gain", None, Some(0.0), -24.0, 72.0, 0.1, ParameterUnit::Decibels),
            float_parameter("bias", "Bias", None, Some(0.0), 0.0, 1.0, 0.01, ParameterUnit::None),
        ],
    }
}

fn build(params: &ParameterSet, sample_rate: f32, layout: AudioChannelLayout) -> Result<BlockProcessor> {
    let mode = required_f32(params, "mode").map_err(anyhow::Error::msg)?;
    let gain = required_f32(params, "gain").map_err(anyhow::Error::msg)?;
    let bias = required_f32(params, "bias").map_err(anyhow::Error::msg)?;
    let lib_path = lv2::resolve_lv2_lib(PLUGIN_BINARY)?;
    let bundle_path = lv2::resolve_lv2_bundle(PLUGIN_DIR)?;

    let control_ports: &[(usize, f32)] = &[
        (PORT_CTRL_MODE, mode),
        (PORT_CTRL_GAIN, gain),
        (PORT_CTRL_BIAS, bias),
    ];

    match layout {
        AudioChannelLayout::Mono => {
            let processor = lv2::build_lv2_processor(&lib_path, PLUGIN_URI, sample_rate as f64, &bundle_path, &[PORT_AUDIO_IN_IN], &[PORT_AUDIO_OUT_OUT], control_ports)?;
            Ok(BlockProcessor::Mono(Box::new(processor)))
        }
        AudioChannelLayout::Stereo => {
            let left = lv2::build_lv2_processor(&lib_path, PLUGIN_URI, sample_rate as f64, &bundle_path, &[PORT_AUDIO_IN_IN], &[PORT_AUDIO_OUT_OUT], control_ports)?;
            let right = lv2::build_lv2_processor(&lib_path, PLUGIN_URI, sample_rate as f64, &bundle_path, &[PORT_AUDIO_IN_IN], &[PORT_AUDIO_OUT_OUT], control_ports)?;
            Ok(BlockProcessor::Stereo(Box::new(DualMonoProcessor { left, right })))
        }
    }
}

struct DualMonoProcessor { left: lv2::Lv2Processor, right: lv2::Lv2Processor }
impl StereoProcessor for DualMonoProcessor {
    fn process_frame(&mut self, input: [f32; 2]) -> [f32; 2] {
        [self.left.process_sample(input[0]), self.right.process_sample(input[1])]
    }
}

fn schema() -> Result<ModelParameterSchema> { Ok(model_schema()) }

pub const MODEL_DEFINITION: GainModelDefinition = GainModelDefinition {
    id: MODEL_ID, display_name: DISPLAY_NAME, brand: BRAND,
    backend_kind: GainBackendKind::Lv2, schema, build,
    validate, asset_summary,
    supported_instruments: block_core::ALL_INSTRUMENTS, knob_layout: &[],
};

fn validate(_params: &ParameterSet) -> Result<()> { Ok(()) }
fn asset_summary(_params: &ParameterSet) -> Result<String> { Ok(String::new()) }
