// AUTO-GENERATED by tools/lv2_catalog_import — do not edit by hand.
// Re-run the tool to regenerate. Manual customisation goes in overrides.yaml.

#![allow(dead_code, unused_imports, unused_variables, clippy::all)]

use crate::registry::GainModelDefinition;
use crate::GainBackendKind;
use anyhow::Result;
use block_core::param::{
    float_parameter, required_f32, ModelParameterSchema, ParameterSet, ParameterUnit,
};
use block_core::{AudioChannelLayout, BlockProcessor, ModelAudioMode};

pub const MODEL_ID: &str = "lv2_mod_mda_degrade";
pub const DISPLAY_NAME: &str = "MDA Degrade";
const BRAND: &str = "mda";

const PLUGIN_URI: &str = "http://moddevices.com/plugins/mda/Degrade";
const PLUGIN_DIR: &str = "mod-mda-Degrade";
pub const THUMBNAIL_PATH: Option<&str> = Some(".plugins/lv2/mod-mda-Degrade.lv2/modgui/thumbnail-mda-degrade.png");

#[cfg(target_os = "macos")]
const PLUGIN_BINARY: &str = "Degrade.dylib";
#[cfg(target_os = "linux")]
const PLUGIN_BINARY: &str = "Degrade.so";
#[cfg(target_os = "windows")]
const PLUGIN_BINARY: &str = "Degrade.dll";

// Port indices (from TTL)
const PORT_CTRL_HEADROOM: usize = 0;
const PORT_CTRL_QUANT: usize = 1;
const PORT_CTRL_RATE: usize = 2;
const PORT_CTRL_INTEGRATOR_SR: usize = 3;
const PORT_CTRL_POST_FILT: usize = 4;
const PORT_CTRL_NON_LIN: usize = 5;
const PORT_CTRL_EVEN_ODD: usize = 6;
const PORT_CTRL_OUTPUT: usize = 7;
const PORT_AUDIO_IN_LEFT_IN: usize = 8;
const PORT_AUDIO_IN_RIGHT_IN: usize = 9;
const PORT_AUDIO_OUT_LEFT_OUT: usize = 10;
const PORT_AUDIO_OUT_RIGHT_OUT: usize = 11;

pub fn model_schema() -> ModelParameterSchema {
    ModelParameterSchema {
        effect_type: block_core::EFFECT_TYPE_GAIN.into(),
        model: MODEL_ID.into(),
        display_name: DISPLAY_NAME.into(),
        audio_mode: ModelAudioMode::TrueStereo,
        parameters: vec![
            float_parameter("headroom", "Headroom", None, Some(-6.0), -30.0, 0.0, 0.1, ParameterUnit::Decibels),
            float_parameter("quant", "Quant", None, Some(10.0), 4.0, 16.0, 0.1, ParameterUnit::None),
            float_parameter("rate", "Rate", None, Some(48000.0), 4800.0, 48000.0, 10.0, ParameterUnit::None),
            float_parameter("integrator_sr", "Integrator", None, Some(0.0), 0.0, 1.0, 0.01, ParameterUnit::None),
            float_parameter("post_filt", "Post Filter", None, Some(15000.0), 200.0, 20000.0, 10.0, ParameterUnit::Hertz),
            float_parameter("non_lin", "Non-Lin", None, Some(0.16), 0.0, 1.0, 0.01, ParameterUnit::None),
            float_parameter("even_odd", "EvenOdd", None, Some(1.0), 0.0, 1.0, 0.01, ParameterUnit::None),
            float_parameter("output", "Output", None, Some(0.0), -20.0, 20.0, 0.1, ParameterUnit::None),
        ],
    }
}

fn build(params: &ParameterSet, sample_rate: f32, layout: AudioChannelLayout) -> Result<BlockProcessor> {
    let headroom = required_f32(params, "headroom").map_err(anyhow::Error::msg)?;
    let quant = required_f32(params, "quant").map_err(anyhow::Error::msg)?;
    let rate = required_f32(params, "rate").map_err(anyhow::Error::msg)?;
    let integrator_sr = required_f32(params, "integrator_sr").map_err(anyhow::Error::msg)?;
    let post_filt = required_f32(params, "post_filt").map_err(anyhow::Error::msg)?;
    let non_lin = required_f32(params, "non_lin").map_err(anyhow::Error::msg)?;
    let even_odd = required_f32(params, "even_odd").map_err(anyhow::Error::msg)?;
    let output = required_f32(params, "output").map_err(anyhow::Error::msg)?;
    let lib_path = lv2::resolve_lv2_lib(PLUGIN_BINARY)?;
    let bundle_path = lv2::resolve_lv2_bundle(PLUGIN_DIR)?;

    let control_ports: &[(usize, f32)] = &[
        (PORT_CTRL_HEADROOM, headroom),
        (PORT_CTRL_QUANT, quant),
        (PORT_CTRL_RATE, rate),
        (PORT_CTRL_INTEGRATOR_SR, integrator_sr),
        (PORT_CTRL_POST_FILT, post_filt),
        (PORT_CTRL_NON_LIN, non_lin),
        (PORT_CTRL_EVEN_ODD, even_odd),
        (PORT_CTRL_OUTPUT, output),
    ];

    let processor = lv2::build_stereo_lv2_processor(&lib_path, PLUGIN_URI, sample_rate as f64, &bundle_path, &[PORT_AUDIO_IN_LEFT_IN, PORT_AUDIO_IN_RIGHT_IN], &[PORT_AUDIO_OUT_LEFT_OUT, PORT_AUDIO_OUT_RIGHT_OUT], control_ports)?;
    let _ = layout;
    Ok(BlockProcessor::Stereo(Box::new(processor)))
}

fn schema() -> Result<ModelParameterSchema> { Ok(model_schema()) }

pub const MODEL_DEFINITION: GainModelDefinition = GainModelDefinition {
    id: MODEL_ID, display_name: DISPLAY_NAME, brand: BRAND,
    backend_kind: GainBackendKind::Lv2, schema, build,
    validate, asset_summary,
    supported_instruments: block_core::ALL_INSTRUMENTS, knob_layout: &[],
};

fn validate(_params: &ParameterSet) -> Result<()> { Ok(()) }
fn asset_summary(_params: &ParameterSet) -> Result<String> { Ok(String::new()) }
