// AUTO-GENERATED by tools/lv2_catalog_import — do not edit by hand.
// Re-run the tool to regenerate. Manual customisation goes in overrides.yaml.

#![allow(dead_code, unused_imports, unused_variables, clippy::all)]

use crate::registry::GainModelDefinition;
use crate::GainBackendKind;
use anyhow::Result;
use block_core::param::{
    bool_parameter, float_parameter, required_bool, required_f32,
    ModelParameterSchema, ParameterSet, ParameterUnit,
};
use block_core::{AudioChannelLayout, BlockProcessor, ModelAudioMode};

pub const MODEL_ID: &str = "lv2_calf_bad_tape_simulator";
pub const DISPLAY_NAME: &str = "Calf Tape Simulator";
const BRAND: &str = "calf";

const PLUGIN_URI: &str = "http://calf.sourceforge.net/plugins/TapeSimulator";
const PLUGIN_DIR: &str = "calf-bad";

#[cfg(target_os = "macos")]
const PLUGIN_BINARY: &str = "calf.dylib";
#[cfg(target_os = "linux")]
const PLUGIN_BINARY: &str = "calf.so";
#[cfg(target_os = "windows")]
const PLUGIN_BINARY: &str = "calf.dll";

// Port indices (from TTL)
const PORT_AUDIO_IN_IN_L: usize = 0;
const PORT_AUDIO_IN_IN_R: usize = 1;
const PORT_AUDIO_OUT_OUT_L: usize = 2;
const PORT_AUDIO_OUT_OUT_R: usize = 3;
const PORT_CTRL_BYPASS: usize = 4;
const PORT_CTRL_LEVEL_IN: usize = 5;
const PORT_CTRL_LEVEL_OUT: usize = 6;
const PORT_CTRL_METER_IN_L: usize = 7;
const PORT_CTRL_METER_IN_R: usize = 8;
const PORT_CTRL_METER_OUT_L: usize = 9;
const PORT_CTRL_METER_OUT_R: usize = 10;
const PORT_CTRL_CLIP_IN_L: usize = 11;
const PORT_CTRL_CLIP_IN_R: usize = 12;
const PORT_CTRL_CLIP_OUT_L: usize = 13;
const PORT_CTRL_CLIP_OUT_R: usize = 14;
const PORT_CTRL_MIX: usize = 15;
const PORT_CTRL_LOWPASS: usize = 16;
const PORT_CTRL_SPEED: usize = 17;
const PORT_CTRL_NOISE: usize = 18;
const PORT_CTRL_MECHANICAL: usize = 19;
const PORT_CTRL_MAGNETICAL: usize = 20;
const PORT_CTRL_POST: usize = 21;

pub fn model_schema() -> ModelParameterSchema {
    ModelParameterSchema {
        effect_type: block_core::EFFECT_TYPE_GAIN.into(),
        model: MODEL_ID.into(),
        display_name: DISPLAY_NAME.into(),
        audio_mode: ModelAudioMode::TrueStereo,
        parameters: vec![
            bool_parameter("bypass", "Bypass", None, Some(false)),
            float_parameter("level_in", "Input Gain", None, Some(0.5), 0.015625, 64.0, 0.1, ParameterUnit::None),
            float_parameter("level_out", "Output Gain", None, Some(1.0), 0.015625, 64.0, 0.1, ParameterUnit::None),
            float_parameter("mix", "Mix", None, Some(1.0), 0.0, 1.0, 0.01, ParameterUnit::None),
            float_parameter("lowpass", "Filter", None, Some(12500.0), 1000.0, 20000.0, 10.0, ParameterUnit::Hertz),
            float_parameter("speed", "Speed Simulation", None, Some(1.0), 0.0, 1.0, 0.01, ParameterUnit::None),
            float_parameter("noise", "Noise", None, Some(0.1), 0.0, 1.0, 0.01, ParameterUnit::None),
            float_parameter("mechanical", "Mechanical", None, Some(0.2), 0.0, 1.0, 0.01, ParameterUnit::None),
            bool_parameter("magnetical", "Magnetical", None, Some(true)),
            bool_parameter("post", "Post-Filter", None, Some(false)),
        ],
    }
}

fn build(params: &ParameterSet, sample_rate: f32, layout: AudioChannelLayout) -> Result<BlockProcessor> {
    let bypass = required_bool(params, "bypass").map_err(anyhow::Error::msg)?;
    let level_in = required_f32(params, "level_in").map_err(anyhow::Error::msg)?;
    let level_out = required_f32(params, "level_out").map_err(anyhow::Error::msg)?;
    let mix = required_f32(params, "mix").map_err(anyhow::Error::msg)?;
    let lowpass = required_f32(params, "lowpass").map_err(anyhow::Error::msg)?;
    let speed = required_f32(params, "speed").map_err(anyhow::Error::msg)?;
    let noise = required_f32(params, "noise").map_err(anyhow::Error::msg)?;
    let mechanical = required_f32(params, "mechanical").map_err(anyhow::Error::msg)?;
    let magnetical = required_bool(params, "magnetical").map_err(anyhow::Error::msg)?;
    let post = required_bool(params, "post").map_err(anyhow::Error::msg)?;
    let lib_path = lv2::resolve_lv2_lib(PLUGIN_BINARY)?;
    let bundle_path = lv2::resolve_lv2_bundle(PLUGIN_DIR)?;

    let control_ports: &[(usize, f32)] = &[
        (PORT_CTRL_BYPASS, if bypass { 1.0 } else { 0.0 }),
        (PORT_CTRL_LEVEL_IN, level_in),
        (PORT_CTRL_LEVEL_OUT, level_out),
        (PORT_CTRL_MIX, mix),
        (PORT_CTRL_LOWPASS, lowpass),
        (PORT_CTRL_SPEED, speed),
        (PORT_CTRL_NOISE, noise),
        (PORT_CTRL_MECHANICAL, mechanical),
        (PORT_CTRL_MAGNETICAL, if magnetical { 1.0 } else { 0.0 }),
        (PORT_CTRL_POST, if post { 1.0 } else { 0.0 }),
    ];

    let processor = lv2::build_stereo_lv2_processor(&lib_path, PLUGIN_URI, sample_rate as f64, &bundle_path, &[PORT_AUDIO_IN_IN_L, PORT_AUDIO_IN_IN_R], &[PORT_AUDIO_OUT_OUT_L, PORT_AUDIO_OUT_OUT_R], control_ports)?;
    let _ = layout;
    Ok(BlockProcessor::Stereo(Box::new(processor)))
}

fn schema() -> Result<ModelParameterSchema> { Ok(model_schema()) }

pub const MODEL_DEFINITION: GainModelDefinition = GainModelDefinition {
    id: MODEL_ID, display_name: DISPLAY_NAME, brand: BRAND,
    backend_kind: GainBackendKind::Lv2, schema, build,
    validate, asset_summary,
    supported_instruments: block_core::ALL_INSTRUMENTS, knob_layout: &[],
};

fn validate(_params: &ParameterSet) -> Result<()> { Ok(()) }
fn asset_summary(_params: &ParameterSet) -> Result<String> { Ok(String::new()) }
