// AUTO-GENERATED by tools/lv2_catalog_import — do not edit by hand.
// Re-run the tool to regenerate. Manual customisation goes in overrides.yaml.

#![allow(dead_code, unused_imports, unused_variables, clippy::approx_constant, clippy::excessive_precision)]

use crate::registry::GainModelDefinition;
use crate::GainBackendKind;
use anyhow::Result;
use block_core::param::{
    bool_parameter, float_parameter, required_bool, required_f32,
    ModelParameterSchema, ParameterSet, ParameterUnit,
};
use block_core::{AudioChannelLayout, BlockProcessor, ModelAudioMode, MonoProcessor, StereoProcessor};

pub const MODEL_ID: &str = "lv2_ojd_schrammel_ojd";
pub const DISPLAY_NAME: &str = "Schrammel OJD";
const BRAND: &str = "schrammel";

const PLUGIN_URI: &str = "https://github.com/JanosGit/Schrammel_OJD";
const PLUGIN_DIR: &str = "OJD";

#[cfg(target_os = "macos")]
const PLUGIN_BINARY: &str = "OJD.dylib.dylib";
#[cfg(target_os = "linux")]
const PLUGIN_BINARY: &str = "OJD.dylib.so";
#[cfg(target_os = "windows")]
const PLUGIN_BINARY: &str = "OJD.dylib.dll";

// Port indices (from TTL)
const PORT_CTRL_LV2_FREEWHEEL: usize = 0;
const PORT_AUDIO_IN_LV2_AUDIO_IN: usize = 1;
const PORT_AUDIO_OUT_LV2_AUDIO_OUT: usize = 2;
const PORT_CTRL_DRIVE: usize = 3;
const PORT_CTRL_TONE: usize = 4;
const PORT_CTRL_VOLUME: usize = 5;
const PORT_CTRL_HP_LP: usize = 6;
const PORT_CTRL_LV2_ENABLED: usize = 7;

pub fn model_schema() -> ModelParameterSchema {
    ModelParameterSchema {
        effect_type: block_core::EFFECT_TYPE_GAIN.into(),
        model: MODEL_ID.into(),
        display_name: DISPLAY_NAME.into(),
        audio_mode: ModelAudioMode::DualMono,
        parameters: vec![
            bool_parameter("lv2_freewheel", "Freewheel", None, Some(false)),
            float_parameter("drive", "Drive", None, Some(0.165), 0.0, 1.0, 0.01, ParameterUnit::None),
            float_parameter("tone", "Tone", None, Some(0.5), 0.0, 1.0, 0.01, ParameterUnit::None),
            float_parameter("volume", "Volume", None, Some(0.835), 0.0, 1.0, 0.01, ParameterUnit::None),
            float_parameter("hp_lp", "HP / LP", None, Some(0.0), 0.0, 1.0, 0.01, ParameterUnit::None),
            bool_parameter("lv2_enabled", "Enabled", None, Some(false)),
        ],
    }
}

fn build(params: &ParameterSet, sample_rate: f32, layout: AudioChannelLayout) -> Result<BlockProcessor> {
    let lv2_freewheel = required_bool(params, "lv2_freewheel").map_err(anyhow::Error::msg)?;
    let drive = required_f32(params, "drive").map_err(anyhow::Error::msg)?;
    let tone = required_f32(params, "tone").map_err(anyhow::Error::msg)?;
    let volume = required_f32(params, "volume").map_err(anyhow::Error::msg)?;
    let hp_lp = required_f32(params, "hp_lp").map_err(anyhow::Error::msg)?;
    let lv2_enabled = required_bool(params, "lv2_enabled").map_err(anyhow::Error::msg)?;
    let lib_path = lv2::resolve_lv2_lib(PLUGIN_BINARY)?;
    let bundle_path = lv2::resolve_lv2_bundle(PLUGIN_DIR)?;

    let control_ports: &[(usize, f32)] = &[
        (PORT_CTRL_LV2_FREEWHEEL, if lv2_freewheel { 1.0 } else { 0.0 }),
        (PORT_CTRL_DRIVE, drive),
        (PORT_CTRL_TONE, tone),
        (PORT_CTRL_VOLUME, volume),
        (PORT_CTRL_HP_LP, hp_lp),
        (PORT_CTRL_LV2_ENABLED, if lv2_enabled { 1.0 } else { 0.0 }),
    ];

    match layout {
        AudioChannelLayout::Mono => {
            let processor = lv2::build_lv2_processor(&lib_path, PLUGIN_URI, sample_rate as f64, &bundle_path, &[PORT_AUDIO_IN_LV2_AUDIO_IN], &[PORT_AUDIO_OUT_LV2_AUDIO_OUT], control_ports)?;
            Ok(BlockProcessor::Mono(Box::new(processor)))
        }
        AudioChannelLayout::Stereo => {
            let left = lv2::build_lv2_processor(&lib_path, PLUGIN_URI, sample_rate as f64, &bundle_path, &[PORT_AUDIO_IN_LV2_AUDIO_IN], &[PORT_AUDIO_OUT_LV2_AUDIO_OUT], control_ports)?;
            let right = lv2::build_lv2_processor(&lib_path, PLUGIN_URI, sample_rate as f64, &bundle_path, &[PORT_AUDIO_IN_LV2_AUDIO_IN], &[PORT_AUDIO_OUT_LV2_AUDIO_OUT], control_ports)?;
            Ok(BlockProcessor::Stereo(Box::new(DualMonoProcessor { left, right })))
        }
    }
}

struct DualMonoProcessor { left: lv2::Lv2Processor, right: lv2::Lv2Processor }
impl StereoProcessor for DualMonoProcessor {
    fn process_frame(&mut self, input: [f32; 2]) -> [f32; 2] {
        [self.left.process_sample(input[0]), self.right.process_sample(input[1])]
    }
}

fn schema() -> Result<ModelParameterSchema> { Ok(model_schema()) }

pub const MODEL_DEFINITION: GainModelDefinition = GainModelDefinition {
    id: MODEL_ID, display_name: DISPLAY_NAME, brand: BRAND,
    backend_kind: GainBackendKind::Lv2, schema, build,
    validate, asset_summary,
    supported_instruments: block_core::ALL_INSTRUMENTS, knob_layout: &[],
};

fn validate(_params: &ParameterSet) -> Result<()> { Ok(()) }
fn asset_summary(_params: &ParameterSet) -> Result<String> { Ok(String::new()) }
