import { HorizontalBox } from "std-widgets.slint";
import { Theme } from "../theme.slint";

export component Header {
    height: 40px;

    HorizontalBox {
        padding-left: Theme.spaces.xlarge;
        padding-right: Theme.spaces.xlarge;
        spacing: Theme.spaces.medium;

        Text {
            text: "OpenRig";
            color: Theme.palette.text-primary;
            font-size: Theme.typo.brand.size;
            font-weight: Theme.typo.brand.weight;
            vertical-alignment: center;
        }

        Rectangle {
            horizontal-stretch: 1;
            background: transparent;
        }
    }
}
