// AUTO-GENERATED by tools/lv2_catalog_import — do not edit by hand.
// Re-run the tool to regenerate. Manual customisation goes in overrides.yaml.

#![allow(dead_code, unused_imports, unused_variables, clippy::all)]

use crate::registry::DelayModelDefinition;
use crate::DelayBackendKind;
use anyhow::Result;
use block_core::param::{
    bool_parameter, float_parameter, required_bool, required_f32,
    ModelParameterSchema, ParameterSet, ParameterUnit,
};
use block_core::{AudioChannelLayout, BlockProcessor, ModelAudioMode};

pub const MODEL_ID: &str = "lv2_calf_bad_reverse_delay";
pub const DISPLAY_NAME: &str = "Calf Reverse Delay";
const BRAND: &str = "calf";

const PLUGIN_URI: &str = "http://calf.sourceforge.net/plugins/ReverseDelay";
const PLUGIN_DIR: &str = "calf-bad";

#[cfg(target_os = "macos")]
const PLUGIN_BINARY: &str = "calf.dylib";
#[cfg(target_os = "linux")]
const PLUGIN_BINARY: &str = "calf.so";
#[cfg(target_os = "windows")]
const PLUGIN_BINARY: &str = "calf.dll";

// Port indices (from TTL)
const PORT_AUDIO_IN_IN_L: usize = 0;
const PORT_AUDIO_IN_IN_R: usize = 1;
const PORT_AUDIO_OUT_OUT_L: usize = 2;
const PORT_AUDIO_OUT_OUT_R: usize = 3;
const PORT_CTRL_BPM: usize = 4;
const PORT_CTRL_BPM_HOST: usize = 5;
const PORT_CTRL_SUBDIV: usize = 6;
const PORT_CTRL_TIME_L: usize = 7;
const PORT_CTRL_TIME_R: usize = 8;
const PORT_CTRL_FEEDBACK: usize = 9;
const PORT_CTRL_AMOUNT: usize = 10;
const PORT_CTRL_WIDTH: usize = 11;
const PORT_CTRL_SYNC: usize = 12;
const PORT_CTRL_SYNC_LED_L: usize = 13;
const PORT_CTRL_SYNC_LED_R: usize = 14;
const PORT_CTRL_RESET: usize = 15;
const PORT_CTRL_WINDOW: usize = 16;

pub fn model_schema() -> ModelParameterSchema {
    ModelParameterSchema {
        effect_type: block_core::EFFECT_TYPE_DELAY.into(),
        model: MODEL_ID.into(),
        display_name: DISPLAY_NAME.into(),
        audio_mode: ModelAudioMode::TrueStereo,
        parameters: vec![
            float_parameter("bpm", "Tempo", None, Some(120.0), 30.0, 300.0, 1.0, ParameterUnit::None),
            float_parameter("bpm_host", "Host BPM", None, Some(120.0), 1.0, 300.0, 1.0, ParameterUnit::None),
            float_parameter("subdiv", "Subdivide", None, Some(4.0), 1.0, 16.0, 0.1, ParameterUnit::None),
            float_parameter("time_l", "Time L", None, Some(5.0), 1.0, 16.0, 0.1, ParameterUnit::None),
            float_parameter("time_r", "Time R", None, Some(5.0), 1.0, 16.0, 0.1, ParameterUnit::None),
            float_parameter("feedback", "Feedback", None, Some(0.5), 0.0, 1.0, 0.01, ParameterUnit::None),
            float_parameter("amount", "Dry/Wet", None, Some(0.0), -1.0, 1.0, 0.01, ParameterUnit::None),
            float_parameter("width", "Stereo Width", None, Some(0.0), 0.0, 1.0, 0.01, ParameterUnit::None),
            bool_parameter("sync", "Sync BPM", None, Some(false)),
            bool_parameter("reset", "Reset", None, Some(false)),
            float_parameter("window", "Window", None, Some(0.5), 0.0, 1.0, 0.01, ParameterUnit::None),
        ],
    }
}

fn build(params: &ParameterSet, sample_rate: f32, layout: AudioChannelLayout) -> Result<BlockProcessor> {
    let bpm = required_f32(params, "bpm").map_err(anyhow::Error::msg)?;
    let bpm_host = required_f32(params, "bpm_host").map_err(anyhow::Error::msg)?;
    let subdiv = required_f32(params, "subdiv").map_err(anyhow::Error::msg)?;
    let time_l = required_f32(params, "time_l").map_err(anyhow::Error::msg)?;
    let time_r = required_f32(params, "time_r").map_err(anyhow::Error::msg)?;
    let feedback = required_f32(params, "feedback").map_err(anyhow::Error::msg)?;
    let amount = required_f32(params, "amount").map_err(anyhow::Error::msg)?;
    let width = required_f32(params, "width").map_err(anyhow::Error::msg)?;
    let sync = required_bool(params, "sync").map_err(anyhow::Error::msg)?;
    let reset = required_bool(params, "reset").map_err(anyhow::Error::msg)?;
    let window = required_f32(params, "window").map_err(anyhow::Error::msg)?;
    let lib_path = lv2::resolve_lv2_lib(PLUGIN_BINARY)?;
    let bundle_path = lv2::resolve_lv2_bundle(PLUGIN_DIR)?;

    let control_ports: &[(usize, f32)] = &[
        (PORT_CTRL_BPM, bpm),
        (PORT_CTRL_BPM_HOST, bpm_host),
        (PORT_CTRL_SUBDIV, subdiv),
        (PORT_CTRL_TIME_L, time_l),
        (PORT_CTRL_TIME_R, time_r),
        (PORT_CTRL_FEEDBACK, feedback),
        (PORT_CTRL_AMOUNT, amount),
        (PORT_CTRL_WIDTH, width),
        (PORT_CTRL_SYNC, if sync { 1.0 } else { 0.0 }),
        (PORT_CTRL_RESET, if reset { 1.0 } else { 0.0 }),
        (PORT_CTRL_WINDOW, window),
    ];

    let processor = lv2::build_stereo_lv2_processor(&lib_path, PLUGIN_URI, sample_rate as f64, &bundle_path, &[PORT_AUDIO_IN_IN_L, PORT_AUDIO_IN_IN_R], &[PORT_AUDIO_OUT_OUT_L, PORT_AUDIO_OUT_OUT_R], control_ports)?;
    let _ = layout;
    Ok(BlockProcessor::Stereo(Box::new(processor)))
}

fn schema() -> Result<ModelParameterSchema> { Ok(model_schema()) }

pub const MODEL_DEFINITION: DelayModelDefinition = DelayModelDefinition {
    id: MODEL_ID, display_name: DISPLAY_NAME, brand: BRAND,
    backend_kind: DelayBackendKind::Lv2, schema, build,
    supported_instruments: block_core::ALL_INSTRUMENTS, knob_layout: &[],
};
