// AUTO-GENERATED by tools/lv2_catalog_import — do not edit by hand.
// Re-run the tool to regenerate. Manual customisation goes in overrides.yaml.

#![allow(dead_code, unused_imports, unused_variables, clippy::all)]

use crate::registry::DelayModelDefinition;
use crate::DelayBackendKind;
use anyhow::Result;
use block_core::param::{
    bool_parameter, float_parameter, required_bool, required_f32,
    ModelParameterSchema, ParameterSet, ParameterUnit,
};
use block_core::{AudioChannelLayout, BlockProcessor, ModelAudioMode};

pub const MODEL_ID: &str = "lv2_rkr_bad_arpie";
pub const DISPLAY_NAME: &str = "rkr Arpie";
const BRAND: &str = "rakarrack";

const PLUGIN_URI: &str = "http://rakarrack.sourceforge.net/effects.html#Arpie";
const PLUGIN_DIR: &str = "rkr-bad";

#[cfg(target_os = "macos")]
const PLUGIN_BINARY: &str = "rkrlv2.dylib";
#[cfg(target_os = "linux")]
const PLUGIN_BINARY: &str = "rkrlv2.so";
#[cfg(target_os = "windows")]
const PLUGIN_BINARY: &str = "rkrlv2.dll";

// Port indices (from TTL)
const PORT_AUDIO_IN_INPUT_L: usize = 0;
const PORT_AUDIO_IN_INPUT_R: usize = 1;
const PORT_AUDIO_OUT_OUTPUT_L: usize = 2;
const PORT_AUDIO_OUT_OUTPUT_R: usize = 3;
const PORT_CTRL_BYPASS: usize = 4;
const PORT_CTRL_WETDRY: usize = 5;
const PORT_CTRL_PAN: usize = 6;
const PORT_CTRL_TEMPO: usize = 7;
const PORT_CTRL_LR_DELAY: usize = 8;
const PORT_CTRL_LR_CR: usize = 9;
const PORT_CTRL_FEEDBACK: usize = 10;
const PORT_CTRL_DAMP: usize = 11;
const PORT_CTRL_ARP: usize = 12;
const PORT_CTRL_HARM: usize = 13;
const PORT_CTRL_PATTERN: usize = 14;
const PORT_CTRL_SUBD: usize = 15;

pub fn model_schema() -> ModelParameterSchema {
    ModelParameterSchema {
        effect_type: block_core::EFFECT_TYPE_DELAY.into(),
        model: MODEL_ID.into(),
        display_name: DISPLAY_NAME.into(),
        audio_mode: ModelAudioMode::TrueStereo,
        parameters: vec![
            bool_parameter("bypass", "Bypass", None, Some(false)),
            float_parameter("wetdry", "Wet/Dry", None, Some(67.0), 0.0, 127.0, 1.0, ParameterUnit::None),
            float_parameter("pan", "Panning", None, Some(0.0), -64.0, 63.0, 1.0, ParameterUnit::None),
            float_parameter("tempo", "Tempo", None, Some(565.0), 1.0, 600.0, 1.0, ParameterUnit::None),
            float_parameter("lr_delay", "Left/Right Delay Offset", None, Some(0.0), -64.0, 63.0, 1.0, ParameterUnit::None),
            float_parameter("lrcr", "Left/Right Crossover", None, Some(30.0), 0.0, 127.0, 1.0, ParameterUnit::None),
            float_parameter("feedback", "Feedback", None, Some(59.0), 0.0, 127.0, 1.0, ParameterUnit::None),
            float_parameter("damp", "Damping", None, Some(0.0), 0.0, 127.0, 1.0, ParameterUnit::None),
            float_parameter("arp", "Arpe's Wet/Dry", None, Some(127.0), 0.0, 127.0, 1.0, ParameterUnit::None),
            float_parameter("harm", "Harmonics", None, Some(1.0), 1.0, 8.0, 0.01, ParameterUnit::None),
            float_parameter("pattern", "Pattern", None, Some(0.0), 0.0, 5.0, 0.01, ParameterUnit::None),
            float_parameter("subd", "Subdivision", None, Some(3.0), 0.0, 5.0, 0.01, ParameterUnit::None),
        ],
    }
}

fn build(params: &ParameterSet, sample_rate: f32, layout: AudioChannelLayout) -> Result<BlockProcessor> {
    let bypass = required_bool(params, "bypass").map_err(anyhow::Error::msg)?;
    let wetdry = required_f32(params, "wetdry").map_err(anyhow::Error::msg)?;
    let pan = required_f32(params, "pan").map_err(anyhow::Error::msg)?;
    let tempo = required_f32(params, "tempo").map_err(anyhow::Error::msg)?;
    let lr_delay = required_f32(params, "lr_delay").map_err(anyhow::Error::msg)?;
    let lrcr = required_f32(params, "lrcr").map_err(anyhow::Error::msg)?;
    let feedback = required_f32(params, "feedback").map_err(anyhow::Error::msg)?;
    let damp = required_f32(params, "damp").map_err(anyhow::Error::msg)?;
    let arp = required_f32(params, "arp").map_err(anyhow::Error::msg)?;
    let harm = required_f32(params, "harm").map_err(anyhow::Error::msg)?;
    let pattern = required_f32(params, "pattern").map_err(anyhow::Error::msg)?;
    let subd = required_f32(params, "subd").map_err(anyhow::Error::msg)?;
    let lib_path = lv2::resolve_lv2_lib(PLUGIN_BINARY)?;
    let bundle_path = lv2::resolve_lv2_bundle(PLUGIN_DIR)?;

    let control_ports: &[(usize, f32)] = &[
        (PORT_CTRL_BYPASS, if bypass { 1.0 } else { 0.0 }),
        (PORT_CTRL_WETDRY, wetdry),
        (PORT_CTRL_PAN, pan),
        (PORT_CTRL_TEMPO, tempo),
        (PORT_CTRL_LR_DELAY, lr_delay),
        (PORT_CTRL_LR_CR, lrcr),
        (PORT_CTRL_FEEDBACK, feedback),
        (PORT_CTRL_DAMP, damp),
        (PORT_CTRL_ARP, arp),
        (PORT_CTRL_HARM, harm),
        (PORT_CTRL_PATTERN, pattern),
        (PORT_CTRL_SUBD, subd),
    ];

    let processor = lv2::build_stereo_lv2_processor(&lib_path, PLUGIN_URI, sample_rate as f64, &bundle_path, &[PORT_AUDIO_IN_INPUT_L, PORT_AUDIO_IN_INPUT_R], &[PORT_AUDIO_OUT_OUTPUT_L, PORT_AUDIO_OUT_OUTPUT_R], control_ports)?;
    let _ = layout;
    Ok(BlockProcessor::Stereo(Box::new(processor)))
}

fn schema() -> Result<ModelParameterSchema> { Ok(model_schema()) }

pub const MODEL_DEFINITION: DelayModelDefinition = DelayModelDefinition {
    id: MODEL_ID, display_name: DISPLAY_NAME, brand: BRAND,
    backend_kind: DelayBackendKind::Lv2, schema, build,
    supported_instruments: block_core::ALL_INSTRUMENTS, knob_layout: &[],
};
