// AUTO-GENERATED by tools/lv2_catalog_import — do not edit by hand.
// Re-run the tool to regenerate. Manual customisation goes in overrides.yaml.

#![allow(dead_code, unused_imports, unused_variables, clippy::approx_constant, clippy::excessive_precision)]

use crate::registry::DelayModelDefinition;
use crate::DelayBackendKind;
use anyhow::Result;
use block_core::param::{
    float_parameter, required_f32, ModelParameterSchema, ParameterSet, ParameterUnit,
};
use block_core::{AudioChannelLayout, BlockProcessor, ModelAudioMode, MonoProcessor, StereoProcessor};

pub const MODEL_ID: &str = "lv2_remaincalm_plugins_floaty";
pub const DISPLAY_NAME: &str = "floaty";
const BRAND: &str = "remaincalm";

const PLUGIN_URI: &str = "http://remaincalm.org/plugins/floaty";
const PLUGIN_DIR: &str = "remaincalm-plugins";

#[cfg(target_os = "macos")]
const PLUGIN_BINARY: &str = "floaty_dsp.dylib";
#[cfg(target_os = "linux")]
const PLUGIN_BINARY: &str = "floaty_dsp.so";
#[cfg(target_os = "windows")]
const PLUGIN_BINARY: &str = "floaty_dsp.dll";

// Port indices (from TTL)
const PORT_AUDIO_IN_LV2_AUDIO_IN_1: usize = 0;
const PORT_AUDIO_OUT_LV2_AUDIO_OUT_1: usize = 1;
const PORT_CTRL_DELAY: usize = 2;
const PORT_CTRL_MIX: usize = 3;
const PORT_CTRL_FEEDBACK: usize = 4;
const PORT_CTRL_WARP: usize = 5;
const PORT_CTRL_FILTER: usize = 6;
const PORT_CTRL_RATE: usize = 7;

pub fn model_schema() -> ModelParameterSchema {
    ModelParameterSchema {
        effect_type: block_core::EFFECT_TYPE_DELAY.into(),
        model: MODEL_ID.into(),
        display_name: DISPLAY_NAME.into(),
        audio_mode: ModelAudioMode::DualMono,
        parameters: vec![
            float_parameter("delay", "Time", None, Some(280.0), 10.0, 653.0612, 1.0, ParameterUnit::Milliseconds),
            float_parameter("mix", "Mix", None, Some(42.0), 0.0, 100.0, 1.0, ParameterUnit::Percent),
            float_parameter("feedback", "Feedback", None, Some(20.0), 0.0, 60.0, 0.1, ParameterUnit::Percent),
            float_parameter("warp", "Warp", None, Some(60.0), 0.0, 100.0, 1.0, ParameterUnit::None),
            float_parameter("filter", "Tone", None, Some(19.0), 0.0, 100.0, 1.0, ParameterUnit::None),
            float_parameter("rate", "Playback Rate", None, Some(1.0), -2.0, 2.0, 0.01, ParameterUnit::None),
        ],
    }
}

fn build(params: &ParameterSet, sample_rate: f32, layout: AudioChannelLayout) -> Result<BlockProcessor> {
    let delay = required_f32(params, "delay").map_err(anyhow::Error::msg)?;
    let mix = required_f32(params, "mix").map_err(anyhow::Error::msg)?;
    let feedback = required_f32(params, "feedback").map_err(anyhow::Error::msg)?;
    let warp = required_f32(params, "warp").map_err(anyhow::Error::msg)?;
    let filter = required_f32(params, "filter").map_err(anyhow::Error::msg)?;
    let rate = required_f32(params, "rate").map_err(anyhow::Error::msg)?;
    let lib_path = lv2::resolve_lv2_lib(PLUGIN_BINARY)?;
    let bundle_path = lv2::resolve_lv2_bundle(PLUGIN_DIR)?;

    let control_ports: &[(usize, f32)] = &[
        (PORT_CTRL_DELAY, delay),
        (PORT_CTRL_MIX, mix),
        (PORT_CTRL_FEEDBACK, feedback),
        (PORT_CTRL_WARP, warp),
        (PORT_CTRL_FILTER, filter),
        (PORT_CTRL_RATE, rate),
    ];

    match layout {
        AudioChannelLayout::Mono => {
            let processor = lv2::build_lv2_processor(&lib_path, PLUGIN_URI, sample_rate as f64, &bundle_path, &[PORT_AUDIO_IN_LV2_AUDIO_IN_1], &[PORT_AUDIO_OUT_LV2_AUDIO_OUT_1], control_ports)?;
            Ok(BlockProcessor::Mono(Box::new(processor)))
        }
        AudioChannelLayout::Stereo => {
            let left = lv2::build_lv2_processor(&lib_path, PLUGIN_URI, sample_rate as f64, &bundle_path, &[PORT_AUDIO_IN_LV2_AUDIO_IN_1], &[PORT_AUDIO_OUT_LV2_AUDIO_OUT_1], control_ports)?;
            let right = lv2::build_lv2_processor(&lib_path, PLUGIN_URI, sample_rate as f64, &bundle_path, &[PORT_AUDIO_IN_LV2_AUDIO_IN_1], &[PORT_AUDIO_OUT_LV2_AUDIO_OUT_1], control_ports)?;
            Ok(BlockProcessor::Stereo(Box::new(DualMonoProcessor { left, right })))
        }
    }
}

struct DualMonoProcessor { left: lv2::Lv2Processor, right: lv2::Lv2Processor }
impl StereoProcessor for DualMonoProcessor {
    fn process_frame(&mut self, input: [f32; 2]) -> [f32; 2] {
        [self.left.process_sample(input[0]), self.right.process_sample(input[1])]
    }
}

fn schema() -> Result<ModelParameterSchema> { Ok(model_schema()) }

pub const MODEL_DEFINITION: DelayModelDefinition = DelayModelDefinition {
    id: MODEL_ID, display_name: DISPLAY_NAME, brand: BRAND,
    backend_kind: DelayBackendKind::Lv2, schema, build,
    supported_instruments: block_core::ALL_INSTRUMENTS, knob_layout: &[],
};
