// AUTO-GENERATED by tools/lv2_catalog_import — do not edit by hand.
// Re-run the tool to regenerate. Manual customisation goes in overrides.yaml.

#![allow(dead_code, unused_imports, unused_variables, clippy::approx_constant, clippy::excessive_precision)]

use crate::registry::DelayModelDefinition;
use crate::DelayBackendKind;
use anyhow::Result;
use block_core::param::{
    float_parameter, required_f32, ModelParameterSchema, ParameterSet, ParameterUnit,
};
use block_core::{AudioChannelLayout, BlockProcessor, ModelAudioMode};

pub const MODEL_ID: &str = "lv2_mod_caps_scape";
pub const DISPLAY_NAME: &str = "C* Scape - Stereo delay + Filters";
const BRAND: &str = "caps";

const PLUGIN_URI: &str = "http://moddevices.com/plugins/caps/Scape";
const PLUGIN_DIR: &str = "mod-caps-Scape";

#[cfg(target_os = "macos")]
const PLUGIN_BINARY: &str = "Scape.dylib.dylib";
#[cfg(target_os = "linux")]
const PLUGIN_BINARY: &str = "Scape.dylib.so";
#[cfg(target_os = "windows")]
const PLUGIN_BINARY: &str = "Scape.dylib.dll";

// Port indices (from TTL)
const PORT_CTRL_BPM: usize = 0;
const PORT_CTRL_DIVIDER: usize = 1;
const PORT_CTRL_FEEDBACK: usize = 2;
const PORT_CTRL_DRY: usize = 3;
const PORT_CTRL_BLEND: usize = 4;
const PORT_CTRL_TUNE: usize = 5;
const PORT_AUDIO_IN_IN: usize = 6;
const PORT_AUDIO_OUT_OUTL: usize = 7;
const PORT_AUDIO_OUT_OUTR: usize = 8;

pub fn model_schema() -> ModelParameterSchema {
    ModelParameterSchema {
        effect_type: block_core::EFFECT_TYPE_DELAY.into(),
        model: MODEL_ID.into(),
        display_name: DISPLAY_NAME.into(),
        audio_mode: ModelAudioMode::MonoToStereo,
        parameters: vec![
            float_parameter("bpm", "BPM", None, Some(100.0), 30.0, 164.0, 1.0, ParameterUnit::None),
            float_parameter("divider", "Divider", None, Some(2.0), 2.0, 4.0, 0.01, ParameterUnit::None),
            float_parameter("feedback", "Feedback", None, Some(0.75), 0.0, 1.0, 0.01, ParameterUnit::None),
            float_parameter("dry", "Dry", None, Some(0.5), 0.0, 1.0, 0.01, ParameterUnit::None),
            float_parameter("blend", "Blend", None, Some(1.0), 0.0, 1.0, 0.01, ParameterUnit::None),
            float_parameter("tune", "Tune", None, Some(440.0), 415.0, 467.0, 0.1, ParameterUnit::Hertz),
        ],
    }
}

fn build(params: &ParameterSet, sample_rate: f32, layout: AudioChannelLayout) -> Result<BlockProcessor> {
    let bpm = required_f32(params, "bpm").map_err(anyhow::Error::msg)?;
    let divider = required_f32(params, "divider").map_err(anyhow::Error::msg)?;
    let feedback = required_f32(params, "feedback").map_err(anyhow::Error::msg)?;
    let dry = required_f32(params, "dry").map_err(anyhow::Error::msg)?;
    let blend = required_f32(params, "blend").map_err(anyhow::Error::msg)?;
    let tune = required_f32(params, "tune").map_err(anyhow::Error::msg)?;
    let lib_path = lv2::resolve_lv2_lib(PLUGIN_BINARY)?;
    let bundle_path = lv2::resolve_lv2_bundle(PLUGIN_DIR)?;

    let control_ports: &[(usize, f32)] = &[
        (PORT_CTRL_BPM, bpm),
        (PORT_CTRL_DIVIDER, divider),
        (PORT_CTRL_FEEDBACK, feedback),
        (PORT_CTRL_DRY, dry),
        (PORT_CTRL_BLEND, blend),
        (PORT_CTRL_TUNE, tune),
    ];

    let extra_outs: &[usize] = &[PORT_AUDIO_OUT_OUTR];
    let _ = layout;
    let processor = lv2::build_lv2_processor_with_extras(&lib_path, PLUGIN_URI, sample_rate as f64, &bundle_path, &[PORT_AUDIO_IN_IN], &[PORT_AUDIO_OUT_OUTL], control_ports, extra_outs)?;
    Ok(BlockProcessor::Mono(Box::new(processor)))
}

fn schema() -> Result<ModelParameterSchema> { Ok(model_schema()) }

pub const MODEL_DEFINITION: DelayModelDefinition = DelayModelDefinition {
    id: MODEL_ID, display_name: DISPLAY_NAME, brand: BRAND,
    backend_kind: DelayBackendKind::Lv2, schema, build,
    supported_instruments: block_core::ALL_INSTRUMENTS, knob_layout: &[],
};
