// AUTO-GENERATED by tools/lv2_catalog_import — do not edit by hand.
// Re-run the tool to regenerate. Manual customisation goes in overrides.yaml.

#![allow(dead_code, unused_imports, unused_variables, clippy::approx_constant, clippy::excessive_precision)]

use crate::registry::DelayModelDefinition;
use crate::DelayBackendKind;
use anyhow::Result;
use block_core::param::{
    bool_parameter, float_parameter, required_bool, required_f32,
    ModelParameterSchema, ParameterSet, ParameterUnit,
};
use block_core::{AudioChannelLayout, BlockProcessor, ModelAudioMode};

pub const MODEL_ID: &str = "lv2_rkr_bad_delm";
pub const DISPLAY_NAME: &str = "rkr Musical Delay";
const BRAND: &str = "rakarrack";

const PLUGIN_URI: &str = "http://rakarrack.sourceforge.net/effects.html#delm";
const PLUGIN_DIR: &str = "rkr-bad";

#[cfg(target_os = "macos")]
const PLUGIN_BINARY: &str = "rkrlv2.dylib";
#[cfg(target_os = "linux")]
const PLUGIN_BINARY: &str = "rkrlv2.so";
#[cfg(target_os = "windows")]
const PLUGIN_BINARY: &str = "rkrlv2.dll";

// Port indices (from TTL)
const PORT_AUDIO_IN_INPUT_L: usize = 0;
const PORT_AUDIO_IN_INPUT_R: usize = 1;
const PORT_AUDIO_OUT_OUTPUT_L: usize = 2;
const PORT_AUDIO_OUT_OUTPUT_R: usize = 3;
const PORT_CTRL_BYPASS: usize = 4;
const PORT_CTRL_WETDRY: usize = 5;
const PORT_CTRL_PAN1: usize = 6;
const PORT_CTRL_DEL1: usize = 7;
const PORT_CTRL_OFFS: usize = 8;
const PORT_CTRL_LR_CR: usize = 9;
const PORT_CTRL_FB1: usize = 10;
const PORT_CTRL_DAMP: usize = 11;
const PORT_CTRL_PAN2: usize = 12;
const PORT_CTRL_DEL2: usize = 13;
const PORT_CTRL_FB2: usize = 14;
const PORT_CTRL_TEMPO: usize = 15;
const PORT_CTRL_GAIN1: usize = 16;
const PORT_CTRL_GAIN2: usize = 17;

pub fn model_schema() -> ModelParameterSchema {
    ModelParameterSchema {
        effect_type: block_core::EFFECT_TYPE_DELAY.into(),
        model: MODEL_ID.into(),
        display_name: DISPLAY_NAME.into(),
        audio_mode: ModelAudioMode::TrueStereo,
        parameters: vec![
            bool_parameter("bypass", "Bypass", None, Some(false)),
            float_parameter("wetdry", "Wet/Dry", None, Some(64.0), 0.0, 127.0, 1.0, ParameterUnit::None),
            float_parameter("pan1", "Panning", None, Some(-64.0), -64.0, 63.0, 1.0, ParameterUnit::None),
            float_parameter("del1", "Delay", None, Some(2.0), 1.0, 6.0, 0.01, ParameterUnit::None),
            float_parameter("offs", "Delay Offset", None, Some(7.0), 1.0, 7.0, 0.01, ParameterUnit::None),
            float_parameter("lrcr", "Left/Right Crossover", None, Some(0.0), 0.0, 127.0, 1.0, ParameterUnit::None),
            float_parameter("fb1", "Feedback", None, Some(59.0), 0.0, 127.0, 1.0, ParameterUnit::None),
            float_parameter("damp", "Damping", None, Some(0.0), 0.0, 127.0, 1.0, ParameterUnit::None),
            float_parameter("pan2", "Panning", None, Some(63.0), -64.0, 63.0, 1.0, ParameterUnit::None),
            float_parameter("del2", "Delay", None, Some(4.0), 1.0, 6.0, 0.01, ParameterUnit::None),
            float_parameter("fb2", "Feedback", None, Some(59.0), 0.0, 127.0, 1.0, ParameterUnit::None),
            float_parameter("tempo", "Tempo", None, Some(106.0), 10.0, 480.0, 1.0, ParameterUnit::None),
            float_parameter("gain1", "Gain", None, Some(75.0), 0.0, 127.0, 1.0, ParameterUnit::None),
            float_parameter("gain2", "Gain", None, Some(75.0), 0.0, 127.0, 1.0, ParameterUnit::None),
        ],
    }
}

fn build(params: &ParameterSet, sample_rate: f32, layout: AudioChannelLayout) -> Result<BlockProcessor> {
    let bypass = required_bool(params, "bypass").map_err(anyhow::Error::msg)?;
    let wetdry = required_f32(params, "wetdry").map_err(anyhow::Error::msg)?;
    let pan1 = required_f32(params, "pan1").map_err(anyhow::Error::msg)?;
    let del1 = required_f32(params, "del1").map_err(anyhow::Error::msg)?;
    let offs = required_f32(params, "offs").map_err(anyhow::Error::msg)?;
    let lrcr = required_f32(params, "lrcr").map_err(anyhow::Error::msg)?;
    let fb1 = required_f32(params, "fb1").map_err(anyhow::Error::msg)?;
    let damp = required_f32(params, "damp").map_err(anyhow::Error::msg)?;
    let pan2 = required_f32(params, "pan2").map_err(anyhow::Error::msg)?;
    let del2 = required_f32(params, "del2").map_err(anyhow::Error::msg)?;
    let fb2 = required_f32(params, "fb2").map_err(anyhow::Error::msg)?;
    let tempo = required_f32(params, "tempo").map_err(anyhow::Error::msg)?;
    let gain1 = required_f32(params, "gain1").map_err(anyhow::Error::msg)?;
    let gain2 = required_f32(params, "gain2").map_err(anyhow::Error::msg)?;
    let lib_path = lv2::resolve_lv2_lib(PLUGIN_BINARY)?;
    let bundle_path = lv2::resolve_lv2_bundle(PLUGIN_DIR)?;

    let control_ports: &[(usize, f32)] = &[
        (PORT_CTRL_BYPASS, if bypass { 1.0 } else { 0.0 }),
        (PORT_CTRL_WETDRY, wetdry),
        (PORT_CTRL_PAN1, pan1),
        (PORT_CTRL_DEL1, del1),
        (PORT_CTRL_OFFS, offs),
        (PORT_CTRL_LR_CR, lrcr),
        (PORT_CTRL_FB1, fb1),
        (PORT_CTRL_DAMP, damp),
        (PORT_CTRL_PAN2, pan2),
        (PORT_CTRL_DEL2, del2),
        (PORT_CTRL_FB2, fb2),
        (PORT_CTRL_TEMPO, tempo),
        (PORT_CTRL_GAIN1, gain1),
        (PORT_CTRL_GAIN2, gain2),
    ];

    let processor = lv2::build_stereo_lv2_processor(&lib_path, PLUGIN_URI, sample_rate as f64, &bundle_path, &[PORT_AUDIO_IN_INPUT_L, PORT_AUDIO_IN_INPUT_R], &[PORT_AUDIO_OUT_OUTPUT_L, PORT_AUDIO_OUT_OUTPUT_R], control_ports)?;
    let _ = layout;
    Ok(BlockProcessor::Stereo(Box::new(processor)))
}

fn schema() -> Result<ModelParameterSchema> { Ok(model_schema()) }

pub const MODEL_DEFINITION: DelayModelDefinition = DelayModelDefinition {
    id: MODEL_ID, display_name: DISPLAY_NAME, brand: BRAND,
    backend_kind: DelayBackendKind::Lv2, schema, build,
    supported_instruments: block_core::ALL_INSTRUMENTS, knob_layout: &[],
};
