// AUTO-GENERATED by tools/lv2_catalog_import — do not edit by hand.
// Re-run the tool to regenerate. Manual customisation goes in overrides.yaml.

#![allow(dead_code, unused_imports, unused_variables, clippy::all)]

use crate::registry::DelayModelDefinition;
use crate::DelayBackendKind;
use anyhow::Result;
use block_core::param::{
    float_parameter, required_f32, ModelParameterSchema, ParameterSet, ParameterUnit,
};
use block_core::{AudioChannelLayout, BlockProcessor, ModelAudioMode};

pub const MODEL_ID: &str = "lv2_granulator";
pub const DISPLAY_NAME: &str = "Granulator";
const BRAND: &str = "mayank";

const PLUGIN_URI: &str = "http://faust-lv2.googlecode.com/Granulator";
const PLUGIN_DIR: &str = "Granulator";
pub const THUMBNAIL_PATH: Option<&str> = Some(".plugins/lv2/Granulator.lv2/modgui/thumbnail-granulator.png");

#[cfg(target_os = "macos")]
const PLUGIN_BINARY: &str = "Granulator.dylib";
#[cfg(target_os = "linux")]
const PLUGIN_BINARY: &str = "Granulator.so";
#[cfg(target_os = "windows")]
const PLUGIN_BINARY: &str = "Granulator.dll";

// Port indices (from TTL)
const PORT_CTRL_DELAY_LENGTH: usize = 0;
const PORT_CTRL_GRAIN_DENSITY: usize = 1;
const PORT_CTRL_GRAIN_LENGTH: usize = 2;
const PORT_CTRL_MIX: usize = 3;
const PORT_AUDIO_IN_IN0: usize = 4;
const PORT_AUDIO_IN_IN1: usize = 5;
const PORT_AUDIO_OUT_OUT0: usize = 6;
const PORT_AUDIO_OUT_OUT1: usize = 7;

pub fn model_schema() -> ModelParameterSchema {
    ModelParameterSchema {
        effect_type: block_core::EFFECT_TYPE_DELAY.into(),
        model: MODEL_ID.into(),
        display_name: DISPLAY_NAME.into(),
        audio_mode: ModelAudioMode::TrueStereo,
        parameters: vec![
            float_parameter("delay_length", "delay length", None, Some(10.0), 0.5, 10.0, 0.01, ParameterUnit::None),
            float_parameter("grain_density", "grain density", None, Some(2.0), 2.0, 16.0, 0.1, ParameterUnit::None),
            float_parameter("grain_length", "grain length", None, Some(0.1), 0.01, 0.5, 0.001, ParameterUnit::None),
            float_parameter("mix", "mix", None, Some(0.5), 0.0, 1.0, 0.01, ParameterUnit::None),
        ],
    }
}

fn build(params: &ParameterSet, sample_rate: f32, layout: AudioChannelLayout) -> Result<BlockProcessor> {
    let delay_length = required_f32(params, "delay_length").map_err(anyhow::Error::msg)?;
    let grain_density = required_f32(params, "grain_density").map_err(anyhow::Error::msg)?;
    let grain_length = required_f32(params, "grain_length").map_err(anyhow::Error::msg)?;
    let mix = required_f32(params, "mix").map_err(anyhow::Error::msg)?;
    let lib_path = lv2::resolve_lv2_lib(PLUGIN_BINARY)?;
    let bundle_path = lv2::resolve_lv2_bundle(PLUGIN_DIR)?;

    let control_ports: &[(usize, f32)] = &[
        (PORT_CTRL_DELAY_LENGTH, delay_length),
        (PORT_CTRL_GRAIN_DENSITY, grain_density),
        (PORT_CTRL_GRAIN_LENGTH, grain_length),
        (PORT_CTRL_MIX, mix),
    ];

    let processor = lv2::build_stereo_lv2_processor(&lib_path, PLUGIN_URI, sample_rate as f64, &bundle_path, &[PORT_AUDIO_IN_IN0, PORT_AUDIO_IN_IN1], &[PORT_AUDIO_OUT_OUT0, PORT_AUDIO_OUT_OUT1], control_ports)?;
    let _ = layout;
    Ok(BlockProcessor::Stereo(Box::new(processor)))
}

fn schema() -> Result<ModelParameterSchema> { Ok(model_schema()) }

pub const MODEL_DEFINITION: DelayModelDefinition = DelayModelDefinition {
    id: MODEL_ID, display_name: DISPLAY_NAME, brand: BRAND,
    backend_kind: DelayBackendKind::Lv2, schema, build,
    supported_instruments: block_core::ALL_INSTRUMENTS, knob_layout: &[],
};
