// AUTO-GENERATED by tools/lv2_catalog_import — do not edit by hand.
// Re-run the tool to regenerate. Manual customisation goes in overrides.yaml.

#![allow(dead_code, unused_imports, unused_variables, clippy::approx_constant, clippy::excessive_precision)]

use crate::registry::DelayModelDefinition;
use crate::DelayBackendKind;
use anyhow::Result;
use block_core::param::{
    bool_parameter, float_parameter, required_bool, required_f32,
    ModelParameterSchema, ParameterSet, ParameterUnit,
};
use block_core::{AudioChannelLayout, BlockProcessor, ModelAudioMode, MonoProcessor, StereoProcessor};

pub const MODEL_ID: &str = "lv2_artyfx_bad_della";
pub const DISPLAY_NAME: &str = "Della";
const BRAND: &str = "openav";

const PLUGIN_URI: &str = "http://www.openavproductions.com/artyfx#della";
const PLUGIN_DIR: &str = "artyfx-bad";

#[cfg(target_os = "macos")]
const PLUGIN_BINARY: &str = "artyfx.dylib";
#[cfg(target_os = "linux")]
const PLUGIN_BINARY: &str = "artyfx.so";
#[cfg(target_os = "windows")]
const PLUGIN_BINARY: &str = "artyfx.dll";

// Port indices (from TTL)
const PORT_AUDIO_IN_INPUT: usize = 0;
const PORT_AUDIO_OUT_OUTPUT: usize = 1;
const PORT_CTRL_TIME: usize = 2;
const PORT_CTRL_VOLUME: usize = 3;
const PORT_CTRL_FEEDBACK: usize = 4;
const PORT_CTRL_ACTIVE: usize = 5;
const PORT_ATOM_IN_CONTROL: usize = 6;

pub fn model_schema() -> ModelParameterSchema {
    ModelParameterSchema {
        effect_type: block_core::EFFECT_TYPE_DELAY.into(),
        model: MODEL_ID.into(),
        display_name: DISPLAY_NAME.into(),
        audio_mode: ModelAudioMode::DualMono,
        parameters: vec![
            float_parameter("time", "Time", None, Some(0.5), 0.0, 1.0, 0.01, ParameterUnit::None),
            float_parameter("volume", "Volume", None, Some(0.5), 0.0, 1.0, 0.01, ParameterUnit::None),
            float_parameter("feedback", "Feedback", None, Some(0.25), 0.0, 1.0, 0.01, ParameterUnit::None),
            bool_parameter("active", "Active", None, Some(true)),
        ],
    }
}

fn build(params: &ParameterSet, sample_rate: f32, layout: AudioChannelLayout) -> Result<BlockProcessor> {
    let time = required_f32(params, "time").map_err(anyhow::Error::msg)?;
    let volume = required_f32(params, "volume").map_err(anyhow::Error::msg)?;
    let feedback = required_f32(params, "feedback").map_err(anyhow::Error::msg)?;
    let active = required_bool(params, "active").map_err(anyhow::Error::msg)?;
    let lib_path = lv2::resolve_lv2_lib(PLUGIN_BINARY)?;
    let bundle_path = lv2::resolve_lv2_bundle(PLUGIN_DIR)?;

    let control_ports: &[(usize, f32)] = &[
        (PORT_CTRL_TIME, time),
        (PORT_CTRL_VOLUME, volume),
        (PORT_CTRL_FEEDBACK, feedback),
        (PORT_CTRL_ACTIVE, if active { 1.0 } else { 0.0 }),
    ];

    match layout {
        AudioChannelLayout::Mono => {
            let processor = lv2::build_lv2_processor(&lib_path, PLUGIN_URI, sample_rate as f64, &bundle_path, &[PORT_AUDIO_IN_INPUT], &[PORT_AUDIO_OUT_OUTPUT], control_ports)?;
            Ok(BlockProcessor::Mono(Box::new(processor)))
        }
        AudioChannelLayout::Stereo => {
            let left = lv2::build_lv2_processor(&lib_path, PLUGIN_URI, sample_rate as f64, &bundle_path, &[PORT_AUDIO_IN_INPUT], &[PORT_AUDIO_OUT_OUTPUT], control_ports)?;
            let right = lv2::build_lv2_processor(&lib_path, PLUGIN_URI, sample_rate as f64, &bundle_path, &[PORT_AUDIO_IN_INPUT], &[PORT_AUDIO_OUT_OUTPUT], control_ports)?;
            Ok(BlockProcessor::Stereo(Box::new(DualMonoProcessor { left, right })))
        }
    }
}

struct DualMonoProcessor { left: lv2::Lv2Processor, right: lv2::Lv2Processor }
impl StereoProcessor for DualMonoProcessor {
    fn process_frame(&mut self, input: [f32; 2]) -> [f32; 2] {
        [self.left.process_sample(input[0]), self.right.process_sample(input[1])]
    }
}

fn schema() -> Result<ModelParameterSchema> { Ok(model_schema()) }

pub const MODEL_DEFINITION: DelayModelDefinition = DelayModelDefinition {
    id: MODEL_ID, display_name: DISPLAY_NAME, brand: BRAND,
    backend_kind: DelayBackendKind::Lv2, schema, build,
    supported_instruments: block_core::ALL_INSTRUMENTS, knob_layout: &[],
};
