// AUTO-GENERATED by tools/lv2_catalog_import — do not edit by hand.
// Re-run the tool to regenerate. Manual customisation goes in overrides.yaml.

#![allow(dead_code, unused_imports, unused_variables, clippy::all)]

use crate::registry::DelayModelDefinition;
use crate::DelayBackendKind;
use anyhow::Result;
use block_core::param::{
    bool_parameter, float_parameter, required_bool, required_f32,
    ModelParameterSchema, ParameterSet, ParameterUnit,
};
use block_core::{AudioChannelLayout, BlockProcessor, ModelAudioMode, MonoProcessor, StereoProcessor};

pub const MODEL_ID: &str = "lv2_stuck_stuckstacker";
pub const DISPLAY_NAME: &str = "the infamous stuck stacker";
const BRAND: &str = "infamous";

const PLUGIN_URI: &str = "http://ssj71.github.io/infamousPlugins/plugs.html#stuckstacker";
const PLUGIN_DIR: &str = "stuck";
pub const THUMBNAIL_PATH: Option<&str> = Some(".plugins/lv2/stuck.lv2/modgui/thumbnail-stuck.png");

#[cfg(target_os = "macos")]
const PLUGIN_BINARY: &str = "stuck.dylib";
#[cfg(target_os = "linux")]
const PLUGIN_BINARY: &str = "stuck.so";
#[cfg(target_os = "windows")]
const PLUGIN_BINARY: &str = "stuck.dll";

// Port indices (from TTL)
const PORT_AUDIO_IN_INPUT: usize = 0;
const PORT_AUDIO_OUT_OUTPUT: usize = 1;
const PORT_CTRL_STICK_IT: usize = 2;
const PORT_CTRL_DRONE_GAIN: usize = 3;
const PORT_CTRL_RELEASE: usize = 4;

pub fn model_schema() -> ModelParameterSchema {
    ModelParameterSchema {
        effect_type: block_core::EFFECT_TYPE_DELAY.into(),
        model: MODEL_ID.into(),
        display_name: DISPLAY_NAME.into(),
        audio_mode: ModelAudioMode::DualMono,
        parameters: vec![
            bool_parameter("stick_it", "Stick it!", None, Some(false)),
            float_parameter("drone_gain", "Drone Gain", None, Some(0.5), 0.0, 2.0, 0.01, ParameterUnit::None),
            float_parameter("release", "Release", None, Some(0.5), 0.01, 3.0, 0.01, ParameterUnit::Milliseconds),
        ],
    }
}

fn build(params: &ParameterSet, sample_rate: f32, layout: AudioChannelLayout) -> Result<BlockProcessor> {
    let stick_it = required_bool(params, "stick_it").map_err(anyhow::Error::msg)?;
    let drone_gain = required_f32(params, "drone_gain").map_err(anyhow::Error::msg)?;
    let release = required_f32(params, "release").map_err(anyhow::Error::msg)?;
    let lib_path = lv2::resolve_lv2_lib(PLUGIN_BINARY)?;
    let bundle_path = lv2::resolve_lv2_bundle(PLUGIN_DIR)?;

    let control_ports: &[(usize, f32)] = &[
        (PORT_CTRL_STICK_IT, if stick_it { 1.0 } else { 0.0 }),
        (PORT_CTRL_DRONE_GAIN, drone_gain),
        (PORT_CTRL_RELEASE, release),
    ];

    match layout {
        AudioChannelLayout::Mono => {
            let processor = lv2::build_lv2_processor(&lib_path, PLUGIN_URI, sample_rate as f64, &bundle_path, &[PORT_AUDIO_IN_INPUT], &[PORT_AUDIO_OUT_OUTPUT], control_ports)?;
            Ok(BlockProcessor::Mono(Box::new(processor)))
        }
        AudioChannelLayout::Stereo => {
            let left = lv2::build_lv2_processor(&lib_path, PLUGIN_URI, sample_rate as f64, &bundle_path, &[PORT_AUDIO_IN_INPUT], &[PORT_AUDIO_OUT_OUTPUT], control_ports)?;
            let right = lv2::build_lv2_processor(&lib_path, PLUGIN_URI, sample_rate as f64, &bundle_path, &[PORT_AUDIO_IN_INPUT], &[PORT_AUDIO_OUT_OUTPUT], control_ports)?;
            Ok(BlockProcessor::Stereo(Box::new(DualMonoProcessor { left, right })))
        }
    }
}

struct DualMonoProcessor { left: lv2::Lv2Processor, right: lv2::Lv2Processor }
impl StereoProcessor for DualMonoProcessor {
    fn process_frame(&mut self, input: [f32; 2]) -> [f32; 2] {
        [self.left.process_sample(input[0]), self.right.process_sample(input[1])]
    }
}

fn schema() -> Result<ModelParameterSchema> { Ok(model_schema()) }

pub const MODEL_DEFINITION: DelayModelDefinition = DelayModelDefinition {
    id: MODEL_ID, display_name: DISPLAY_NAME, brand: BRAND,
    backend_kind: DelayBackendKind::Lv2, schema, build,
    supported_instruments: block_core::ALL_INSTRUMENTS, knob_layout: &[],
};
