// AUTO-GENERATED by tools/lv2_catalog_import — do not edit by hand.
// Re-run the tool to regenerate. Manual customisation goes in overrides.yaml.

#![allow(dead_code, unused_imports, unused_variables, clippy::approx_constant, clippy::excessive_precision)]

use crate::registry::DelayModelDefinition;
use crate::DelayBackendKind;
use anyhow::Result;
use block_core::param::{
    float_parameter, required_f32, ModelParameterSchema, ParameterSet, ParameterUnit,
};
use block_core::{AudioChannelLayout, BlockProcessor, ModelAudioMode};

pub const MODEL_ID: &str = "lv2_mod_mda_dub_delay";
pub const DISPLAY_NAME: &str = "MDA DubDelay";
const BRAND: &str = "mda";

const PLUGIN_URI: &str = "http://moddevices.com/plugins/mda/DubDelay";
const PLUGIN_DIR: &str = "mod-mda-DubDelay";

#[cfg(target_os = "macos")]
const PLUGIN_BINARY: &str = "DubDelay.dylib";
#[cfg(target_os = "linux")]
const PLUGIN_BINARY: &str = "DubDelay.so";
#[cfg(target_os = "windows")]
const PLUGIN_BINARY: &str = "DubDelay.dll";

// Port indices (from TTL)
const PORT_CTRL_DELAY: usize = 0;
const PORT_CTRL_FEEDBACK: usize = 1;
const PORT_CTRL_FB_TONE: usize = 2;
const PORT_CTRL_LFO_DEPTH: usize = 3;
const PORT_CTRL_LFO_RATE: usize = 4;
const PORT_CTRL_FX_MIX: usize = 5;
const PORT_CTRL_OUTPUT: usize = 6;
const PORT_AUDIO_IN_LEFT_IN: usize = 7;
const PORT_AUDIO_IN_RIGHT_IN: usize = 8;
const PORT_AUDIO_OUT_LEFT_OUT: usize = 9;
const PORT_AUDIO_OUT_RIGHT_OUT: usize = 10;

pub fn model_schema() -> ModelParameterSchema {
    ModelParameterSchema {
        effect_type: block_core::EFFECT_TYPE_DELAY.into(),
        model: MODEL_ID.into(),
        display_name: DISPLAY_NAME.into(),
        audio_mode: ModelAudioMode::TrueStereo,
        parameters: vec![
            float_parameter("delay", "Delay", None, Some(460.0), 1.0, 7500.0, 10.0, ParameterUnit::Milliseconds),
            float_parameter("feedback", "Feedback", None, Some(55.0), -110.0, 110.0, 1.0, ParameterUnit::Percent),
            float_parameter("fb_tone", "Fb Tone", None, Some(0.0), -100.0, 100.0, 1.0, ParameterUnit::Percent),
            float_parameter("lfo_depth", "LFO Depth", None, Some(30.0), 0.0, 100.0, 1.0, ParameterUnit::Percent),
            float_parameter("lfo_rate", "LFO Rate", None, Some(0.05), 0.01, 10.0, 0.01, ParameterUnit::Hertz),
            float_parameter("fx_mix", "FX Mix", None, Some(50.0), 0.0, 100.0, 1.0, ParameterUnit::Percent),
            float_parameter("output", "Level", None, Some(0.0), -12.0, 6.0, 0.1, ParameterUnit::Decibels),
        ],
    }
}

fn build(params: &ParameterSet, sample_rate: f32, layout: AudioChannelLayout) -> Result<BlockProcessor> {
    let delay = required_f32(params, "delay").map_err(anyhow::Error::msg)?;
    let feedback = required_f32(params, "feedback").map_err(anyhow::Error::msg)?;
    let fb_tone = required_f32(params, "fb_tone").map_err(anyhow::Error::msg)?;
    let lfo_depth = required_f32(params, "lfo_depth").map_err(anyhow::Error::msg)?;
    let lfo_rate = required_f32(params, "lfo_rate").map_err(anyhow::Error::msg)?;
    let fx_mix = required_f32(params, "fx_mix").map_err(anyhow::Error::msg)?;
    let output = required_f32(params, "output").map_err(anyhow::Error::msg)?;
    let lib_path = lv2::resolve_lv2_lib(PLUGIN_BINARY)?;
    let bundle_path = lv2::resolve_lv2_bundle(PLUGIN_DIR)?;

    let control_ports: &[(usize, f32)] = &[
        (PORT_CTRL_DELAY, delay),
        (PORT_CTRL_FEEDBACK, feedback),
        (PORT_CTRL_FB_TONE, fb_tone),
        (PORT_CTRL_LFO_DEPTH, lfo_depth),
        (PORT_CTRL_LFO_RATE, lfo_rate),
        (PORT_CTRL_FX_MIX, fx_mix),
        (PORT_CTRL_OUTPUT, output),
    ];

    let processor = lv2::build_stereo_lv2_processor(&lib_path, PLUGIN_URI, sample_rate as f64, &bundle_path, &[PORT_AUDIO_IN_LEFT_IN, PORT_AUDIO_IN_RIGHT_IN], &[PORT_AUDIO_OUT_LEFT_OUT, PORT_AUDIO_OUT_RIGHT_OUT], control_ports)?;
    let _ = layout;
    Ok(BlockProcessor::Stereo(Box::new(processor)))
}

fn schema() -> Result<ModelParameterSchema> { Ok(model_schema()) }

pub const MODEL_DEFINITION: DelayModelDefinition = DelayModelDefinition {
    id: MODEL_ID, display_name: DISPLAY_NAME, brand: BRAND,
    backend_kind: DelayBackendKind::Lv2, schema, build,
    supported_instruments: block_core::ALL_INSTRUMENTS, knob_layout: &[],
};
