// AUTO-GENERATED by tools/lv2_catalog_import — do not edit by hand.
// Re-run the tool to regenerate. Manual customisation goes in overrides.yaml.

#![allow(dead_code, unused_imports, unused_variables, clippy::all)]

use crate::registry::DynModelDefinition;
use crate::DynBackendKind;
use anyhow::Result;
use block_core::param::{
    bool_parameter, float_parameter, required_bool, required_f32,
    ModelParameterSchema, ParameterSet, ParameterUnit,
};
use block_core::{AudioChannelLayout, BlockProcessor, ModelAudioMode};

pub const MODEL_ID: &str = "lv2_calf_bad_deesser";
pub const DISPLAY_NAME: &str = "Calf Deesser";
const BRAND: &str = "calf";

const PLUGIN_URI: &str = "http://calf.sourceforge.net/plugins/Deesser";
const PLUGIN_DIR: &str = "calf-bad";

#[cfg(target_os = "macos")]
const PLUGIN_BINARY: &str = "calf.dylib";
#[cfg(target_os = "linux")]
const PLUGIN_BINARY: &str = "calf.so";
#[cfg(target_os = "windows")]
const PLUGIN_BINARY: &str = "calf.dll";

// Port indices (from TTL)
const PORT_AUDIO_IN_IN_L: usize = 0;
const PORT_AUDIO_IN_IN_R: usize = 1;
const PORT_AUDIO_OUT_OUT_L: usize = 2;
const PORT_AUDIO_OUT_OUT_R: usize = 3;
const PORT_CTRL_BYPASS: usize = 4;
const PORT_CTRL_DETECTED: usize = 5;
const PORT_CTRL_COMPRESSION: usize = 6;
const PORT_CTRL_DETECTED_LED: usize = 7;
const PORT_CTRL_CLIP_OUT: usize = 8;
const PORT_CTRL_DETECTION: usize = 9;
const PORT_CTRL_MODE: usize = 10;
const PORT_CTRL_THRESHOLD: usize = 11;
const PORT_CTRL_RATIO: usize = 12;
const PORT_CTRL_LAXITY: usize = 13;
const PORT_CTRL_MAKEUP: usize = 14;
const PORT_CTRL_F1_FREQ: usize = 15;
const PORT_CTRL_F2_FREQ: usize = 16;
const PORT_CTRL_F1_LEVEL: usize = 17;
const PORT_CTRL_F2_LEVEL: usize = 18;
const PORT_CTRL_F2_Q: usize = 19;
const PORT_CTRL_SC_LISTEN: usize = 20;

pub fn model_schema() -> ModelParameterSchema {
    ModelParameterSchema {
        effect_type: block_core::EFFECT_TYPE_DYNAMICS.into(),
        model: MODEL_ID.into(),
        display_name: DISPLAY_NAME.into(),
        audio_mode: ModelAudioMode::TrueStereo,
        parameters: vec![
            bool_parameter("bypass", "Bypass", None, Some(false)),
            float_parameter("detection", "Detection", None, Some(0.0), 0.0, 1.0, 0.01, ParameterUnit::None),
            float_parameter("mode", "Mode", None, Some(0.0), 0.0, 1.0, 0.01, ParameterUnit::None),
            float_parameter("threshold", "Threshold", None, Some(0.125), 0.000976563, 1.0, 0.001, ParameterUnit::None),
            float_parameter("ratio", "Ratio", None, Some(3.0), 1.0, 20.0, 0.1, ParameterUnit::None),
            float_parameter("laxity", "Laxity", None, Some(15.0), 1.0, 100.0, 0.1, ParameterUnit::None),
            float_parameter("makeup", "Makeup", None, Some(1.0), 1.0, 64.0, 0.1, ParameterUnit::None),
            float_parameter("f1_freq", "Split", None, Some(6000.0), 10.0, 18000.0, 10.0, ParameterUnit::Hertz),
            float_parameter("f2_freq", "Peak", None, Some(4500.0), 10.0, 18000.0, 10.0, ParameterUnit::Hertz),
            float_parameter("f1_level", "Gain", None, Some(1.0), 0.0625, 16.0, 0.1, ParameterUnit::None),
            float_parameter("f2_level", "Level", None, Some(4.0), 0.0625, 16.0, 0.1, ParameterUnit::None),
            float_parameter("f2_q", "Peak Q", None, Some(1.0), 0.1, 100.0, 0.1, ParameterUnit::None),
            bool_parameter("sc_listen", "S/C-Listen", None, Some(false)),
        ],
    }
}

fn build(params: &ParameterSet, sample_rate: f32, layout: AudioChannelLayout) -> Result<BlockProcessor> {
    let bypass = required_bool(params, "bypass").map_err(anyhow::Error::msg)?;
    let detection = required_f32(params, "detection").map_err(anyhow::Error::msg)?;
    let mode = required_f32(params, "mode").map_err(anyhow::Error::msg)?;
    let threshold = required_f32(params, "threshold").map_err(anyhow::Error::msg)?;
    let ratio = required_f32(params, "ratio").map_err(anyhow::Error::msg)?;
    let laxity = required_f32(params, "laxity").map_err(anyhow::Error::msg)?;
    let makeup = required_f32(params, "makeup").map_err(anyhow::Error::msg)?;
    let f1_freq = required_f32(params, "f1_freq").map_err(anyhow::Error::msg)?;
    let f2_freq = required_f32(params, "f2_freq").map_err(anyhow::Error::msg)?;
    let f1_level = required_f32(params, "f1_level").map_err(anyhow::Error::msg)?;
    let f2_level = required_f32(params, "f2_level").map_err(anyhow::Error::msg)?;
    let f2_q = required_f32(params, "f2_q").map_err(anyhow::Error::msg)?;
    let sc_listen = required_bool(params, "sc_listen").map_err(anyhow::Error::msg)?;
    let lib_path = lv2::resolve_lv2_lib(PLUGIN_BINARY)?;
    let bundle_path = lv2::resolve_lv2_bundle(PLUGIN_DIR)?;

    let control_ports: &[(usize, f32)] = &[
        (PORT_CTRL_BYPASS, if bypass { 1.0 } else { 0.0 }),
        (PORT_CTRL_DETECTION, detection),
        (PORT_CTRL_MODE, mode),
        (PORT_CTRL_THRESHOLD, threshold),
        (PORT_CTRL_RATIO, ratio),
        (PORT_CTRL_LAXITY, laxity),
        (PORT_CTRL_MAKEUP, makeup),
        (PORT_CTRL_F1_FREQ, f1_freq),
        (PORT_CTRL_F2_FREQ, f2_freq),
        (PORT_CTRL_F1_LEVEL, f1_level),
        (PORT_CTRL_F2_LEVEL, f2_level),
        (PORT_CTRL_F2_Q, f2_q),
        (PORT_CTRL_SC_LISTEN, if sc_listen { 1.0 } else { 0.0 }),
    ];

    let processor = lv2::build_stereo_lv2_processor(&lib_path, PLUGIN_URI, sample_rate as f64, &bundle_path, &[PORT_AUDIO_IN_IN_L, PORT_AUDIO_IN_IN_R], &[PORT_AUDIO_OUT_OUT_L, PORT_AUDIO_OUT_OUT_R], control_ports)?;
    let _ = layout;
    Ok(BlockProcessor::Stereo(Box::new(processor)))
}

fn schema() -> Result<ModelParameterSchema> { Ok(model_schema()) }

pub const MODEL_DEFINITION: DynModelDefinition = DynModelDefinition {
    id: MODEL_ID, display_name: DISPLAY_NAME, brand: BRAND,
    backend_kind: DynBackendKind::Lv2, schema, build,
    supported_instruments: block_core::ALL_INSTRUMENTS, knob_layout: &[],
};
