// AUTO-GENERATED by tools/lv2_catalog_import — do not edit by hand.
// Re-run the tool to regenerate. Manual customisation goes in overrides.yaml.

#![allow(dead_code, unused_imports, unused_variables, clippy::all)]

use crate::registry::DynModelDefinition;
use crate::DynBackendKind;
use anyhow::Result;
use block_core::param::{
    bool_parameter, float_parameter, required_bool, required_f32,
    ModelParameterSchema, ParameterSet, ParameterUnit,
};
use block_core::{AudioChannelLayout, BlockProcessor, ModelAudioMode};

pub const MODEL_ID: &str = "lv2_rkr_comp_band";
pub const DISPLAY_NAME: &str = "rkr CompBand";
const BRAND: &str = "rakarrack";

const PLUGIN_URI: &str = "http://rakarrack.sourceforge.net/effects.html#CompBand";
const PLUGIN_DIR: &str = "rkr";

#[cfg(target_os = "macos")]
const PLUGIN_BINARY: &str = "plugin.dylib";
#[cfg(target_os = "linux")]
const PLUGIN_BINARY: &str = "plugin.so";
#[cfg(target_os = "windows")]
const PLUGIN_BINARY: &str = "plugin.dll";

// Port indices (from TTL)
const PORT_AUDIO_IN_INPUT_L: usize = 0;
const PORT_AUDIO_IN_INPUT_R: usize = 1;
const PORT_AUDIO_OUT_OUTPUT_L: usize = 2;
const PORT_AUDIO_OUT_OUTPUT_R: usize = 3;
const PORT_CTRL_BYPASS: usize = 4;
const PORT_CTRL_WETDRY: usize = 5;
const PORT_CTRL_LR: usize = 6;
const PORT_CTRL_M1R: usize = 7;
const PORT_CTRL_M2R: usize = 8;
const PORT_CTRL_HR: usize = 9;
const PORT_CTRL_LT: usize = 10;
const PORT_CTRL_M1T: usize = 11;
const PORT_CTRL_M2T: usize = 12;
const PORT_CTRL_HT: usize = 13;
const PORT_CTRL_LMCR: usize = 14;
const PORT_CTRL_MMCR: usize = 15;
const PORT_CTRL_MHCR: usize = 16;
const PORT_CTRL_GAIN: usize = 17;

pub fn model_schema() -> ModelParameterSchema {
    ModelParameterSchema {
        effect_type: block_core::EFFECT_TYPE_DYNAMICS.into(),
        model: MODEL_ID.into(),
        display_name: DISPLAY_NAME.into(),
        audio_mode: ModelAudioMode::TrueStereo,
        parameters: vec![
            bool_parameter("bypass", "Bypass", None, Some(false)),
            float_parameter("wetdry", "Wet/Dry", None, Some(0.0), 0.0, 127.0, 1.0, ParameterUnit::None),
            float_parameter("lr", "Low Band Ratio", None, Some(4.0), 2.0, 42.0, 0.1, ParameterUnit::None),
            float_parameter("m1r", "Mid Band 1 Ratio", None, Some(4.0), 2.0, 42.0, 0.1, ParameterUnit::None),
            float_parameter("m2r", "Mid Band 2 Ratio", None, Some(4.0), 2.0, 42.0, 0.1, ParameterUnit::None),
            float_parameter("hr", "High Band Ratio", None, Some(4.0), 2.0, 42.0, 0.1, ParameterUnit::None),
            float_parameter("lt", "Low Band Threshold", None, Some(0.0), -70.0, 24.0, 0.1, ParameterUnit::Decibels),
            float_parameter("m1t", "Mid Band 1 Threshold", None, Some(0.0), -70.0, 24.0, 0.1, ParameterUnit::Decibels),
            float_parameter("m2t", "Mid Band 2 Threshold", None, Some(0.0), -70.0, 24.0, 0.1, ParameterUnit::Decibels),
            float_parameter("ht", "High Threshold", None, Some(0.0), -70.0, 24.0, 0.1, ParameterUnit::Decibels),
            float_parameter("lmcr", "Low/Mid1 Crossover", None, Some(200.0), 20.0, 1000.0, 1.0, ParameterUnit::Hertz),
            float_parameter("mmcr", "Mid1/Mid2 Crossover", None, Some(2000.0), 1000.0, 8000.0, 10.0, ParameterUnit::Hertz),
            float_parameter("mhcr", "Mid2/High Crossover", None, Some(15000.0), 2000.0, 26000.0, 10.0, ParameterUnit::Hertz),
            float_parameter("gain", "Gain", None, Some(88.0), 0.0, 127.0, 1.0, ParameterUnit::None),
        ],
    }
}

fn build(params: &ParameterSet, sample_rate: f32, layout: AudioChannelLayout) -> Result<BlockProcessor> {
    let bypass = required_bool(params, "bypass").map_err(anyhow::Error::msg)?;
    let wetdry = required_f32(params, "wetdry").map_err(anyhow::Error::msg)?;
    let lr = required_f32(params, "lr").map_err(anyhow::Error::msg)?;
    let m1r = required_f32(params, "m1r").map_err(anyhow::Error::msg)?;
    let m2r = required_f32(params, "m2r").map_err(anyhow::Error::msg)?;
    let hr = required_f32(params, "hr").map_err(anyhow::Error::msg)?;
    let lt = required_f32(params, "lt").map_err(anyhow::Error::msg)?;
    let m1t = required_f32(params, "m1t").map_err(anyhow::Error::msg)?;
    let m2t = required_f32(params, "m2t").map_err(anyhow::Error::msg)?;
    let ht = required_f32(params, "ht").map_err(anyhow::Error::msg)?;
    let lmcr = required_f32(params, "lmcr").map_err(anyhow::Error::msg)?;
    let mmcr = required_f32(params, "mmcr").map_err(anyhow::Error::msg)?;
    let mhcr = required_f32(params, "mhcr").map_err(anyhow::Error::msg)?;
    let gain = required_f32(params, "gain").map_err(anyhow::Error::msg)?;
    let lib_path = lv2::resolve_lv2_lib(PLUGIN_BINARY)?;
    let bundle_path = lv2::resolve_lv2_bundle(PLUGIN_DIR)?;

    let control_ports: &[(usize, f32)] = &[
        (PORT_CTRL_BYPASS, if bypass { 1.0 } else { 0.0 }),
        (PORT_CTRL_WETDRY, wetdry),
        (PORT_CTRL_LR, lr),
        (PORT_CTRL_M1R, m1r),
        (PORT_CTRL_M2R, m2r),
        (PORT_CTRL_HR, hr),
        (PORT_CTRL_LT, lt),
        (PORT_CTRL_M1T, m1t),
        (PORT_CTRL_M2T, m2t),
        (PORT_CTRL_HT, ht),
        (PORT_CTRL_LMCR, lmcr),
        (PORT_CTRL_MMCR, mmcr),
        (PORT_CTRL_MHCR, mhcr),
        (PORT_CTRL_GAIN, gain),
    ];

    let processor = lv2::build_stereo_lv2_processor(&lib_path, PLUGIN_URI, sample_rate as f64, &bundle_path, &[PORT_AUDIO_IN_INPUT_L, PORT_AUDIO_IN_INPUT_R], &[PORT_AUDIO_OUT_OUTPUT_L, PORT_AUDIO_OUT_OUTPUT_R], control_ports)?;
    let _ = layout;
    Ok(BlockProcessor::Stereo(Box::new(processor)))
}

fn schema() -> Result<ModelParameterSchema> { Ok(model_schema()) }

pub const MODEL_DEFINITION: DynModelDefinition = DynModelDefinition {
    id: MODEL_ID, display_name: DISPLAY_NAME, brand: BRAND,
    backend_kind: DynBackendKind::Lv2, schema, build,
    supported_instruments: block_core::ALL_INSTRUMENTS, knob_layout: &[],
};
