// AUTO-GENERATED by tools/lv2_catalog_import — do not edit by hand.
// Re-run the tool to regenerate. Manual customisation goes in overrides.yaml.

#![allow(dead_code, unused_imports, unused_variables, clippy::all)]

use crate::registry::DynModelDefinition;
use crate::DynBackendKind;
use anyhow::Result;
use block_core::param::{
    bool_parameter, float_parameter, required_bool, required_f32,
    ModelParameterSchema, ParameterSet, ParameterUnit,
};
use block_core::{AudioChannelLayout, BlockProcessor, ModelAudioMode};

pub const MODEL_ID: &str = "lv2_calf_bad_multiband_limiter";
pub const DISPLAY_NAME: &str = "Calf Multiband Limiter";
const BRAND: &str = "calf";

const PLUGIN_URI: &str = "http://calf.sourceforge.net/plugins/MultibandLimiter";
const PLUGIN_DIR: &str = "calf-bad";
pub const THUMBNAIL_PATH: Option<&str> = None;

#[cfg(target_os = "macos")]
const PLUGIN_BINARY: &str = "calf.dylib";
#[cfg(target_os = "linux")]
const PLUGIN_BINARY: &str = "calf.so";
#[cfg(target_os = "windows")]
const PLUGIN_BINARY: &str = "calf.dll";

// Port indices (from TTL)
const PORT_AUDIO_IN_IN_L: usize = 0;
const PORT_AUDIO_IN_IN_R: usize = 1;
const PORT_AUDIO_OUT_OUT_L: usize = 2;
const PORT_AUDIO_OUT_OUT_R: usize = 3;
const PORT_CTRL_BYPASS: usize = 4;
const PORT_CTRL_LEVEL_IN: usize = 5;
const PORT_CTRL_LEVEL_OUT: usize = 6;
const PORT_CTRL_METER_IN_L: usize = 7;
const PORT_CTRL_METER_IN_R: usize = 8;
const PORT_CTRL_METER_OUT_L: usize = 9;
const PORT_CTRL_METER_OUT_R: usize = 10;
const PORT_CTRL_CLIP_IN_L: usize = 11;
const PORT_CTRL_CLIP_IN_R: usize = 12;
const PORT_CTRL_CLIP_OUT_L: usize = 13;
const PORT_CTRL_CLIP_OUT_R: usize = 14;
const PORT_CTRL_FREQ0: usize = 15;
const PORT_CTRL_FREQ1: usize = 16;
const PORT_CTRL_FREQ2: usize = 17;
const PORT_CTRL_MODE: usize = 18;
const PORT_CTRL_LIMIT: usize = 19;
const PORT_CTRL_ATTACK: usize = 20;
const PORT_CTRL_RELEASE: usize = 21;
const PORT_CTRL_MINREL: usize = 22;
const PORT_CTRL_ATT0: usize = 23;
const PORT_CTRL_ATT1: usize = 24;
const PORT_CTRL_ATT2: usize = 25;
const PORT_CTRL_ATT3: usize = 26;
const PORT_CTRL_WEIGHT0: usize = 27;
const PORT_CTRL_WEIGHT1: usize = 28;
const PORT_CTRL_WEIGHT2: usize = 29;
const PORT_CTRL_WEIGHT3: usize = 30;
const PORT_CTRL_RELEASE0: usize = 31;
const PORT_CTRL_RELEASE1: usize = 32;
const PORT_CTRL_RELEASE2: usize = 33;
const PORT_CTRL_RELEASE3: usize = 34;
const PORT_CTRL_SOLO0: usize = 35;
const PORT_CTRL_SOLO1: usize = 36;
const PORT_CTRL_SOLO2: usize = 37;
const PORT_CTRL_SOLO3: usize = 38;
const PORT_CTRL_EFFRELEASE0: usize = 39;
const PORT_CTRL_EFFRELEASE1: usize = 40;
const PORT_CTRL_EFFRELEASE2: usize = 41;
const PORT_CTRL_EFFRELEASE3: usize = 42;
const PORT_CTRL_ASC: usize = 43;
const PORT_CTRL_ASC_LED: usize = 44;
const PORT_CTRL_ASC_COEFF: usize = 45;
const PORT_CTRL_OVERSAMPLING: usize = 46;

pub fn model_schema() -> ModelParameterSchema {
    ModelParameterSchema {
        effect_type: block_core::EFFECT_TYPE_DYNAMICS.into(),
        model: MODEL_ID.into(),
        display_name: DISPLAY_NAME.into(),
        audio_mode: ModelAudioMode::TrueStereo,
        parameters: vec![
            bool_parameter("bypass", "Bypass", None, Some(false)),
            float_parameter("level_in", "Input Gain", None, Some(1.0), 0.015625, 64.0, 0.1, ParameterUnit::None),
            float_parameter("level_out", "Output Gain", None, Some(1.0), 0.015625, 64.0, 0.1, ParameterUnit::None),
            float_parameter("freq0", "Split 1/2", None, Some(100.0), 10.0, 20000.0, 10.0, ParameterUnit::Hertz),
            float_parameter("freq1", "Split 2/3", None, Some(750.0), 10.0, 20000.0, 10.0, ParameterUnit::Hertz),
            float_parameter("freq2", "Split 3/4", None, Some(5000.0), 10.0, 20000.0, 10.0, ParameterUnit::Hertz),
            float_parameter("mode", "Filter Mode", None, Some(1.0), 0.0, 1.0, 0.01, ParameterUnit::None),
            float_parameter("limit", "Limit", None, Some(1.0), 0.0625, 1.0, 0.001, ParameterUnit::None),
            float_parameter("attack", "Lookahead", None, Some(4.0), 0.1, 10.0, 0.01, ParameterUnit::Milliseconds),
            float_parameter("release", "Release", None, Some(30.0), 1.0, 1000.0, 1.0, ParameterUnit::Milliseconds),
            bool_parameter("minrel", "Min Release", None, Some(false)),
            float_parameter("weight0", "Weight 1", None, Some(0.0), -1.0, 1.0, 0.01, ParameterUnit::None),
            float_parameter("weight1", "Weight 2", None, Some(0.0), -1.0, 1.0, 0.01, ParameterUnit::None),
            float_parameter("weight2", "Weight 3", None, Some(0.0), -1.0, 1.0, 0.01, ParameterUnit::None),
            float_parameter("weight3", "Weight 4", None, Some(0.0), -1.0, 1.0, 0.01, ParameterUnit::None),
            float_parameter("release0", "Release 1", None, Some(0.5), -1.0, 1.0, 0.01, ParameterUnit::None),
            float_parameter("release1", "Release 2", None, Some(0.2), -1.0, 1.0, 0.01, ParameterUnit::None),
            float_parameter("release2", "Release 3", None, Some(-0.2), -1.0, 1.0, 0.01, ParameterUnit::None),
            float_parameter("release3", "Release 4", None, Some(-0.5), -1.0, 1.0, 0.01, ParameterUnit::None),
            bool_parameter("solo0", "Solo 1", None, Some(false)),
            bool_parameter("solo1", "Solo 2", None, Some(false)),
            bool_parameter("solo2", "Solo 3", None, Some(false)),
            bool_parameter("solo3", "Solo 4", None, Some(false)),
            bool_parameter("asc", "ASC", None, Some(true)),
            float_parameter("asc_coeff", "ASC Level", None, Some(0.5), 0.0, 1.0, 0.01, ParameterUnit::None),
            float_parameter("oversampling", "Oversampling", None, Some(1.0), 1.0, 4.0, 0.01, ParameterUnit::None),
        ],
    }
}

fn build(params: &ParameterSet, sample_rate: f32, layout: AudioChannelLayout) -> Result<BlockProcessor> {
    let bypass = required_bool(params, "bypass").map_err(anyhow::Error::msg)?;
    let level_in = required_f32(params, "level_in").map_err(anyhow::Error::msg)?;
    let level_out = required_f32(params, "level_out").map_err(anyhow::Error::msg)?;
    let freq0 = required_f32(params, "freq0").map_err(anyhow::Error::msg)?;
    let freq1 = required_f32(params, "freq1").map_err(anyhow::Error::msg)?;
    let freq2 = required_f32(params, "freq2").map_err(anyhow::Error::msg)?;
    let mode = required_f32(params, "mode").map_err(anyhow::Error::msg)?;
    let limit = required_f32(params, "limit").map_err(anyhow::Error::msg)?;
    let attack = required_f32(params, "attack").map_err(anyhow::Error::msg)?;
    let release = required_f32(params, "release").map_err(anyhow::Error::msg)?;
    let minrel = required_bool(params, "minrel").map_err(anyhow::Error::msg)?;
    let weight0 = required_f32(params, "weight0").map_err(anyhow::Error::msg)?;
    let weight1 = required_f32(params, "weight1").map_err(anyhow::Error::msg)?;
    let weight2 = required_f32(params, "weight2").map_err(anyhow::Error::msg)?;
    let weight3 = required_f32(params, "weight3").map_err(anyhow::Error::msg)?;
    let release0 = required_f32(params, "release0").map_err(anyhow::Error::msg)?;
    let release1 = required_f32(params, "release1").map_err(anyhow::Error::msg)?;
    let release2 = required_f32(params, "release2").map_err(anyhow::Error::msg)?;
    let release3 = required_f32(params, "release3").map_err(anyhow::Error::msg)?;
    let solo0 = required_bool(params, "solo0").map_err(anyhow::Error::msg)?;
    let solo1 = required_bool(params, "solo1").map_err(anyhow::Error::msg)?;
    let solo2 = required_bool(params, "solo2").map_err(anyhow::Error::msg)?;
    let solo3 = required_bool(params, "solo3").map_err(anyhow::Error::msg)?;
    let asc = required_bool(params, "asc").map_err(anyhow::Error::msg)?;
    let asc_coeff = required_f32(params, "asc_coeff").map_err(anyhow::Error::msg)?;
    let oversampling = required_f32(params, "oversampling").map_err(anyhow::Error::msg)?;
    let lib_path = lv2::resolve_lv2_lib(PLUGIN_BINARY)?;
    let bundle_path = lv2::resolve_lv2_bundle(PLUGIN_DIR)?;

    let control_ports: &[(usize, f32)] = &[
        (PORT_CTRL_BYPASS, if bypass { 1.0 } else { 0.0 }),
        (PORT_CTRL_LEVEL_IN, level_in),
        (PORT_CTRL_LEVEL_OUT, level_out),
        (PORT_CTRL_FREQ0, freq0),
        (PORT_CTRL_FREQ1, freq1),
        (PORT_CTRL_FREQ2, freq2),
        (PORT_CTRL_MODE, mode),
        (PORT_CTRL_LIMIT, limit),
        (PORT_CTRL_ATTACK, attack),
        (PORT_CTRL_RELEASE, release),
        (PORT_CTRL_MINREL, if minrel { 1.0 } else { 0.0 }),
        (PORT_CTRL_WEIGHT0, weight0),
        (PORT_CTRL_WEIGHT1, weight1),
        (PORT_CTRL_WEIGHT2, weight2),
        (PORT_CTRL_WEIGHT3, weight3),
        (PORT_CTRL_RELEASE0, release0),
        (PORT_CTRL_RELEASE1, release1),
        (PORT_CTRL_RELEASE2, release2),
        (PORT_CTRL_RELEASE3, release3),
        (PORT_CTRL_SOLO0, if solo0 { 1.0 } else { 0.0 }),
        (PORT_CTRL_SOLO1, if solo1 { 1.0 } else { 0.0 }),
        (PORT_CTRL_SOLO2, if solo2 { 1.0 } else { 0.0 }),
        (PORT_CTRL_SOLO3, if solo3 { 1.0 } else { 0.0 }),
        (PORT_CTRL_ASC, if asc { 1.0 } else { 0.0 }),
        (PORT_CTRL_ASC_COEFF, asc_coeff),
        (PORT_CTRL_OVERSAMPLING, oversampling),
    ];

    let processor = lv2::build_stereo_lv2_processor(&lib_path, PLUGIN_URI, sample_rate as f64, &bundle_path, &[PORT_AUDIO_IN_IN_L, PORT_AUDIO_IN_IN_R], &[PORT_AUDIO_OUT_OUT_L, PORT_AUDIO_OUT_OUT_R], control_ports)?;
    let _ = layout;
    Ok(BlockProcessor::Stereo(Box::new(processor)))
}

fn schema() -> Result<ModelParameterSchema> { Ok(model_schema()) }

pub const MODEL_DEFINITION: DynModelDefinition = DynModelDefinition {
    id: MODEL_ID, display_name: DISPLAY_NAME, brand: BRAND,
    backend_kind: DynBackendKind::Lv2, schema, build,
    supported_instruments: block_core::ALL_INSTRUMENTS, knob_layout: &[],
};
