// AUTO-GENERATED by tools/lv2_catalog_import — do not edit by hand.
// Re-run the tool to regenerate. Manual customisation goes in overrides.yaml.

#![allow(dead_code, unused_imports, unused_variables, clippy::all)]

use crate::registry::DynModelDefinition;
use crate::DynBackendKind;
use anyhow::Result;
use block_core::param::{
    bool_parameter, float_parameter, required_bool, required_f32,
    ModelParameterSchema, ParameterSet, ParameterUnit,
};
use block_core::{AudioChannelLayout, BlockProcessor, ModelAudioMode};

pub const MODEL_ID: &str = "lv2_calf_bad_limiter";
pub const DISPLAY_NAME: &str = "Calf Limiter";
const BRAND: &str = "calf";

const PLUGIN_URI: &str = "http://calf.sourceforge.net/plugins/Limiter";
const PLUGIN_DIR: &str = "calf-bad";

#[cfg(target_os = "macos")]
const PLUGIN_BINARY: &str = "calf.dylib";
#[cfg(target_os = "linux")]
const PLUGIN_BINARY: &str = "calf.so";
#[cfg(target_os = "windows")]
const PLUGIN_BINARY: &str = "calf.dll";

// Port indices (from TTL)
const PORT_AUDIO_IN_IN_L: usize = 0;
const PORT_AUDIO_IN_IN_R: usize = 1;
const PORT_AUDIO_OUT_OUT_L: usize = 2;
const PORT_AUDIO_OUT_OUT_R: usize = 3;
const PORT_CTRL_BYPASS: usize = 4;
const PORT_CTRL_LEVEL_IN: usize = 5;
const PORT_CTRL_LEVEL_OUT: usize = 6;
const PORT_CTRL_METER_IN_L: usize = 7;
const PORT_CTRL_METER_IN_R: usize = 8;
const PORT_CTRL_METER_OUT_L: usize = 9;
const PORT_CTRL_METER_OUT_R: usize = 10;
const PORT_CTRL_CLIP_IN_L: usize = 11;
const PORT_CTRL_CLIP_IN_R: usize = 12;
const PORT_CTRL_CLIP_OUT_L: usize = 13;
const PORT_CTRL_CLIP_OUT_R: usize = 14;
const PORT_CTRL_LIMIT: usize = 15;
const PORT_CTRL_ATTACK: usize = 16;
const PORT_CTRL_RELEASE: usize = 17;
const PORT_CTRL_ATT: usize = 18;
const PORT_CTRL_ASC: usize = 19;
const PORT_CTRL_ASC_LED: usize = 20;
const PORT_CTRL_ASC_COEFF: usize = 21;
const PORT_CTRL_OVERSAMPLING: usize = 22;

pub fn model_schema() -> ModelParameterSchema {
    ModelParameterSchema {
        effect_type: block_core::EFFECT_TYPE_DYNAMICS.into(),
        model: MODEL_ID.into(),
        display_name: DISPLAY_NAME.into(),
        audio_mode: ModelAudioMode::TrueStereo,
        parameters: vec![
            bool_parameter("bypass", "Bypass", None, Some(false)),
            float_parameter("level_in", "Input Gain", None, Some(1.0), 0.015625, 64.0, 0.1, ParameterUnit::None),
            float_parameter("level_out", "Output Gain", None, Some(1.0), 0.015625, 64.0, 0.1, ParameterUnit::None),
            float_parameter("limit", "Limit", None, Some(1.0), 0.0625, 1.0, 0.001, ParameterUnit::None),
            float_parameter("attack", "Lookahead", None, Some(5.0), 0.1, 10.0, 0.01, ParameterUnit::Milliseconds),
            float_parameter("release", "Release", None, Some(50.0), 1.0, 1000.0, 1.0, ParameterUnit::Milliseconds),
            bool_parameter("asc", "ASC", None, Some(true)),
            float_parameter("asc_coeff", "ASC Level", None, Some(0.5), 0.0, 1.0, 0.01, ParameterUnit::None),
            float_parameter("oversampling", "Oversampling", None, Some(1.0), 1.0, 4.0, 0.01, ParameterUnit::None),
        ],
    }
}

fn build(params: &ParameterSet, sample_rate: f32, layout: AudioChannelLayout) -> Result<BlockProcessor> {
    let bypass = required_bool(params, "bypass").map_err(anyhow::Error::msg)?;
    let level_in = required_f32(params, "level_in").map_err(anyhow::Error::msg)?;
    let level_out = required_f32(params, "level_out").map_err(anyhow::Error::msg)?;
    let limit = required_f32(params, "limit").map_err(anyhow::Error::msg)?;
    let attack = required_f32(params, "attack").map_err(anyhow::Error::msg)?;
    let release = required_f32(params, "release").map_err(anyhow::Error::msg)?;
    let asc = required_bool(params, "asc").map_err(anyhow::Error::msg)?;
    let asc_coeff = required_f32(params, "asc_coeff").map_err(anyhow::Error::msg)?;
    let oversampling = required_f32(params, "oversampling").map_err(anyhow::Error::msg)?;
    let lib_path = lv2::resolve_lv2_lib(PLUGIN_BINARY)?;
    let bundle_path = lv2::resolve_lv2_bundle(PLUGIN_DIR)?;

    let control_ports: &[(usize, f32)] = &[
        (PORT_CTRL_BYPASS, if bypass { 1.0 } else { 0.0 }),
        (PORT_CTRL_LEVEL_IN, level_in),
        (PORT_CTRL_LEVEL_OUT, level_out),
        (PORT_CTRL_LIMIT, limit),
        (PORT_CTRL_ATTACK, attack),
        (PORT_CTRL_RELEASE, release),
        (PORT_CTRL_ASC, if asc { 1.0 } else { 0.0 }),
        (PORT_CTRL_ASC_COEFF, asc_coeff),
        (PORT_CTRL_OVERSAMPLING, oversampling),
    ];

    let processor = lv2::build_stereo_lv2_processor(&lib_path, PLUGIN_URI, sample_rate as f64, &bundle_path, &[PORT_AUDIO_IN_IN_L, PORT_AUDIO_IN_IN_R], &[PORT_AUDIO_OUT_OUT_L, PORT_AUDIO_OUT_OUT_R], control_ports)?;
    let _ = layout;
    Ok(BlockProcessor::Stereo(Box::new(processor)))
}

fn schema() -> Result<ModelParameterSchema> { Ok(model_schema()) }

pub const MODEL_DEFINITION: DynModelDefinition = DynModelDefinition {
    id: MODEL_ID, display_name: DISPLAY_NAME, brand: BRAND,
    backend_kind: DynBackendKind::Lv2, schema, build,
    supported_instruments: block_core::ALL_INSTRUMENTS, knob_layout: &[],
};
