// AUTO-GENERATED by tools/lv2_catalog_import — do not edit by hand.
// Re-run the tool to regenerate. Manual customisation goes in overrides.yaml.

#![allow(dead_code, unused_imports, unused_variables, clippy::all)]

use crate::registry::DynModelDefinition;
use crate::DynBackendKind;
use anyhow::Result;
use block_core::param::{
    bool_parameter, float_parameter, required_bool, required_f32,
    ModelParameterSchema, ParameterSet, ParameterUnit,
};
use block_core::{AudioChannelLayout, BlockProcessor, ModelAudioMode};

pub const MODEL_ID: &str = "lv2_rkr_comp";
pub const DISPLAY_NAME: &str = "rkr Compressor";
const BRAND: &str = "rakarrack";

const PLUGIN_URI: &str = "http://rakarrack.sourceforge.net/effects.html#comp";
const PLUGIN_DIR: &str = "rkr";

#[cfg(target_os = "macos")]
const PLUGIN_BINARY: &str = "plugin.dylib";
#[cfg(target_os = "linux")]
const PLUGIN_BINARY: &str = "plugin.so";
#[cfg(target_os = "windows")]
const PLUGIN_BINARY: &str = "plugin.dll";

// Port indices (from TTL)
const PORT_AUDIO_IN_INPUT_L: usize = 0;
const PORT_AUDIO_IN_INPUT_R: usize = 1;
const PORT_AUDIO_OUT_OUTPUT_L: usize = 2;
const PORT_AUDIO_OUT_OUTPUT_R: usize = 3;
const PORT_CTRL_BYPASS: usize = 4;
const PORT_CTRL_THRESHOLD: usize = 5;
const PORT_CTRL_RATIO: usize = 6;
const PORT_CTRL_OUTPUT: usize = 7;
const PORT_CTRL_ATTACK: usize = 8;
const PORT_CTRL_RELEASE: usize = 9;
const PORT_CTRL_AUTOOUT: usize = 10;
const PORT_CTRL_KNEE: usize = 11;
const PORT_CTRL_STEREO: usize = 12;
const PORT_CTRL_PEAK: usize = 13;

pub fn model_schema() -> ModelParameterSchema {
    ModelParameterSchema {
        effect_type: block_core::EFFECT_TYPE_DYNAMICS.into(),
        model: MODEL_ID.into(),
        display_name: DISPLAY_NAME.into(),
        audio_mode: ModelAudioMode::TrueStereo,
        parameters: vec![
            bool_parameter("bypass", "Bypass", None, Some(false)),
            float_parameter("threshold", "Threshold", None, Some(-30.0), -60.0, -3.0, 0.1, ParameterUnit::Decibels),
            float_parameter("ratio", "RATIO", None, Some(2.0), 2.0, 42.0, 0.1, ParameterUnit::None),
            float_parameter("output", "Output Gain", None, Some(-6.0), -40.0, 0.0, 0.1, ParameterUnit::Decibels),
            float_parameter("attack", "Attack Time", None, Some(20.0), 10.0, 250.0, 1.0, ParameterUnit::Milliseconds),
            float_parameter("release", "Release Time", None, Some(120.0), 10.0, 500.0, 1.0, ParameterUnit::Milliseconds),
            bool_parameter("autoout", "Auto Output", None, Some(true)),
            float_parameter("knee", "Knee", None, Some(0.0), 0.0, 100.0, 1.0, ParameterUnit::Percent),
            bool_parameter("stereo", "Stereo", None, Some(false)),
            bool_parameter("peak", "Peak", None, Some(false)),
        ],
    }
}

fn build(params: &ParameterSet, sample_rate: f32, layout: AudioChannelLayout) -> Result<BlockProcessor> {
    let bypass = required_bool(params, "bypass").map_err(anyhow::Error::msg)?;
    let threshold = required_f32(params, "threshold").map_err(anyhow::Error::msg)?;
    let ratio = required_f32(params, "ratio").map_err(anyhow::Error::msg)?;
    let output = required_f32(params, "output").map_err(anyhow::Error::msg)?;
    let attack = required_f32(params, "attack").map_err(anyhow::Error::msg)?;
    let release = required_f32(params, "release").map_err(anyhow::Error::msg)?;
    let autoout = required_bool(params, "autoout").map_err(anyhow::Error::msg)?;
    let knee = required_f32(params, "knee").map_err(anyhow::Error::msg)?;
    let stereo = required_bool(params, "stereo").map_err(anyhow::Error::msg)?;
    let peak = required_bool(params, "peak").map_err(anyhow::Error::msg)?;
    let lib_path = lv2::resolve_lv2_lib(PLUGIN_BINARY)?;
    let bundle_path = lv2::resolve_lv2_bundle(PLUGIN_DIR)?;

    let control_ports: &[(usize, f32)] = &[
        (PORT_CTRL_BYPASS, if bypass { 1.0 } else { 0.0 }),
        (PORT_CTRL_THRESHOLD, threshold),
        (PORT_CTRL_RATIO, ratio),
        (PORT_CTRL_OUTPUT, output),
        (PORT_CTRL_ATTACK, attack),
        (PORT_CTRL_RELEASE, release),
        (PORT_CTRL_AUTOOUT, if autoout { 1.0 } else { 0.0 }),
        (PORT_CTRL_KNEE, knee),
        (PORT_CTRL_STEREO, if stereo { 1.0 } else { 0.0 }),
        (PORT_CTRL_PEAK, if peak { 1.0 } else { 0.0 }),
    ];

    let processor = lv2::build_stereo_lv2_processor(&lib_path, PLUGIN_URI, sample_rate as f64, &bundle_path, &[PORT_AUDIO_IN_INPUT_L, PORT_AUDIO_IN_INPUT_R], &[PORT_AUDIO_OUT_OUTPUT_L, PORT_AUDIO_OUT_OUTPUT_R], control_ports)?;
    let _ = layout;
    Ok(BlockProcessor::Stereo(Box::new(processor)))
}

fn schema() -> Result<ModelParameterSchema> { Ok(model_schema()) }

pub const MODEL_DEFINITION: DynModelDefinition = DynModelDefinition {
    id: MODEL_ID, display_name: DISPLAY_NAME, brand: BRAND,
    backend_kind: DynBackendKind::Lv2, schema, build,
    supported_instruments: block_core::ALL_INSTRUMENTS, knob_layout: &[],
};
