// AUTO-GENERATED by tools/lv2_catalog_import — do not edit by hand.
// Re-run the tool to regenerate. Manual customisation goes in overrides.yaml.

#![allow(dead_code, unused_imports, unused_variables, clippy::all)]

use crate::registry::DynModelDefinition;
use crate::DynBackendKind;
use anyhow::Result;
use block_core::param::{
    bool_parameter, float_parameter, required_bool, required_f32,
    ModelParameterSchema, ParameterSet, ParameterUnit,
};
use block_core::{AudioChannelLayout, BlockProcessor, ModelAudioMode};

pub const MODEL_ID: &str = "lv2_calf_compressor";
pub const DISPLAY_NAME: &str = "Calf Compressor";
const BRAND: &str = "calf";

const PLUGIN_URI: &str = "http://calf.sourceforge.net/plugins/Compressor";
const PLUGIN_DIR: &str = "calf";
pub const THUMBNAIL_PATH: Option<&str> = Some(".plugins/lv2/calf.lv2/modgui/thumb-calf-compressor.png");

#[cfg(target_os = "macos")]
const PLUGIN_BINARY: &str = "plugin.dylib";
#[cfg(target_os = "linux")]
const PLUGIN_BINARY: &str = "plugin.so";
#[cfg(target_os = "windows")]
const PLUGIN_BINARY: &str = "plugin.dll";

// Port indices (from TTL)
const PORT_AUDIO_IN_IN_L: usize = 0;
const PORT_AUDIO_IN_IN_R: usize = 1;
const PORT_AUDIO_OUT_OUT_L: usize = 2;
const PORT_AUDIO_OUT_OUT_R: usize = 3;
const PORT_CTRL_BYPASS: usize = 4;
const PORT_CTRL_LEVEL_IN: usize = 5;
const PORT_CTRL_METER_IN: usize = 6;
const PORT_CTRL_METER_OUT: usize = 7;
const PORT_CTRL_CLIP_IN: usize = 8;
const PORT_CTRL_CLIP_OUT: usize = 9;
const PORT_CTRL_THRESHOLD: usize = 10;
const PORT_CTRL_RATIO: usize = 11;
const PORT_CTRL_ATTACK: usize = 12;
const PORT_CTRL_RELEASE: usize = 13;
const PORT_CTRL_MAKEUP: usize = 14;
const PORT_CTRL_KNEE: usize = 15;
const PORT_CTRL_DETECTION: usize = 16;
const PORT_CTRL_STEREO_LINK: usize = 17;
const PORT_CTRL_COMPRESSION: usize = 18;
const PORT_CTRL_MIX: usize = 19;

pub fn model_schema() -> ModelParameterSchema {
    ModelParameterSchema {
        effect_type: block_core::EFFECT_TYPE_DYNAMICS.into(),
        model: MODEL_ID.into(),
        display_name: DISPLAY_NAME.into(),
        audio_mode: ModelAudioMode::TrueStereo,
        parameters: vec![
            bool_parameter("bypass", "Bypass", None, Some(false)),
            float_parameter("level_in", "Input", None, Some(1.0), 0.015625, 64.0, 0.1, ParameterUnit::None),
            float_parameter("threshold", "Threshold", None, Some(0.125), 0.000976563, 1.0, 0.001, ParameterUnit::None),
            float_parameter("ratio", "Ratio", None, Some(2.0), 1.0, 20.0, 0.1, ParameterUnit::None),
            float_parameter("attack", "Attack", None, Some(20.0), 0.01, 2000.0, 10.0, ParameterUnit::Milliseconds),
            float_parameter("release", "Release", None, Some(250.0), 0.01, 2000.0, 10.0, ParameterUnit::Milliseconds),
            float_parameter("makeup", "Makeup Gain", None, Some(2.0), 1.0, 64.0, 0.1, ParameterUnit::None),
            float_parameter("knee", "Knee", None, Some(2.82843), 1.0, 8.0, 0.01, ParameterUnit::None),
            float_parameter("detection", "Detection", None, Some(0.0), 0.0, 1.0, 0.01, ParameterUnit::None),
            float_parameter("stereo_link", "Stereo Link", None, Some(0.0), 0.0, 1.0, 0.01, ParameterUnit::None),
            float_parameter("mix", "Mix", None, Some(1.0), 0.0, 1.0, 0.01, ParameterUnit::None),
        ],
    }
}

fn build(params: &ParameterSet, sample_rate: f32, layout: AudioChannelLayout) -> Result<BlockProcessor> {
    let bypass = required_bool(params, "bypass").map_err(anyhow::Error::msg)?;
    let level_in = required_f32(params, "level_in").map_err(anyhow::Error::msg)?;
    let threshold = required_f32(params, "threshold").map_err(anyhow::Error::msg)?;
    let ratio = required_f32(params, "ratio").map_err(anyhow::Error::msg)?;
    let attack = required_f32(params, "attack").map_err(anyhow::Error::msg)?;
    let release = required_f32(params, "release").map_err(anyhow::Error::msg)?;
    let makeup = required_f32(params, "makeup").map_err(anyhow::Error::msg)?;
    let knee = required_f32(params, "knee").map_err(anyhow::Error::msg)?;
    let detection = required_f32(params, "detection").map_err(anyhow::Error::msg)?;
    let stereo_link = required_f32(params, "stereo_link").map_err(anyhow::Error::msg)?;
    let mix = required_f32(params, "mix").map_err(anyhow::Error::msg)?;
    let lib_path = lv2::resolve_lv2_lib(PLUGIN_BINARY)?;
    let bundle_path = lv2::resolve_lv2_bundle(PLUGIN_DIR)?;

    let control_ports: &[(usize, f32)] = &[
        (PORT_CTRL_BYPASS, if bypass { 1.0 } else { 0.0 }),
        (PORT_CTRL_LEVEL_IN, level_in),
        (PORT_CTRL_THRESHOLD, threshold),
        (PORT_CTRL_RATIO, ratio),
        (PORT_CTRL_ATTACK, attack),
        (PORT_CTRL_RELEASE, release),
        (PORT_CTRL_MAKEUP, makeup),
        (PORT_CTRL_KNEE, knee),
        (PORT_CTRL_DETECTION, detection),
        (PORT_CTRL_STEREO_LINK, stereo_link),
        (PORT_CTRL_MIX, mix),
    ];

    let processor = lv2::build_stereo_lv2_processor(&lib_path, PLUGIN_URI, sample_rate as f64, &bundle_path, &[PORT_AUDIO_IN_IN_L, PORT_AUDIO_IN_IN_R], &[PORT_AUDIO_OUT_OUT_L, PORT_AUDIO_OUT_OUT_R], control_ports)?;
    let _ = layout;
    Ok(BlockProcessor::Stereo(Box::new(processor)))
}

fn schema() -> Result<ModelParameterSchema> { Ok(model_schema()) }

pub const MODEL_DEFINITION: DynModelDefinition = DynModelDefinition {
    id: MODEL_ID, display_name: DISPLAY_NAME, brand: BRAND,
    backend_kind: DynBackendKind::Lv2, schema, build,
    supported_instruments: block_core::ALL_INSTRUMENTS, knob_layout: &[],
};
