// AUTO-GENERATED by tools/lv2_catalog_import — do not edit by hand.
// Re-run the tool to regenerate. Manual customisation goes in overrides.yaml.

#![allow(dead_code, unused_imports, unused_variables, clippy::approx_constant, clippy::excessive_precision)]

use crate::registry::DynModelDefinition;
use crate::DynBackendKind;
use anyhow::Result;
use block_core::param::{
    bool_parameter, float_parameter, required_bool, required_f32,
    ModelParameterSchema, ParameterSet, ParameterUnit,
};
use block_core::{AudioChannelLayout, BlockProcessor, ModelAudioMode, MonoProcessor, StereoProcessor};

pub const MODEL_ID: &str = "lv2_ab_gate";
pub const DISPLAY_NAME: &str = "abGate";
const BRAND: &str = "a__bruzas";

const PLUGIN_URI: &str = "http://hippie.lt/lv2/gate";
const PLUGIN_DIR: &str = "abGate";

#[cfg(target_os = "macos")]
const PLUGIN_BINARY: &str = "gate.dylib.dylib";
#[cfg(target_os = "linux")]
const PLUGIN_BINARY: &str = "gate.dylib.so";
#[cfg(target_os = "windows")]
const PLUGIN_BINARY: &str = "gate.dylib.dll";

// Port indices (from TTL)
const PORT_AUDIO_OUT_OUTPUT: usize = 0;
const PORT_AUDIO_IN_INPUT: usize = 1;
const PORT_CTRL_SWITCH: usize = 2;
const PORT_CTRL_THRESHOLD: usize = 3;
const PORT_CTRL_ATTACK: usize = 4;
const PORT_CTRL_HOLD: usize = 5;
const PORT_CTRL_DECAY: usize = 6;
const PORT_CTRL_GATERANGE: usize = 7;

pub fn model_schema() -> ModelParameterSchema {
    ModelParameterSchema {
        effect_type: block_core::EFFECT_TYPE_DYNAMICS.into(),
        model: MODEL_ID.into(),
        display_name: DISPLAY_NAME.into(),
        audio_mode: ModelAudioMode::DualMono,
        parameters: vec![
            bool_parameter("switch", "Switch", None, Some(true)),
            float_parameter("threshold", "Threshold", None, Some(-70.0), -70.0, 12.0, 0.1, ParameterUnit::Decibels),
            float_parameter("attack", "Attack", None, Some(30.0), 0.1, 500.0, 1.0, ParameterUnit::Milliseconds),
            float_parameter("hold", "Hold", None, Some(500.0), 5.0, 3000.0, 10.0, ParameterUnit::Milliseconds),
            float_parameter("decay", "Decay", None, Some(1000.0), 5.0, 4000.0, 10.0, ParameterUnit::Milliseconds),
            float_parameter("gaterange", "Range", None, Some(-90.0), -90.0, -20.0, 0.1, ParameterUnit::Decibels),
        ],
    }
}

fn build(params: &ParameterSet, sample_rate: f32, layout: AudioChannelLayout) -> Result<BlockProcessor> {
    let switch = required_bool(params, "switch").map_err(anyhow::Error::msg)?;
    let threshold = required_f32(params, "threshold").map_err(anyhow::Error::msg)?;
    let attack = required_f32(params, "attack").map_err(anyhow::Error::msg)?;
    let hold = required_f32(params, "hold").map_err(anyhow::Error::msg)?;
    let decay = required_f32(params, "decay").map_err(anyhow::Error::msg)?;
    let gaterange = required_f32(params, "gaterange").map_err(anyhow::Error::msg)?;
    let lib_path = lv2::resolve_lv2_lib(PLUGIN_BINARY)?;
    let bundle_path = lv2::resolve_lv2_bundle(PLUGIN_DIR)?;

    let control_ports: &[(usize, f32)] = &[
        (PORT_CTRL_SWITCH, if switch { 1.0 } else { 0.0 }),
        (PORT_CTRL_THRESHOLD, threshold),
        (PORT_CTRL_ATTACK, attack),
        (PORT_CTRL_HOLD, hold),
        (PORT_CTRL_DECAY, decay),
        (PORT_CTRL_GATERANGE, gaterange),
    ];

    match layout {
        AudioChannelLayout::Mono => {
            let processor = lv2::build_lv2_processor(&lib_path, PLUGIN_URI, sample_rate as f64, &bundle_path, &[PORT_AUDIO_IN_INPUT], &[PORT_AUDIO_OUT_OUTPUT], control_ports)?;
            Ok(BlockProcessor::Mono(Box::new(processor)))
        }
        AudioChannelLayout::Stereo => {
            let left = lv2::build_lv2_processor(&lib_path, PLUGIN_URI, sample_rate as f64, &bundle_path, &[PORT_AUDIO_IN_INPUT], &[PORT_AUDIO_OUT_OUTPUT], control_ports)?;
            let right = lv2::build_lv2_processor(&lib_path, PLUGIN_URI, sample_rate as f64, &bundle_path, &[PORT_AUDIO_IN_INPUT], &[PORT_AUDIO_OUT_OUTPUT], control_ports)?;
            Ok(BlockProcessor::Stereo(Box::new(DualMonoProcessor { left, right })))
        }
    }
}

struct DualMonoProcessor { left: lv2::Lv2Processor, right: lv2::Lv2Processor }
impl StereoProcessor for DualMonoProcessor {
    fn process_frame(&mut self, input: [f32; 2]) -> [f32; 2] {
        [self.left.process_sample(input[0]), self.right.process_sample(input[1])]
    }
}

fn schema() -> Result<ModelParameterSchema> { Ok(model_schema()) }

pub const MODEL_DEFINITION: DynModelDefinition = DynModelDefinition {
    id: MODEL_ID, display_name: DISPLAY_NAME, brand: BRAND,
    backend_kind: DynBackendKind::Lv2, schema, build,
    supported_instruments: block_core::ALL_INSTRUMENTS, knob_layout: &[],
};
