// AUTO-GENERATED by tools/lv2_catalog_import — do not edit by hand.
// Re-run the tool to regenerate. Manual customisation goes in overrides.yaml.

#![allow(dead_code, unused_imports, unused_variables, clippy::all)]

use crate::registry::DynModelDefinition;
use crate::DynBackendKind;
use anyhow::Result;
use block_core::param::{
    float_parameter, required_f32, ModelParameterSchema, ParameterSet, ParameterUnit,
};
use block_core::{AudioChannelLayout, BlockProcessor, ModelAudioMode, MonoProcessor, StereoProcessor};

pub const MODEL_ID: &str = "lv2_gx_slowgear";
pub const DISPLAY_NAME: &str = "GxSlowGear";
const BRAND: &str = "guitarix";

const PLUGIN_URI: &str = "http://guitarix.sourceforge.net/plugins/gx_slowgear_#_slowgear_";
const PLUGIN_DIR: &str = "gx_slowgear";
pub const THUMBNAIL_PATH: Option<&str> = Some(".plugins/lv2/gx_slowgear.lv2/modgui/thumbnail-gxslowgear.png");

#[cfg(target_os = "macos")]
const PLUGIN_BINARY: &str = "gx_slowgear.dylib";
#[cfg(target_os = "linux")]
const PLUGIN_BINARY: &str = "gx_slowgear.so";
#[cfg(target_os = "windows")]
const PLUGIN_BINARY: &str = "gx_slowgear.dll";

// Port indices (from TTL)
const PORT_AUDIO_OUT_OUT: usize = 0;
const PORT_AUDIO_IN_IN: usize = 1;
const PORT_CTRL_DOWNTIME: usize = 2;
const PORT_CTRL_TRESHOLD: usize = 3;
const PORT_CTRL_UPTIME: usize = 4;

pub fn model_schema() -> ModelParameterSchema {
    ModelParameterSchema {
        effect_type: block_core::EFFECT_TYPE_DYNAMICS.into(),
        model: MODEL_ID.into(),
        display_name: DISPLAY_NAME.into(),
        audio_mode: ModelAudioMode::DualMono,
        parameters: vec![
            float_parameter("downtime", "DOWNTIME", None, Some(5.0), 0.0, 1000.0, 10.0, ParameterUnit::None),
            float_parameter("treshold", "TRESHOLD", None, Some(1.0), 0.0, 10.0, 0.1, ParameterUnit::None),
            float_parameter("uptime", "UPTIME", None, Some(100.0), 0.0, 1000.0, 10.0, ParameterUnit::None),
        ],
    }
}

fn build(params: &ParameterSet, sample_rate: f32, layout: AudioChannelLayout) -> Result<BlockProcessor> {
    let downtime = required_f32(params, "downtime").map_err(anyhow::Error::msg)?;
    let treshold = required_f32(params, "treshold").map_err(anyhow::Error::msg)?;
    let uptime = required_f32(params, "uptime").map_err(anyhow::Error::msg)?;
    let lib_path = lv2::resolve_lv2_lib(PLUGIN_BINARY)?;
    let bundle_path = lv2::resolve_lv2_bundle(PLUGIN_DIR)?;

    let control_ports: &[(usize, f32)] = &[
        (PORT_CTRL_DOWNTIME, downtime),
        (PORT_CTRL_TRESHOLD, treshold),
        (PORT_CTRL_UPTIME, uptime),
    ];

    match layout {
        AudioChannelLayout::Mono => {
            let processor = lv2::build_lv2_processor(&lib_path, PLUGIN_URI, sample_rate as f64, &bundle_path, &[PORT_AUDIO_IN_IN], &[PORT_AUDIO_OUT_OUT], control_ports)?;
            Ok(BlockProcessor::Mono(Box::new(processor)))
        }
        AudioChannelLayout::Stereo => {
            let left = lv2::build_lv2_processor(&lib_path, PLUGIN_URI, sample_rate as f64, &bundle_path, &[PORT_AUDIO_IN_IN], &[PORT_AUDIO_OUT_OUT], control_ports)?;
            let right = lv2::build_lv2_processor(&lib_path, PLUGIN_URI, sample_rate as f64, &bundle_path, &[PORT_AUDIO_IN_IN], &[PORT_AUDIO_OUT_OUT], control_ports)?;
            Ok(BlockProcessor::Stereo(Box::new(DualMonoProcessor { left, right })))
        }
    }
}

struct DualMonoProcessor { left: lv2::Lv2Processor, right: lv2::Lv2Processor }
impl StereoProcessor for DualMonoProcessor {
    fn process_frame(&mut self, input: [f32; 2]) -> [f32; 2] {
        [self.left.process_sample(input[0]), self.right.process_sample(input[1])]
    }
}

fn schema() -> Result<ModelParameterSchema> { Ok(model_schema()) }

pub const MODEL_DEFINITION: DynModelDefinition = DynModelDefinition {
    id: MODEL_ID, display_name: DISPLAY_NAME, brand: BRAND,
    backend_kind: DynBackendKind::Lv2, schema, build,
    supported_instruments: block_core::ALL_INSTRUMENTS, knob_layout: &[],
};
