// AUTO-GENERATED by tools/lv2_catalog_import — do not edit by hand.
// Re-run the tool to regenerate. Manual customisation goes in overrides.yaml.

#![allow(dead_code, unused_imports, unused_variables, clippy::all)]

use crate::registry::DynModelDefinition;
use crate::DynBackendKind;
use anyhow::Result;
use block_core::param::{
    float_parameter, required_f32, ModelParameterSchema, ParameterSet, ParameterUnit,
};
use block_core::{AudioChannelLayout, BlockProcessor, ModelAudioMode};

pub const MODEL_ID: &str = "lv2_tap_dynamics_st";
pub const DISPLAY_NAME: &str = "TAP Stereo Dynamics";
const BRAND: &str = "tap";

const PLUGIN_URI: &str = "http://moddevices.com/plugins/tap/dynamics-st";
const PLUGIN_DIR: &str = "tap-dynamics-st";
pub const THUMBNAIL_PATH: Option<&str> = Some(".plugins/lv2/tap-dynamics-st.lv2/modgui/thumbnail-tap-stereo-dynamics.png");

#[cfg(target_os = "macos")]
const PLUGIN_BINARY: &str = "tap_dynamics-st.dylib";
#[cfg(target_os = "linux")]
const PLUGIN_BINARY: &str = "tap_dynamics-st.so";
#[cfg(target_os = "windows")]
const PLUGIN_BINARY: &str = "tap_dynamics-st.dll";

// Port indices (from TTL)
const PORT_CTRL_ATTACK: usize = 0;
const PORT_CTRL_RELEASE_M: usize = 1;
const PORT_CTRL_OFFSET: usize = 2;
const PORT_CTRL_MAKEUP: usize = 3;
const PORT_CTRL_LENVELOPE: usize = 4;
const PORT_CTRL_RENVELOPE: usize = 5;
const PORT_CTRL_LGAIN: usize = 6;
const PORT_CTRL_RGAIN: usize = 7;
const PORT_CTRL_STEREO: usize = 8;
const PORT_CTRL_FUNCTION: usize = 9;
const PORT_AUDIO_IN_INL: usize = 10;
const PORT_AUDIO_IN_INR: usize = 11;
const PORT_AUDIO_OUT_OUTL: usize = 12;
const PORT_AUDIO_OUT_OUTR: usize = 13;

pub fn model_schema() -> ModelParameterSchema {
    ModelParameterSchema {
        effect_type: block_core::EFFECT_TYPE_DYNAMICS.into(),
        model: MODEL_ID.into(),
        display_name: DISPLAY_NAME.into(),
        audio_mode: ModelAudioMode::TrueStereo,
        parameters: vec![
            float_parameter("attack", "Attack", None, Some(128.0), 4.0, 500.0, 1.0, ParameterUnit::None),
            float_parameter("releasem", "Release", None, Some(502.0), 4.0, 1000.0, 1.0, ParameterUnit::None),
            float_parameter("offset", "Offset Gain", None, Some(0.0), -20.0, 20.0, 0.1, ParameterUnit::None),
            float_parameter("makeup", "Makeup Gain", None, Some(0.0), -20.0, 20.0, 0.1, ParameterUnit::None),
            float_parameter("stereo", "Stereo Mode", None, Some(0.0), 0.0, 2.0, 0.01, ParameterUnit::None),
            float_parameter("function", "Function", None, Some(0.0), 0.0, 14.0, 0.1, ParameterUnit::None),
        ],
    }
}

fn build(params: &ParameterSet, sample_rate: f32, layout: AudioChannelLayout) -> Result<BlockProcessor> {
    let attack = required_f32(params, "attack").map_err(anyhow::Error::msg)?;
    let releasem = required_f32(params, "releasem").map_err(anyhow::Error::msg)?;
    let offset = required_f32(params, "offset").map_err(anyhow::Error::msg)?;
    let makeup = required_f32(params, "makeup").map_err(anyhow::Error::msg)?;
    let stereo = required_f32(params, "stereo").map_err(anyhow::Error::msg)?;
    let function = required_f32(params, "function").map_err(anyhow::Error::msg)?;
    let lib_path = lv2::resolve_lv2_lib(PLUGIN_BINARY)?;
    let bundle_path = lv2::resolve_lv2_bundle(PLUGIN_DIR)?;

    let control_ports: &[(usize, f32)] = &[
        (PORT_CTRL_ATTACK, attack),
        (PORT_CTRL_RELEASE_M, releasem),
        (PORT_CTRL_OFFSET, offset),
        (PORT_CTRL_MAKEUP, makeup),
        (PORT_CTRL_STEREO, stereo),
        (PORT_CTRL_FUNCTION, function),
    ];

    let processor = lv2::build_stereo_lv2_processor(&lib_path, PLUGIN_URI, sample_rate as f64, &bundle_path, &[PORT_AUDIO_IN_INL, PORT_AUDIO_IN_INR], &[PORT_AUDIO_OUT_OUTL, PORT_AUDIO_OUT_OUTR], control_ports)?;
    let _ = layout;
    Ok(BlockProcessor::Stereo(Box::new(processor)))
}

fn schema() -> Result<ModelParameterSchema> { Ok(model_schema()) }

pub const MODEL_DEFINITION: DynModelDefinition = DynModelDefinition {
    id: MODEL_ID, display_name: DISPLAY_NAME, brand: BRAND,
    backend_kind: DynBackendKind::Lv2, schema, build,
    supported_instruments: block_core::ALL_INSTRUMENTS, knob_layout: &[],
};
