// AUTO-GENERATED by tools/lv2_catalog_import — do not edit by hand.
// Re-run the tool to regenerate. Manual customisation goes in overrides.yaml.

#![allow(dead_code, unused_imports, unused_variables, clippy::approx_constant, clippy::excessive_precision)]

use crate::registry::DynModelDefinition;
use crate::DynBackendKind;
use anyhow::Result;
use block_core::param::{
    bool_parameter, float_parameter, required_bool, required_f32,
    ModelParameterSchema, ParameterSet, ParameterUnit,
};
use block_core::{AudioChannelLayout, BlockProcessor, ModelAudioMode, MonoProcessor, StereoProcessor};

pub const MODEL_ID: &str = "lv2_invada_mono";
pub const DISPLAY_NAME: &str = "Invada Compressor (mono)";
const BRAND: &str = "invada";

const PLUGIN_URI: &str = "http://invadarecords.com/plugins/lv2/compressor/mono";
const PLUGIN_DIR: &str = "invada";

#[cfg(target_os = "macos")]
const PLUGIN_BINARY: &str = "inv_compressor.dylib.dylib";
#[cfg(target_os = "linux")]
const PLUGIN_BINARY: &str = "inv_compressor.dylib.so";
#[cfg(target_os = "windows")]
const PLUGIN_BINARY: &str = "inv_compressor.dylib.dll";

// Port indices (from TTL)
const PORT_CTRL_BYPASS: usize = 0;
const PORT_CTRL_RMS: usize = 1;
const PORT_CTRL_ATTACK: usize = 2;
const PORT_CTRL_RELEASE: usize = 3;
const PORT_CTRL_THRESHOLD: usize = 4;
const PORT_CTRL_RATIO: usize = 5;
const PORT_CTRL_GAIN: usize = 6;
const PORT_CTRL_NO_CLIP: usize = 7;
const PORT_CTRL_GRMETER: usize = 8;
const PORT_CTRL_LAMP_DRIVE: usize = 9;
const PORT_CTRL_METER_IN: usize = 10;
const PORT_CTRL_METER_OUT: usize = 11;
const PORT_AUDIO_IN_IN: usize = 12;
const PORT_AUDIO_OUT_OUT: usize = 13;

pub fn model_schema() -> ModelParameterSchema {
    ModelParameterSchema {
        effect_type: block_core::EFFECT_TYPE_DYNAMICS.into(),
        model: MODEL_ID.into(),
        display_name: DISPLAY_NAME.into(),
        audio_mode: ModelAudioMode::DualMono,
        parameters: vec![
            bool_parameter("bypass", "Bypass", None, Some(false)),
            float_parameter("rms", "RMS", None, Some(0.5), 0.0, 1.0, 0.01, ParameterUnit::None),
            float_parameter("attack", "Attack", None, Some(0.015), 1e-5, 0.75, 0.001, ParameterUnit::Milliseconds),
            float_parameter("release", "Release", None, Some(0.05), 0.001, 5.0, 0.01, ParameterUnit::Milliseconds),
            float_parameter("threshold", "Threshold", None, Some(0.0), -36.0, 0.0, 0.1, ParameterUnit::Decibels),
            float_parameter("ratio", "Ratio", None, Some(1.0), 1.0, 20.0, 0.1, ParameterUnit::None),
            float_parameter("gain", "Gain", None, Some(0.0), -6.0, 36.0, 0.1, ParameterUnit::Decibels),
            bool_parameter("noclip", "Soft Clip", None, Some(true)),
        ],
    }
}

fn build(params: &ParameterSet, sample_rate: f32, layout: AudioChannelLayout) -> Result<BlockProcessor> {
    let bypass = required_bool(params, "bypass").map_err(anyhow::Error::msg)?;
    let rms = required_f32(params, "rms").map_err(anyhow::Error::msg)?;
    let attack = required_f32(params, "attack").map_err(anyhow::Error::msg)?;
    let release = required_f32(params, "release").map_err(anyhow::Error::msg)?;
    let threshold = required_f32(params, "threshold").map_err(anyhow::Error::msg)?;
    let ratio = required_f32(params, "ratio").map_err(anyhow::Error::msg)?;
    let gain = required_f32(params, "gain").map_err(anyhow::Error::msg)?;
    let noclip = required_bool(params, "noclip").map_err(anyhow::Error::msg)?;
    let lib_path = lv2::resolve_lv2_lib(PLUGIN_BINARY)?;
    let bundle_path = lv2::resolve_lv2_bundle(PLUGIN_DIR)?;

    let control_ports: &[(usize, f32)] = &[
        (PORT_CTRL_BYPASS, if bypass { 1.0 } else { 0.0 }),
        (PORT_CTRL_RMS, rms),
        (PORT_CTRL_ATTACK, attack),
        (PORT_CTRL_RELEASE, release),
        (PORT_CTRL_THRESHOLD, threshold),
        (PORT_CTRL_RATIO, ratio),
        (PORT_CTRL_GAIN, gain),
        (PORT_CTRL_NO_CLIP, if noclip { 1.0 } else { 0.0 }),
    ];

    match layout {
        AudioChannelLayout::Mono => {
            let processor = lv2::build_lv2_processor(&lib_path, PLUGIN_URI, sample_rate as f64, &bundle_path, &[PORT_AUDIO_IN_IN], &[PORT_AUDIO_OUT_OUT], control_ports)?;
            Ok(BlockProcessor::Mono(Box::new(processor)))
        }
        AudioChannelLayout::Stereo => {
            let left = lv2::build_lv2_processor(&lib_path, PLUGIN_URI, sample_rate as f64, &bundle_path, &[PORT_AUDIO_IN_IN], &[PORT_AUDIO_OUT_OUT], control_ports)?;
            let right = lv2::build_lv2_processor(&lib_path, PLUGIN_URI, sample_rate as f64, &bundle_path, &[PORT_AUDIO_IN_IN], &[PORT_AUDIO_OUT_OUT], control_ports)?;
            Ok(BlockProcessor::Stereo(Box::new(DualMonoProcessor { left, right })))
        }
    }
}

struct DualMonoProcessor { left: lv2::Lv2Processor, right: lv2::Lv2Processor }
impl StereoProcessor for DualMonoProcessor {
    fn process_frame(&mut self, input: [f32; 2]) -> [f32; 2] {
        [self.left.process_sample(input[0]), self.right.process_sample(input[1])]
    }
}

fn schema() -> Result<ModelParameterSchema> { Ok(model_schema()) }

pub const MODEL_DEFINITION: DynModelDefinition = DynModelDefinition {
    id: MODEL_ID, display_name: DISPLAY_NAME, brand: BRAND,
    backend_kind: DynBackendKind::Lv2, schema, build,
    supported_instruments: block_core::ALL_INSTRUMENTS, knob_layout: &[],
};
