// AUTO-GENERATED by tools/lv2_catalog_import — do not edit by hand.
// Re-run the tool to regenerate. Manual customisation goes in overrides.yaml.

#![allow(dead_code, unused_imports, unused_variables, clippy::all)]

use crate::registry::ReverbModelDefinition;
use crate::ReverbBackendKind;
use anyhow::Result;
use block_core::param::{
    float_parameter, required_f32, ModelParameterSchema, ParameterSet, ParameterUnit,
};
use block_core::{AudioChannelLayout, BlockProcessor, ModelAudioMode};

pub const MODEL_ID: &str = "lv2_calf_bad_reverb";
pub const DISPLAY_NAME: &str = "Calf Reverb";
const BRAND: &str = "calf";

const PLUGIN_URI: &str = "http://calf.sourceforge.net/plugins/Reverb";
const PLUGIN_DIR: &str = "calf-bad";

#[cfg(target_os = "macos")]
const PLUGIN_BINARY: &str = "calf.dylib";
#[cfg(target_os = "linux")]
const PLUGIN_BINARY: &str = "calf.so";
#[cfg(target_os = "windows")]
const PLUGIN_BINARY: &str = "calf.dll";

// Port indices (from TTL)
const PORT_AUDIO_IN_IN_L: usize = 0;
const PORT_AUDIO_IN_IN_R: usize = 1;
const PORT_AUDIO_OUT_OUT_L: usize = 2;
const PORT_AUDIO_OUT_OUT_R: usize = 3;
const PORT_CTRL_CLIP: usize = 4;
const PORT_CTRL_METER_WET: usize = 5;
const PORT_CTRL_METER_OUT: usize = 6;
const PORT_CTRL_DECAY_TIME: usize = 7;
const PORT_CTRL_HF_DAMP: usize = 8;
const PORT_CTRL_ROOM_SIZE: usize = 9;
const PORT_CTRL_DIFFUSION: usize = 10;
const PORT_CTRL_AMOUNT: usize = 11;
const PORT_CTRL_DRY: usize = 12;
const PORT_CTRL_PREDELAY: usize = 13;
const PORT_CTRL_BASS_CUT: usize = 14;
const PORT_CTRL_TREBLE_CUT: usize = 15;

pub fn model_schema() -> ModelParameterSchema {
    ModelParameterSchema {
        effect_type: block_core::EFFECT_TYPE_REVERB.into(),
        model: MODEL_ID.into(),
        display_name: DISPLAY_NAME.into(),
        audio_mode: ModelAudioMode::TrueStereo,
        parameters: vec![
            float_parameter("decay_time", "Decay time", None, Some(1.5), 0.4, 15.0, 0.1, ParameterUnit::Milliseconds),
            float_parameter("hf_damp", "High Frq Damp", None, Some(5000.0), 2000.0, 20000.0, 10.0, ParameterUnit::Hertz),
            float_parameter("room_size", "Room size", None, Some(2.0), 0.0, 5.0, 0.01, ParameterUnit::None),
            float_parameter("diffusion", "Diffusion", None, Some(0.5), 0.0, 1.0, 0.01, ParameterUnit::None),
            float_parameter("amount", "Wet Amount", None, Some(0.25), 0.0, 2.0, 0.01, ParameterUnit::None),
            float_parameter("dry", "Dry Amount", None, Some(1.0), 0.0, 2.0, 0.01, ParameterUnit::None),
            float_parameter("predelay", "Pre Delay", None, Some(0.0), 0.0, 500.0, 1.0, ParameterUnit::Milliseconds),
            float_parameter("bass_cut", "Bass Cut", None, Some(300.0), 20.0, 20000.0, 10.0, ParameterUnit::Hertz),
            float_parameter("treble_cut", "Treble Cut", None, Some(5000.0), 20.0, 20000.0, 10.0, ParameterUnit::Hertz),
        ],
    }
}

fn build(params: &ParameterSet, sample_rate: f32, layout: AudioChannelLayout) -> Result<BlockProcessor> {
    let decay_time = required_f32(params, "decay_time").map_err(anyhow::Error::msg)?;
    let hf_damp = required_f32(params, "hf_damp").map_err(anyhow::Error::msg)?;
    let room_size = required_f32(params, "room_size").map_err(anyhow::Error::msg)?;
    let diffusion = required_f32(params, "diffusion").map_err(anyhow::Error::msg)?;
    let amount = required_f32(params, "amount").map_err(anyhow::Error::msg)?;
    let dry = required_f32(params, "dry").map_err(anyhow::Error::msg)?;
    let predelay = required_f32(params, "predelay").map_err(anyhow::Error::msg)?;
    let bass_cut = required_f32(params, "bass_cut").map_err(anyhow::Error::msg)?;
    let treble_cut = required_f32(params, "treble_cut").map_err(anyhow::Error::msg)?;
    let lib_path = lv2::resolve_lv2_lib(PLUGIN_BINARY)?;
    let bundle_path = lv2::resolve_lv2_bundle(PLUGIN_DIR)?;

    let control_ports: &[(usize, f32)] = &[
        (PORT_CTRL_DECAY_TIME, decay_time),
        (PORT_CTRL_HF_DAMP, hf_damp),
        (PORT_CTRL_ROOM_SIZE, room_size),
        (PORT_CTRL_DIFFUSION, diffusion),
        (PORT_CTRL_AMOUNT, amount),
        (PORT_CTRL_DRY, dry),
        (PORT_CTRL_PREDELAY, predelay),
        (PORT_CTRL_BASS_CUT, bass_cut),
        (PORT_CTRL_TREBLE_CUT, treble_cut),
    ];

    let processor = lv2::build_stereo_lv2_processor(&lib_path, PLUGIN_URI, sample_rate as f64, &bundle_path, &[PORT_AUDIO_IN_IN_L, PORT_AUDIO_IN_IN_R], &[PORT_AUDIO_OUT_OUT_L, PORT_AUDIO_OUT_OUT_R], control_ports)?;
    let _ = layout;
    Ok(BlockProcessor::Stereo(Box::new(processor)))
}

fn schema() -> Result<ModelParameterSchema> { Ok(model_schema()) }

pub const MODEL_DEFINITION: ReverbModelDefinition = ReverbModelDefinition {
    id: MODEL_ID, display_name: DISPLAY_NAME, brand: BRAND,
    backend_kind: ReverbBackendKind::Lv2, schema, build,
    supported_instruments: block_core::ALL_INSTRUMENTS, knob_layout: &[],
};
