// AUTO-GENERATED by tools/lv2_catalog_import — do not edit by hand.
// Re-run the tool to regenerate. Manual customisation goes in overrides.yaml.

#![allow(dead_code, unused_imports, unused_variables, clippy::all)]

use crate::registry::ReverbModelDefinition;
use crate::ReverbBackendKind;
use anyhow::Result;
use block_core::param::{
    bool_parameter, float_parameter, required_bool, required_f32,
    ModelParameterSchema, ParameterSet, ParameterUnit,
};
use block_core::{AudioChannelLayout, BlockProcessor, ModelAudioMode};

pub const MODEL_ID: &str = "lv2_mod_tal_reverb_2";
pub const DISPLAY_NAME: &str = "TAL-Reverb-II";
const BRAND: &str = "kxstudio";

const PLUGIN_URI: &str = "http://moddevices.com/plugins/tal-reverb-2";
const PLUGIN_DIR: &str = "mod-tal-Reverb-2";

#[cfg(target_os = "macos")]
const PLUGIN_BINARY: &str = "TAL-Reverb-2.dylib";
#[cfg(target_os = "linux")]
const PLUGIN_BINARY: &str = "TAL-Reverb-2.so";
#[cfg(target_os = "windows")]
const PLUGIN_BINARY: &str = "TAL-Reverb-2.dll";

// Port indices (from TTL)
const PORT_CTRL_LV2_FREEWHEEL: usize = 0;
const PORT_AUDIO_IN_LV2_AUDIO_IN_1: usize = 1;
const PORT_AUDIO_IN_LV2_AUDIO_IN_2: usize = 2;
const PORT_AUDIO_OUT_LV2_AUDIO_OUT_1: usize = 3;
const PORT_AUDIO_OUT_LV2_AUDIO_OUT_2: usize = 4;
const PORT_CTRL_DRY: usize = 5;
const PORT_CTRL_WET: usize = 6;
const PORT_CTRL_ROOM_SIZE: usize = 7;
const PORT_CTRL_PRE_DELAY: usize = 8;
const PORT_CTRL_LOW_SHELF_FREQUENCY: usize = 9;
const PORT_CTRL_HIGH_SHELF_FREQUENCY: usize = 10;
const PORT_CTRL_PEAK_FREQUENCY: usize = 11;
const PORT_CTRL_LOW_SHELF_GAIN: usize = 12;
const PORT_CTRL_HIGH_SHELF_GAIN: usize = 13;
const PORT_CTRL_PEAK_GAIN: usize = 14;
const PORT_CTRL_STEREO_WIDTH: usize = 15;
const PORT_CTRL_STEREO_INPUT: usize = 16;

pub fn model_schema() -> ModelParameterSchema {
    ModelParameterSchema {
        effect_type: block_core::EFFECT_TYPE_REVERB.into(),
        model: MODEL_ID.into(),
        display_name: DISPLAY_NAME.into(),
        audio_mode: ModelAudioMode::TrueStereo,
        parameters: vec![
            bool_parameter("lv2_freewheel", "Freewheel", None, Some(false)),
            float_parameter("dry", "dry", None, Some(0.0), -96.0, 26.4, 1.0, ParameterUnit::Decibels),
            float_parameter("wet", "wet", None, Some(-24.1), -96.0, 26.4, 1.0, ParameterUnit::Decibels),
            float_parameter("room_size", "room size", None, Some(0.752), 0.0, 1.0, 0.01, ParameterUnit::None),
            float_parameter("pre_delay", "pre delay", None, Some(37.0), 0.0, 1000.0, 10.0, ParameterUnit::Milliseconds),
            float_parameter("low_shelf_frequency", "low frequency", None, Some(257.0), 100.0, 10000.0, 10.0, ParameterUnit::Hertz),
            float_parameter("high_shelf_frequency", "high frequency", None, Some(3039.0), 100.0, 10000.0, 10.0, ParameterUnit::Hertz),
            float_parameter("peak_frequency", "mid frequency", None, Some(2237.0), 100.0, 10000.0, 10.0, ParameterUnit::Hertz),
            float_parameter("low_shelf_gain", "low gain", None, Some(-0.4), -18.0, 0.0, 0.1, ParameterUnit::Decibels),
            float_parameter("high_shelf_gain", "high gain", None, Some(-1.2), -18.0, 0.0, 0.1, ParameterUnit::Decibels),
            float_parameter("peak_gain", "mid gain", None, Some(-1.7), -18.0, 0.0, 0.1, ParameterUnit::Decibels),
            float_parameter("stereo_width", "stereo width", None, Some(1.0), 0.0, 1.0, 0.01, ParameterUnit::None),
            bool_parameter("stereo_input", "stereo input", None, Some(false)),
        ],
    }
}

fn build(params: &ParameterSet, sample_rate: f32, layout: AudioChannelLayout) -> Result<BlockProcessor> {
    let lv2_freewheel = required_bool(params, "lv2_freewheel").map_err(anyhow::Error::msg)?;
    let dry = required_f32(params, "dry").map_err(anyhow::Error::msg)?;
    let wet = required_f32(params, "wet").map_err(anyhow::Error::msg)?;
    let room_size = required_f32(params, "room_size").map_err(anyhow::Error::msg)?;
    let pre_delay = required_f32(params, "pre_delay").map_err(anyhow::Error::msg)?;
    let low_shelf_frequency = required_f32(params, "low_shelf_frequency").map_err(anyhow::Error::msg)?;
    let high_shelf_frequency = required_f32(params, "high_shelf_frequency").map_err(anyhow::Error::msg)?;
    let peak_frequency = required_f32(params, "peak_frequency").map_err(anyhow::Error::msg)?;
    let low_shelf_gain = required_f32(params, "low_shelf_gain").map_err(anyhow::Error::msg)?;
    let high_shelf_gain = required_f32(params, "high_shelf_gain").map_err(anyhow::Error::msg)?;
    let peak_gain = required_f32(params, "peak_gain").map_err(anyhow::Error::msg)?;
    let stereo_width = required_f32(params, "stereo_width").map_err(anyhow::Error::msg)?;
    let stereo_input = required_bool(params, "stereo_input").map_err(anyhow::Error::msg)?;
    let lib_path = lv2::resolve_lv2_lib(PLUGIN_BINARY)?;
    let bundle_path = lv2::resolve_lv2_bundle(PLUGIN_DIR)?;

    let control_ports: &[(usize, f32)] = &[
        (PORT_CTRL_LV2_FREEWHEEL, if lv2_freewheel { 1.0 } else { 0.0 }),
        (PORT_CTRL_DRY, dry),
        (PORT_CTRL_WET, wet),
        (PORT_CTRL_ROOM_SIZE, room_size),
        (PORT_CTRL_PRE_DELAY, pre_delay),
        (PORT_CTRL_LOW_SHELF_FREQUENCY, low_shelf_frequency),
        (PORT_CTRL_HIGH_SHELF_FREQUENCY, high_shelf_frequency),
        (PORT_CTRL_PEAK_FREQUENCY, peak_frequency),
        (PORT_CTRL_LOW_SHELF_GAIN, low_shelf_gain),
        (PORT_CTRL_HIGH_SHELF_GAIN, high_shelf_gain),
        (PORT_CTRL_PEAK_GAIN, peak_gain),
        (PORT_CTRL_STEREO_WIDTH, stereo_width),
        (PORT_CTRL_STEREO_INPUT, if stereo_input { 1.0 } else { 0.0 }),
    ];

    let processor = lv2::build_stereo_lv2_processor(&lib_path, PLUGIN_URI, sample_rate as f64, &bundle_path, &[PORT_AUDIO_IN_LV2_AUDIO_IN_1, PORT_AUDIO_IN_LV2_AUDIO_IN_2], &[PORT_AUDIO_OUT_LV2_AUDIO_OUT_1, PORT_AUDIO_OUT_LV2_AUDIO_OUT_2], control_ports)?;
    let _ = layout;
    Ok(BlockProcessor::Stereo(Box::new(processor)))
}

fn schema() -> Result<ModelParameterSchema> { Ok(model_schema()) }

pub const MODEL_DEFINITION: ReverbModelDefinition = ReverbModelDefinition {
    id: MODEL_ID, display_name: DISPLAY_NAME, brand: BRAND,
    backend_kind: ReverbBackendKind::Lv2, schema, build,
    supported_instruments: block_core::ALL_INSTRUMENTS, knob_layout: &[],
};
