// AUTO-GENERATED by tools/lv2_catalog_import — do not edit by hand.
// Re-run the tool to regenerate. Manual customisation goes in overrides.yaml.

#![allow(dead_code, unused_imports, unused_variables, clippy::approx_constant, clippy::excessive_precision)]

use crate::registry::ReverbModelDefinition;
use crate::ReverbBackendKind;
use anyhow::Result;
use block_core::param::{
    bool_parameter, float_parameter, required_bool, required_f32,
    ModelParameterSchema, ParameterSet, ParameterUnit,
};
use block_core::{AudioChannelLayout, BlockProcessor, ModelAudioMode};

pub const MODEL_ID: &str = "lv2_invada_mono";
pub const DISPLAY_NAME: &str = "Invada Early Reflection Reverb (mono in)";
const BRAND: &str = "invada";

const PLUGIN_URI: &str = "http://invadarecords.com/plugins/lv2/erreverb/mono";
const PLUGIN_DIR: &str = "invada";

#[cfg(target_os = "macos")]
const PLUGIN_BINARY: &str = "plugin.dylib";
#[cfg(target_os = "linux")]
const PLUGIN_BINARY: &str = "plugin.so";
#[cfg(target_os = "windows")]
const PLUGIN_BINARY: &str = "plugin.dll";

// Port indices (from TTL)
const PORT_CTRL_BYPASS: usize = 0;
const PORT_CTRL_ROOM_LENGTH: usize = 1;
const PORT_CTRL_ROOM_WIDTH: usize = 2;
const PORT_CTRL_ROOM_HEIGHT: usize = 3;
const PORT_CTRL_SOURCE_LR: usize = 4;
const PORT_CTRL_SOURCE_FB: usize = 5;
const PORT_CTRL_LIST_LR: usize = 6;
const PORT_CTRL_LIST_FB: usize = 7;
const PORT_CTRL_HPF: usize = 8;
const PORT_CTRL_WARMTH: usize = 9;
const PORT_CTRL_DIFFUSION: usize = 10;
const PORT_AUDIO_OUT_OUT_L: usize = 11;
const PORT_AUDIO_OUT_OUT_R: usize = 12;
const PORT_AUDIO_IN_IN: usize = 13;
const PORT_CTRL_METER_IN: usize = 14;
const PORT_CTRL_METER_OUT_L: usize = 15;
const PORT_CTRL_METER_OUT_R: usize = 16;

pub fn model_schema() -> ModelParameterSchema {
    ModelParameterSchema {
        effect_type: block_core::EFFECT_TYPE_REVERB.into(),
        model: MODEL_ID.into(),
        display_name: DISPLAY_NAME.into(),
        audio_mode: ModelAudioMode::MonoToStereo,
        parameters: vec![
            bool_parameter("bypass", "Bypass", None, Some(false)),
            float_parameter("roomlength", "Room Length", None, Some(25.0), 3.0, 100.0, 0.1, ParameterUnit::None),
            float_parameter("roomwidth", "Room Width", None, Some(30.0), 3.0, 100.0, 0.1, ParameterUnit::None),
            float_parameter("roomheight", "Room Height", None, Some(10.0), 3.0, 30.0, 0.1, ParameterUnit::None),
            float_parameter("sourcelr", "Source Pan", None, Some(-0.01), -1.0, 1.0, 0.01, ParameterUnit::None),
            float_parameter("sourcefb", "Source (F/B)", None, Some(0.8), 0.5, 1.0, 0.001, ParameterUnit::None),
            float_parameter("listlr", "Listener Pan", None, Some(0.01), -1.0, 1.0, 0.01, ParameterUnit::None),
            float_parameter("listfb", "Listener (F/B)", None, Some(0.2), 0.0, 0.5, 0.001, ParameterUnit::None),
            float_parameter("hpf", "HPF", None, Some(1000.0), 20.0, 2000.0, 10.0, ParameterUnit::Hertz),
            float_parameter("warmth", "Warmth", None, Some(50.0), 0.0, 100.0, 1.0, ParameterUnit::Percent),
            float_parameter("diffusion", "Diffusion", None, Some(50.0), 0.0, 100.0, 1.0, ParameterUnit::Percent),
        ],
    }
}

fn build(params: &ParameterSet, sample_rate: f32, layout: AudioChannelLayout) -> Result<BlockProcessor> {
    let bypass = required_bool(params, "bypass").map_err(anyhow::Error::msg)?;
    let roomlength = required_f32(params, "roomlength").map_err(anyhow::Error::msg)?;
    let roomwidth = required_f32(params, "roomwidth").map_err(anyhow::Error::msg)?;
    let roomheight = required_f32(params, "roomheight").map_err(anyhow::Error::msg)?;
    let sourcelr = required_f32(params, "sourcelr").map_err(anyhow::Error::msg)?;
    let sourcefb = required_f32(params, "sourcefb").map_err(anyhow::Error::msg)?;
    let listlr = required_f32(params, "listlr").map_err(anyhow::Error::msg)?;
    let listfb = required_f32(params, "listfb").map_err(anyhow::Error::msg)?;
    let hpf = required_f32(params, "hpf").map_err(anyhow::Error::msg)?;
    let warmth = required_f32(params, "warmth").map_err(anyhow::Error::msg)?;
    let diffusion = required_f32(params, "diffusion").map_err(anyhow::Error::msg)?;
    let lib_path = lv2::resolve_lv2_lib(PLUGIN_BINARY)?;
    let bundle_path = lv2::resolve_lv2_bundle(PLUGIN_DIR)?;

    let control_ports: &[(usize, f32)] = &[
        (PORT_CTRL_BYPASS, if bypass { 1.0 } else { 0.0 }),
        (PORT_CTRL_ROOM_LENGTH, roomlength),
        (PORT_CTRL_ROOM_WIDTH, roomwidth),
        (PORT_CTRL_ROOM_HEIGHT, roomheight),
        (PORT_CTRL_SOURCE_LR, sourcelr),
        (PORT_CTRL_SOURCE_FB, sourcefb),
        (PORT_CTRL_LIST_LR, listlr),
        (PORT_CTRL_LIST_FB, listfb),
        (PORT_CTRL_HPF, hpf),
        (PORT_CTRL_WARMTH, warmth),
        (PORT_CTRL_DIFFUSION, diffusion),
    ];

    let extra_outs: &[usize] = &[PORT_AUDIO_OUT_OUT_R];
    let _ = layout;
    let processor = lv2::build_lv2_processor_with_extras(&lib_path, PLUGIN_URI, sample_rate as f64, &bundle_path, &[PORT_AUDIO_IN_IN], &[PORT_AUDIO_OUT_OUT_L], control_ports, extra_outs)?;
    Ok(BlockProcessor::Mono(Box::new(processor)))
}

fn schema() -> Result<ModelParameterSchema> { Ok(model_schema()) }

pub const MODEL_DEFINITION: ReverbModelDefinition = ReverbModelDefinition {
    id: MODEL_ID, display_name: DISPLAY_NAME, brand: BRAND,
    backend_kind: ReverbBackendKind::Lv2, schema, build,
    supported_instruments: block_core::ALL_INSTRUMENTS, knob_layout: &[],
};
