// AUTO-GENERATED by tools/lv2_catalog_import — do not edit by hand.
// Re-run the tool to regenerate. Manual customisation goes in overrides.yaml.

#![allow(dead_code, unused_imports, unused_variables, clippy::all)]

use crate::registry::ReverbModelDefinition;
use crate::ReverbBackendKind;
use anyhow::Result;
use block_core::param::{
    bool_parameter, float_parameter, required_bool, required_f32,
    ModelParameterSchema, ParameterSet, ParameterUnit,
};
use block_core::{AudioChannelLayout, BlockProcessor, ModelAudioMode};

pub const MODEL_ID: &str = "lv2_lsp_plugins_impulsantworten_impulse_responses_stereo";
pub const DISPLAY_NAME: &str = "LSP Impulse Responses Stereo";
const BRAND: &str = "lsp";

const PLUGIN_URI: &str = "http://lsp-plug.in/plugins/lv2/impulse_responses_stereo";
const PLUGIN_DIR: &str = "lsp-plugins-impulsantworten";

#[cfg(target_os = "macos")]
const PLUGIN_BINARY: &str = "lsp-plugins-lv2.dylib";
#[cfg(target_os = "linux")]
const PLUGIN_BINARY: &str = "lsp-plugins-lv2.so";
#[cfg(target_os = "windows")]
const PLUGIN_BINARY: &str = "lsp-plugins-lv2.dll";

// Port indices (from TTL)
const PORT_AUDIO_IN_IN_L: usize = 0;
const PORT_AUDIO_IN_IN_R: usize = 1;
const PORT_AUDIO_OUT_OUT_L: usize = 2;
const PORT_AUDIO_OUT_OUT_R: usize = 3;
const PORT_CTRL_ENABLED: usize = 4;
const PORT_CTRL_FFT: usize = 5;
const PORT_CTRL_DRY: usize = 6;
const PORT_CTRL_WET: usize = 7;
const PORT_CTRL_G_OUT: usize = 8;
const PORT_CTRL_FSEL: usize = 9;
const PORT_CTRL_IHC0: usize = 10;
const PORT_CTRL_ITC0: usize = 11;
const PORT_CTRL_IFI0: usize = 12;
const PORT_CTRL_IFO0: usize = 13;
const PORT_CTRL_ILS0: usize = 14;
const PORT_CTRL_IFS0: usize = 15;
const PORT_CTRL_IFL0: usize = 16;
const PORT_CTRL_IHC1: usize = 17;
const PORT_CTRL_ITC1: usize = 18;
const PORT_CTRL_IFI1: usize = 19;
const PORT_CTRL_IFO1: usize = 20;
const PORT_CTRL_ILS1: usize = 21;
const PORT_CTRL_IFS1: usize = 22;
const PORT_CTRL_IFL1: usize = 23;
const PORT_CTRL_CS_L: usize = 24;
const PORT_CTRL_MK_L: usize = 25;
const PORT_CTRL_CA_L: usize = 26;
const PORT_CTRL_PD_L: usize = 27;
const PORT_CTRL_CS_R: usize = 28;
const PORT_CTRL_MK_R: usize = 29;
const PORT_CTRL_CA_R: usize = 30;
const PORT_CTRL_PD_R: usize = 31;
const PORT_CTRL_WPP: usize = 32;
const PORT_CTRL_EQV: usize = 33;
const PORT_CTRL_LCM: usize = 34;
const PORT_CTRL_LCF: usize = 35;
const PORT_CTRL_EQ_0: usize = 36;
const PORT_CTRL_EQ_1: usize = 37;
const PORT_CTRL_EQ_2: usize = 38;
const PORT_CTRL_EQ_3: usize = 39;
const PORT_CTRL_EQ_4: usize = 40;
const PORT_CTRL_EQ_5: usize = 41;
const PORT_CTRL_EQ_6: usize = 42;
const PORT_CTRL_EQ_7: usize = 43;
const PORT_CTRL_HCM: usize = 44;
const PORT_CTRL_HCF: usize = 45;
const PORT_ATOM_IN_IN_UI: usize = 46;
const PORT_ATOM_OUT_OUT_UI: usize = 47;
const PORT_CTRL_OUT_LATENCY: usize = 48;

pub fn model_schema() -> ModelParameterSchema {
    ModelParameterSchema {
        effect_type: block_core::EFFECT_TYPE_REVERB.into(),
        model: MODEL_ID.into(),
        display_name: DISPLAY_NAME.into(),
        audio_mode: ModelAudioMode::TrueStereo,
        parameters: vec![
            bool_parameter("enabled", "Enabled", None, Some(true)),
            float_parameter("fft", "FFT size", None, Some(4.0), 0.0, 7.0, 0.01, ParameterUnit::None),
            float_parameter("dry", "Dry amount", None, Some(1.0), 0.01, 10.0, 0.01, ParameterUnit::None),
            float_parameter("wet", "Wet amount", None, Some(0.5), 0.01, 10.0, 0.01, ParameterUnit::None),
            float_parameter("g_out", "Output gain", None, Some(1.0), 0.01, 1000.0, 1.0, ParameterUnit::None),
            float_parameter("fsel", "File selector", None, Some(0.0), 0.0, 1.0, 0.01, ParameterUnit::None),
            float_parameter("ihc0", "Head cut 1", None, Some(0.0), 0.0, 10000.0, 10.0, ParameterUnit::Milliseconds),
            float_parameter("itc0", "Tail cut 1", None, Some(0.0), 0.0, 10000.0, 10.0, ParameterUnit::Milliseconds),
            float_parameter("ifi0", "Fade in 1", None, Some(0.0), 0.0, 10000.0, 10.0, ParameterUnit::Milliseconds),
            float_parameter("ifo0", "Fade out 1", None, Some(0.0), 0.0, 10000.0, 10.0, ParameterUnit::Milliseconds),
            bool_parameter("ils0", "Impulse listen 1", None, Some(false)),
            float_parameter("ihc1", "Head cut 2", None, Some(0.0), 0.0, 10000.0, 10.0, ParameterUnit::Milliseconds),
            float_parameter("itc1", "Tail cut 2", None, Some(0.0), 0.0, 10000.0, 10.0, ParameterUnit::Milliseconds),
            float_parameter("ifi1", "Fade in 2", None, Some(0.0), 0.0, 10000.0, 10.0, ParameterUnit::Milliseconds),
            float_parameter("ifo1", "Fade out 2", None, Some(0.0), 0.0, 10000.0, 10.0, ParameterUnit::Milliseconds),
            bool_parameter("ils1", "Impulse listen 2", None, Some(false)),
            float_parameter("cs_l", "Channel source Left", None, Some(1.0), 0.0, 4.0, 0.01, ParameterUnit::None),
            float_parameter("mk_l", "Makeup gain Left", None, Some(1.0), 0.01, 100.0, 0.1, ParameterUnit::None),
            float_parameter("pd_l", "Pre-delay Left", None, Some(0.0), 0.0, 100.0, 1.0, ParameterUnit::Milliseconds),
            float_parameter("cs_r", "Channel source Right", None, Some(2.0), 0.0, 4.0, 0.01, ParameterUnit::None),
            float_parameter("mk_r", "Makeup gain Right", None, Some(1.0), 0.01, 100.0, 0.1, ParameterUnit::None),
            float_parameter("pd_r", "Pre-delay Right", None, Some(0.0), 0.0, 100.0, 1.0, ParameterUnit::Milliseconds),
            bool_parameter("wpp", "Wet post-process", None, Some(false)),
            bool_parameter("eqv", "Equalizer visibility", None, Some(false)),
            float_parameter("lcm", "Low-cut mode", None, Some(0.0), 0.0, 3.0, 0.01, ParameterUnit::None),
            float_parameter("lcf", "Low-cut frequency", None, Some(50.0), 10.0, 1000.0, 1.0, ParameterUnit::Hertz),
            float_parameter("eq_0", "Band 50Hz gain", None, Some(1.0), 0.25119, 3.98107, 0.01, ParameterUnit::None),
            float_parameter("eq_1", "Band 107Hz gain", None, Some(1.0), 0.25119, 3.98107, 0.01, ParameterUnit::None),
            float_parameter("eq_2", "Band 227Hz gain", None, Some(1.0), 0.25119, 3.98107, 0.01, ParameterUnit::None),
            float_parameter("eq_3", "Band 484Hz gain", None, Some(1.0), 0.25119, 3.98107, 0.01, ParameterUnit::None),
            float_parameter("eq_4", "Band 1 kHz gain", None, Some(1.0), 0.25119, 3.98107, 0.01, ParameterUnit::None),
            float_parameter("eq_5", "Band 2.2 kHz gain", None, Some(1.0), 0.25119, 3.98107, 0.01, ParameterUnit::None),
            float_parameter("eq_6", "Band 4.7 kHz gain", None, Some(1.0), 0.25119, 3.98107, 0.01, ParameterUnit::None),
            float_parameter("eq_7", "Band 10 kHz gain", None, Some(1.0), 0.25119, 3.98107, 0.01, ParameterUnit::None),
            float_parameter("hcm", "High-cut mode", None, Some(0.0), 0.0, 3.0, 0.01, ParameterUnit::None),
            float_parameter("hcf", "High-cut frequency", None, Some(10000.0), 2000.0, 22000.0, 10.0, ParameterUnit::Hertz),
        ],
    }
}

fn build(params: &ParameterSet, sample_rate: f32, layout: AudioChannelLayout) -> Result<BlockProcessor> {
    let enabled = required_bool(params, "enabled").map_err(anyhow::Error::msg)?;
    let fft = required_f32(params, "fft").map_err(anyhow::Error::msg)?;
    let dry = required_f32(params, "dry").map_err(anyhow::Error::msg)?;
    let wet = required_f32(params, "wet").map_err(anyhow::Error::msg)?;
    let g_out = required_f32(params, "g_out").map_err(anyhow::Error::msg)?;
    let fsel = required_f32(params, "fsel").map_err(anyhow::Error::msg)?;
    let ihc0 = required_f32(params, "ihc0").map_err(anyhow::Error::msg)?;
    let itc0 = required_f32(params, "itc0").map_err(anyhow::Error::msg)?;
    let ifi0 = required_f32(params, "ifi0").map_err(anyhow::Error::msg)?;
    let ifo0 = required_f32(params, "ifo0").map_err(anyhow::Error::msg)?;
    let ils0 = required_bool(params, "ils0").map_err(anyhow::Error::msg)?;
    let ihc1 = required_f32(params, "ihc1").map_err(anyhow::Error::msg)?;
    let itc1 = required_f32(params, "itc1").map_err(anyhow::Error::msg)?;
    let ifi1 = required_f32(params, "ifi1").map_err(anyhow::Error::msg)?;
    let ifo1 = required_f32(params, "ifo1").map_err(anyhow::Error::msg)?;
    let ils1 = required_bool(params, "ils1").map_err(anyhow::Error::msg)?;
    let cs_l = required_f32(params, "cs_l").map_err(anyhow::Error::msg)?;
    let mk_l = required_f32(params, "mk_l").map_err(anyhow::Error::msg)?;
    let pd_l = required_f32(params, "pd_l").map_err(anyhow::Error::msg)?;
    let cs_r = required_f32(params, "cs_r").map_err(anyhow::Error::msg)?;
    let mk_r = required_f32(params, "mk_r").map_err(anyhow::Error::msg)?;
    let pd_r = required_f32(params, "pd_r").map_err(anyhow::Error::msg)?;
    let wpp = required_bool(params, "wpp").map_err(anyhow::Error::msg)?;
    let eqv = required_bool(params, "eqv").map_err(anyhow::Error::msg)?;
    let lcm = required_f32(params, "lcm").map_err(anyhow::Error::msg)?;
    let lcf = required_f32(params, "lcf").map_err(anyhow::Error::msg)?;
    let eq_0 = required_f32(params, "eq_0").map_err(anyhow::Error::msg)?;
    let eq_1 = required_f32(params, "eq_1").map_err(anyhow::Error::msg)?;
    let eq_2 = required_f32(params, "eq_2").map_err(anyhow::Error::msg)?;
    let eq_3 = required_f32(params, "eq_3").map_err(anyhow::Error::msg)?;
    let eq_4 = required_f32(params, "eq_4").map_err(anyhow::Error::msg)?;
    let eq_5 = required_f32(params, "eq_5").map_err(anyhow::Error::msg)?;
    let eq_6 = required_f32(params, "eq_6").map_err(anyhow::Error::msg)?;
    let eq_7 = required_f32(params, "eq_7").map_err(anyhow::Error::msg)?;
    let hcm = required_f32(params, "hcm").map_err(anyhow::Error::msg)?;
    let hcf = required_f32(params, "hcf").map_err(anyhow::Error::msg)?;
    let lib_path = lv2::resolve_lv2_lib(PLUGIN_BINARY)?;
    let bundle_path = lv2::resolve_lv2_bundle(PLUGIN_DIR)?;

    let control_ports: &[(usize, f32)] = &[
        (PORT_CTRL_ENABLED, if enabled { 1.0 } else { 0.0 }),
        (PORT_CTRL_FFT, fft),
        (PORT_CTRL_DRY, dry),
        (PORT_CTRL_WET, wet),
        (PORT_CTRL_G_OUT, g_out),
        (PORT_CTRL_FSEL, fsel),
        (PORT_CTRL_IHC0, ihc0),
        (PORT_CTRL_ITC0, itc0),
        (PORT_CTRL_IFI0, ifi0),
        (PORT_CTRL_IFO0, ifo0),
        (PORT_CTRL_ILS0, if ils0 { 1.0 } else { 0.0 }),
        (PORT_CTRL_IHC1, ihc1),
        (PORT_CTRL_ITC1, itc1),
        (PORT_CTRL_IFI1, ifi1),
        (PORT_CTRL_IFO1, ifo1),
        (PORT_CTRL_ILS1, if ils1 { 1.0 } else { 0.0 }),
        (PORT_CTRL_CS_L, cs_l),
        (PORT_CTRL_MK_L, mk_l),
        (PORT_CTRL_PD_L, pd_l),
        (PORT_CTRL_CS_R, cs_r),
        (PORT_CTRL_MK_R, mk_r),
        (PORT_CTRL_PD_R, pd_r),
        (PORT_CTRL_WPP, if wpp { 1.0 } else { 0.0 }),
        (PORT_CTRL_EQV, if eqv { 1.0 } else { 0.0 }),
        (PORT_CTRL_LCM, lcm),
        (PORT_CTRL_LCF, lcf),
        (PORT_CTRL_EQ_0, eq_0),
        (PORT_CTRL_EQ_1, eq_1),
        (PORT_CTRL_EQ_2, eq_2),
        (PORT_CTRL_EQ_3, eq_3),
        (PORT_CTRL_EQ_4, eq_4),
        (PORT_CTRL_EQ_5, eq_5),
        (PORT_CTRL_EQ_6, eq_6),
        (PORT_CTRL_EQ_7, eq_7),
        (PORT_CTRL_HCM, hcm),
        (PORT_CTRL_HCF, hcf),
    ];

    let processor = lv2::build_stereo_lv2_processor(&lib_path, PLUGIN_URI, sample_rate as f64, &bundle_path, &[PORT_AUDIO_IN_IN_L, PORT_AUDIO_IN_IN_R], &[PORT_AUDIO_OUT_OUT_L, PORT_AUDIO_OUT_OUT_R], control_ports)?;
    let _ = layout;
    Ok(BlockProcessor::Stereo(Box::new(processor)))
}

fn schema() -> Result<ModelParameterSchema> { Ok(model_schema()) }

pub const MODEL_DEFINITION: ReverbModelDefinition = ReverbModelDefinition {
    id: MODEL_ID, display_name: DISPLAY_NAME, brand: BRAND,
    backend_kind: ReverbBackendKind::Lv2, schema, build,
    supported_instruments: block_core::ALL_INSTRUMENTS, knob_layout: &[],
};
