// AUTO-GENERATED by tools/lv2_catalog_import — do not edit by hand.
// Re-run the tool to regenerate. Manual customisation goes in overrides.yaml.

#![allow(dead_code, unused_imports, unused_variables, clippy::approx_constant, clippy::excessive_precision)]

use crate::registry::ReverbModelDefinition;
use crate::ReverbBackendKind;
use anyhow::Result;
use block_core::param::{
    float_parameter, required_f32, ModelParameterSchema, ParameterSet, ParameterUnit,
};
use block_core::{AudioChannelLayout, BlockProcessor, ModelAudioMode};

pub const MODEL_ID: &str = "lv2_fomp_reverb";
pub const DISPLAY_NAME: &str = "reverb";
const BRAND: &str = "fomp";

const PLUGIN_URI: &str = "http://drobilla.net/plugins/fomp/reverb";
const PLUGIN_DIR: &str = "fomp";

#[cfg(target_os = "macos")]
const PLUGIN_BINARY: &str = "reverbs.dylib";
#[cfg(target_os = "linux")]
const PLUGIN_BINARY: &str = "reverbs.so";
#[cfg(target_os = "windows")]
const PLUGIN_BINARY: &str = "reverbs.dll";

// Port indices (from TTL)
const PORT_AUDIO_IN_IN_L: usize = 0;
const PORT_AUDIO_IN_IN_R: usize = 1;
const PORT_AUDIO_OUT_OUT_L: usize = 2;
const PORT_AUDIO_OUT_OUT_R: usize = 3;
const PORT_CTRL_DELAY: usize = 4;
const PORT_CTRL_XOVER: usize = 5;
const PORT_CTRL_RT_LOW: usize = 6;
const PORT_CTRL_RT_MID: usize = 7;
const PORT_CTRL_DAMPING: usize = 8;
const PORT_CTRL_F1_FREQ: usize = 9;
const PORT_CTRL_F1_GAIN: usize = 10;
const PORT_CTRL_F2_FREQ: usize = 11;
const PORT_CTRL_F2_GAIN: usize = 12;
const PORT_CTRL_OUT_MIX: usize = 13;

pub fn model_schema() -> ModelParameterSchema {
    ModelParameterSchema {
        effect_type: block_core::EFFECT_TYPE_REVERB.into(),
        model: MODEL_ID.into(),
        display_name: DISPLAY_NAME.into(),
        audio_mode: ModelAudioMode::TrueStereo,
        parameters: vec![
            float_parameter("delay", "Delay", None, Some(0.06), 0.02, 0.1, 0.001, ParameterUnit::None),
            float_parameter("xover", "Xover", None, Some(223.607), 50.0, 1000.0, 1.0, ParameterUnit::None),
            float_parameter("rt_low", "RT-low", None, Some(2.75), 1.0, 8.0, 0.01, ParameterUnit::None),
            float_parameter("rt_mid", "RT-mid", None, Some(2.75), 1.0, 8.0, 0.01, ParameterUnit::None),
            float_parameter("damping", "Damping", None, Some(6000.0), 1500.0, 24000.0, 10.0, ParameterUnit::None),
            float_parameter("f1_freq", "F1-freq", None, Some(159.054), 40.0, 10000.0, 10.0, ParameterUnit::None),
            float_parameter("f1_gain", "F1-gain", None, Some(0.0), -20.0, 20.0, 0.1, ParameterUnit::None),
            float_parameter("f2_freq", "F2-freq", None, Some(2514.87), 40.0, 10000.0, 10.0, ParameterUnit::None),
            float_parameter("f2_gain", "F2-gain", None, Some(0.0), -20.0, 20.0, 0.1, ParameterUnit::None),
            float_parameter("out_mix", "Output mix", None, Some(0.5), 0.0, 1.0, 0.01, ParameterUnit::None),
        ],
    }
}

fn build(params: &ParameterSet, sample_rate: f32, layout: AudioChannelLayout) -> Result<BlockProcessor> {
    let delay = required_f32(params, "delay").map_err(anyhow::Error::msg)?;
    let xover = required_f32(params, "xover").map_err(anyhow::Error::msg)?;
    let rt_low = required_f32(params, "rt_low").map_err(anyhow::Error::msg)?;
    let rt_mid = required_f32(params, "rt_mid").map_err(anyhow::Error::msg)?;
    let damping = required_f32(params, "damping").map_err(anyhow::Error::msg)?;
    let f1_freq = required_f32(params, "f1_freq").map_err(anyhow::Error::msg)?;
    let f1_gain = required_f32(params, "f1_gain").map_err(anyhow::Error::msg)?;
    let f2_freq = required_f32(params, "f2_freq").map_err(anyhow::Error::msg)?;
    let f2_gain = required_f32(params, "f2_gain").map_err(anyhow::Error::msg)?;
    let out_mix = required_f32(params, "out_mix").map_err(anyhow::Error::msg)?;
    let lib_path = lv2::resolve_lv2_lib(PLUGIN_BINARY)?;
    let bundle_path = lv2::resolve_lv2_bundle(PLUGIN_DIR)?;

    let control_ports: &[(usize, f32)] = &[
        (PORT_CTRL_DELAY, delay),
        (PORT_CTRL_XOVER, xover),
        (PORT_CTRL_RT_LOW, rt_low),
        (PORT_CTRL_RT_MID, rt_mid),
        (PORT_CTRL_DAMPING, damping),
        (PORT_CTRL_F1_FREQ, f1_freq),
        (PORT_CTRL_F1_GAIN, f1_gain),
        (PORT_CTRL_F2_FREQ, f2_freq),
        (PORT_CTRL_F2_GAIN, f2_gain),
        (PORT_CTRL_OUT_MIX, out_mix),
    ];

    let processor = lv2::build_stereo_lv2_processor(&lib_path, PLUGIN_URI, sample_rate as f64, &bundle_path, &[PORT_AUDIO_IN_IN_L, PORT_AUDIO_IN_IN_R], &[PORT_AUDIO_OUT_OUT_L, PORT_AUDIO_OUT_OUT_R], control_ports)?;
    let _ = layout;
    Ok(BlockProcessor::Stereo(Box::new(processor)))
}

fn schema() -> Result<ModelParameterSchema> { Ok(model_schema()) }

pub const MODEL_DEFINITION: ReverbModelDefinition = ReverbModelDefinition {
    id: MODEL_ID, display_name: DISPLAY_NAME, brand: BRAND,
    backend_kind: ReverbBackendKind::Lv2, schema, build,
    supported_instruments: block_core::ALL_INSTRUMENTS, knob_layout: &[],
};
