// AUTO-GENERATED by tools/lv2_catalog_import — do not edit by hand.
// Re-run the tool to regenerate. Manual customisation goes in overrides.yaml.

#![allow(dead_code, unused_imports, unused_variables, clippy::all)]

use crate::registry::ReverbModelDefinition;
use crate::ReverbBackendKind;
use anyhow::Result;
use block_core::param::{
    float_parameter, required_f32, ModelParameterSchema, ParameterSet, ParameterUnit,
};
use block_core::{AudioChannelLayout, BlockProcessor, ModelAudioMode};

pub const MODEL_ID: &str = "lv2_airwindows_star_child_starchild";
pub const DISPLAY_NAME: &str = "StarChild";
const BRAND: &str = "airwindows";

const PLUGIN_URI: &str = "https://hannesbraun.net/ns/lv2/airwindows/starchild";
const PLUGIN_DIR: &str = "Airwindows-StarChild";

#[cfg(target_os = "macos")]
const PLUGIN_BINARY: &str = "StarChild.dylib";
#[cfg(target_os = "linux")]
const PLUGIN_BINARY: &str = "StarChild.so";
#[cfg(target_os = "windows")]
const PLUGIN_BINARY: &str = "StarChild.dll";

// Port indices (from TTL)
const PORT_AUDIO_IN_IN_L: usize = 0;
const PORT_AUDIO_IN_IN_R: usize = 1;
const PORT_AUDIO_OUT_OUT_L: usize = 2;
const PORT_AUDIO_OUT_OUT_R: usize = 3;
const PORT_CTRL_SUSTAIN: usize = 4;
const PORT_CTRL_GRAIN: usize = 5;
const PORT_CTRL_DRYWET: usize = 6;

pub fn model_schema() -> ModelParameterSchema {
    ModelParameterSchema {
        effect_type: block_core::EFFECT_TYPE_REVERB.into(),
        model: MODEL_ID.into(),
        display_name: DISPLAY_NAME.into(),
        audio_mode: ModelAudioMode::TrueStereo,
        parameters: vec![
            float_parameter("sustain", "Sustain", None, Some(1.0), 0.0, 1.0, 0.01, ParameterUnit::None),
            float_parameter("grain", "Grain", None, Some(0.7), 0.0, 1.0, 0.01, ParameterUnit::None),
            float_parameter("drywet", "Dry/Wet", None, Some(0.2), 0.0, 1.0, 0.01, ParameterUnit::None),
        ],
    }
}

fn build(params: &ParameterSet, sample_rate: f32, layout: AudioChannelLayout) -> Result<BlockProcessor> {
    let sustain = required_f32(params, "sustain").map_err(anyhow::Error::msg)?;
    let grain = required_f32(params, "grain").map_err(anyhow::Error::msg)?;
    let drywet = required_f32(params, "drywet").map_err(anyhow::Error::msg)?;
    let lib_path = lv2::resolve_lv2_lib(PLUGIN_BINARY)?;
    let bundle_path = lv2::resolve_lv2_bundle(PLUGIN_DIR)?;

    let control_ports: &[(usize, f32)] = &[
        (PORT_CTRL_SUSTAIN, sustain),
        (PORT_CTRL_GRAIN, grain),
        (PORT_CTRL_DRYWET, drywet),
    ];

    let processor = lv2::build_stereo_lv2_processor(&lib_path, PLUGIN_URI, sample_rate as f64, &bundle_path, &[PORT_AUDIO_IN_IN_L, PORT_AUDIO_IN_IN_R], &[PORT_AUDIO_OUT_OUT_L, PORT_AUDIO_OUT_OUT_R], control_ports)?;
    let _ = layout;
    Ok(BlockProcessor::Stereo(Box::new(processor)))
}

fn schema() -> Result<ModelParameterSchema> { Ok(model_schema()) }

pub const MODEL_DEFINITION: ReverbModelDefinition = ReverbModelDefinition {
    id: MODEL_ID, display_name: DISPLAY_NAME, brand: BRAND,
    backend_kind: ReverbBackendKind::Lv2, schema, build,
    supported_instruments: block_core::ALL_INSTRUMENTS, knob_layout: &[],
};
