// AUTO-GENERATED by tools/lv2_catalog_import — do not edit by hand.
// Re-run the tool to regenerate. Manual customisation goes in overrides.yaml.

#![allow(dead_code, unused_imports, unused_variables, clippy::all)]

use crate::registry::ReverbModelDefinition;
use crate::ReverbBackendKind;
use anyhow::Result;
use block_core::param::{
    bool_parameter, float_parameter, required_bool, required_f32,
    ModelParameterSchema, ParameterSet, ParameterUnit,
};
use block_core::{AudioChannelLayout, BlockProcessor, ModelAudioMode, MonoProcessor, StereoProcessor};

pub const MODEL_ID: &str = "lv2_zeroconvo_cfg_mono";
pub const DISPLAY_NAME: &str = "x42 - IR Convolver Mono";
const BRAND: &str = "x42";

const PLUGIN_URI: &str = "http://gareus.org/oss/lv2/zeroconvolv#CfgMono";
const PLUGIN_DIR: &str = "zeroconvo";
pub const THUMBNAIL_PATH: Option<&str> = Some(".plugins/lv2/zeroconvo.lv2/modgui/thumbnail-mono.png");

#[cfg(target_os = "macos")]
const PLUGIN_BINARY: &str = "zeroconvolv.dylib";
#[cfg(target_os = "linux")]
const PLUGIN_BINARY: &str = "zeroconvolv.so";
#[cfg(target_os = "windows")]
const PLUGIN_BINARY: &str = "zeroconvolv.dll";

// Port indices (from TTL)
const PORT_ATOM_IN_CONTROL: usize = 0;
const PORT_ATOM_OUT_NOTIFY: usize = 1;
const PORT_CTRL_DRY: usize = 2;
const PORT_CTRL_WET: usize = 3;
const PORT_CTRL_ENABLE: usize = 4;
const PORT_CTRL_LATENCY: usize = 5;
const PORT_AUDIO_OUT_OUT: usize = 6;
const PORT_AUDIO_IN_IN: usize = 7;

pub fn model_schema() -> ModelParameterSchema {
    ModelParameterSchema {
        effect_type: block_core::EFFECT_TYPE_REVERB.into(),
        model: MODEL_ID.into(),
        display_name: DISPLAY_NAME.into(),
        audio_mode: ModelAudioMode::DualMono,
        parameters: vec![
            float_parameter("dry", "Dry Signal Level", None, Some(-60.0), -60.0, 6.0, 0.1, ParameterUnit::Decibels),
            float_parameter("wet", "Wet Signal Level", None, Some(-30.0), -60.0, 6.0, 0.1, ParameterUnit::Decibels),
            bool_parameter("enable", "Enable", None, Some(true)),
        ],
    }
}

fn build(params: &ParameterSet, sample_rate: f32, layout: AudioChannelLayout) -> Result<BlockProcessor> {
    let dry = required_f32(params, "dry").map_err(anyhow::Error::msg)?;
    let wet = required_f32(params, "wet").map_err(anyhow::Error::msg)?;
    let enable = required_bool(params, "enable").map_err(anyhow::Error::msg)?;
    let lib_path = lv2::resolve_lv2_lib(PLUGIN_BINARY)?;
    let bundle_path = lv2::resolve_lv2_bundle(PLUGIN_DIR)?;

    let control_ports: &[(usize, f32)] = &[
        (PORT_CTRL_DRY, dry),
        (PORT_CTRL_WET, wet),
        (PORT_CTRL_ENABLE, if enable { 1.0 } else { 0.0 }),
    ];

    match layout {
        AudioChannelLayout::Mono => {
            let processor = lv2::build_lv2_processor(&lib_path, PLUGIN_URI, sample_rate as f64, &bundle_path, &[PORT_AUDIO_IN_IN], &[PORT_AUDIO_OUT_OUT], control_ports)?;
            Ok(BlockProcessor::Mono(Box::new(processor)))
        }
        AudioChannelLayout::Stereo => {
            let left = lv2::build_lv2_processor(&lib_path, PLUGIN_URI, sample_rate as f64, &bundle_path, &[PORT_AUDIO_IN_IN], &[PORT_AUDIO_OUT_OUT], control_ports)?;
            let right = lv2::build_lv2_processor(&lib_path, PLUGIN_URI, sample_rate as f64, &bundle_path, &[PORT_AUDIO_IN_IN], &[PORT_AUDIO_OUT_OUT], control_ports)?;
            Ok(BlockProcessor::Stereo(Box::new(DualMonoProcessor { left, right })))
        }
    }
}

struct DualMonoProcessor { left: lv2::Lv2Processor, right: lv2::Lv2Processor }
impl StereoProcessor for DualMonoProcessor {
    fn process_frame(&mut self, input: [f32; 2]) -> [f32; 2] {
        [self.left.process_sample(input[0]), self.right.process_sample(input[1])]
    }
}

fn schema() -> Result<ModelParameterSchema> { Ok(model_schema()) }

pub const MODEL_DEFINITION: ReverbModelDefinition = ReverbModelDefinition {
    id: MODEL_ID, display_name: DISPLAY_NAME, brand: BRAND,
    backend_kind: ReverbBackendKind::Lv2, schema, build,
    supported_instruments: block_core::ALL_INSTRUMENTS, knob_layout: &[],
};
