// AUTO-GENERATED by tools/lv2_catalog_import — do not edit by hand.
// Re-run the tool to regenerate. Manual customisation goes in overrides.yaml.

#![allow(dead_code, unused_imports, unused_variables, clippy::approx_constant, clippy::excessive_precision)]

use crate::registry::ReverbModelDefinition;
use crate::ReverbBackendKind;
use anyhow::Result;
use block_core::param::{
    bool_parameter, float_parameter, required_bool, required_f32,
    ModelParameterSchema, ParameterSet, ParameterUnit,
};
use block_core::{AudioChannelLayout, BlockProcessor, ModelAudioMode};

pub const MODEL_ID: &str = "lv2_mod_convolution_loader";
pub const DISPLAY_NAME: &str = "Convolution Loader";
const BRAND: &str = "mod";

const PLUGIN_URI: &str = "https://mod.audio/plugins/ConvolutionLoader";
const PLUGIN_DIR: &str = "MOD-ConvolutionLoader";

#[cfg(target_os = "macos")]
const PLUGIN_BINARY: &str = "MOD-ConvolutionLoader_dsp.dylib";
#[cfg(target_os = "linux")]
const PLUGIN_BINARY: &str = "MOD-ConvolutionLoader_dsp.so";
#[cfg(target_os = "windows")]
const PLUGIN_BINARY: &str = "MOD-ConvolutionLoader_dsp.dll";

// Port indices (from TTL)
const PORT_AUDIO_IN_LV2_AUDIO_IN_1: usize = 0;
const PORT_AUDIO_IN_LV2_AUDIO_IN_2: usize = 1;
const PORT_AUDIO_OUT_LV2_AUDIO_OUT_1: usize = 2;
const PORT_AUDIO_OUT_LV2_AUDIO_OUT_2: usize = 3;
const PORT_ATOM_IN_LV2_EVENTS_IN: usize = 4;
const PORT_ATOM_OUT_LV2_EVENTS_OUT: usize = 5;
const PORT_CTRL_DRYLEVEL: usize = 6;
const PORT_CTRL_WETLEVEL: usize = 7;
const PORT_CTRL_HPF: usize = 8;
const PORT_CTRL_TRAILS: usize = 9;
const PORT_CTRL_LV2_ENABLED: usize = 10;
const PORT_CTRL_BUFFERED: usize = 11;

pub fn model_schema() -> ModelParameterSchema {
    ModelParameterSchema {
        effect_type: block_core::EFFECT_TYPE_REVERB.into(),
        model: MODEL_ID.into(),
        display_name: DISPLAY_NAME.into(),
        audio_mode: ModelAudioMode::TrueStereo,
        parameters: vec![
            float_parameter("drylevel", "Dry Level", None, Some(0.0), -60.0, 0.0, 0.1, ParameterUnit::Decibels),
            float_parameter("wetlevel", "Wet Level", None, Some(-30.0), -60.0, 0.0, 0.1, ParameterUnit::Decibels),
            float_parameter("hpf", "High Pass Filter", None, Some(0.0), 0.0, 500.0, 1.0, ParameterUnit::Hertz),
            bool_parameter("trails", "Trails", None, Some(true)),
            bool_parameter("lv2_enabled", "Enabled", None, Some(true)),
            bool_parameter("buffered", "Buffered", None, Some(false)),
        ],
    }
}

fn build(params: &ParameterSet, sample_rate: f32, layout: AudioChannelLayout) -> Result<BlockProcessor> {
    let drylevel = required_f32(params, "drylevel").map_err(anyhow::Error::msg)?;
    let wetlevel = required_f32(params, "wetlevel").map_err(anyhow::Error::msg)?;
    let hpf = required_f32(params, "hpf").map_err(anyhow::Error::msg)?;
    let trails = required_bool(params, "trails").map_err(anyhow::Error::msg)?;
    let lv2_enabled = required_bool(params, "lv2_enabled").map_err(anyhow::Error::msg)?;
    let buffered = required_bool(params, "buffered").map_err(anyhow::Error::msg)?;
    let lib_path = lv2::resolve_lv2_lib(PLUGIN_BINARY)?;
    let bundle_path = lv2::resolve_lv2_bundle(PLUGIN_DIR)?;

    let control_ports: &[(usize, f32)] = &[
        (PORT_CTRL_DRYLEVEL, drylevel),
        (PORT_CTRL_WETLEVEL, wetlevel),
        (PORT_CTRL_HPF, hpf),
        (PORT_CTRL_TRAILS, if trails { 1.0 } else { 0.0 }),
        (PORT_CTRL_LV2_ENABLED, if lv2_enabled { 1.0 } else { 0.0 }),
        (PORT_CTRL_BUFFERED, if buffered { 1.0 } else { 0.0 }),
    ];

    let processor = lv2::build_stereo_lv2_processor(&lib_path, PLUGIN_URI, sample_rate as f64, &bundle_path, &[PORT_AUDIO_IN_LV2_AUDIO_IN_1, PORT_AUDIO_IN_LV2_AUDIO_IN_2], &[PORT_AUDIO_OUT_LV2_AUDIO_OUT_1, PORT_AUDIO_OUT_LV2_AUDIO_OUT_2], control_ports)?;
    let _ = layout;
    Ok(BlockProcessor::Stereo(Box::new(processor)))
}

fn schema() -> Result<ModelParameterSchema> { Ok(model_schema()) }

pub const MODEL_DEFINITION: ReverbModelDefinition = ReverbModelDefinition {
    id: MODEL_ID, display_name: DISPLAY_NAME, brand: BRAND,
    backend_kind: ReverbBackendKind::Lv2, schema, build,
    supported_instruments: block_core::ALL_INSTRUMENTS, knob_layout: &[],
};
