// AUTO-GENERATED by tools/lv2_catalog_import — do not edit by hand.
// Re-run the tool to regenerate. Manual customisation goes in overrides.yaml.

#![allow(dead_code, unused_imports, unused_variables, clippy::approx_constant, clippy::excessive_precision)]

use crate::registry::ReverbModelDefinition;
use crate::ReverbBackendKind;
use anyhow::Result;
use block_core::param::{
    float_parameter, required_f32, ModelParameterSchema, ParameterSet, ParameterUnit,
};
use block_core::{AudioChannelLayout, BlockProcessor, ModelAudioMode};

pub const MODEL_ID: &str = "lv2_artyfx_roomy";
pub const DISPLAY_NAME: &str = "Roomy";
const BRAND: &str = "openav";

const PLUGIN_URI: &str = "http://www.openavproductions.com/artyfx#roomy";
const PLUGIN_DIR: &str = "artyfx";

#[cfg(target_os = "macos")]
const PLUGIN_BINARY: &str = "artyfx.dylib.dylib";
#[cfg(target_os = "linux")]
const PLUGIN_BINARY: &str = "artyfx.dylib.so";
#[cfg(target_os = "windows")]
const PLUGIN_BINARY: &str = "artyfx.dylib.dll";

// Port indices (from TTL)
const PORT_AUDIO_IN_IN_LEFT: usize = 0;
const PORT_AUDIO_IN_IN_RIGHT: usize = 1;
const PORT_AUDIO_OUT_OUT_LEFT: usize = 2;
const PORT_AUDIO_OUT_OUT_RIGHT: usize = 3;
const PORT_CTRL_TIME: usize = 4;
const PORT_CTRL_DAMPING: usize = 5;
const PORT_CTRL_DRY_WET: usize = 6;

pub fn model_schema() -> ModelParameterSchema {
    ModelParameterSchema {
        effect_type: block_core::EFFECT_TYPE_REVERB.into(),
        model: MODEL_ID.into(),
        display_name: DISPLAY_NAME.into(),
        audio_mode: ModelAudioMode::TrueStereo,
        parameters: vec![
            float_parameter("time", "Time", None, Some(0.5), 0.0, 1.0, 0.01, ParameterUnit::None),
            float_parameter("damping", "Damping", None, Some(0.5), 0.0, 1.0, 0.01, ParameterUnit::None),
            float_parameter("dry_wet", "Dry/Wet Mix", None, Some(0.5), 0.0, 1.0, 0.01, ParameterUnit::None),
        ],
    }
}

fn build(params: &ParameterSet, sample_rate: f32, layout: AudioChannelLayout) -> Result<BlockProcessor> {
    let time = required_f32(params, "time").map_err(anyhow::Error::msg)?;
    let damping = required_f32(params, "damping").map_err(anyhow::Error::msg)?;
    let dry_wet = required_f32(params, "dry_wet").map_err(anyhow::Error::msg)?;
    let lib_path = lv2::resolve_lv2_lib(PLUGIN_BINARY)?;
    let bundle_path = lv2::resolve_lv2_bundle(PLUGIN_DIR)?;

    let control_ports: &[(usize, f32)] = &[
        (PORT_CTRL_TIME, time),
        (PORT_CTRL_DAMPING, damping),
        (PORT_CTRL_DRY_WET, dry_wet),
    ];

    let processor = lv2::build_stereo_lv2_processor(&lib_path, PLUGIN_URI, sample_rate as f64, &bundle_path, &[PORT_AUDIO_IN_IN_LEFT, PORT_AUDIO_IN_IN_RIGHT], &[PORT_AUDIO_OUT_OUT_LEFT, PORT_AUDIO_OUT_OUT_RIGHT], control_ports)?;
    let _ = layout;
    Ok(BlockProcessor::Stereo(Box::new(processor)))
}

fn schema() -> Result<ModelParameterSchema> { Ok(model_schema()) }

pub const MODEL_DEFINITION: ReverbModelDefinition = ReverbModelDefinition {
    id: MODEL_ID, display_name: DISPLAY_NAME, brand: BRAND,
    backend_kind: ReverbBackendKind::Lv2, schema, build,
    supported_instruments: block_core::ALL_INSTRUMENTS, knob_layout: &[],
};
