// AUTO-GENERATED by tools/lv2_catalog_import — do not edit by hand.
// Re-run the tool to regenerate. Manual customisation goes in overrides.yaml.

#![allow(dead_code, unused_imports, unused_variables, clippy::approx_constant, clippy::excessive_precision)]

use crate::registry::ReverbModelDefinition;
use crate::ReverbBackendKind;
use anyhow::Result;
use block_core::param::{
    bool_parameter, float_parameter, required_bool, required_f32,
    ModelParameterSchema, ParameterSet, ParameterUnit,
};
use block_core::{AudioChannelLayout, BlockProcessor, ModelAudioMode};

pub const MODEL_ID: &str = "lv2_rkr_reverbtron";
pub const DISPLAY_NAME: &str = "rkr Reverbtron";
const BRAND: &str = "rakarrack";

const PLUGIN_URI: &str = "http://rakarrack.sourceforge.net/effects.html#Reverbtron";
const PLUGIN_DIR: &str = "rkr";

#[cfg(target_os = "macos")]
const PLUGIN_BINARY: &str = "plugin.dylib";
#[cfg(target_os = "linux")]
const PLUGIN_BINARY: &str = "plugin.so";
#[cfg(target_os = "windows")]
const PLUGIN_BINARY: &str = "plugin.dll";

// Port indices (from TTL)
const PORT_AUDIO_IN_INPUT_L: usize = 0;
const PORT_AUDIO_IN_INPUT_R: usize = 1;
const PORT_AUDIO_OUT_OUTPUT_L: usize = 2;
const PORT_AUDIO_OUT_OUTPUT_R: usize = 3;
const PORT_ATOM_IN_CONTROL: usize = 4;
const PORT_ATOM_OUT_NOTIFY: usize = 5;
const PORT_CTRL_BYPASS: usize = 6;
const PORT_CTRL_WETDRY: usize = 7;
const PORT_CTRL_FADE: usize = 8;
const PORT_CTRL_SAFE: usize = 9;
const PORT_CTRL_LENGTH: usize = 10;
const PORT_CTRL_DELAY: usize = 11;
const PORT_CTRL_DAMP: usize = 12;
const PORT_CTRL_LEVEL: usize = 13;
const PORT_CTRL_STRETCH: usize = 14;
const PORT_CTRL_FB: usize = 15;
const PORT_CTRL_PAN: usize = 16;
const PORT_CTRL_ES: usize = 17;
const PORT_CTRL_SH: usize = 18;
const PORT_CTRL_LPF: usize = 19;
const PORT_CTRL_DIFFUSE: usize = 20;

pub fn model_schema() -> ModelParameterSchema {
    ModelParameterSchema {
        effect_type: block_core::EFFECT_TYPE_REVERB.into(),
        model: MODEL_ID.into(),
        display_name: DISPLAY_NAME.into(),
        audio_mode: ModelAudioMode::TrueStereo,
        parameters: vec![
            bool_parameter("bypass", "Bypass", None, Some(false)),
            float_parameter("wetdry", "Wet/Dry", None, Some(64.0), 0.0, 127.0, 1.0, ParameterUnit::None),
            float_parameter("fade", "Fade", None, Some(0.0), 0.0, 127.0, 1.0, ParameterUnit::None),
            bool_parameter("safe", "Safe", None, Some(true)),
            float_parameter("length", "Length", None, Some(500.0), 20.0, 1500.0, 10.0, ParameterUnit::Milliseconds),
            float_parameter("delay", "Initial Delay", None, Some(64.0), 0.0, 500.0, 1.0, ParameterUnit::Milliseconds),
            float_parameter("damp", "Dampening", None, Some(99.0), 0.0, 127.0, 1.0, ParameterUnit::None),
            float_parameter("level", "Level", None, Some(70.0), 0.0, 127.0, 1.0, ParameterUnit::None),
            float_parameter("stretch", "Time Stretch", None, Some(0.0), -64.0, 64.0, 1.0, ParameterUnit::None),
            float_parameter("fb", "Feedback", None, Some(0.0), -64.0, 64.0, 1.0, ParameterUnit::None),
            float_parameter("pan", "Pan", None, Some(0.0), -64.0, 63.0, 1.0, ParameterUnit::None),
            bool_parameter("es", "Extra Stereo", None, Some(false)),
            bool_parameter("sh", "Shuffle", None, Some(false)),
            float_parameter("lpf", "Lowpass Filter", None, Some(20000.0), 20.0, 26000.0, 10.0, ParameterUnit::Hertz),
            float_parameter("diffuse", "Diffusion", None, Some(0.0), 0.0, 127.0, 1.0, ParameterUnit::None),
        ],
    }
}

fn build(params: &ParameterSet, sample_rate: f32, layout: AudioChannelLayout) -> Result<BlockProcessor> {
    let bypass = required_bool(params, "bypass").map_err(anyhow::Error::msg)?;
    let wetdry = required_f32(params, "wetdry").map_err(anyhow::Error::msg)?;
    let fade = required_f32(params, "fade").map_err(anyhow::Error::msg)?;
    let safe = required_bool(params, "safe").map_err(anyhow::Error::msg)?;
    let length = required_f32(params, "length").map_err(anyhow::Error::msg)?;
    let delay = required_f32(params, "delay").map_err(anyhow::Error::msg)?;
    let damp = required_f32(params, "damp").map_err(anyhow::Error::msg)?;
    let level = required_f32(params, "level").map_err(anyhow::Error::msg)?;
    let stretch = required_f32(params, "stretch").map_err(anyhow::Error::msg)?;
    let fb = required_f32(params, "fb").map_err(anyhow::Error::msg)?;
    let pan = required_f32(params, "pan").map_err(anyhow::Error::msg)?;
    let es = required_bool(params, "es").map_err(anyhow::Error::msg)?;
    let sh = required_bool(params, "sh").map_err(anyhow::Error::msg)?;
    let lpf = required_f32(params, "lpf").map_err(anyhow::Error::msg)?;
    let diffuse = required_f32(params, "diffuse").map_err(anyhow::Error::msg)?;
    let lib_path = lv2::resolve_lv2_lib(PLUGIN_BINARY)?;
    let bundle_path = lv2::resolve_lv2_bundle(PLUGIN_DIR)?;

    let control_ports: &[(usize, f32)] = &[
        (PORT_CTRL_BYPASS, if bypass { 1.0 } else { 0.0 }),
        (PORT_CTRL_WETDRY, wetdry),
        (PORT_CTRL_FADE, fade),
        (PORT_CTRL_SAFE, if safe { 1.0 } else { 0.0 }),
        (PORT_CTRL_LENGTH, length),
        (PORT_CTRL_DELAY, delay),
        (PORT_CTRL_DAMP, damp),
        (PORT_CTRL_LEVEL, level),
        (PORT_CTRL_STRETCH, stretch),
        (PORT_CTRL_FB, fb),
        (PORT_CTRL_PAN, pan),
        (PORT_CTRL_ES, if es { 1.0 } else { 0.0 }),
        (PORT_CTRL_SH, if sh { 1.0 } else { 0.0 }),
        (PORT_CTRL_LPF, lpf),
        (PORT_CTRL_DIFFUSE, diffuse),
    ];

    let processor = lv2::build_stereo_lv2_processor(&lib_path, PLUGIN_URI, sample_rate as f64, &bundle_path, &[PORT_AUDIO_IN_INPUT_L, PORT_AUDIO_IN_INPUT_R], &[PORT_AUDIO_OUT_OUTPUT_L, PORT_AUDIO_OUT_OUTPUT_R], control_ports)?;
    let _ = layout;
    Ok(BlockProcessor::Stereo(Box::new(processor)))
}

fn schema() -> Result<ModelParameterSchema> { Ok(model_schema()) }

pub const MODEL_DEFINITION: ReverbModelDefinition = ReverbModelDefinition {
    id: MODEL_ID, display_name: DISPLAY_NAME, brand: BRAND,
    backend_kind: ReverbBackendKind::Lv2, schema, build,
    supported_instruments: block_core::ALL_INSTRUMENTS, knob_layout: &[],
};
