// AUTO-GENERATED by tools/lv2_catalog_import — do not edit by hand.
// Re-run the tool to regenerate. Manual customisation goes in overrides.yaml.

#![allow(dead_code, unused_imports, unused_variables, clippy::all)]

use crate::registry::ReverbModelDefinition;
use crate::ReverbBackendKind;
use anyhow::Result;
use block_core::param::{
    bool_parameter, float_parameter, required_bool, required_f32,
    ModelParameterSchema, ParameterSet, ParameterUnit,
};
use block_core::{AudioChannelLayout, BlockProcessor, ModelAudioMode};

pub const MODEL_ID: &str = "lv2_rkr_eco";
pub const DISPLAY_NAME: &str = "rkr Echo";
const BRAND: &str = "rakarrack";

const PLUGIN_URI: &str = "http://rakarrack.sourceforge.net/effects.html#eco";
const PLUGIN_DIR: &str = "rkr";
pub const THUMBNAIL_PATH: Option<&str> = Some(".plugins/lv2/rkr.lv2/modgui/thumbnail-rkr-echo.png");

#[cfg(target_os = "macos")]
const PLUGIN_BINARY: &str = "plugin.dylib";
#[cfg(target_os = "linux")]
const PLUGIN_BINARY: &str = "plugin.so";
#[cfg(target_os = "windows")]
const PLUGIN_BINARY: &str = "plugin.dll";

// Port indices (from TTL)
const PORT_AUDIO_IN_INPUT_L: usize = 0;
const PORT_AUDIO_IN_INPUT_R: usize = 1;
const PORT_AUDIO_OUT_OUTPUT_L: usize = 2;
const PORT_AUDIO_OUT_OUTPUT_R: usize = 3;
const PORT_CTRL_BYPASS: usize = 4;
const PORT_CTRL_WETDRY: usize = 5;
const PORT_CTRL_PAN: usize = 6;
const PORT_CTRL_DELAY: usize = 7;
const PORT_CTRL_LR_DELAY: usize = 8;
const PORT_CTRL_LR_CR: usize = 9;
const PORT_CTRL_FEEDBACK: usize = 10;
const PORT_CTRL_DAMP: usize = 11;
const PORT_CTRL_REV: usize = 12;
const PORT_CTRL_DIRECT: usize = 13;

pub fn model_schema() -> ModelParameterSchema {
    ModelParameterSchema {
        effect_type: block_core::EFFECT_TYPE_REVERB.into(),
        model: MODEL_ID.into(),
        display_name: DISPLAY_NAME.into(),
        audio_mode: ModelAudioMode::TrueStereo,
        parameters: vec![
            bool_parameter("bypass", "Bypass", None, Some(false)),
            float_parameter("wetdry", "Wet/Dry", None, Some(67.0), 0.0, 127.0, 1.0, ParameterUnit::None),
            float_parameter("pan", "Panning", None, Some(0.0), -64.0, 63.0, 1.0, ParameterUnit::None),
            float_parameter("delay", "Delay", None, Some(565.0), 20.0, 2000.0, 10.0, ParameterUnit::Milliseconds),
            float_parameter("lr_delay", "Left/Right Delay Offset", None, Some(0.0), -64.0, 63.0, 1.0, ParameterUnit::None),
            float_parameter("lrcr", "Left/Right Crossover", None, Some(30.0), 0.0, 127.0, 1.0, ParameterUnit::None),
            float_parameter("feedback", "Feedback", None, Some(59.0), 0.0, 127.0, 1.0, ParameterUnit::None),
            float_parameter("damp", "Damping", None, Some(0.0), 0.0, 127.0, 1.0, ParameterUnit::None),
            float_parameter("rev", "Reverse", None, Some(127.0), 0.0, 127.0, 1.0, ParameterUnit::None),
            bool_parameter("direct", "Direct", None, Some(false)),
        ],
    }
}

fn build(params: &ParameterSet, sample_rate: f32, layout: AudioChannelLayout) -> Result<BlockProcessor> {
    let bypass = required_bool(params, "bypass").map_err(anyhow::Error::msg)?;
    let wetdry = required_f32(params, "wetdry").map_err(anyhow::Error::msg)?;
    let pan = required_f32(params, "pan").map_err(anyhow::Error::msg)?;
    let delay = required_f32(params, "delay").map_err(anyhow::Error::msg)?;
    let lr_delay = required_f32(params, "lr_delay").map_err(anyhow::Error::msg)?;
    let lrcr = required_f32(params, "lrcr").map_err(anyhow::Error::msg)?;
    let feedback = required_f32(params, "feedback").map_err(anyhow::Error::msg)?;
    let damp = required_f32(params, "damp").map_err(anyhow::Error::msg)?;
    let rev = required_f32(params, "rev").map_err(anyhow::Error::msg)?;
    let direct = required_bool(params, "direct").map_err(anyhow::Error::msg)?;
    let lib_path = lv2::resolve_lv2_lib(PLUGIN_BINARY)?;
    let bundle_path = lv2::resolve_lv2_bundle(PLUGIN_DIR)?;

    let control_ports: &[(usize, f32)] = &[
        (PORT_CTRL_BYPASS, if bypass { 1.0 } else { 0.0 }),
        (PORT_CTRL_WETDRY, wetdry),
        (PORT_CTRL_PAN, pan),
        (PORT_CTRL_DELAY, delay),
        (PORT_CTRL_LR_DELAY, lr_delay),
        (PORT_CTRL_LR_CR, lrcr),
        (PORT_CTRL_FEEDBACK, feedback),
        (PORT_CTRL_DAMP, damp),
        (PORT_CTRL_REV, rev),
        (PORT_CTRL_DIRECT, if direct { 1.0 } else { 0.0 }),
    ];

    let processor = lv2::build_stereo_lv2_processor(&lib_path, PLUGIN_URI, sample_rate as f64, &bundle_path, &[PORT_AUDIO_IN_INPUT_L, PORT_AUDIO_IN_INPUT_R], &[PORT_AUDIO_OUT_OUTPUT_L, PORT_AUDIO_OUT_OUTPUT_R], control_ports)?;
    let _ = layout;
    Ok(BlockProcessor::Stereo(Box::new(processor)))
}

fn schema() -> Result<ModelParameterSchema> { Ok(model_schema()) }

pub const MODEL_DEFINITION: ReverbModelDefinition = ReverbModelDefinition {
    id: MODEL_ID, display_name: DISPLAY_NAME, brand: BRAND,
    backend_kind: ReverbBackendKind::Lv2, schema, build,
    supported_instruments: block_core::ALL_INSTRUMENTS, knob_layout: &[],
};
