use crate::model::{AudioMode, BlockType, Classification, Plugin, Port, PortDirection, PortKind};
use std::fmt::Write as _;

pub fn render_model_def(plugin: &Plugin, classification: &Classification) -> Option<String> {
    let block_type = classification.block_type?;
    let audio_mode = classification.audio_mode?;
    let registry_type = block_type.registry_type_name();
    let backend_kind = block_type.backend_kind_path();
    let effect_type = block_type.effect_type_const();
    let model_id = &classification.model_id;
    let display_name = escape_str(&classification.display_name);
    let brand = escape_str(&classification.brand);
    let plugin_uri = escape_str(&plugin.uri);
    let plugin_dir = escape_str(
        plugin
            .bundle_dir
            .strip_suffix(".lv2")
            .unwrap_or(&plugin.bundle_dir),
    );
    let bin = plugin.binary.as_deref().unwrap_or("plugin.so");
    let bin_stem = bin.strip_suffix(".so").unwrap_or(bin);

    let audio_in_indices = audio_port_indices(plugin, PortDirection::Input);
    let audio_out_indices = audio_port_indices(plugin, PortDirection::Output);
    let control_in_ports: Vec<&Port> = plugin
        .ports
        .iter()
        .filter(|p| p.kind == PortKind::Control && p.direction == PortDirection::Input)
        .collect();
    let extra_audio_outs: Vec<usize> = match audio_mode {
        AudioMode::MonoToStereo => audio_out_indices.iter().skip(1).copied().collect(),
        _ => Vec::new(),
    };

    let mut out = String::new();
    let _ = writeln!(
        out,
        "// AUTO-GENERATED by tools/lv2_catalog_import — do not edit by hand."
    );
    let _ = writeln!(
        out,
        "// Re-run the tool to regenerate. Manual customisation goes in overrides.yaml."
    );
    let _ = writeln!(out);
    let _ = writeln!(out, "use crate::registry::{};", registry_type);
    let _ = writeln!(out, "use crate::{};", strip_kind(backend_kind));
    let _ = writeln!(out, "use anyhow::Result;");
    let _ = writeln!(out, "use block_core::param::{{");
    let _ = writeln!(
        out,
        "    bool_parameter, float_parameter, int_parameter, required_bool, required_f32,"
    );
    let _ = writeln!(
        out,
        "    required_i32, ModelParameterSchema, ParameterSet, ParameterUnit,"
    );
    let _ = writeln!(out, "}};");
    let _ = writeln!(out, "use block_core::{{AudioChannelLayout, BlockProcessor, ModelAudioMode, MonoProcessor, StereoProcessor}};");
    let _ = writeln!(out);
    let _ = writeln!(out, "pub const MODEL_ID: &str = \"{}\";", model_id);
    let _ = writeln!(out, "pub const DISPLAY_NAME: &str = \"{}\";", display_name);
    let _ = writeln!(out, "const BRAND: &str = \"{}\";", brand);
    let _ = writeln!(out);
    let _ = writeln!(out, "const PLUGIN_URI: &str = \"{}\";", plugin_uri);
    let _ = writeln!(out, "const PLUGIN_DIR: &str = \"{}\";", plugin_dir);
    let _ = writeln!(out);
    let _ = writeln!(out, "#[cfg(target_os = \"macos\")]");
    let _ = writeln!(out, "const PLUGIN_BINARY: &str = \"{}.dylib\";", bin_stem);
    let _ = writeln!(out, "#[cfg(target_os = \"linux\")]");
    let _ = writeln!(out, "const PLUGIN_BINARY: &str = \"{}.so\";", bin_stem);
    let _ = writeln!(out, "#[cfg(target_os = \"windows\")]");
    let _ = writeln!(out, "const PLUGIN_BINARY: &str = \"{}.dll\";", bin_stem);
    let _ = writeln!(out);

    write_port_consts(&mut out, plugin);
    let _ = writeln!(out);

    write_schema_fn(&mut out, audio_mode, effect_type, &control_in_ports);
    let _ = writeln!(out);

    write_build_fn(
        &mut out,
        audio_mode,
        &audio_in_indices,
        &audio_out_indices,
        &extra_audio_outs,
        &control_in_ports,
    );
    let _ = writeln!(out);

    let _ = writeln!(
        out,
        "fn schema() -> Result<ModelParameterSchema> {{ Ok(model_schema()) }}"
    );
    let _ = writeln!(out);
    let _ = writeln!(
        out,
        "pub const MODEL_DEFINITION: {} = {} {{",
        registry_type, registry_type
    );
    let _ = writeln!(
        out,
        "    id: MODEL_ID, display_name: DISPLAY_NAME, brand: BRAND,"
    );
    let _ = writeln!(out, "    backend_kind: {}, schema, build,", backend_kind);
    let _ = writeln!(
        out,
        "    supported_instruments: block_core::ALL_INSTRUMENTS, knob_layout: &[],"
    );
    let _ = writeln!(out, "}};");

    Some(out)
}

fn audio_port_indices(plugin: &Plugin, dir: PortDirection) -> Vec<usize> {
    let mut idx: Vec<usize> = plugin
        .ports
        .iter()
        .filter(|p| p.kind == PortKind::Audio && p.direction == dir)
        .map(|p| p.index)
        .collect();
    idx.sort_unstable();
    idx
}

fn write_port_consts(out: &mut String, plugin: &Plugin) {
    let _ = writeln!(out, "// Port indices (from TTL)");
    for port in &plugin.ports {
        if matches!(port.kind, PortKind::Other) {
            continue;
        }
        let const_name = port_const_name(port);
        let _ = writeln!(out, "const {}: usize = {};", const_name, port.index);
    }
}

fn port_const_name(port: &Port) -> String {
    use heck::ToShoutySnakeCase;
    let role = match (port.kind, port.direction) {
        (PortKind::Audio, PortDirection::Input) => "AUDIO_IN",
        (PortKind::Audio, PortDirection::Output) => "AUDIO_OUT",
        (PortKind::Control, _) => "CTRL",
        (PortKind::Cv, PortDirection::Input) => "CV_IN",
        (PortKind::Cv, PortDirection::Output) => "CV_OUT",
        (PortKind::Atom, PortDirection::Input) => "ATOM_IN",
        (PortKind::Atom, PortDirection::Output) => "ATOM_OUT",
        (PortKind::Event, PortDirection::Input) => "EVENT_IN",
        (PortKind::Event, PortDirection::Output) => "EVENT_OUT",
        _ => "PORT",
    };
    let sym = port.symbol.to_shouty_snake_case();
    let sym = sym
        .chars()
        .filter(|c| c.is_ascii_alphanumeric() || *c == '_')
        .collect::<String>();
    format!("PORT_{}_{}", role, sym)
}

fn write_schema_fn(
    out: &mut String,
    audio_mode: AudioMode,
    effect_type: &str,
    ctrl_ports: &[&Port],
) {
    let _ = writeln!(out, "pub fn model_schema() -> ModelParameterSchema {{");
    let _ = writeln!(out, "    ModelParameterSchema {{");
    let _ = writeln!(out, "        effect_type: {}.into(),", effect_type);
    let _ = writeln!(out, "        model: MODEL_ID.into(),");
    let _ = writeln!(out, "        display_name: DISPLAY_NAME.into(),");
    let _ = writeln!(out, "        audio_mode: {},", audio_mode.variant_path());
    let _ = writeln!(out, "        parameters: vec![");
    for port in ctrl_ports {
        let _ = writeln!(out, "            {},", render_param(port));
    }
    let _ = writeln!(out, "        ],");
    let _ = writeln!(out, "    }}");
    let _ = writeln!(out, "}}");
}

fn render_param(port: &Port) -> String {
    let symbol = sanitize_param_id(&port.symbol);
    let label = port
        .name
        .as_deref()
        .map(escape_str)
        .unwrap_or_else(|| symbol.clone());
    let unit = guess_unit(port);
    let default = port.default.unwrap_or(0.0);
    let min = port.minimum.unwrap_or(0.0);
    let max = port.maximum.unwrap_or(1.0);

    if port.is_toggle {
        return format!(
            "bool_parameter(\"{}\", \"{}\", None, Some({}))",
            symbol,
            label,
            default != 0.0
        );
    }
    if port.is_integer {
        let step = 1.0_f32;
        let _ = step;
        return format!(
            "int_parameter(\"{}\", \"{}\", None, Some({}), {}, {}, 1, ParameterUnit::{})",
            symbol, label, default as i32, min as i32, max as i32, unit,
        );
    }
    let step = pick_step(min, max);
    format!(
        "float_parameter(\"{}\", \"{}\", None, Some({:?}), {:?}, {:?}, {:?}, ParameterUnit::{})",
        symbol, label, default, min, max, step, unit
    )
}

fn pick_step(min: f32, max: f32) -> f32 {
    let range = (max - min).abs();
    if range >= 1000.0 {
        10.0
    } else if range >= 100.0 {
        1.0
    } else if range >= 10.0 {
        0.1
    } else if range >= 1.0 {
        0.01
    } else {
        0.001
    }
}

fn guess_unit(port: &Port) -> &'static str {
    let unit = port.unit_uri.as_deref().unwrap_or("");
    if unit.ends_with("#hz") || unit.ends_with("hertz") {
        "Hertz"
    } else if unit.ends_with("#db") || unit.ends_with("decibel") {
        "Decibels"
    } else if unit.ends_with("#ms") || unit.ends_with("millisecond") {
        "Milliseconds"
    } else if unit.ends_with("#s") || unit.ends_with("second") {
        "Seconds"
    } else if unit.ends_with("#pc") || unit.ends_with("percent") {
        "Percent"
    } else {
        "None"
    }
}

fn sanitize_param_id(s: &str) -> String {
    s.chars()
        .map(|c| if c.is_ascii_alphanumeric() { c } else { '_' })
        .collect::<String>()
        .to_lowercase()
        .trim_matches('_')
        .to_string()
}

fn write_build_fn(
    out: &mut String,
    audio_mode: AudioMode,
    audio_in: &[usize],
    audio_out: &[usize],
    extra_outs: &[usize],
    ctrl_ports: &[&Port],
) {
    let _ = writeln!(out, "fn build(params: &ParameterSet, sample_rate: f32, layout: AudioChannelLayout) -> Result<BlockProcessor> {{");

    for port in ctrl_ports {
        let id = sanitize_param_id(&port.symbol);
        if port.is_toggle {
            let _ = writeln!(
                out,
                "    let {} = required_bool(params, \"{}\").map_err(anyhow::Error::msg)?;",
                id, id
            );
        } else if port.is_integer {
            let _ = writeln!(
                out,
                "    let {} = required_i32(params, \"{}\").map_err(anyhow::Error::msg)?;",
                id, id
            );
        } else {
            let _ = writeln!(
                out,
                "    let {} = required_f32(params, \"{}\").map_err(anyhow::Error::msg)?;",
                id, id
            );
        }
    }

    let _ = writeln!(
        out,
        "    let lib_path = lv2::resolve_lv2_lib(PLUGIN_BINARY)?;"
    );
    let _ = writeln!(
        out,
        "    let bundle_path = lv2::resolve_lv2_bundle(PLUGIN_DIR)?;"
    );
    let _ = writeln!(out);
    let _ = writeln!(out, "    let control_ports: &[(usize, f32)] = &[");
    for port in ctrl_ports {
        let id = sanitize_param_id(&port.symbol);
        let const_name = port_const_name(port);
        if port.is_toggle {
            let _ = writeln!(
                out,
                "        ({}, if {} {{ 1.0 }} else {{ 0.0 }}),",
                const_name, id
            );
        } else if port.is_integer {
            let _ = writeln!(out, "        ({}, {} as f32),", const_name, id);
        } else {
            let _ = writeln!(out, "        ({}, {}),", const_name, id);
        }
    }
    let _ = writeln!(out, "    ];");
    let _ = writeln!(out);

    match audio_mode {
        AudioMode::DualMono | AudioMode::MonoOnly => {
            let in_const = audio_const_lookup(audio_in.first().copied(), "AUDIO_IN");
            let out_const = audio_const_lookup(audio_out.first().copied(), "AUDIO_OUT");
            let _ = writeln!(out, "    let _extras: &[usize] = &[];");
            let _ = writeln!(out, "    match layout {{");
            let _ = writeln!(out, "        AudioChannelLayout::Mono => {{");
            let _ = writeln!(out, "            let processor = lv2::build_lv2_processor(&lib_path, PLUGIN_URI, sample_rate as f64, &bundle_path,");
            let _ = writeln!(
                out,
                "                &[{}], &[{}], control_ports)?;",
                in_const, out_const
            );
            let _ = writeln!(
                out,
                "            Ok(BlockProcessor::Mono(Box::new(processor)))"
            );
            let _ = writeln!(out, "        }}");
            let _ = writeln!(out, "        AudioChannelLayout::Stereo => {{");
            let _ = writeln!(out, "            let left = lv2::build_lv2_processor(&lib_path, PLUGIN_URI, sample_rate as f64, &bundle_path, &[{}], &[{}], control_ports)?;", in_const, out_const);
            let _ = writeln!(out, "            let right = lv2::build_lv2_processor(&lib_path, PLUGIN_URI, sample_rate as f64, &bundle_path, &[{}], &[{}], control_ports)?;", in_const, out_const);
            let _ = writeln!(out, "            Ok(BlockProcessor::Stereo(Box::new(DualMonoProcessor {{ left, right }})))");
            let _ = writeln!(out, "        }}");
            let _ = writeln!(out, "    }}");
            let _ = writeln!(out, "}}");
            let _ = writeln!(out);
            let _ = writeln!(
                out,
                "struct DualMonoProcessor {{ left: lv2::Lv2Processor, right: lv2::Lv2Processor }}"
            );
            let _ = writeln!(out, "impl StereoProcessor for DualMonoProcessor {{");
            let _ = writeln!(
                out,
                "    fn process_frame(&mut self, input: [f32; 2]) -> [f32; 2] {{"
            );
            let _ = writeln!(
                out,
                "        [self.left.process_sample(input[0]), self.right.process_sample(input[1])]"
            );
            let _ = writeln!(out, "    }}");
            let _ = writeln!(out, "}}");
        }
        AudioMode::MonoToStereo => {
            let in_const = audio_const_lookup(audio_in.first().copied(), "AUDIO_IN");
            let out_l_const = audio_const_lookup(audio_out.first().copied(), "AUDIO_OUT");
            let extras: Vec<String> = extra_outs
                .iter()
                .map(|i| format!("PORT_AUDIO_OUT_{}", i))
                .collect();
            let _ = writeln!(
                out,
                "    let extra_outs: &[usize] = &[{}];",
                extras.join(", ")
            );
            let _ = writeln!(out, "    let processor = lv2::build_lv2_processor_with_extras(&lib_path, PLUGIN_URI, sample_rate as f64, &bundle_path,");
            let _ = writeln!(
                out,
                "        &[{}], &[{}], control_ports, extra_outs)?;",
                in_const, out_l_const
            );
            let _ = writeln!(out, "    match layout {{");
            let _ = writeln!(out, "        AudioChannelLayout::Mono => Ok(BlockProcessor::Mono(Box::new(processor))),");
            let _ = writeln!(out, "        AudioChannelLayout::Stereo => {{");
            let _ = writeln!(
                out,
                "            // mono in, stereo out — duplicate processing per side"
            );
            let _ = writeln!(
                out,
                "            Ok(BlockProcessor::Mono(Box::new(processor)))"
            );
            let _ = writeln!(out, "        }}");
            let _ = writeln!(out, "    }}");
            let _ = writeln!(out, "}}");
        }
        AudioMode::TrueStereo => {
            let in_l = audio_const_lookup(audio_in.first().copied(), "AUDIO_IN");
            let in_r = audio_const_lookup(audio_in.get(1).copied(), "AUDIO_IN");
            let out_l = audio_const_lookup(audio_out.first().copied(), "AUDIO_OUT");
            let out_r = audio_const_lookup(audio_out.get(1).copied(), "AUDIO_OUT");
            let _ = writeln!(out, "    let processor = lv2::build_stereo_lv2_processor(&lib_path, PLUGIN_URI, sample_rate as f64, &bundle_path,");
            let _ = writeln!(
                out,
                "        &[{}, {}], &[{}, {}], control_ports)?;",
                in_l, in_r, out_l, out_r
            );
            let _ = writeln!(out, "    match layout {{");
            let _ = writeln!(out, "        AudioChannelLayout::Mono => Ok(BlockProcessor::Stereo(Box::new(processor))),");
            let _ = writeln!(out, "        AudioChannelLayout::Stereo => Ok(BlockProcessor::Stereo(Box::new(processor))),");
            let _ = writeln!(out, "    }}");
            let _ = writeln!(out, "}}");
        }
    }
}

fn audio_const_lookup(idx: Option<usize>, role: &str) -> String {
    match idx {
        Some(i) => format!("PORT_{}_{}", role, i),
        None => "0".to_string(),
    }
}

fn strip_kind(path: &str) -> &str {
    path.split("::").next().unwrap_or(path)
}

fn escape_str(s: &str) -> String {
    s.replace('\\', "\\\\").replace('"', "\\\"")
}

#[allow(dead_code)]
fn _silence(_: BlockType) {}
