use crate::model::{AudioMode, Classification, Plugin, Port, PortDirection, PortKind};
use std::collections::HashSet;
use std::fmt::Write as _;

pub fn render_model_def(plugin: &Plugin, classification: &Classification) -> Option<String> {
    let block_type = classification.block_type?;
    if !block_type.supports_lv2_codegen() {
        return None;
    }
    let audio_mode = classification.audio_mode?;
    let registry_type = block_type.registry_type_name();
    let backend_kind = block_type.backend_kind_path();
    let effect_type = block_type.effect_type_const();

    let model_id = &classification.model_id;
    let display_name = escape_str(&classification.display_name);
    let brand = escape_str(&classification.brand);
    let plugin_uri = escape_str(&plugin.uri);
    let plugin_dir = escape_str(
        plugin
            .bundle_dir
            .strip_suffix(".lv2")
            .unwrap_or(&plugin.bundle_dir),
    );
    let bin = plugin.binary.as_deref().unwrap_or("plugin.so");
    let bin_stem = bin.strip_suffix(".so").unwrap_or(bin);

    let port_const_names = name_ports(plugin);
    let audio_in_consts = audio_const_list(plugin, &port_const_names, PortDirection::Input);
    let audio_out_consts = audio_const_list(plugin, &port_const_names, PortDirection::Output);
    let control_ports: Vec<&Port> = plugin
        .ports
        .iter()
        .filter(|p| p.kind == PortKind::Control && p.direction == PortDirection::Input)
        .collect();
    let has_bool = control_ports.iter().any(|p| p.is_toggle);

    let mut out = String::new();
    let _ = writeln!(
        out,
        "// AUTO-GENERATED by tools/lv2_catalog_import — do not edit by hand."
    );
    let _ = writeln!(
        out,
        "// Re-run the tool to regenerate. Manual customisation goes in overrides.yaml."
    );
    let _ = writeln!(out);
    let _ = writeln!(out, "#![allow(dead_code, unused_imports, unused_variables, clippy::approx_constant, clippy::excessive_precision)]");
    let _ = writeln!(out);
    let _ = writeln!(out, "use crate::registry::{};", registry_type);
    let _ = writeln!(out, "use crate::{};", strip_kind(backend_kind));
    let _ = writeln!(out, "use anyhow::Result;");
    write_param_imports(&mut out, has_bool);
    write_core_imports(&mut out, audio_mode);
    let _ = writeln!(out);
    let _ = writeln!(out, "pub const MODEL_ID: &str = \"{}\";", model_id);
    let _ = writeln!(out, "pub const DISPLAY_NAME: &str = \"{}\";", display_name);
    let _ = writeln!(out, "const BRAND: &str = \"{}\";", brand);
    let _ = writeln!(out);
    let _ = writeln!(out, "const PLUGIN_URI: &str = \"{}\";", plugin_uri);
    let _ = writeln!(out, "const PLUGIN_DIR: &str = \"{}\";", plugin_dir);
    let _ = writeln!(out);
    let _ = writeln!(out, "#[cfg(target_os = \"macos\")]");
    let _ = writeln!(out, "const PLUGIN_BINARY: &str = \"{}.dylib\";", bin_stem);
    let _ = writeln!(out, "#[cfg(target_os = \"linux\")]");
    let _ = writeln!(out, "const PLUGIN_BINARY: &str = \"{}.so\";", bin_stem);
    let _ = writeln!(out, "#[cfg(target_os = \"windows\")]");
    let _ = writeln!(out, "const PLUGIN_BINARY: &str = \"{}.dll\";", bin_stem);
    let _ = writeln!(out);

    write_port_consts(&mut out, plugin, &port_const_names);
    let _ = writeln!(out);

    write_schema_fn(&mut out, audio_mode, effect_type, &control_ports);
    let _ = writeln!(out);

    write_build_fn(
        &mut out,
        audio_mode,
        &audio_in_consts,
        &audio_out_consts,
        &control_ports,
        &port_const_names,
    );
    let _ = writeln!(out);

    let _ = writeln!(
        out,
        "fn schema() -> Result<ModelParameterSchema> {{ Ok(model_schema()) }}"
    );
    let _ = writeln!(out);
    let _ = writeln!(
        out,
        "pub const MODEL_DEFINITION: {} = {} {{",
        registry_type, registry_type
    );
    let _ = writeln!(
        out,
        "    id: MODEL_ID, display_name: DISPLAY_NAME, brand: BRAND,"
    );
    let _ = writeln!(out, "    backend_kind: {}, schema, build,", backend_kind);
    if block_type.needs_validate_and_asset_summary() {
        let _ = writeln!(out, "    validate, asset_summary,");
    }
    let _ = writeln!(
        out,
        "    supported_instruments: block_core::ALL_INSTRUMENTS, knob_layout: &[],"
    );
    let _ = writeln!(out, "}};");

    if block_type.needs_validate_and_asset_summary() {
        let _ = writeln!(out);
        let _ = writeln!(
            out,
            "fn validate(_params: &ParameterSet) -> Result<()> {{ Ok(()) }}"
        );
        let _ = writeln!(
            out,
            "fn asset_summary(_params: &ParameterSet) -> Result<String> {{ Ok(String::new()) }}"
        );
    }

    Some(out)
}

const RESERVED_RUST_KEYWORDS: &[&str] = &[
    "as", "break", "const", "continue", "crate", "else", "enum", "extern", "false", "fn", "for",
    "if", "impl", "in", "let", "loop", "match", "mod", "move", "mut", "pub", "ref", "return",
    "self", "static", "struct", "super", "trait", "true", "type", "unsafe", "use", "where",
    "while", "async", "await", "dyn", "abstract", "become", "box", "do", "final", "macro",
    "override", "priv", "typeof", "unsized", "virtual", "yield", "try",
];

fn safe_param_id(id: &str) -> String {
    if RESERVED_RUST_KEYWORDS.contains(&id) {
        format!("p_{}", id)
    } else {
        id.to_string()
    }
}

fn write_param_imports(out: &mut String, has_bool: bool) {
    let _ = writeln!(out, "use block_core::param::{{");
    if has_bool {
        let _ = writeln!(
            out,
            "    bool_parameter, float_parameter, required_bool, required_f32,"
        );
        let _ = writeln!(
            out,
            "    ModelParameterSchema, ParameterSet, ParameterUnit,"
        );
    } else {
        let _ = writeln!(
            out,
            "    float_parameter, required_f32, ModelParameterSchema, ParameterSet, ParameterUnit,"
        );
    }
    let _ = writeln!(out, "}};");
}

fn write_core_imports(out: &mut String, audio_mode: AudioMode) {
    match audio_mode {
        AudioMode::DualMono | AudioMode::MonoOnly => {
            let _ = writeln!(out, "use block_core::{{AudioChannelLayout, BlockProcessor, ModelAudioMode, MonoProcessor, StereoProcessor}};");
        }
        AudioMode::MonoToStereo => {
            let _ = writeln!(
                out,
                "use block_core::{{AudioChannelLayout, BlockProcessor, ModelAudioMode}};"
            );
        }
        AudioMode::TrueStereo => {
            let _ = writeln!(
                out,
                "use block_core::{{AudioChannelLayout, BlockProcessor, ModelAudioMode}};"
            );
        }
    }
}

/// Build a unique const name per port, indexed by port index.
fn name_ports(plugin: &Plugin) -> std::collections::HashMap<usize, String> {
    let mut names = std::collections::HashMap::new();
    let mut used: HashSet<String> = HashSet::new();
    for port in &plugin.ports {
        if matches!(port.kind, PortKind::Other) {
            continue;
        }
        let mut base = port_const_base(port);
        if used.contains(&base) {
            base = format!("{}_{}", base, port.index);
        }
        used.insert(base.clone());
        names.insert(port.index, base);
    }
    names
}

fn port_const_base(port: &Port) -> String {
    use heck::ToShoutySnakeCase;
    let role = match (port.kind, port.direction) {
        (PortKind::Audio, PortDirection::Input) => "AUDIO_IN",
        (PortKind::Audio, PortDirection::Output) => "AUDIO_OUT",
        (PortKind::Control, _) => "CTRL",
        (PortKind::Cv, PortDirection::Input) => "CV_IN",
        (PortKind::Cv, PortDirection::Output) => "CV_OUT",
        (PortKind::Atom, PortDirection::Input) => "ATOM_IN",
        (PortKind::Atom, PortDirection::Output) => "ATOM_OUT",
        (PortKind::Event, PortDirection::Input) => "EVENT_IN",
        (PortKind::Event, PortDirection::Output) => "EVENT_OUT",
        _ => "PORT",
    };
    let sym: String = port
        .symbol
        .to_shouty_snake_case()
        .chars()
        .filter(|c| c.is_ascii_alphanumeric() || *c == '_')
        .collect();
    if sym.is_empty() {
        format!("PORT_{}_{}", role, port.index)
    } else {
        format!("PORT_{}_{}", role, sym)
    }
}

fn audio_const_list(
    plugin: &Plugin,
    names: &std::collections::HashMap<usize, String>,
    dir: PortDirection,
) -> Vec<String> {
    let mut entries: Vec<(usize, String)> = plugin
        .ports
        .iter()
        .filter(|p| p.kind == PortKind::Audio && p.direction == dir)
        .filter_map(|p| names.get(&p.index).map(|n| (p.index, n.clone())))
        .collect();
    entries.sort_by_key(|(i, _)| *i);
    entries.into_iter().map(|(_, n)| n).collect()
}

fn write_port_consts(
    out: &mut String,
    plugin: &Plugin,
    names: &std::collections::HashMap<usize, String>,
) {
    let _ = writeln!(out, "// Port indices (from TTL)");
    let mut entries: Vec<(usize, &String)> = names.iter().map(|(i, n)| (*i, n)).collect();
    entries.sort_by_key(|(i, _)| *i);
    for (idx, name) in entries {
        let _ = writeln!(out, "const {}: usize = {};", name, idx);
    }
    let _ = plugin; // unused but kept for future
}

fn write_schema_fn(
    out: &mut String,
    audio_mode: AudioMode,
    effect_type: &str,
    ctrl_ports: &[&Port],
) {
    let _ = writeln!(out, "pub fn model_schema() -> ModelParameterSchema {{");
    let _ = writeln!(out, "    ModelParameterSchema {{");
    let _ = writeln!(out, "        effect_type: {}.into(),", effect_type);
    let _ = writeln!(out, "        model: MODEL_ID.into(),");
    let _ = writeln!(out, "        display_name: DISPLAY_NAME.into(),");
    let _ = writeln!(out, "        audio_mode: {},", audio_mode.variant_path());
    let _ = writeln!(out, "        parameters: vec![");
    for port in ctrl_ports {
        let _ = writeln!(out, "            {},", render_param(port));
    }
    let _ = writeln!(out, "        ],");
    let _ = writeln!(out, "    }}");
    let _ = writeln!(out, "}}");
}

fn render_param(port: &Port) -> String {
    let symbol = safe_param_id(&sanitize_param_id(&port.symbol));
    let label = port
        .name
        .as_deref()
        .map(escape_str)
        .unwrap_or_else(|| symbol.clone());
    let unit = guess_unit(port);
    let default = port.default.unwrap_or(0.0);
    let min = port.minimum.unwrap_or(0.0);
    let max = port.maximum.unwrap_or(1.0);

    if port.is_toggle {
        return format!(
            "bool_parameter(\"{}\", \"{}\", None, Some({}))",
            symbol,
            label,
            default != 0.0
        );
    }
    let step = pick_step(min, max);
    format!(
        "float_parameter(\"{}\", \"{}\", None, Some({:?}), {:?}, {:?}, {:?}, ParameterUnit::{})",
        symbol, label, default, min, max, step, unit
    )
}

fn pick_step(min: f32, max: f32) -> f32 {
    let range = (max - min).abs();
    if range >= 1000.0 {
        10.0
    } else if range >= 100.0 {
        1.0
    } else if range >= 10.0 {
        0.1
    } else if range >= 1.0 {
        0.01
    } else {
        0.001
    }
}

fn guess_unit(port: &Port) -> &'static str {
    let unit = port.unit_uri.as_deref().unwrap_or("");
    if unit.ends_with("#hz") || unit.ends_with("hertz") {
        "Hertz"
    } else if unit.ends_with("#db") || unit.ends_with("decibel") {
        "Decibels"
    } else if unit.ends_with("#ms") || unit.ends_with("millisecond") {
        "Milliseconds"
    } else if unit.ends_with("#s") || unit.ends_with("second") {
        // ParameterUnit has no Seconds variant — collapse to Milliseconds.
        "Milliseconds"
    } else if unit.ends_with("#pc") || unit.ends_with("percent") {
        "Percent"
    } else if unit.ends_with("semitone") {
        "Semitones"
    } else if unit.ends_with("ratio") {
        "Ratio"
    } else {
        "None"
    }
}

fn sanitize_param_id(s: &str) -> String {
    s.chars()
        .map(|c| if c.is_ascii_alphanumeric() { c } else { '_' })
        .collect::<String>()
        .to_lowercase()
        .trim_matches('_')
        .to_string()
}

fn write_build_fn(
    out: &mut String,
    audio_mode: AudioMode,
    audio_in_consts: &[String],
    audio_out_consts: &[String],
    ctrl_ports: &[&Port],
    names: &std::collections::HashMap<usize, String>,
) {
    let _ = writeln!(
        out,
        "fn build(params: &ParameterSet, sample_rate: f32, layout: AudioChannelLayout) -> Result<BlockProcessor> {{"
    );

    for port in ctrl_ports {
        let id = safe_param_id(&sanitize_param_id(&port.symbol));
        if port.is_toggle {
            let _ = writeln!(
                out,
                "    let {} = required_bool(params, \"{}\").map_err(anyhow::Error::msg)?;",
                id, id
            );
        } else {
            let _ = writeln!(
                out,
                "    let {} = required_f32(params, \"{}\").map_err(anyhow::Error::msg)?;",
                id, id
            );
        }
    }

    let _ = writeln!(
        out,
        "    let lib_path = lv2::resolve_lv2_lib(PLUGIN_BINARY)?;"
    );
    let _ = writeln!(
        out,
        "    let bundle_path = lv2::resolve_lv2_bundle(PLUGIN_DIR)?;"
    );
    let _ = writeln!(out);
    let _ = writeln!(out, "    let control_ports: &[(usize, f32)] = &[");
    for port in ctrl_ports {
        let id = safe_param_id(&sanitize_param_id(&port.symbol));
        let const_name = names
            .get(&port.index)
            .cloned()
            .unwrap_or_else(|| format!("PORT_CTRL_{}", port.index));
        if port.is_toggle {
            let _ = writeln!(
                out,
                "        ({}, if {} {{ 1.0 }} else {{ 0.0 }}),",
                const_name, id
            );
        } else {
            let _ = writeln!(out, "        ({}, {}),", const_name, id);
        }
    }
    let _ = writeln!(out, "    ];");
    let _ = writeln!(out);

    write_runtime_branch(out, audio_mode, audio_in_consts, audio_out_consts);
}

fn write_runtime_branch(
    out: &mut String,
    audio_mode: AudioMode,
    audio_in_consts: &[String],
    audio_out_consts: &[String],
) {
    let join = |v: &[String]| v.join(", ");
    match audio_mode {
        AudioMode::DualMono | AudioMode::MonoOnly => {
            let in_c = audio_in_consts
                .first()
                .cloned()
                .unwrap_or_else(|| "0".to_string());
            let out_c = audio_out_consts
                .first()
                .cloned()
                .unwrap_or_else(|| "0".to_string());
            let _ = writeln!(out, "    match layout {{");
            let _ = writeln!(out, "        AudioChannelLayout::Mono => {{");
            let _ = writeln!(out, "            let processor = lv2::build_lv2_processor(&lib_path, PLUGIN_URI, sample_rate as f64, &bundle_path, &[{}], &[{}], control_ports)?;", in_c, out_c);
            let _ = writeln!(
                out,
                "            Ok(BlockProcessor::Mono(Box::new(processor)))"
            );
            let _ = writeln!(out, "        }}");
            let _ = writeln!(out, "        AudioChannelLayout::Stereo => {{");
            let _ = writeln!(out, "            let left = lv2::build_lv2_processor(&lib_path, PLUGIN_URI, sample_rate as f64, &bundle_path, &[{}], &[{}], control_ports)?;", in_c, out_c);
            let _ = writeln!(out, "            let right = lv2::build_lv2_processor(&lib_path, PLUGIN_URI, sample_rate as f64, &bundle_path, &[{}], &[{}], control_ports)?;", in_c, out_c);
            let _ = writeln!(out, "            Ok(BlockProcessor::Stereo(Box::new(DualMonoProcessor {{ left, right }})))");
            let _ = writeln!(out, "        }}");
            let _ = writeln!(out, "    }}");
            let _ = writeln!(out, "}}");
            let _ = writeln!(out);
            let _ = writeln!(
                out,
                "struct DualMonoProcessor {{ left: lv2::Lv2Processor, right: lv2::Lv2Processor }}"
            );
            let _ = writeln!(out, "impl StereoProcessor for DualMonoProcessor {{");
            let _ = writeln!(
                out,
                "    fn process_frame(&mut self, input: [f32; 2]) -> [f32; 2] {{"
            );
            let _ = writeln!(
                out,
                "        [self.left.process_sample(input[0]), self.right.process_sample(input[1])]"
            );
            let _ = writeln!(out, "    }}");
            let _ = writeln!(out, "}}");
        }
        AudioMode::MonoToStereo => {
            let in_c = audio_in_consts
                .first()
                .cloned()
                .unwrap_or_else(|| "0".to_string());
            let out_l = audio_out_consts
                .first()
                .cloned()
                .unwrap_or_else(|| "0".to_string());
            let extras: Vec<String> = audio_out_consts.iter().skip(1).cloned().collect();
            let _ = writeln!(out, "    let extra_outs: &[usize] = &[{}];", join(&extras));
            let _ = writeln!(out, "    let _ = layout;");
            let _ = writeln!(out, "    let processor = lv2::build_lv2_processor_with_extras(&lib_path, PLUGIN_URI, sample_rate as f64, &bundle_path, &[{}], &[{}], control_ports, extra_outs)?;", in_c, out_l);
            let _ = writeln!(out, "    Ok(BlockProcessor::Mono(Box::new(processor)))");
            let _ = writeln!(out, "}}");
        }
        AudioMode::TrueStereo => {
            let in_c = join(audio_in_consts);
            let out_c = join(audio_out_consts);
            let _ = writeln!(out, "    let processor = lv2::build_stereo_lv2_processor(&lib_path, PLUGIN_URI, sample_rate as f64, &bundle_path, &[{}], &[{}], control_ports)?;", in_c, out_c);
            let _ = writeln!(out, "    let _ = layout;");
            let _ = writeln!(out, "    Ok(BlockProcessor::Stereo(Box::new(processor)))");
            let _ = writeln!(out, "}}");
        }
    }
}

fn strip_kind(path: &str) -> &str {
    path.split("::").next().unwrap_or(path)
}

fn escape_str(s: &str) -> String {
    s.replace('\\', "\\\\").replace('"', "\\\"")
}
