import { ProjectLauncherPage } from "project_launcher.slint";
import { ProjectSettingsPage } from "project_settings.slint";
import { ProjectTracksPage } from "project_tracks.slint";
import { TrackEditorPage } from "track_editor.slint";

export { ProjectLauncherPage, ProjectSettingsPage, ProjectTracksPage, TrackEditorPage }

export component WizardConfigPage inherits Rectangle {
    background: transparent;
}
