import { ProjectLauncherPage } from "project_launcher.slint";
import { ProjectSettingsPage } from "project_settings.slint";
import { ProjectChainsPage, BlockEditorPanel } from "project_chains.slint";
import { ChainEditorPage } from "chain_editor.slint";
import { ChainEndpointEditorPage } from "chain_endpoint_editor.slint";
import { AmpPanelEditor } from "amp_panel_editor.slint";

export { ProjectLauncherPage, ProjectSettingsPage, ProjectChainsPage, BlockEditorPanel, ChainEditorPage, ChainEndpointEditorPage, AmpPanelEditor }

export component WizardConfigPage inherits Rectangle {
    background: transparent;
}
