import { WizardConfigPage } from "wizard_config.slint";
import { ProjectLauncherPage } from "project_launcher.slint";
import { ProjectTracksPage } from "project_tracks.slint";
import { TrackEditorPage } from "track_editor.slint";
import { ProjectSettingsPage } from "project_settings.slint";

export { WizardConfigPage }
export { ProjectLauncherPage }
export { ProjectTracksPage }
export { TrackEditorPage }
export { ProjectSettingsPage }
