#!/bin/bash
# Armbian customize-image.sh hook.
# Runs INSIDE the image chroot after base packages are installed.
# /tmp/overlay/ contains the contents of orange-pi/rootfs/ plus the staged binary and libs.
set -euo pipefail

RELEASE="$1"   # e.g. "bookworm"

echo ">>> [OpenRig] Customizing image for release: $RELEASE"

# ── 1. Install runtime dependencies ──────────────────────────────────────────
echo "jackd2 jackd/tweak_rt_limits boolean true" | debconf-set-selections
DEBIAN_FRONTEND=noninteractive apt-get update -qq
DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
    alsa-utils \
    jackd2 \
    libfreetype6 \
    libfontconfig1 \
    libdrm2 \
    libseat1 \
    libgles2 \
    libgl1-mesa-dri \
    weston \
    adwaita-icon-theme \
    plymouth \
    librsvg2-bin \
    udev \
    locales \
    tzdata \
    keyboard-configuration \
    console-setup

# ── 2. Copy rootfs overlay (etc, usr) ────────────────────────────────────────
echo ">>> [OpenRig] Copying rootfs overlay (systemd, plymouth, helpers)..."
cp -r /tmp/overlay/etc /
cp -r /tmp/overlay/usr /

# ── 3. Install OpenRig from the staged .deb ──────────────────────────────────
echo ">>> [OpenRig] Installing openrig.deb..."
DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
    /tmp/overlay/openrig.deb

if [ ! -e /usr/share/openrig/libs ]; then
    ln -sf /usr/lib/openrig/libs /usr/share/openrig/libs
fi

rm -rf /var/lib/apt/lists/*

# ── 5. Convert OpenRig logo SVGs → PNGs for Plymouth ────────────────────────
echo ">>> [OpenRig] Converting logo assets to PNG..."
rsvg-convert \
    -w 256 -h 256 \
    /tmp/overlay/openrig-logomark.svg \
    -o /usr/share/plymouth/themes/openrig/logo.png
rsvg-convert \
    -w 400 \
    /tmp/overlay/openrig-logotype.svg \
    -o /usr/share/plymouth/themes/openrig/logotype.png

# ── 6. Register and activate Plymouth theme ──────────────────────────────────
echo ">>> [OpenRig] Activating Plymouth theme..."
# plymouth-set-default-theme writes Theme= to /etc/plymouth/plymouthd.conf
# AND updates the alternatives symlink. update-alternatives alone only updates
# the symlink — plymouthd.conf stays at default ("text") and Plymouth ignores
# the symlink when plymouthd.conf has an explicit (or default) value.
plymouth-set-default-theme openrig

# Load rockchipdrm in the initramfs so Plymouth has a DRM device to render on.
# simpledrm does NOT bind on RK3588 (no simple-framebuffer DT node). The actual
# display driver is rockchipdrm — a .ko module that is not built into the kernel.
# Adding it here causes initramfs-tools to include it (and all modprobe deps) in
# the initramfs so /dev/dri/card1 is available before plymouthd starts.
echo 'rockchipdrm' >> /etc/initramfs-tools/modules

# The default Plymouth initramfs hook does NOT copy the 'script' plugin nor
# the openrig theme files — it only copies the 'details' fallback. This custom
# hook explicitly copies both so the theme works at early boot.
TRIPLET="$(dpkg-architecture -qDEB_HOST_MULTIARCH 2>/dev/null || echo "aarch64-linux-gnu")"
cat > /etc/initramfs-tools/hooks/openrig-plymouth << HOOK_EOF
#!/bin/sh
PREREQ="plymouth"
prereqs() { echo "\$PREREQ"; }
case "\$1" in prereqs) prereqs; exit 0;; esac
. /usr/share/initramfs-tools/hook-functions

# Plymouth script plugin (required by ModuleName=script themes)
PLUGIN_DIR="usr/lib/${TRIPLET}/plymouth"
mkdir -p "\${DESTDIR}/\${PLUGIN_DIR}"
cp -a "/\${PLUGIN_DIR}/script.so" "\${DESTDIR}/\${PLUGIN_DIR}/" 2>/dev/null || true

# OpenRig theme files (logo.png generated by customize-image.sh step 5)
THEME_SRC="/usr/share/plymouth/themes/openrig"
THEME_DST="\${DESTDIR}/usr/share/plymouth/themes/openrig"
mkdir -p "\${THEME_DST}"
cp -a "\${THEME_SRC}/." "\${THEME_DST}/"
HOOK_EOF
chmod +x /etc/initramfs-tools/hooks/openrig-plymouth

# Rebuild initramfs with rockchipdrm + script plugin + openrig theme baked in.
# OPENRIG_SKIP_INITRAMFS=1 is set when this script runs inside a qemu-user
# chroot (the "official image" Docker pipeline) because update-initramfs
# emulated under qemu can produce a broken initrd that fails to boot. In
# that case we keep the initrd that Armbians maintainers shipped with the
# official image, and defer this rebuild to a first-boot oneshot on the
# board itself.
if [ "${OPENRIG_SKIP_INITRAMFS:-0}" = "1" ]; then
    echo ">>> [OpenRig] Skipping update-initramfs (runs on first boot instead)"
    cat > /etc/systemd/system/openrig-initramfs-rebuild.service << 'UNIT_EOF'
[Unit]
Description=Rebuild initramfs on first boot (OpenRig Plymouth theme + rockchipdrm)
DefaultDependencies=yes
# After (not Before) multi-user.target so the boot completes even if
# update-initramfs takes minutes or stalls — the board reaches SSH/network
# first, then the rebuild runs in the background. Next boot picks up the
# rebuilt initramfs. This avoids blocking a first boot on a chroot-assembled
# initramfs whose only purpose is to upgrade cosmetic Plymouth branding.
After=multi-user.target
ConditionPathExists=!/var/lib/openrig-initramfs-done

[Service]
Type=oneshot
ExecStart=/usr/sbin/update-initramfs -u -k all
ExecStartPost=/bin/sh -c 'touch /var/lib/openrig-initramfs-done'
RemainAfterExit=yes

[Install]
WantedBy=multi-user.target
UNIT_EOF
    systemctl enable openrig-initramfs-rebuild.service
else
    update-initramfs -u -k all
fi

# ── 7. Create users with fixed passwords ─────────────────────────────────────
echo ">>> [OpenRig] Creating openrig user and setting passwords..."
for g in audio video tty input render plugdev dialout; do
    groupadd -f "$g"
done
if ! id openrig >/dev/null 2>&1; then
    useradd --create-home \
        --groups audio,video,tty,input,render,plugdev,dialout \
        --shell /bin/bash \
        openrig
fi
chown -R openrig:openrig /home/openrig
echo 'openrig:openrig' | chpasswd
echo 'root:root'       | chpasswd

# Pre-configure audio device settings for TEYUN Q26 via JACK.
# Both input and output point to jack:system so OpenRig uses a single
# clock and channels are selectable from first boot.
mkdir -p /root/.config/OpenRig
cat > /root/.config/OpenRig/gui-settings.yaml << 'GUI_SETTINGS'
input_devices:
- device_id: jack:system
  name: TEYUN Q26 (JACK)
  sample_rate: 48000
  buffer_size_frames: 64
  bit_depth: 32
output_devices:
- device_id: jack:system
  name: TEYUN Q26 (JACK)
  sample_rate: 48000
  buffer_size_frames: 64
  bit_depth: 32
GUI_SETTINGS

# Create the default project config that openrig.service uses.
cat > /etc/openrig.yaml << 'DEFAULT_PROJECT'
version: 1
name: My Rig
chains:
  - description: guitar 1
    instrument: electric_guitar
    blocks:
      - type: input
        model: standard
        enabled: true
        entries:
          - device_id: "jack:system"
            mode: mono
            channels: [0]
      - type: output
        model: standard
        enabled: true
        entries:
          - device_id: "jack:system"
            mode: stereo
            channels: [0, 1]
DEFAULT_PROJECT

# ── 8. Locale, keyboard, timezone ────────────────────────────────────────────
echo ">>> [OpenRig] Configuring locale (en_US.UTF-8), keyboard (br-abnt2), timezone (America/Sao_Paulo)..."

sed -i 's/^# *en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/' /etc/locale.gen
locale-gen en_US.UTF-8
update-locale LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8 LANGUAGE=en_US:en

cat > /etc/default/keyboard <<'EOF'
XKBMODEL="abnt2"
XKBLAYOUT="br"
XKBVARIANT="abnt2"
XKBOPTIONS=""
BACKSPACE="guess"
EOF

ln -sf /usr/share/zoneinfo/America/Sao_Paulo /etc/localtime
echo 'America/Sao_Paulo' > /etc/timezone
dpkg-reconfigure -f noninteractive tzdata || true

# ── 8b. Audio RT capabilities ────────────────────────────────────────────────
echo ">>> [OpenRig] Setting JACK RT capabilities and audio group membership..."
setcap cap_sys_nice,cap_ipc_lock=ep /usr/bin/jackd || true
usermod -aG audio root

# ── 9. Enable systemd services ───────────────────────────────────────────────
echo ">>> [OpenRig] Enabling services, masking jackd..."
systemctl disable jackd.service  2>/dev/null || true
systemctl mask    jackd.service  2>/dev/null || true
systemctl enable weston.service
systemctl enable openrig.service
systemctl enable openrig-irq-affinity.service
systemctl enable openrig-resize-rootfs.service

# ── 9b. Kill stale ALSA mixer state ──────────────────────────────────────────
# alsa-restore.service runs at boot and restores ALSA mixer controls from
# /var/lib/alsa/asound.state if present. A state file produced during image
# build or baked into the base rootfs can resurrect attenuated defaults
# (e.g. Q-26 boots with PCM Playback at 60/100 = -20 dB instead of unity)
# and overrides the udev rule that sets USB audio PCM to 100% on attach.
# Wipe the file so the udev rule wins the race; alsa-store on shutdown
# will repopulate it with whatever the user actually chose at runtime.
echo ">>> [OpenRig] Removing stale ALSA mixer state to let udev rule win..."
rm -f /var/lib/alsa/asound.state

# ── 9a. Plymouth quit failsafe ────────────────────────────────────────────────
echo ">>> [OpenRig] Capping plymouth-quit-wait timeout at 10s..."
mkdir -p /etc/systemd/system/plymouth-quit-wait.service.d/
cat > /etc/systemd/system/plymouth-quit-wait.service.d/openrig-timeout.conf << 'EOF'
[Service]
TimeoutStartSec=10
EOF

# ── 10. Set permissions on install script ────────────────────────────────────
chmod 755 /usr/local/bin/openrig-install-to-emmc
chmod 755 /usr/local/bin/openrig-resize-rootfs
chmod 755 /usr/local/bin/openrig-set-usb-audio-volume

# ── 10a. USB-C TCPM workaround (RK3588 USB-C port stability) ─────────────────
echo ">>> [OpenRig] Installing USB-C host-mode DTB overlay (Scarlett stability)..."
if command -v armbian-add-overlay >/dev/null 2>&1; then
    armbian-add-overlay /tmp/overlay/openrig-usbc-host.dts || \
        echo ">>> [OpenRig] WARNING: armbian-add-overlay failed, skipping USB-C overlay"
else
    echo ">>> [OpenRig] armbian-add-overlay missing, falling back to manual dtc"
    mkdir -p /boot/overlay-user
    dtc -I dts -O dtb -o /boot/overlay-user/openrig-usbc-host.dtbo \
        /tmp/overlay/openrig-usbc-host.dts || \
        echo ">>> [OpenRig] WARNING: dtc failed, skipping USB-C overlay"
    if grep -q '^user_overlays=' /boot/armbianEnv.txt 2>/dev/null; then
        sed -i 's|^user_overlays=.*|&  openrig-usbc-host|' /boot/armbianEnv.txt || true
    else
        echo 'user_overlays=openrig-usbc-host' >> /boot/armbianEnv.txt || true
    fi
fi

# ── 11. Silent kiosk boot + RT audio CPU isolation ──────────────────────────
echo ">>> [OpenRig] Configuring silent kiosk boot and RT audio CPU isolation..."

# CPU isolation for RT audio (RK3588 big.LITTLE: 0-3 = A55 little, 4-7 = A76 big):
#   isolcpus=4-7    Scheduler skips 4-7 by default; DSP worker and jackd get
#                   exclusive use of the big cores via explicit sched_setaffinity.
#   nohz_full=4-7   Disable scheduling-tick timer on 4-7 when only one task runs,
#                   eliminating timer-interrupt jitter (sub-µs stability).
#   rcu_nocbs=4-7   Keep RCU callbacks off the big cores so audio is never
#                   preempted by kernel housekeeping bursts.
#   irqaffinity=0-3 All IRQs default to the little cores, leaving the audio
#                   path free of device-interrupt jitter.
# Without this, UI repaints and kernel work share big cores with the DSP worker
# and the JACK RT callback — mouse over blocks produces audible clicks.
KERNEL_ARGS='quiet splash loglevel=3 rd.systemd.show_status=false rd.udev.log_level=3 isolcpus=4-7 nohz_full=4-7 rcu_nocbs=4-7 irqaffinity=0-3'
if grep -q "^extraargs=" /boot/armbianEnv.txt 2>/dev/null; then
    sed -i "s|^extraargs=.*|extraargs=${KERNEL_ARGS}|" /boot/armbianEnv.txt
else
    echo "extraargs=${KERNEL_ARGS}" >> /boot/armbianEnv.txt
fi

sed -i 's/^verbosity=.*/verbosity=0/' /boot/armbianEnv.txt 2>/dev/null || true
sed -i 's/^console=.*/console=serial/' /boot/armbianEnv.txt 2>/dev/null || true
sed -i 's/^bootlogo=.*/bootlogo=true/' /boot/armbianEnv.txt 2>/dev/null || true

# Armbian first-run wizard and filesystem resize.
rm -f /root/.not_logged_in_yet
touch /root/.no_rootfs_resize_at_firstboot
systemctl disable armbian-firstrun.service              2>/dev/null || true
systemctl disable armbian-firstrun-config.service       2>/dev/null || true
systemctl disable armbian-resize-filesystem.service     2>/dev/null || true
systemctl mask    armbian-firstrun.service              2>/dev/null || true
systemctl mask    armbian-firstrun-config.service       2>/dev/null || true
systemctl mask    armbian-resize-filesystem.service     2>/dev/null || true
rm -f /etc/profile.d/armbian-check-first-run.sh
rm -f /etc/update-motd.d/30-armbian-sysinfo             2>/dev/null || true

# Mask gettys so no text login prompt appears on any tty.
for tty in 1 2 3 4 5 6; do
    systemctl disable "getty@tty${tty}.service" 2>/dev/null || true
    systemctl mask    "getty@tty${tty}.service" 2>/dev/null || true
done
systemctl disable serial-getty@ttyS0.service  2>/dev/null || true
systemctl mask    serial-getty@ttyS0.service  2>/dev/null || true

echo ">>> [OpenRig] Image customization complete."
