export struct Palette {
    pure-black: brush,
    deep-space: brush,
    card: brush,
    card-secondary: brush,
    row-start: brush,
    row-end: brush,
    border: brush,
    border-strong: brush,
    text-primary: brush,
    text-secondary: brush,
    text-muted: brush,
    accent-start: brush,
    accent-end: brush,
    accent-border: brush,
    secondary-start: brush,
    secondary-end: brush,
    secondary-border: brush,
    background-gradient: brush,
}

export struct Spaces {
    small: length,
    medium: length,
    large: length,
    xlarge: length,
}

struct Font {
    size: length,
    weight: float,
}

export struct Typo {
    brand: Font,
    section: Font,
    body: Font,
    caption: Font,
    button: Font,
}

export global Theme {
    in property <Palette> palette: {
        pure-black: #040708,
        deep-space: #070b2a,
        card: #070b2a,
        card-secondary: #090d33,
        row-start: #181d44,
        row-end: #121730,
        border: #252d6d,
        border-strong: #283171,
        text-primary: #ffffff,
        text-secondary: #dce2ff,
        text-muted: #a6aed8,
        accent-start: #8e73ff,
        accent-end: #694dff,
        accent-border: #7d63ff,
        secondary-start: #1a2250,
        secondary-end: #121838,
        secondary-border: #4e5aa6,
        background-gradient: @radial-gradient(circle, #0d1a7850 0%, #040708 72%),
    };

    in property <Spaces> spaces: {
        small: 5px,
        medium: 10px,
        large: 20px,
        xlarge: 20px,
    };

    in property <Typo> typo: {
        brand: {
            size: 18px,
            weight: 600
        },
        section: {
            size: 16px,
            weight: 600
        },
        body: {
            size: 14px,
            weight: 400
        },
        caption: {
            size: 12px,
            weight: 400
        },
        button: {
            size: 14px,
            weight: 500
        },
    };
}
