// AUTO-GENERATED by tools/lv2_catalog_import — do not edit by hand.
// Re-run the tool to regenerate. Manual customisation goes in overrides.yaml.

#![allow(dead_code, unused_imports, unused_variables, clippy::all)]

use crate::registry::PitchModelDefinition;
use crate::PitchBackendKind;
use anyhow::Result;
use block_core::param::{
    float_parameter, required_f32, ModelParameterSchema, ParameterSet, ParameterUnit,
};
use block_core::{AudioChannelLayout, BlockProcessor, ModelAudioMode, MonoProcessor, StereoProcessor};

pub const MODEL_ID: &str = "lv2_gx_detune";
pub const DISPLAY_NAME: &str = "Gxdetune";
const BRAND: &str = "guitarix";

const PLUGIN_URI: &str = "http://guitarix.sourceforge.net/plugins/gx_detune_#_detune_";
const PLUGIN_DIR: &str = "gx_detune";
pub const THUMBNAIL_PATH: Option<&str> = Some(".plugins/lv2/gx_detune.lv2/modgui/thumbnail-gxdetune.png");

#[cfg(target_os = "macos")]
const PLUGIN_BINARY: &str = "gx_detune.dylib";
#[cfg(target_os = "linux")]
const PLUGIN_BINARY: &str = "gx_detune.so";
#[cfg(target_os = "windows")]
const PLUGIN_BINARY: &str = "gx_detune.dll";

// Port indices (from TTL)
const PORT_AUDIO_OUT_OUT: usize = 0;
const PORT_AUDIO_IN_IN: usize = 1;
const PORT_CTRL_DETUNE: usize = 2;
const PORT_CTRL_OCTAVE: usize = 3;
const PORT_CTRL_COMPENSATE: usize = 4;
const PORT_CTRL_LATENCY: usize = 5;
const PORT_CTRL_WET: usize = 6;
const PORT_CTRL_DRY: usize = 7;
const PORT_CTRL_LOW: usize = 8;
const PORT_CTRL_MIDDLELOW: usize = 9;
const PORT_CTRL_MIDDLETREBLE: usize = 10;
const PORT_CTRL_TREBLE: usize = 11;
const PORT_CTRL_LATENC: usize = 12;

pub fn model_schema() -> ModelParameterSchema {
    ModelParameterSchema {
        effect_type: block_core::EFFECT_TYPE_PITCH.into(),
        model: MODEL_ID.into(),
        display_name: DISPLAY_NAME.into(),
        audio_mode: ModelAudioMode::DualMono,
        parameters: vec![
            float_parameter("detune", "DETUNE", None, Some(0.0), -0.25, 0.25, 0.001, ParameterUnit::None),
            float_parameter("octave", "OCTAVE", None, Some(0.0), 0.0, 2.0, 0.01, ParameterUnit::None),
            float_parameter("compensate", "COMPENSATE", None, Some(0.0), 0.0, 1.0, 0.01, ParameterUnit::None),
            float_parameter("latency", "LATENCY", None, Some(1.0), 0.0, 2.0, 0.01, ParameterUnit::None),
            float_parameter("wet", "WET", None, Some(50.0), 0.0, 100.0, 1.0, ParameterUnit::None),
            float_parameter("dry", "DRY", None, Some(50.0), 0.0, 100.0, 1.0, ParameterUnit::None),
            float_parameter("low", "LOW", None, Some(1.0), 0.0, 2.0, 0.01, ParameterUnit::None),
            float_parameter("middlelow", "MIDDLELOW", None, Some(1.0), 0.0, 2.0, 0.01, ParameterUnit::None),
            float_parameter("middletreble", "MIDDLETREBLE", None, Some(1.0), 0.0, 2.0, 0.01, ParameterUnit::None),
            float_parameter("treble", "TREBLE", None, Some(1.0), 0.0, 2.0, 0.01, ParameterUnit::None),
        ],
    }
}

fn build(params: &ParameterSet, sample_rate: f32, layout: AudioChannelLayout) -> Result<BlockProcessor> {
    let detune = required_f32(params, "detune").map_err(anyhow::Error::msg)?;
    let octave = required_f32(params, "octave").map_err(anyhow::Error::msg)?;
    let compensate = required_f32(params, "compensate").map_err(anyhow::Error::msg)?;
    let latency = required_f32(params, "latency").map_err(anyhow::Error::msg)?;
    let wet = required_f32(params, "wet").map_err(anyhow::Error::msg)?;
    let dry = required_f32(params, "dry").map_err(anyhow::Error::msg)?;
    let low = required_f32(params, "low").map_err(anyhow::Error::msg)?;
    let middlelow = required_f32(params, "middlelow").map_err(anyhow::Error::msg)?;
    let middletreble = required_f32(params, "middletreble").map_err(anyhow::Error::msg)?;
    let treble = required_f32(params, "treble").map_err(anyhow::Error::msg)?;
    let lib_path = lv2::resolve_lv2_lib(PLUGIN_BINARY)?;
    let bundle_path = lv2::resolve_lv2_bundle(PLUGIN_DIR)?;

    let control_ports: &[(usize, f32)] = &[
        (PORT_CTRL_DETUNE, detune),
        (PORT_CTRL_OCTAVE, octave),
        (PORT_CTRL_COMPENSATE, compensate),
        (PORT_CTRL_LATENCY, latency),
        (PORT_CTRL_WET, wet),
        (PORT_CTRL_DRY, dry),
        (PORT_CTRL_LOW, low),
        (PORT_CTRL_MIDDLELOW, middlelow),
        (PORT_CTRL_MIDDLETREBLE, middletreble),
        (PORT_CTRL_TREBLE, treble),
    ];

    match layout {
        AudioChannelLayout::Mono => {
            let processor = lv2::build_lv2_processor(&lib_path, PLUGIN_URI, sample_rate as f64, &bundle_path, &[PORT_AUDIO_IN_IN], &[PORT_AUDIO_OUT_OUT], control_ports)?;
            Ok(BlockProcessor::Mono(Box::new(processor)))
        }
        AudioChannelLayout::Stereo => {
            let left = lv2::build_lv2_processor(&lib_path, PLUGIN_URI, sample_rate as f64, &bundle_path, &[PORT_AUDIO_IN_IN], &[PORT_AUDIO_OUT_OUT], control_ports)?;
            let right = lv2::build_lv2_processor(&lib_path, PLUGIN_URI, sample_rate as f64, &bundle_path, &[PORT_AUDIO_IN_IN], &[PORT_AUDIO_OUT_OUT], control_ports)?;
            Ok(BlockProcessor::Stereo(Box::new(DualMonoProcessor { left, right })))
        }
    }
}

struct DualMonoProcessor { left: lv2::Lv2Processor, right: lv2::Lv2Processor }
impl StereoProcessor for DualMonoProcessor {
    fn process_frame(&mut self, input: [f32; 2]) -> [f32; 2] {
        [self.left.process_sample(input[0]), self.right.process_sample(input[1])]
    }
}

fn schema() -> Result<ModelParameterSchema> { Ok(model_schema()) }

pub const MODEL_DEFINITION: PitchModelDefinition = PitchModelDefinition {
    id: MODEL_ID, display_name: DISPLAY_NAME, brand: BRAND,
    backend_kind: PitchBackendKind::Lv2, schema, build,
    supported_instruments: block_core::ALL_INSTRUMENTS, knob_layout: &[],
};
