// AUTO-GENERATED by tools/lv2_catalog_import — do not edit by hand.
// Re-run the tool to regenerate. Manual customisation goes in overrides.yaml.

#![allow(dead_code, unused_imports, unused_variables, clippy::all)]

use crate::registry::PitchModelDefinition;
use crate::PitchBackendKind;
use anyhow::Result;
use block_core::param::{
    float_parameter, required_f32, ModelParameterSchema, ParameterSet, ParameterUnit,
};
use block_core::{AudioChannelLayout, BlockProcessor, ModelAudioMode};

pub const MODEL_ID: &str = "lv2_mod_mda_detune";
pub const DISPLAY_NAME: &str = "MDA Detune";
const BRAND: &str = "mda";

const PLUGIN_URI: &str = "http://moddevices.com/plugins/mda/Detune";
const PLUGIN_DIR: &str = "mod-mda-Detune";
pub const THUMBNAIL_PATH: Option<&str> = Some(".plugins/lv2/mod-mda-Detune.lv2/modgui/thumbnail-mda-detune.png");

#[cfg(target_os = "macos")]
const PLUGIN_BINARY: &str = "Detune.dylib";
#[cfg(target_os = "linux")]
const PLUGIN_BINARY: &str = "Detune.so";
#[cfg(target_os = "windows")]
const PLUGIN_BINARY: &str = "Detune.dll";

// Port indices (from TTL)
const PORT_CTRL_DETUNE: usize = 0;
const PORT_CTRL_MIX: usize = 1;
const PORT_CTRL_OUTPUT: usize = 2;
const PORT_CTRL_LATENCY: usize = 3;
const PORT_AUDIO_IN_LEFT_IN: usize = 4;
const PORT_AUDIO_IN_RIGHT_IN: usize = 5;
const PORT_AUDIO_OUT_LEFT_OUT: usize = 6;
const PORT_AUDIO_OUT_RIGHT_OUT: usize = 7;

pub fn model_schema() -> ModelParameterSchema {
    ModelParameterSchema {
        effect_type: block_core::EFFECT_TYPE_PITCH.into(),
        model: MODEL_ID.into(),
        display_name: DISPLAY_NAME.into(),
        audio_mode: ModelAudioMode::TrueStereo,
        parameters: vec![
            float_parameter("detune", "Detune", None, Some(2.4), 0.0, 300.0, 1.0, ParameterUnit::None),
            float_parameter("mix", "Mix", None, Some(50.0), 0.0, 99.0, 0.1, ParameterUnit::Percent),
            float_parameter("output", "Level", None, Some(0.0), -20.0, 20.0, 0.1, ParameterUnit::Decibels),
            float_parameter("latency", "Latency", None, Some(0.5), 0.0, 1.0, 0.01, ParameterUnit::Milliseconds),
        ],
    }
}

fn build(params: &ParameterSet, sample_rate: f32, layout: AudioChannelLayout) -> Result<BlockProcessor> {
    let detune = required_f32(params, "detune").map_err(anyhow::Error::msg)?;
    let mix = required_f32(params, "mix").map_err(anyhow::Error::msg)?;
    let output = required_f32(params, "output").map_err(anyhow::Error::msg)?;
    let latency = required_f32(params, "latency").map_err(anyhow::Error::msg)?;
    let lib_path = lv2::resolve_lv2_lib(PLUGIN_BINARY)?;
    let bundle_path = lv2::resolve_lv2_bundle(PLUGIN_DIR)?;

    let control_ports: &[(usize, f32)] = &[
        (PORT_CTRL_DETUNE, detune),
        (PORT_CTRL_MIX, mix),
        (PORT_CTRL_OUTPUT, output),
        (PORT_CTRL_LATENCY, latency),
    ];

    let processor = lv2::build_stereo_lv2_processor(&lib_path, PLUGIN_URI, sample_rate as f64, &bundle_path, &[PORT_AUDIO_IN_LEFT_IN, PORT_AUDIO_IN_RIGHT_IN], &[PORT_AUDIO_OUT_LEFT_OUT, PORT_AUDIO_OUT_RIGHT_OUT], control_ports)?;
    let _ = layout;
    Ok(BlockProcessor::Stereo(Box::new(processor)))
}

fn schema() -> Result<ModelParameterSchema> { Ok(model_schema()) }

pub const MODEL_DEFINITION: PitchModelDefinition = PitchModelDefinition {
    id: MODEL_ID, display_name: DISPLAY_NAME, brand: BRAND,
    backend_kind: PitchBackendKind::Lv2, schema, build,
    supported_instruments: block_core::ALL_INSTRUMENTS, knob_layout: &[],
};
