// AUTO-GENERATED by tools/lv2_catalog_import — do not edit by hand.
// Re-run the tool to regenerate. Manual customisation goes in overrides.yaml.

#![allow(dead_code, unused_imports, unused_variables, clippy::approx_constant, clippy::excessive_precision)]

use crate::registry::PitchModelDefinition;
use crate::PitchBackendKind;
use anyhow::Result;
use block_core::param::{
    bool_parameter, float_parameter, required_bool, required_f32,
    ModelParameterSchema, ParameterSet, ParameterUnit,
};
use block_core::{AudioChannelLayout, BlockProcessor, ModelAudioMode, MonoProcessor, StereoProcessor};

pub const MODEL_ID: &str = "lv2_fat1_scales";
pub const DISPLAY_NAME: &str = "x42-Autotune (scales)";
const BRAND: &str = "x42";

const PLUGIN_URI: &str = "http://gareus.org/oss/lv2/fat1#scales";
const PLUGIN_DIR: &str = "fat1";

#[cfg(target_os = "macos")]
const PLUGIN_BINARY: &str = "fat1.dylib.dylib";
#[cfg(target_os = "linux")]
const PLUGIN_BINARY: &str = "fat1.dylib.so";
#[cfg(target_os = "windows")]
const PLUGIN_BINARY: &str = "fat1.dylib.dll";

// Port indices (from TTL)
const PORT_ATOM_IN_MIDIIN: usize = 0;
const PORT_AUDIO_IN_IN: usize = 1;
const PORT_AUDIO_OUT_OUT: usize = 2;
const PORT_CTRL_MODE: usize = 3;
const PORT_CTRL_CHANNELF: usize = 4;
const PORT_CTRL_TUNING: usize = 5;
const PORT_CTRL_BIAS: usize = 6;
const PORT_CTRL_FILTER: usize = 7;
const PORT_CTRL_CORR: usize = 8;
const PORT_CTRL_OFFSET: usize = 9;
const PORT_CTRL_BENDRANGE: usize = 10;
const PORT_CTRL_FASTMODE: usize = 11;
const PORT_CTRL_SCALE: usize = 12;
const PORT_CTRL_NMASK: usize = 13;
const PORT_CTRL_NSET: usize = 14;
const PORT_CTRL_BEND: usize = 15;
const PORT_CTRL_ERROR: usize = 16;
const PORT_CTRL_LATENCY: usize = 17;

pub fn model_schema() -> ModelParameterSchema {
    ModelParameterSchema {
        effect_type: block_core::EFFECT_TYPE_PITCH.into(),
        model: MODEL_ID.into(),
        display_name: DISPLAY_NAME.into(),
        audio_mode: ModelAudioMode::DualMono,
        parameters: vec![
            float_parameter("mode", "Mode", None, Some(0.0), 0.0, 2.0, 0.01, ParameterUnit::None),
            float_parameter("channelf", "Filter Channel", None, Some(0.0), 0.0, 16.0, 0.1, ParameterUnit::None),
            float_parameter("tuning", "Tuning", None, Some(440.0), 400.0, 480.0, 0.1, ParameterUnit::Hertz),
            float_parameter("bias", "Bias", None, Some(0.5), 0.0, 1.0, 0.01, ParameterUnit::None),
            float_parameter("filter", "Filter", None, Some(0.1), 0.02, 0.5, 0.001, ParameterUnit::None),
            float_parameter("corr", "Correction", None, Some(1.0), 0.0, 1.0, 0.01, ParameterUnit::None),
            float_parameter("offset", "Offset", None, Some(0.0), -2.0, 2.0, 0.01, ParameterUnit::None),
            float_parameter("bendrange", "Pitch Bend Range", None, Some(2.0), 0.0, 7.0, 0.01, ParameterUnit::None),
            bool_parameter("fastmode", "Fast Correction", None, Some(false)),
            float_parameter("scale", "Scale", None, Some(0.0), 0.0, 24.0, 0.1, ParameterUnit::None),
        ],
    }
}

fn build(params: &ParameterSet, sample_rate: f32, layout: AudioChannelLayout) -> Result<BlockProcessor> {
    let mode = required_f32(params, "mode").map_err(anyhow::Error::msg)?;
    let channelf = required_f32(params, "channelf").map_err(anyhow::Error::msg)?;
    let tuning = required_f32(params, "tuning").map_err(anyhow::Error::msg)?;
    let bias = required_f32(params, "bias").map_err(anyhow::Error::msg)?;
    let filter = required_f32(params, "filter").map_err(anyhow::Error::msg)?;
    let corr = required_f32(params, "corr").map_err(anyhow::Error::msg)?;
    let offset = required_f32(params, "offset").map_err(anyhow::Error::msg)?;
    let bendrange = required_f32(params, "bendrange").map_err(anyhow::Error::msg)?;
    let fastmode = required_bool(params, "fastmode").map_err(anyhow::Error::msg)?;
    let scale = required_f32(params, "scale").map_err(anyhow::Error::msg)?;
    let lib_path = lv2::resolve_lv2_lib(PLUGIN_BINARY)?;
    let bundle_path = lv2::resolve_lv2_bundle(PLUGIN_DIR)?;

    let control_ports: &[(usize, f32)] = &[
        (PORT_CTRL_MODE, mode),
        (PORT_CTRL_CHANNELF, channelf),
        (PORT_CTRL_TUNING, tuning),
        (PORT_CTRL_BIAS, bias),
        (PORT_CTRL_FILTER, filter),
        (PORT_CTRL_CORR, corr),
        (PORT_CTRL_OFFSET, offset),
        (PORT_CTRL_BENDRANGE, bendrange),
        (PORT_CTRL_FASTMODE, if fastmode { 1.0 } else { 0.0 }),
        (PORT_CTRL_SCALE, scale),
    ];

    match layout {
        AudioChannelLayout::Mono => {
            let processor = lv2::build_lv2_processor(&lib_path, PLUGIN_URI, sample_rate as f64, &bundle_path, &[PORT_AUDIO_IN_IN], &[PORT_AUDIO_OUT_OUT], control_ports)?;
            Ok(BlockProcessor::Mono(Box::new(processor)))
        }
        AudioChannelLayout::Stereo => {
            let left = lv2::build_lv2_processor(&lib_path, PLUGIN_URI, sample_rate as f64, &bundle_path, &[PORT_AUDIO_IN_IN], &[PORT_AUDIO_OUT_OUT], control_ports)?;
            let right = lv2::build_lv2_processor(&lib_path, PLUGIN_URI, sample_rate as f64, &bundle_path, &[PORT_AUDIO_IN_IN], &[PORT_AUDIO_OUT_OUT], control_ports)?;
            Ok(BlockProcessor::Stereo(Box::new(DualMonoProcessor { left, right })))
        }
    }
}

struct DualMonoProcessor { left: lv2::Lv2Processor, right: lv2::Lv2Processor }
impl StereoProcessor for DualMonoProcessor {
    fn process_frame(&mut self, input: [f32; 2]) -> [f32; 2] {
        [self.left.process_sample(input[0]), self.right.process_sample(input[1])]
    }
}

fn schema() -> Result<ModelParameterSchema> { Ok(model_schema()) }

pub const MODEL_DEFINITION: PitchModelDefinition = PitchModelDefinition {
    id: MODEL_ID, display_name: DISPLAY_NAME, brand: BRAND,
    backend_kind: PitchBackendKind::Lv2, schema, build,
    supported_instruments: block_core::ALL_INSTRUMENTS, knob_layout: &[],
};
