// AUTO-GENERATED by tools/lv2_catalog_import — do not edit by hand.
// Re-run the tool to regenerate. Manual customisation goes in overrides.yaml.

#![allow(dead_code, unused_imports, unused_variables, clippy::approx_constant, clippy::excessive_precision)]

use crate::registry::PitchModelDefinition;
use crate::PitchBackendKind;
use anyhow::Result;
use block_core::param::{
    bool_parameter, float_parameter, required_bool, required_f32,
    ModelParameterSchema, ParameterSet, ParameterUnit,
};
use block_core::{AudioChannelLayout, BlockProcessor, ModelAudioMode};

pub const MODEL_ID: &str = "lv2_rkr_shifter";
pub const DISPLAY_NAME: &str = "rkr Shifter";
const BRAND: &str = "rkr";

const PLUGIN_URI: &str = "http://rakarrack.sourceforge.net/effects.html#Shifter";
const PLUGIN_DIR: &str = "rkr";

#[cfg(target_os = "macos")]
const PLUGIN_BINARY: &str = "plugin.dylib";
#[cfg(target_os = "linux")]
const PLUGIN_BINARY: &str = "plugin.so";
#[cfg(target_os = "windows")]
const PLUGIN_BINARY: &str = "plugin.dll";

// Port indices (from TTL)
const PORT_AUDIO_IN_INPUT_L: usize = 0;
const PORT_AUDIO_IN_INPUT_R: usize = 1;
const PORT_AUDIO_OUT_OUTPUT_L: usize = 2;
const PORT_AUDIO_OUT_OUTPUT_R: usize = 3;
const PORT_CTRL_BYPASS: usize = 4;
const PORT_CTRL_WETDRY: usize = 5;
const PORT_CTRL_PAN: usize = 6;
const PORT_CTRL_GAIN: usize = 7;
const PORT_CTRL_ATACK: usize = 8;
const PORT_CTRL_DECAY: usize = 9;
const PORT_CTRL_THRESH: usize = 10;
const PORT_CTRL_INT: usize = 11;
const PORT_CTRL_DN: usize = 12;
const PORT_CTRL_MODE: usize = 13;
const PORT_CTRL_WHAMMY: usize = 14;

pub fn model_schema() -> ModelParameterSchema {
    ModelParameterSchema {
        effect_type: block_core::EFFECT_TYPE_PITCH.into(),
        model: MODEL_ID.into(),
        display_name: DISPLAY_NAME.into(),
        audio_mode: ModelAudioMode::TrueStereo,
        parameters: vec![
            bool_parameter("bypass", "Bypass", None, Some(false)),
            float_parameter("wetdry", "Wet/Dry", None, Some(0.0), 0.0, 127.0, 1.0, ParameterUnit::None),
            float_parameter("pan", "Pan", None, Some(0.0), -64.0, 63.0, 1.0, ParameterUnit::None),
            float_parameter("gain", "Gain", None, Some(0.0), -64.0, 63.0, 1.0, ParameterUnit::None),
            float_parameter("atack", "Attack", None, Some(500.0), 1.0, 2000.0, 10.0, ParameterUnit::Milliseconds),
            float_parameter("decay", "Decay", None, Some(500.0), 1.0, 2000.0, 10.0, ParameterUnit::Milliseconds),
            float_parameter("thresh", "Thresold", None, Some(0.0), -70.0, 20.0, 0.1, ParameterUnit::Decibels),
            float_parameter("int", "Interval", None, Some(1.0), 0.0, 12.0, 0.1, ParameterUnit::None),
            bool_parameter("dn", "Shift Down", None, Some(false)),
            float_parameter("mode", "Mode", None, Some(0.0), 0.0, 2.0, 0.01, ParameterUnit::None),
            float_parameter("whammy", "Interval", None, Some(0.0), 0.0, 127.0, 1.0, ParameterUnit::None),
        ],
    }
}

fn build(params: &ParameterSet, sample_rate: f32, layout: AudioChannelLayout) -> Result<BlockProcessor> {
    let bypass = required_bool(params, "bypass").map_err(anyhow::Error::msg)?;
    let wetdry = required_f32(params, "wetdry").map_err(anyhow::Error::msg)?;
    let pan = required_f32(params, "pan").map_err(anyhow::Error::msg)?;
    let gain = required_f32(params, "gain").map_err(anyhow::Error::msg)?;
    let atack = required_f32(params, "atack").map_err(anyhow::Error::msg)?;
    let decay = required_f32(params, "decay").map_err(anyhow::Error::msg)?;
    let thresh = required_f32(params, "thresh").map_err(anyhow::Error::msg)?;
    let int = required_f32(params, "int").map_err(anyhow::Error::msg)?;
    let dn = required_bool(params, "dn").map_err(anyhow::Error::msg)?;
    let mode = required_f32(params, "mode").map_err(anyhow::Error::msg)?;
    let whammy = required_f32(params, "whammy").map_err(anyhow::Error::msg)?;
    let lib_path = lv2::resolve_lv2_lib(PLUGIN_BINARY)?;
    let bundle_path = lv2::resolve_lv2_bundle(PLUGIN_DIR)?;

    let control_ports: &[(usize, f32)] = &[
        (PORT_CTRL_BYPASS, if bypass { 1.0 } else { 0.0 }),
        (PORT_CTRL_WETDRY, wetdry),
        (PORT_CTRL_PAN, pan),
        (PORT_CTRL_GAIN, gain),
        (PORT_CTRL_ATACK, atack),
        (PORT_CTRL_DECAY, decay),
        (PORT_CTRL_THRESH, thresh),
        (PORT_CTRL_INT, int),
        (PORT_CTRL_DN, if dn { 1.0 } else { 0.0 }),
        (PORT_CTRL_MODE, mode),
        (PORT_CTRL_WHAMMY, whammy),
    ];

    let processor = lv2::build_stereo_lv2_processor(&lib_path, PLUGIN_URI, sample_rate as f64, &bundle_path, &[PORT_AUDIO_IN_INPUT_L, PORT_AUDIO_IN_INPUT_R], &[PORT_AUDIO_OUT_OUTPUT_L, PORT_AUDIO_OUT_OUTPUT_R], control_ports)?;
    let _ = layout;
    Ok(BlockProcessor::Stereo(Box::new(processor)))
}

fn schema() -> Result<ModelParameterSchema> { Ok(model_schema()) }

pub const MODEL_DEFINITION: PitchModelDefinition = PitchModelDefinition {
    id: MODEL_ID, display_name: DISPLAY_NAME, brand: BRAND,
    backend_kind: PitchBackendKind::Lv2, schema, build,
    supported_instruments: block_core::ALL_INSTRUMENTS, knob_layout: &[],
};
